export const htmlBlockInlineQuestions = [
  {
    id: "html_elements_61",
    title: "Какой элемент является блочным по умолчанию?",
    options: ["<span>", "<div>", "<a>", "<strong>"],
    correctAnswers: [1],
    descriptions: [
      "<span> — строчный элемент.",
      "<div> — классический блочный элемент.",
      "<a> — строчный элемент (ссылка).",
      "<strong> — строчный (текстовое форматирование).",
    ],
    moduleId: "html",
    sectionTitle: "Элементы и теги",
    topic: "html_elements",
  },
  {
    id: "html_elements_62",
    title: "Какой элемент является строчным по умолчанию?",
    options: ["<p>", "<section>", "<em>", "<ul>"],
    correctAnswers: [2],
    descriptions: [
      "<p> — блочный (абзац).",
      "<section> — блочный (семантический раздел).",
      "<em> — строчный (курсив).",
      "<ul> — блочный (список).",
    ],
    moduleId: "html",
    sectionTitle: "Элементы и теги",
    topic: "html_elements",
  },
  {
    id: "html_elements_63",
    title: "Как ведут себя блочные элементы в потоке документа?",
    options: [
      "Не создают переносов строки",
      "Занимают всю доступную ширину и начинаются с новой строки",
      "Можно задать ширину через атрибуты HTML",
      "Автоматически выравниваются по центру",
    ],
    correctAnswers: [1],
    descriptions: [
      "Это характеристика строчных элементов.",
      "Правильное описание блочных элементов.",
      "Ширина задаётся через CSS, не HTML-атрибуты.",
      "Выравнивание — свойство CSS, не HTML.",
    ],
    moduleId: "html",
    sectionTitle: "Элементы и теги",
    topic: "html_elements",
  },
  {
    id: "html_elements_64",
    title: "Какой элемент можно вложить в <p> без нарушения валидации?",
    options: ["<div>", "<article>", "<span>", "<section>"],
    correctAnswers: [2],
    descriptions: [
      "<div> — блочный, нельзя вкладывать в <p>.",
      "<article> — блочный, нарушает структуру.",
      "<span> — строчный, допустим внутри <p>.",
      "<section> — блочный, недопустим.",
    ],
    moduleId: "html",
    sectionTitle: "Элементы и теги",
    topic: "html_elements",
  },
  {
    id: "html_elements_65",
    title: "Какой элемент НЕ является строчным?",
    options: ["<code>", "<input>", "<h1>", "<img>"],
    correctAnswers: [2],
    descriptions: [
      "<code> — строчный (код в тексте).",
      "<input> — строчный (форма).",
      "<h1> — блочный (заголовок).",
      "<img> — строчно-блочный (особый случай).",
    ],
    moduleId: "html",
    sectionTitle: "Элементы и теги",
    topic: "html_elements",
  },
  {
    id: "html_elements_66",
    title: "Как изменить тип отображения элемента со строчного на блочный?",
    options: [
      "Атрибутом type='block'",
      "Через CSS-свойство display: block",
      "Добавить тег <block>",
      "Использовать HTML-комментарий",
    ],
    correctAnswers: [1],
    descriptions: [
      "Нет такого атрибута.",
      "display: block — правильный способ.",
      "<block> — несуществующий тег.",
      "Комментарии не влияют на отображение.",
    ],
    moduleId: "html",
    sectionTitle: "Элементы и теги",
    topic: "html_elements",
  },
  {
    id: "html_elements_67",
    title: "Какой элемент является исключением (строчно-блочным)?",
    options: ["<textarea>", "<header>", "<br>", "<table>"],
    correctAnswers: [0],
    descriptions: [
      "<textarea> — inline-block (можно задать ширину/высоту).",
      "<header> — блочный.",
      "<br> — строчный (перенос строки).",
      "<table> — блочный.",
    ],
    moduleId: "html",
    sectionTitle: "Элементы и теги",
    topic: "html_elements",
  },
  {
    id: "html_elements_68",
    title: "Какой элемент нельзя вложить в <span>?",
    options: ["<strong>", "<div>", "<a>", "<img>"],
    correctAnswers: [1],
    descriptions: [
      "<strong> — строчный, допустим.",
      "<div> — блочный, нарушает структуру.",
      "<a> — строчный, допустим.",
      "<img> — строчный, допустим.",
    ],
    moduleId: "html",
    sectionTitle: "Элементы и теги",
    topic: "html_elements",
  },
  {
    id: "html_elements_69",
    title: "Какое свойство CSS делает элемент строчно-блочным?",
    options: [
      "display: flex",
      "display: inline-block",
      "position: absolute",
      "float: left",
    ],
    correctAnswers: [1],
    descriptions: [
      "flex — создаёт flex-контейнер.",
      "inline-block — гибрид строчного и блочного.",
      "absolute — меняет позиционирование, не тип.",
      "float — обтекание, не тип элемента.",
    ],
    moduleId: "html",
    sectionTitle: "Элементы и теги",
    topic: "html_elements",
  },
  {
    id: "html_elements_70",
    title: "Какой элемент создаёт перенос строки без добавления отступа?",
    options: ["<p>", "<br>", "<div>", "<hr>"],
    correctAnswers: [1],
    descriptions: [
      "<p> — абзац с отступами.",
      "<br> — перенос без отступа.",
      "<div> — блочный контейнер.",
      "<hr> — горизонтальная линия.",
    ],
    moduleId: "html",
    sectionTitle: "Элементы и теги",
    topic: "html_elements",
  },
  {
    id: "html_elements_71",
    title: "Какой элемент НЕ является блочным?",
    options: ["<footer>", "<nav>", "<button>", "<blockquote>"],
    correctAnswers: [2],
    descriptions: [
      "<footer> — блочный (нижний колонтитул).",
      "<nav> — блочный (навигация).",
      "<button> — строчно-блочный (особый случай).",
      "<blockquote> — блочный (цитата).",
    ],
    moduleId: "html",
    sectionTitle: "Элементы и теги",
    topic: "html_elements",
  },
  {
    id: "html_elements_72",
    title:
      "Какой элемент можно использовать для группировки строчных элементов?",
    options: ["<section>", "<div>", "<span>", "<main>"],
    correctAnswers: [2],
    descriptions: [
      "<section> — блочный, для смысловых разделов.",
      "<div> — блочный, избыточен для строчных.",
      "<span> — строчный контейнер.",
      "<main> — блочный (основное содержимое).",
    ],
    moduleId: "html",
    sectionTitle: "Элементы и теги",
    topic: "html_elements",
  },
  {
    id: "html_elements_73",
    title: "Какой элемент является блочным, но не создаёт видимых отступов?",
    options: ["<p>", "<ul>", "<main>", "<pre>"],
    correctAnswers: [2],
    descriptions: [
      "<p> — имеет отступы по умолчанию.",
      "<ul> — имеет отступы для маркеров.",
      "<main> — блочный без стандартных отступов.",
      "<pre> — сохраняет пробелы, но может иметь отступы.",
    ],
    moduleId: "html",
    sectionTitle: "Элементы и теги",
    topic: "html_elements",
  },
  {
    id: "html_elements_74",
    title: "Какой элемент НЕЛЬЗЯ вложить в <ul>?",
    options: ["<li>", "<span>", "<div>", "<script>"],
    correctAnswers: [3],
    descriptions: [
      "<li> — единственный допустимый потомок <ul>.",
      "<span> — можно вложить в <li>, но не напрямую.",
      "<div> — аналогично, только внутри <li>.",
      "<script> — не имеет смысла в списке.",
    ],
    moduleId: "html",
    sectionTitle: "Элементы и теги",
    topic: "html_elements",
  },
  {
    id: "html_elements_75",
    title: "Какой элемент является строчным, но может содержать блочные?",
    options: ["<a> (в HTML5)", "<strong>", "<code>", "<label>"],
    correctAnswers: [0],
    descriptions: [
      "<a> — в HTML5 может оборачивать блоки.",
      "<strong> — только текст и строчные.",
      "<code> — только строчное содержимое.",
      "<label> — только строчные.",
    ],
    moduleId: "html",
    sectionTitle: "Элементы и теги",
    topic: "html_elements",
  },
  {
    id: "html_elements_76",
    title: "Какой элемент не создаёт нового контекста форматирования?",
    options: ["<div>", "<span>", "<table>", "<article>"],
    correctAnswers: [1],
    descriptions: [
      "<div> — блочный, создаёт контекст.",
      "<span> — строчный, не влияет на поток.",
      "<table> — создаёт табличный контекст.",
      "<article> — блочный контекст.",
    ],
    moduleId: "html",
    sectionTitle: "Элементы и теги",
    topic: "html_elements",
  },
  {
    id: "html_elements_77",
    title: "Какой элемент является блочным, но не семантическим?",
    options: ["<header>", "<div>", "<aside>", "<nav>"],
    correctAnswers: [1],
    descriptions: [
      "<header> — семантический.",
      "<div> — универсальный блочный контейнер.",
      "<aside> — семантический (боковая панель).",
      "<nav> — семантический (навигация).",
    ],
    moduleId: "html",
    sectionTitle: "Элементы и теги",
    topic: "html_elements",
  },
  {
    id: "html_elements_78",
    title:
      "Какой элемент можно использовать для переноса строки внутри текста без изменения структуры?",
    options: ["<p>", "<br>", "<div>", "<wbr>"],
    correctAnswers: [3],
    descriptions: [
      "<p> — создаёт абзац (блочный).",
      "<br> — принудительный перенос.",
      "<div> — блочный, ломает структуру.",
      "<wbr> — перенос по возможности (не видимый).",
    ],
    moduleId: "html",
    sectionTitle: "Элементы и теги",
    topic: "html_elements",
  },
  {
    id: "html_elements_79",
    title: "Какой элемент является строчным, но поддерживает ширину и высоту?",
    options: ["<button>", "<em>", "<a>", "<time>"],
    correctAnswers: [0],
    descriptions: [
      "<button> — inline-block по умолчанию.",
      "<em> — чистый строчный.",
      "<a> — строчный (без размеров).",
      "<time> — строчный.",
    ],
    moduleId: "html",
    sectionTitle: "Элементы и теги",
    topic: "html_elements",
  },
  {
    id: "html_elements_80",
    title:
      "Какой элемент НЕ является чисто строчным или блочным (особый случай)?",
    options: ["<img>", "<h2>", "<span>", "<ul>"],
    correctAnswers: [0],
    descriptions: [
      "<img> — заменяемый строчный элемент (replaced inline).",
      "<h2> — классический блочный.",
      "<span> — классический строчный.",
      "<ul> — классический блочный.",
    ],
    moduleId: "html",
    sectionTitle: "Элементы и теги",
    topic: "html_elements",
  },
];
