export const htmlTextStructureQuestions = [
  {
    id: "html_elements_81",
    title: "Какой тег используется для главного заголовка страницы?",
    options: ["<header>", "<h1>", "<title>", "<head>"],
    correctAnswers: [1],
    descriptions: [
      "<header> — шапка раздела, не заголовок.",
      "<h1> — главный заголовок (должен быть один на странице).",
      "<title> — заголовок вкладки браузера.",
      "<head> — контейнер метаданных.",
    ],
    moduleId: "html",
    sectionTitle: "Элементы и теги",
    topic: "html_elements",
  },
  {
    id: "html_elements_82",
    title: "Какой уровень заголовка НЕ существует в HTML?",
    options: ["<h0>", "<h3>", "<h5>", "<h6>"],
    correctAnswers: [0],
    descriptions: [
      "<h0> — не существует (диапазон h1-h6).",
      "<h3> — стандартный заголовок 3-го уровня.",
      "<h5> — заголовок 5-го уровня.",
      "<h6> — минимальный уровень заголовка.",
    ],
    moduleId: "html",
    sectionTitle: "Элементы и теги",
    topic: "html_elements",
  },
  {
    id: "html_elements_83",
    title: "Какой тег создаёт абзац текста?",
    options: ["<br>", "<section>", "<p>", "<div>"],
    correctAnswers: [2],
    descriptions: [
      "<br> — перенос строки, не абзац.",
      "<section> — смысловой раздел.",
      "<p> — тег для абзаца (paragraph).",
      "<div> — универсальный блочный контейнер.",
    ],
    moduleId: "html",
    sectionTitle: "Элементы и теги",
    topic: "html_elements",
  },
  {
    id: "html_elements_84",
    title: "Какой тег используется для маркированного списка?",
    options: ["<ol>", "<ul>", "<li>", "<dl>"],
    correctAnswers: [1],
    descriptions: [
      "<ol> — нумерованный список (ordered list).",
      "<ul> — маркированный список (unordered list).",
      "<li> — элемент списка, но не сам список.",
      "<dl> — список определений.",
    ],
    moduleId: "html",
    sectionTitle: "Элементы и теги",
    topic: "html_elements",
  },
  {
    id: "html_elements_85",
    title: "Какой тег обязателен внутри <ul> или <ol>?",
    options: ["<p>", "<span>", "<li>", "<div>"],
    correctAnswers: [2],
    descriptions: [
      "<p> — недопустим напрямую в списке.",
      "<span> — строчный, не для элементов списка.",
      "<li> — единственный допустимый потомок.",
      "<div> — блочный, нарушает структуру списка.",
    ],
    moduleId: "html",
    sectionTitle: "Элементы и теги",
    topic: "html_elements",
  },
  {
    id: "html_elements_86",
    title: "Какой тег создаёт нумерованный список?",
    options: ["<ul>", "<nl>", "<ol>", "<list>"],
    correctAnswers: [2],
    descriptions: [
      "<ul> — маркированный список.",
      "<nl> — несуществующий тег.",
      "<ol> — нумерованный список (ordered list).",
      "<list> — нестандартный тег.",
    ],
    moduleId: "html",
    sectionTitle: "Элементы и теги",
    topic: "html_elements",
  },
  {
    id: "html_elements_87",
    title: "Какой элемент НЕ является частью иерархии заголовков?",
    options: ["<h2>", "<h4>", "<heading>", "<h6>"],
    correctAnswers: [2],
    descriptions: [
      "<h2> — стандартный заголовок.",
      "<h4> — часть иерархии.",
      "<heading> — несуществующий тег.",
      "<h6> — минимальный уровень.",
    ],
    moduleId: "html",
    sectionTitle: "Элементы и теги",
    topic: "html_elements",
  },
  {
    id: "html_elements_88",
    title:
      "Что произойдёт, если пропустить уровень заголовка (например, поставить <h3> после <h1>)?",
    options: [
      "Страница не загрузится",
      "Это нарушит семантическую структуру",
      "Заголовки станут красными",
      "Ничего, это допустимо",
    ],
    correctAnswers: [1],
    descriptions: [
      "Страница загрузится, но с плохой структурой.",
      "Нарушение иерархии ухудшает SEO и доступность.",
      "Цвет не изменится автоматически.",
      "Допустимо технически, но не рекомендуется.",
    ],
    moduleId: "html",
    sectionTitle: "Элементы и теги",
    topic: "html_elements",
  },
  {
    id: "html_elements_89",
    title: "Какой тег можно использовать внутри <p> для выделения текста?",
    options: ["<strong>", "<section>", "<h3>", "<ul>"],
    correctAnswers: [0],
    descriptions: [
      "<strong> — строчный, для выделения.",
      "<section> — блочный, нарушит структуру.",
      "<h3> — заголовок, недопустим в абзаце.",
      "<ul> — список, недопустим в абзаце.",
    ],
    moduleId: "html",
    sectionTitle: "Элементы и теги",
    topic: "html_elements",
  },
  {
    id: "html_elements_90",
    title: "Как создать вложенный список внутри <li>?",
    options: [
      "Поместить новый <li> без обёртки",
      "Добавить <ul> или <ol> внутрь <li>",
      "Использовать <sublist>",
      "Вложенные списки невозможны",
    ],
    correctAnswers: [1],
    descriptions: [
      "<li> должен содержать полноценный список.",
      "<ul> или <ol> внутри <li> — правильный способ.",
      "<sublist> — несуществующий тег.",
      "Вложенность поддерживается стандартом.",
    ],
    moduleId: "html",
    sectionTitle: "Элементы и теги",
    topic: "html_elements",
  },
  {
    id: "html_elements_91",
    title: "Какой атрибут <ol> изменяет тип нумерации?",
    options: ["type", "numbering", "style", "list-type"],
    correctAnswers: [0],
    descriptions: [
      "type='1|a|A|i|I' — задаёт вид маркеров.",
      "numbering — несуществующий атрибут.",
      "style — CSS-свойство, не HTML-атрибут.",
      "list-type — не существует.",
    ],
    moduleId: "html",
    sectionTitle: "Элементы и теги",
    topic: "html_elements",
  },
  {
    id: "html_elements_92",
    title: "Какой тег используется для списка определений?",
    options: ["<ul>", "<dl>", "<def>", "<list>"],
    correctAnswers: [1],
    descriptions: [
      "<ul> — маркированный список.",
      "<dl> — список определений (definition list).",
      "<def> — несуществующий тег.",
      "<list> — нестандартный тег.",
    ],
    moduleId: "html",
    sectionTitle: "Элементы и теги",
    topic: "html_elements",
  },
  {
    id: "html_elements_93",
    title: "Какие теги используются внутри <dl>?",
    options: [
      "<dt> и <dd>",
      "<li>",
      "<def> и <desc>",
      "<item> и <description>",
    ],
    correctAnswers: [0],
    descriptions: [
      "<dt> (термин) и <dd> (описание) — правильная пара.",
      "<li> — для обычных списков, не <dl>.",
      "Несуществующие теги.",
      "Нестандартные названия.",
    ],
    moduleId: "html",
    sectionTitle: "Элементы и теги",
    topic: "html_elements",
  },
  {
    id: "html_elements_94",
    title: "Какой тег НЕ является текстовым структурным элементом?",
    options: ["<blockquote>", "<pre>", "<hr>", "<h4>"],
    correctAnswers: [2],
    descriptions: [
      "<blockquote> — цитата (текстовый элемент).",
      "<pre> — преформатированный текст.",
      "<hr> — горизонтальная линия (не текст).",
      "<h4> — заголовок (текстовая структура).",
    ],
    moduleId: "html",
    sectionTitle: "Элементы и теги",
    topic: "html_elements",
  },
  {
    id: "html_elements_95",
    title: "Какой тег сохраняет пробелы и переносы в тексте?",
    options: ["<p>", "<pre>", "<plaintext>", "<code>"],
    correctAnswers: [1],
    descriptions: [
      "<p> — игнорирует множественные пробелы.",
      "<pre> — сохраняет форматирование (preformatted).",
      "<plaintext> — устаревший тег.",
      "<code> — для кода, но не сохраняет пробелы без CSS.",
    ],
    moduleId: "html",
    sectionTitle: "Элементы и теги",
    topic: "html_elements",
  },
  {
    id: "html_elements_96",
    title: "Какой атрибут <ol> задаёт начальное значение нумерации?",
    options: ["begin", "beginning", "beginNumber", "start"],
    correctAnswers: [3],
    descriptions: [
      "begin — несуществующий атрибут.",
      "beginning — не существует.",
      "beginNumber — неверное название.",
      "start='5' — правильный атрибут.",
    ],
    moduleId: "html",
    sectionTitle: "Элементы и теги",
    topic: "html_elements",
  },
  {
    id: "html_elements_97",
    title: "Какой тег создаёт горизонтальную линию для разделения контента?",
    options: ["<line>", "<divider>", "<hr>", "<br>"],
    correctAnswers: [2],
    descriptions: [
      "<line> — несуществующий тег.",
      "<divider> — нестандартный тег.",
      "<hr> — горизонтальная линия (horizontal rule).",
      "<br> — перенос строки.",
    ],
    moduleId: "html",
    sectionTitle: "Элементы и теги",
    topic: "html_elements",
  },
  {
    id: "html_elements_98",
    title: "Какой тег используется для цитирования?",
    options: ["<cite>", "<quote>", "<blockquote>", "<q>"],
    correctAnswers: [2],
    descriptions: [
      "<cite> — для названия источника, не цитаты.",
      "<quote> — несуществующий тег.",
      "<blockquote> — блочная цитата.",
      "<q> — строчная цитата (для коротких).",
    ],
    moduleId: "html",
    sectionTitle: "Элементы и теги",
    topic: "html_elements",
  },
  {
    id: "html_elements_99",
    title: "Какой элемент списка поддерживает атрибут value?",
    options: ["<ul>", "<ol>", "<li>", "<dl>"],
    correctAnswers: [2],
    descriptions: [
      "<ul> — маркированный список.",
      "<ol> — нумерованный, но атрибут в <li>.",
      "<li value='3'> — изменяет номер пункта.",
      "<dl> — список определений.",
    ],
    moduleId: "html",
    sectionTitle: "Элементы и теги",
    topic: "html_elements",
  },
  {
    id: "html_elements_100",
    title:
      "Какой тег НЕ рекомендуется использовать для визуального выделения текста?",
    options: ["<strong>", "<em>", "<b>", "<h3>"],
    correctAnswers: [3],
    descriptions: [
      "<strong> — семантическое выделение важности.",
      "<em> — семантическое выделение (курсив).",
      "<b> — визуальное выделение (жирный).",
      "<h3> — заголовок, не для выделения в тексте.",
    ],
    moduleId: "html",
    sectionTitle: "Элементы и теги",
    topic: "html_elements",
  },
];
