export const htmlForms = [
  {
    id: "html_forms_01",
    title:
      "Какой атрибут тега <form> определяет URL-адрес для отправки данных?",
    options: ["method", "action", "url", "href"],
    correctAnswers: [1],
    descriptions: [
      "method — определяет тип HTTP-запроса (GET или POST).",
      "action — правильный ответ, указывает адрес, куда отправятся данные.",
      "url — не является атрибутом <form>.",
      "href — используется в <a> для ссылок.",
    ],
    moduleId: "html",
    sectionTitle: "HTML-формы и элементы управления",
    topic: "html_forms",
  },
  {
    id: "html_forms_02",
    title: "Какой атрибут <form> определяет способ отправки данных на сервер?",
    options: ["action", "method", "target", "submit"],
    correctAnswers: [1],
    descriptions: [
      "action — указывает URL для отправки данных.",
      "method — правильный ответ, определяет способ передачи данных (GET или POST).",
      "target — указывает, в какой вкладке или окне откроется результат.",
      "submit — это событие, но не атрибут.",
    ],
    moduleId: "html",
    sectionTitle: "HTML-формы и элементы управления",
    topic: "html_forms",
  },
  {
    id: "html_forms_03",
    title:
      "Какой метод HTTP-запроса используется для передачи данных в теле запроса?",
    options: ["GET", "POST", "PUT", "DELETE"],
    correctAnswers: [1],
    descriptions: [
      "GET — отправляет данные в URL-адресе (параметры запроса).",
      "POST — правильный ответ, отправляет данные в теле запроса.",
      "PUT — используется для обновления данных, но не в форме по умолчанию.",
      "DELETE — удаляет данные, но не используется в <form> напрямую.",
    ],
    moduleId: "html",
    sectionTitle: "HTML-формы и элементы управления",
    topic: "html_forms",
  },
  {
    id: "html_forms_04",
    title: "Для чего используется атрибут target в <form>?",
    options: [
      "Для выбора метода отправки данных",
      "Для указания URL-адреса",
      "Для открытия результата в новой вкладке или окне",
      "Для установки времени отправки данных",
    ],
    correctAnswers: [2],
    descriptions: [
      "Для выбора метода отправки данных — это метод (GET или POST).",
      "Для указания URL-адреса — это атрибут action.",
      "Для открытия результата в новой вкладке или окне — правильный ответ.",
      "Для установки времени отправки данных — такого атрибута нет.",
    ],
    moduleId: "html",
    sectionTitle: "HTML-формы и элементы управления",
    topic: "html_forms",
  },
  {
    id: "html_forms_05",
    title: "Что произойдёт, если в форме не указан атрибут action?",
    options: [
      "Данные не будут отправлены",
      "Форма отправится на текущий URL",
      "Появится ошибка в консоли",
      "Отправка формы заблокируется",
    ],
    correctAnswers: [1],
    descriptions: [
      "Данные не будут отправлены — это неправда, отправка произойдёт.",
      "Форма отправится на текущий URL — правильный ответ.",
      "Появится ошибка в консоли — ошибок не будет.",
      "Отправка формы заблокируется — отправка не блокируется.",
    ],
    moduleId: "html",
    sectionTitle: "HTML-формы и элементы управления",
    topic: "html_forms",
  },
  {
    id: "html_forms_06",
    title:
      "Какой метод передачи данных в форме отображает параметры в адресной строке?",
    options: ["GET", "POST", "PUT", "DELETE"],
    correctAnswers: [0],
    descriptions: [
      "GET — правильный ответ, данные видны в URL.",
      "POST — данные передаются в теле запроса и не видны в URL.",
      "PUT — используется для обновления данных, но не в форме по умолчанию.",
      "DELETE — для удаления данных, не применяется в форме.",
    ],
    moduleId: "html",
    sectionTitle: "HTML-формы и элементы управления",
    topic: "html_forms",
  },
  {
    id: "html_forms_07",
    title:
      "Какой элемент формы используется для создания многострочного текстового поля?",
    options: ["<input>", "<textarea>", "<select>", "<button>"],
    correctAnswers: [1],
    descriptions: [
      "<input> — однострочное поле ввода.",
      "<textarea> — правильный ответ, используется для многострочного текста.",
      "<select> — выпадающий список.",
      "<button> — это кнопка, не поле ввода.",
    ],
    moduleId: "html",
    sectionTitle: "HTML-формы и элементы управления",
    topic: "html_forms",
  },
  {
    id: "html_forms_08",
    title: "Какой тег используется для создания выпадающего списка в форме?",
    options: ["<select>", "<textarea>", "<input>", "<option>"],
    correctAnswers: [0],
    descriptions: [
      "<select> — правильный ответ, создаёт выпадающий список.",
      "<textarea> — используется для многострочного ввода.",
      "<input> — одиночное поле ввода.",
      "<option> — это элемент внутри <select>, но не сам список.",
    ],
    moduleId: "html",
    sectionTitle: "HTML-формы и элементы управления",
    topic: "html_forms",
  },
  {
    id: "html_forms_09",
    title: "Какой тип <input> следует использовать для выбора даты?",
    options: ["text", "date", "datetime-local", "calendar"],
    correctAnswers: [1],
    descriptions: [
      "text — это обычное текстовое поле.",
      "date — правильный ответ, позволяет выбрать дату.",
      "datetime-local — позволяет выбрать дату и время, но не только дату.",
      "calendar — такого типа ввода не существует.",
    ],
    moduleId: "html",
    sectionTitle: "HTML-формы и элементы управления",
    topic: "html_forms",
  },
  {
    id: "html_forms_10",
    title:
      "Какой атрибут <form> позволяет избежать перезагрузки страницы при отправке?",
    options: ["method", "action", "onsubmit", "novalidate"],
    correctAnswers: [2],
    descriptions: [
      "method — отвечает за метод отправки (GET или POST).",
      "action — указывает URL-адрес отправки.",
      "onsubmit — правильный ответ, через JS можно отменить стандартное поведение.",
      "novalidate — отключает HTML-валидацию, но не предотвращает перезагрузку.",
    ],
    moduleId: "html",
    sectionTitle: "HTML-формы и элементы управления",
    topic: "html_forms",
  },
  {
    id: "html_forms_11",
    title: "Какой атрибут <input> определяет тип вводимых данных?",
    options: ["name", "type", "placeholder", "value"],
    correctAnswers: [1],
    descriptions: [
      "name — задаёт имя поля для отправки данных на сервер.",
      "type — правильный ответ, определяет тип ввода (text, email, password и т.д.).",
      "placeholder — отображает текст-заглушку в поле ввода.",
      "value — задаёт значение по умолчанию.",
    ],
    moduleId: "html",
    sectionTitle: "HTML-формы и элементы управления",
    topic: "html_forms",
  },
  {
    id: "html_forms_12",
    title: "Какой тип <input> следует использовать для ввода пароля?",
    options: ["text", "password", "secure", "hidden"],
    correctAnswers: [1],
    descriptions: [
      "text — это стандартное текстовое поле, не скрывает ввод.",
      "password — правильный ответ, символы отображаются как точки или звёздочки.",
      "secure — не является валидным типом.",
      "hidden — скрывает поле, но не используется для ввода.",
    ],
    moduleId: "html",
    sectionTitle: "HTML-формы и элементы управления",
    topic: "html_forms",
  },
  {
    id: "html_forms_13",
    title:
      "Какой атрибут позволяет отображать текст-заглушку внутри поля ввода?",
    options: ["placeholder", "value", "title", "label"],
    correctAnswers: [0],
    descriptions: [
      "placeholder — правильный ответ, отображает текст-заглушку до ввода данных.",
      "value — задаёт значение по умолчанию, но не является заглушкой.",
      "title — показывает всплывающую подсказку при наведении.",
      "label — это тег для описания поля, но не для заглушки.",
    ],
    moduleId: "html",
    sectionTitle: "HTML-формы и элементы управления",
    topic: "html_forms",
  },
  {
    id: "html_forms_14",
    title:
      "Какой тип <input> позволяет выбрать несколько значений одновременно?",
    options: ["checkbox", "radio", "select", "text"],
    correctAnswers: [0],
    descriptions: [
      "checkbox — правильный ответ, позволяет выбрать несколько вариантов.",
      "radio — позволяет выбрать только один вариант из группы.",
      "select — выпадающий список, но зависит от атрибута multiple.",
      "text — это однострочное поле ввода, не для множественного выбора.",
    ],
    moduleId: "html",
    sectionTitle: "HTML-формы и элементы управления",
    topic: "html_forms",
  },
  {
    id: "html_forms_15",
    title:
      "Какой тип <input> следует использовать для выбора пола (мужской/женский)?",
    options: ["checkbox", "radio", "select", "text"],
    correctAnswers: [1],
    descriptions: [
      "checkbox — позволяет выбирать несколько вариантов, что не подходит для пола.",
      "radio — правильный ответ, позволяет выбрать только один из двух вариантов.",
      "select — можно использовать, но radio более подходящий.",
      "text — не подходит для выбора фиксированных значений.",
    ],
    moduleId: "html",
    sectionTitle: "HTML-формы и элементы управления",
    topic: "html_forms",
  },
  {
    id: "html_forms_16",
    title:
      "Какой атрибут делает поле обязательным для заполнения перед отправкой формы?",
    options: ["required", "disabled", "readonly", "validate"],
    correctAnswers: [0],
    descriptions: [
      "required — правильный ответ, делает поле обязательным.",
      "disabled — отключает поле, но не требует его заполнения.",
      "readonly — делает поле доступным только для чтения, но не обязательным.",
      "validate — не является валидным атрибутом HTML.",
    ],
    moduleId: "html",
    sectionTitle: "HTML-формы и элементы управления",
    topic: "html_forms",
  },
  {
    id: "html_forms_17",
    title:
      "Какой атрибут позволяет заблокировать изменение значения в <input>?",
    options: ["readonly", "disabled", "value", "immutable"],
    correctAnswers: [0],
    descriptions: [
      "readonly — правильный ответ, делает поле доступным только для чтения.",
      "disabled — полностью отключает поле, оно не отправляется на сервер.",
      "value — просто задаёт значение по умолчанию, но не блокирует ввод.",
      "immutable — не является атрибутом HTML.",
    ],
    moduleId: "html",
    sectionTitle: "HTML-формы и элементы управления",
    topic: "html_forms",
  },
  {
    id: "html_forms_18",
    title:
      "Какой атрибут следует использовать, чтобы пользователь мог вводить только email в поле?",
    options: ["type='text'", "type='email'", "type='url'", "type='password'"],
    correctAnswers: [1],
    descriptions: [
      "type='text' — позволяет вводить любой текст.",
      "type='email' — правильный ответ, позволяет ввести только валидный email.",
      "type='url' — ожидает URL-адрес.",
      "type='password' — используется для ввода пароля.",
    ],
    moduleId: "html",
    sectionTitle: "HTML-формы и элементы управления",
    topic: "html_forms",
  },
  {
    id: "html_forms_19",
    title: "Какой атрибут <input> позволяет указать значение по умолчанию?",
    options: ["placeholder", "default", "value", "text"],
    correctAnswers: [2],
    descriptions: [
      "placeholder — это текст-заглушка, но не значение.",
      "default — не существует в стандартном HTML.",
      "value — правильный ответ, устанавливает значение по умолчанию.",
      "text — это тип ввода, а не значение.",
    ],
    moduleId: "html",
    sectionTitle: "HTML-формы и элементы управления",
    topic: "html_forms",
  },
  {
    id: "html_forms_20",
    title: "Как объединить несколько radio-кнопок в одну группу выбора?",
    options: [
      "Использовать одинаковое значение атрибута id",
      "Использовать одинаковое значение атрибута name",
      "Объединить в <fieldset>",
      "Прописать одинаковый value",
    ],
    correctAnswers: [1],
    descriptions: [
      "Использовать одинаковое значение атрибута id — id должен быть уникальным.",
      "Использовать одинаковое значение атрибута name — правильный ответ, радио-кнопки объединяются в группу.",
      "Объединить в <fieldset> — улучшает вид, но не создаёт группировку.",
      "Прописать одинаковый value — значение не влияет на группировку.",
    ],
    moduleId: "html",
    sectionTitle: "HTML-формы и элементы управления",
    topic: "html_forms",
  },
  {
    id: "html_forms_21",
    title: "Какой тег используется для создания выпадающего списка?",
    options: ["<select>", "<option>", "<textarea>", "<input>"],
    correctAnswers: [0],
    descriptions: [
      "<select> — правильный ответ, он создаёт выпадающий список.",
      "<option> — это элемент внутри <select>, но не сам список.",
      "<textarea> — это многострочное текстовое поле.",
      "<input> — это однострочное текстовое поле или другой тип ввода.",
    ],
    moduleId: "html",
    sectionTitle: "HTML-формы и элементы управления",
    topic: "html_forms",
  },
  {
    id: "html_forms_22",
    title:
      "Какой тег используется внутри <select> для обозначения вариантов выбора?",
    options: ["<option>", "<textarea>", "<input>", "<button>"],
    correctAnswers: [0],
    descriptions: [
      "<option> — правильный ответ, он обозначает элементы внутри выпадающего списка.",
      "<textarea> — используется для ввода многострочного текста.",
      "<input> — это однострочное поле ввода, не выпадающий список.",
      "<button> — это кнопка, не список.",
    ],
    moduleId: "html",
    sectionTitle: "HTML-формы и элементы управления",
    topic: "html_forms",
  },
  {
    id: "html_forms_23",
    title:
      "Какой атрибут у <select> позволяет выбрать несколько значений одновременно?",
    options: ["multiple", "selected", "checked", "value"],
    correctAnswers: [0],
    descriptions: [
      "multiple — правильный ответ, он позволяет выбрать несколько опций.",
      "selected — делает элемент выбранным по умолчанию, но не позволяет множественный выбор.",
      "checked — используется для checkbox и radio, не для select.",
      "value — указывает значение опции, но не управляет множественным выбором.",
    ],
    moduleId: "html",
    sectionTitle: "HTML-формы и элементы управления",
    topic: "html_forms",
  },
  {
    id: "html_forms_24",
    title: "Какой тег HTML используется для многострочного текстового ввода?",
    options: ["<input>", "<textarea>", "<select>", "<button>"],
    correctAnswers: [1],
    descriptions: [
      "<input> — это однострочное поле ввода.",
      "<textarea> — правильный ответ, позволяет вводить многострочный текст.",
      "<select> — создаёт выпадающий список.",
      "<button> — это кнопка, не текстовое поле.",
    ],
    moduleId: "html",
    sectionTitle: "HTML-формы и элементы управления",
    topic: "html_forms",
  },
  {
    id: "html_forms_25",
    title:
      "Какие атрибуты можно использовать с <textarea> для задания размеров?",
    options: [
      "width и height",
      "rows и cols",
      "size и maxlength",
      "minlength и maxlength",
    ],
    correctAnswers: [1],
    descriptions: [
      "width и height — используются в CSS, но не являются атрибутами <textarea>.",
      "rows и cols — правильный ответ, задают количество строк и столбцов.",
      "size и maxlength — применяются к <input>, но не к <textarea>.",
      "minlength и maxlength — контролируют длину ввода, но не размеры.",
    ],
    moduleId: "html",
    sectionTitle: "HTML-формы и элементы управления",
    topic: "html_forms",
  },
  {
    id: "html_forms_26",
    title:
      "Какой тип <button> используется для сброса данных формы к значениям по умолчанию?",
    options: ["submit", "reset", "button", "clear"],
    correctAnswers: [1],
    descriptions: [
      "submit — отправляет форму на сервер.",
      "reset — правильный ответ, сбрасывает значения к дефолтным.",
      "button — просто кнопка без действий по умолчанию.",
      "clear — не является валидным типом для <button>.",
    ],
    moduleId: "html",
    sectionTitle: "HTML-формы и элементы управления",
    topic: "html_forms",
  },
  {
    id: "html_forms_27",
    title: "Какой атрибут у <option> делает его выбранным по умолчанию?",
    options: ["selected", "checked", "value", "default"],
    correctAnswers: [0],
    descriptions: [
      "selected — правильный ответ, делает элемент выбранным по умолчанию.",
      "checked — используется для checkbox и radio.",
      "value — указывает значение, но не делает выбранным по умолчанию.",
      "default — не является валидным атрибутом.",
    ],
    moduleId: "html",
    sectionTitle: "HTML-формы и элементы управления",
    topic: "html_forms",
  },
  {
    id: "html_forms_28",
    title:
      "Какой тип кнопки <button> используется по умолчанию, если не указан атрибут type?",
    options: ["submit", "button", "reset", "click"],
    correctAnswers: [0],
    descriptions: [
      "submit — правильный ответ, если тип не указан, кнопка отправляет форму.",
      "button — требует явного указания типа.",
      "reset — сбрасывает форму, но не является типом по умолчанию.",
      "click — не существует как тип кнопки.",
    ],
    moduleId: "html",
    sectionTitle: "HTML-формы и элементы управления",
    topic: "html_forms",
  },
  {
    id: "html_forms_29",
    title:
      "Как сделать кнопку <button>, которая не отправляет форму при клике?",
    options: [
      "Задать атрибут value='none'",
      "Задать атрибут type='button'",
      "Задать атрибут disabled",
      "Задать атрибут action='none'",
    ],
    correctAnswers: [1],
    descriptions: [
      "value='none' — это значение, но не тип кнопки.",
      "type='button' — правильный ответ, кнопка не отправляет форму.",
      "disabled — отключает кнопку, но не изменяет её поведение.",
      "action='none' — это не валидный атрибут.",
    ],
    moduleId: "html",
    sectionTitle: "HTML-формы и элементы управления",
    topic: "html_forms",
  },
  {
    id: "html_forms_30",
    title:
      "Какой тег HTML позволяет добавить описание для группы полей в форме?",
    options: ["<fieldset>", "<legend>", "<group>", "<label>"],
    correctAnswers: [0],
    descriptions: [
      "<fieldset> — правильный ответ, создаёт контейнер для группы полей.",
      "<legend> — это подпись группы, но не сам контейнер.",
      "<group> — такого тега не существует в HTML.",
      "<label> — используется для связывания подписи с <input>.",
    ],
    moduleId: "html",
    sectionTitle: "HTML-формы и элементы управления",
    topic: "html_forms",
  },
  {
    id: "html_forms_31",
    title:
      "Какой атрибут делает поле формы обязательным для заполнения перед отправкой?",
    options: ["required", "disabled", "readonly", "mandatory"],
    correctAnswers: [0],
    descriptions: [
      "required — правильный ответ, делает поле обязательным.",
      "disabled — блокирует ввод, но не делает поле обязательным.",
      "readonly — позволяет видеть значение, но не изменять.",
      "mandatory — не существует в HTML.",
    ],
    moduleId: "html",
    sectionTitle: "HTML-формы и элементы управления",
    topic: "html_forms",
  },
  {
    id: "html_forms_32",
    title:
      "Какой атрибут отключает возможность ввода в поле и делает его неактивным?",
    options: ["disabled", "readonly", "locked", "required"],
    correctAnswers: [0],
    descriptions: [
      "disabled — правильный ответ, делает поле недоступным для ввода.",
      "readonly — позволяет видеть значение, но не редактировать его.",
      "locked — не существует в HTML.",
      "required — делает поле обязательным, но не блокирует ввод.",
    ],
    moduleId: "html",
    sectionTitle: "HTML-формы и элементы управления",
    topic: "html_forms",
  },
  {
    id: "html_forms_33",
    title:
      "Какой атрибут позволяет пользователю видеть значение в поле, но не изменять его?",
    options: ["readonly", "disabled", "immutable", "hidden"],
    correctAnswers: [0],
    descriptions: [
      "readonly — правильный ответ, поле доступно только для чтения.",
      "disabled — полностью отключает поле, даже для отправки на сервер.",
      "immutable — не является валидным атрибутом HTML.",
      "hidden — скрывает поле, но не делает его доступным для чтения.",
    ],
    moduleId: "html",
    sectionTitle: "HTML-формы и элементы управления",
    topic: "html_forms",
  },
  {
    id: "html_forms_34",
    title:
      "Будет ли отправлено значение отключенного поля (disabled) на сервер при отправке формы?",
    options: ["Да", "Нет"],
    correctAnswers: [1],
    descriptions: [
      "Да — это неверно, disabled-поля не отправляются на сервер.",
      "Нет — правильный ответ, disabled-поля игнорируются при отправке.",
    ],
    moduleId: "html",
    sectionTitle: "HTML-формы и элементы управления",
    topic: "html_forms",
  },
  {
    id: "html_forms_35",
    title: "Как визуально отличается поле с атрибутом disabled в браузере?",
    options: [
      "Оно выделено зелёным цветом",
      "Оно выглядит как обычное поле",
      "Оно становится серым и неактивным",
      "Оно подсвечивается красным",
    ],
    correctAnswers: [2],
    descriptions: [
      "Оно выделено зелёным цветом — это не так, цвет не меняется на зелёный.",
      "Оно выглядит как обычное поле — это неверно, оно становится серым.",
      "Оно становится серым и неактивным — правильный ответ.",
      "Оно подсвечивается красным — это не происходит с disabled.",
    ],
    moduleId: "html",
    sectionTitle: "HTML-формы и элементы управления",
    topic: "html_forms",
  },
  {
    id: "html_forms_36",
    title: "Может ли поле с атрибутом readonly быть отправлено на сервер?",
    options: ["Да", "Нет"],
    correctAnswers: [0],
    descriptions: [
      "Да — правильный ответ, данные отправляются на сервер.",
      "Нет — это неверно, значение отправляется, но не редактируется.",
    ],
    moduleId: "html",
    sectionTitle: "HTML-формы и элементы управления",
    topic: "html_forms",
  },
  {
    id: "html_forms_37",
    title:
      "Какой атрибут следует использовать, чтобы заблокировать изменение значения в поле, но оставить его видимым и доступным для отправки?",
    options: ["disabled", "readonly", "hidden", "lock"],
    correctAnswers: [1],
    descriptions: [
      "disabled — полностью отключает поле, оно не отправляется.",
      "readonly — правильный ответ, значение видно, но изменить его нельзя.",
      "hidden — скрывает поле, но не блокирует ввод.",
      "lock — не существует в HTML.",
    ],
    moduleId: "html",
    sectionTitle: "HTML-формы и элементы управления",
    topic: "html_forms",
  },
  {
    id: "html_forms_38",
    title: "Может ли атрибут required использоваться с <textarea>?",
    options: ["Да", "Нет"],
    correctAnswers: [0],
    descriptions: [
      "Да — правильный ответ, <textarea> поддерживает атрибут required.",
      "Нет — это неверно, поддержка есть.",
    ],
    moduleId: "html",
    sectionTitle: "HTML-формы и элементы управления",
    topic: "html_forms",
  },
  {
    id: "html_forms_39",
    title:
      "Какой атрибут предотвратит изменение значения <select> на странице, но оставит его отправляемым?",
    options: ["disabled", "readonly", "locked", "immutable"],
    correctAnswers: [1],
    descriptions: [
      "disabled — полностью отключает <select>, его значение не отправляется.",
      "readonly — правильный ответ, оставляет видимым, но не изменяемым.",
      "locked — не существует в HTML.",
      "immutable — не является валидным атрибутом.",
    ],
    moduleId: "html",
    sectionTitle: "HTML-формы и элементы управления",
    topic: "html_forms",
  },
  {
    id: "html_forms_40",
    title: "Какой атрибут делает кнопку <button> неактивной?",
    options: ["readonly", "disabled", "required", "inactive"],
    correctAnswers: [1],
    descriptions: [
      "readonly — не используется с кнопками.",
      "disabled — правильный ответ, делает кнопку неактивной.",
      "required — применяется к полям формы, а не к кнопкам.",
      "inactive — не является валидным атрибутом HTML.",
    ],
    moduleId: "html",
    sectionTitle: "HTML-формы и элементы управления",
    topic: "html_forms",
  },
  {
    id: "html_forms_41",
    title:
      "Можно ли добавить атрибут required к <select> для обязательного выбора?",
    options: ["Да", "Нет"],
    correctAnswers: [0],
    descriptions: [
      "Да — правильный ответ, <select> поддерживает атрибут required.",
      "Нет — это неверно, required работает с <select>.",
    ],
    moduleId: "html",
    sectionTitle: "HTML-формы и элементы управления",
    topic: "html_forms",
  },
  {
    id: "html_forms_42",
    title:
      "Какой атрибут HTML полностью отключает взаимодействие с элементом формы?",
    options: ["readonly", "disabled", "required", "inactive"],
    correctAnswers: [1],
    descriptions: [
      "readonly — позволяет видеть значение, но не отключает взаимодействие.",
      "disabled — правильный ответ, элемент становится полностью неактивным.",
      "required — требует ввода, но не блокирует поле.",
      "inactive — не является атрибутом HTML.",
    ],
    moduleId: "html",
    sectionTitle: "HTML-формы и элементы управления",
    topic: "html_forms",
  },
  {
    id: "html_forms_43",
    title:
      "Какой атрибут позволяет сделать поле формы обязательным для заполнения?",
    options: ["required", "disabled", "readonly", "mandatory"],
    correctAnswers: [0],
    descriptions: [
      "required — правильный ответ, делает поле обязательным.",
      "disabled — блокирует ввод, но не требует заполнения.",
      "readonly — позволяет видеть значение, но не изменять его.",
      "mandatory — не является валидным атрибутом HTML.",
    ],
    moduleId: "html",
    sectionTitle: "HTML-формы и элементы управления",
    topic: "html_forms",
  },
  {
    id: "html_forms_44",
    title:
      "Какой атрибут используется для задания минимального значения в числовом поле?",
    options: ["min", "max", "step", "range"],
    correctAnswers: [0],
    descriptions: [
      "min — правильный ответ, задаёт минимально допустимое значение.",
      "max — задаёт максимальное допустимое значение.",
      "step — определяет шаг увеличения/уменьшения.",
      "range — это тип <input>, но не атрибут.",
    ],
    moduleId: "html",
    sectionTitle: "HTML-формы и элементы управления",
    topic: "html_forms",
  },
  {
    id: "html_forms_45",
    title: "Какой атрибут следует использовать для проверки формата email?",
    options: ["type='text'", "type='email'", "pattern", "type='url'"],
    correctAnswers: [1],
    descriptions: [
      "type='text' — это стандартное текстовое поле, не проверяет формат.",
      "type='email' — правильный ответ, автоматически проверяет наличие '@' и домена.",
      "pattern — можно использовать, но type='email' делает это автоматически.",
      "type='url' — проверяет формат URL, а не email.",
    ],
    moduleId: "html",
    sectionTitle: "HTML-формы и элементы управления",
    topic: "html_forms",
  },
  {
    id: "html_forms_46",
    title: "Какой атрибут ограничивает максимальную длину вводимого текста?",
    options: ["maxlength", "length", "size", "max"],
    correctAnswers: [0],
    descriptions: [
      "maxlength — правильный ответ, ограничивает количество символов.",
      "length — не является атрибутом HTML.",
      "size — определяет ширину поля в символах, но не ограничивает ввод.",
      "max — используется для числовых значений, но не для текста.",
    ],
    moduleId: "html",
    sectionTitle: "HTML-формы и элементы управления",
    topic: "html_forms",
  },
  {
    id: "html_forms_47",
    title:
      "Какой атрибут <input> позволяет задать регулярное выражение для валидации?",
    options: ["pattern", "regexp", "match", "validate"],
    correctAnswers: [0],
    descriptions: [
      "pattern — правильный ответ, позволяет задать регулярное выражение.",
      "regexp — не является валидным атрибутом HTML.",
      "match — это метод в JavaScript, но не атрибут HTML.",
      "validate — не существует в HTML.",
    ],
    moduleId: "html",
    sectionTitle: "HTML-формы и элементы управления",
    topic: "html_forms",
  },
  {
    id: "html_forms_48",
    title:
      "Какой атрибут используется для задания шага при выборе числового значения?",
    options: ["min", "step", "range", "max"],
    correctAnswers: [1],
    descriptions: [
      "min — определяет минимальное значение, но не шаг.",
      "step — правильный ответ, задаёт шаг при выборе значения.",
      "range — это тип <input>, но не атрибут.",
      "max — определяет максимальное значение, но не шаг.",
    ],
    moduleId: "html",
    sectionTitle: "HTML-формы и элементы управления",
    topic: "html_forms",
  },
  {
    id: "html_forms_49",
    title:
      "Какой атрибут нужно использовать для ввода только чисел в поле формы?",
    options: ["type='text'", "type='number'", "type='range'", "pattern"],
    correctAnswers: [1],
    descriptions: [
      "type='text' — позволяет ввести любой текст.",
      "type='number' — правильный ответ, ограничивает ввод только числами.",
      "type='range' — создаёт слайдер, но не позволяет ввести число вручную.",
      "pattern — можно использовать, но type='number' делает это автоматически.",
    ],
    moduleId: "html",
    sectionTitle: "HTML-формы и элементы управления",
    topic: "html_forms",
  },
  {
    id: "html_forms_50",
    title:
      "Что произойдёт, если ввести некорректный email в поле с type='email'?",
    options: [
      "Форма отправится, но с предупреждением",
      "Форма не отправится, браузер покажет ошибку",
      "Поля очистятся автоматически",
      "Браузер заменит email на 'example@example.com'",
    ],
    correctAnswers: [1],
    descriptions: [
      "Форма отправится, но с предупреждением — это неверно, отправка заблокируется.",
      "Форма не отправится, браузер покажет ошибку — правильный ответ.",
      "Поля очистятся автоматически — это не происходит автоматически.",
      "Браузер заменит email на 'example@example.com' — это невозможно.",
    ],
    moduleId: "html",
    sectionTitle: "HTML-формы и элементы управления",
    topic: "html_forms",
  },
  {
    id: "html_forms_51",
    title: "Какой атрибут позволяет ограничить вводимую дату диапазоном?",
    options: ["min", "max", "range", "step"],
    correctAnswers: [0, 1],
    descriptions: [
      "min — правильный ответ, задаёт минимально допустимую дату.",
      "max — правильный ответ, задаёт максимально допустимую дату.",
      "range — не используется в <input type='date'>.",
      "step — регулирует шаг, но не диапазон.",
    ],
    moduleId: "html",
    sectionTitle: "HTML-формы и элементы управления",
    topic: "html_forms",
  },
  {
    id: "html_forms_52",
    title: "Какой атрибут позволяет ввести URL-адрес и проверить его формат?",
    options: ["type='text'", "type='url'", "type='email'", "type='link'"],
    correctAnswers: [1],
    descriptions: [
      "type='text' — это просто текстовое поле, без проверки формата.",
      "type='url' — правильный ответ, позволяет проверить URL.",
      "type='email' — проверяет формат email, а не URL.",
      "type='link' — не существует в HTML.",
    ],
    moduleId: "html",
    sectionTitle: "HTML-формы и элементы управления",
    topic: "html_forms",
  },
];
