export const htmlStructureQuestions = [
  {
    id: "html_structure_21",
    title: "Какой тег должен быть первым в HTML-документе?",
    options: ["<html>", "<!DOCTYPE html>", "<head>", "<body>"],
    correctAnswers: [1],
    descriptions: [
      "<html> — корневой элемент, но не первый.",
      "<!DOCTYPE html> — объявление типа документа, должно быть первой строкой.",
      "<head> — идёт после <!DOCTYPE html> и <html>.",
      "<body> — содержимое, размещается после <head>.",
    ],
    moduleId: "html",
    sectionTitle: "Структура HTML-документа",
    topic: "html_structure",
  },
  {
    id: "html_structure_22",
    title: "Какой тег является корневым для всего HTML-документа?",
    options: ["<!DOCTYPE>", "<head>", "<html>", "<body>"],
    correctAnswers: [2],
    descriptions: [
      "<!DOCTYPE> — не является тегом, это объявление.",
      "<head> — содержит метаданные, но не корневой.",
      "<html> — корневой элемент, оборачивает весь документ.",
      "<body> — содержит контент, но вложен в <html>.",
    ],
    moduleId: "html",
    sectionTitle: "Структура HTML-документа",
    topic: "html_structure",
  },
  {
    id: "html_structure_23",
    title: "Какой раздел содержит метаданные документа?",
    options: ["<body>", "<header>", "<head>", "<meta>"],
    correctAnswers: [2],
    descriptions: [
      "<body> — содержит контент, а не метаданные.",
      "<header> — секция для заголовка страницы, но не метаданные.",
      "<head> — содержит метатеги, заголовок, подключения CSS/JS.",
      "<meta> — это тег внутри <head>, а не раздел.",
    ],
    moduleId: "html",
    sectionTitle: "Структура HTML-документа",
    topic: "html_structure",
  },
  {
    id: "html_structure_24",
    title: "Какой тег указывает кодировку документа?",
    options: ["<title>", "<meta charset='UTF-8'>", "<link>", "<style>"],
    correctAnswers: [1],
    descriptions: [
      "<title> — задаёт заголовок вкладки, не кодировку.",
      "<meta charset='UTF-8'> — определяет кодировку символов.",
      "<link> — подключает ресурсы, не влияет на кодировку.",
      "<style> — для CSS-стилей, не для кодировки.",
    ],
    moduleId: "html",
    sectionTitle: "Структура HTML-документа",
    topic: "html_structure",
  },
  {
    id: "html_structure_25",
    title: "Где должен располагаться тег <title>?",
    options: [
      "Внутри <body>",
      "Внутри <head>",
      "Внутри <html> но вне <head>",
      "Перед <!DOCTYPE html>",
    ],
    correctAnswers: [1],
    descriptions: [
      "<body> — для контента, <title> здесь недопустим.",
      "<head> — корректное место для <title>.",
      "<html> — но только внутри <head>, а не вне его.",
      "До <!DOCTYPE> — нарушит структуру документа.",
    ],
    moduleId: "html",
    sectionTitle: "Структура HTML-документа",
    topic: "html_structure",
  },
  {
    id: "html_structure_26",
    title: "Какой тег содержит основное содержимое страницы?",
    options: ["<head>", "<main>", "<body>", "<content>"],
    correctAnswers: [2],
    descriptions: [
      "<head> — для метаданных, не для контента.",
      "<main> — смысловой контент, но вложен в <body>.",
      "<body> — основной контейнер для содержимого.",
      "<content> — не является стандартным тегом.",
    ],
    moduleId: "html",
    sectionTitle: "Структура HTML-документа",
    topic: "html_structure",
  },
  {
    id: "html_structure_27",
    title: "Что произойдёт, если пропустить <!DOCTYPE html>?",
    options: [
      "Страница не откроется",
      "Браузер включит режим совместимости (quirks mode)",
      "Контент не отобразится",
      "Ничего, это необязательно",
    ],
    correctAnswers: [1],
    descriptions: [
      "Страница откроется, но возможны ошибки.",
      "Режим совместимости — устаревший способ рендеринга.",
      "Контент отобразится, но некорректно.",
      "<!DOCTYPE> обязательно для стандартного режима.",
    ],
    moduleId: "html",
    sectionTitle: "Структура HTML-документа",
    topic: "html_structure",
  },
  {
    id: "html_structure_28",
    title: "Какой атрибут тега <meta> указывает кодировку?",
    options: ["name", "content", "charset", "type"],
    correctAnswers: [2],
    descriptions: [
      "name — для других метаданных (например, description).",
      "content — используется с name, но не для кодировки.",
      "charset — прямое указание кодировки (например, UTF-8).",
      "type — для MIME-типов, не для кодировки.",
    ],
    moduleId: "html",
    sectionTitle: "Структура HTML-документа",
    topic: "html_structure",
  },
  {
    id: "html_structure_29",
    title: "Какой тег отображается в заголовке вкладки браузера?",
    options: ["<h1>", "<header>", "<title>", "<meta title='...'>"],
    correctAnswers: [2],
    descriptions: [
      "<h1> — заголовок на странице, не во вкладке.",
      "<header> — шапка сайта, не связана с вкладкой.",
      "<title> — текст во вкладке браузера.",
      "<meta title> — не существует.",
    ],
    moduleId: "html",
    sectionTitle: "Структура HTML-документа",
    topic: "html_structure",
  },
  {
    id: "html_structure_30",
    title: "Какие теги должны быть в минимальном HTML-документе?",
    options: [
      "<!DOCTYPE>, <html>, <body>",
      "<!DOCTYPE>, <html>, <head>, <body>",
      "<html>, <head>, <body>",
      "<!DOCTYPE>, <html>, <head>, <meta>, <body>",
    ],
    correctAnswers: [1],
    descriptions: [
      "Пропущен <head> — неполная структура.",
      "Минимум: <!DOCTYPE>, <html>, <head>, <body>.",
      "Пропущен <!DOCTYPE> — нарушение стандарта.",
      "<meta> желателен, но не обязателен для минимальной структуры.",
    ],
    moduleId: "html",
    sectionTitle: "Структура HTML-документа",
    topic: "html_structure",
  },
  {
    id: "html_structure_31",
    title: "Для чего используется <!DOCTYPE html>?",
    options: [
      "Для подключения CSS",
      "Для объявления типа документа и стандартного режима",
      "Для указания языка страницы",
      "Для вставки комментария",
    ],
    correctAnswers: [1],
    descriptions: [
      "CSS подключается через <link> или <style>.",
      "Объявление типа документа и стандартного режима рендеринга.",
      "Язык указывается в атрибуте lang у <html>.",
      "Комментарии используют <!-- ... -->.",
    ],
    moduleId: "html",
    sectionTitle: "Структура HTML-документа",
    topic: "html_structure",
  },
  {
    id: "html_structure_32",
    title: "Где рекомендуется указывать атрибут lang?",
    options: [
      "В <!DOCTYPE html>",
      "В теге <html>",
      "В теге <head>",
      "В теге <body>",
    ],
    correctAnswers: [1],
    descriptions: [
      "<!DOCTYPE> не поддерживает атрибуты.",
      "<html lang='ru'> — правильное место.",
      "<head> — не для указания языка.",
      "<body> — не влияет на определение языка.",
    ],
    moduleId: "html",
    sectionTitle: "Структура HTML-документа",
    topic: "html_structure",
  },
  {
    id: "html_structure_33",
    title: "Какой тег НЕ является обязательным в HTML5?",
    options: ["<html>", "<head>", "<body>", "<meta charset>"],
    correctAnswers: [3],
    descriptions: [
      "<html> — обязательный корневой элемент.",
      "<head> — обязателен (даже если пуст).",
      "<body> — обязателен для контента.",
      "<meta charset> — крайне рекомендуется, но технически без него документ будет работать.",
    ],
    moduleId: "html",
    sectionTitle: "Структура HTML-документа",
    topic: "html_structure",
  },
  {
    id: "html_structure_34",
    title: "Какой элемент НЕ должен находиться в <head>?",
    options: ["<title>", "<script>", "<h1>", "<meta>"],
    correctAnswers: [2],
    descriptions: [
      "<title> — обязателен в <head>.",
      "<script> — может быть в <head> (хотя часто размещают перед </body>).",
      "<h1> — контентный тег, принадлежит <body>.",
      "<meta> — стандартный элемент <head>.",
    ],
    moduleId: "html",
    sectionTitle: "Структура HTML-документа",
    topic: "html_structure",
  },
  {
    id: "html_structure_35",
    title: "Какой тег используется для подключения CSS-файла?",
    options: ["<style>", "<link>", "<script>", "<css>"],
    correctAnswers: [1],
    descriptions: [
      "<style> — для встроенных стилей, не для файлов.",
      "<link rel='stylesheet'> — правильный способ.",
      "<script> — для JavaScript, не CSS.",
      "<css> — не существует.",
    ],
    moduleId: "html",
    sectionTitle: "Структура HTML-документа",
    topic: "html_structure",
  },
  {
    id: "html_structure_36",
    title: "Куда правильно вставлять JavaScript-код?",
    options: [
      "Только в <head>",
      "Только в <body>",
      "В <head> или перед закрывающим </body>",
      "Только в отдельный файл",
    ],
    correctAnswers: [2],
    descriptions: [
      "Не только в <head> — это может замедлить загрузку.",
      "Не только в <body> — можно и в <head>.",
      "Оба варианта допустимы, но рекомендуют перед </body>.",
      "Можно и в HTML, и в отдельный файл.",
    ],
    moduleId: "html",
    sectionTitle: "Структура HTML-документа",
    topic: "html_structure",
  },
  {
    id: "html_structure_37",
    title: "Какой тег определяет заголовок документа?",
    options: ["<h1>", "<title>", "<header>", "<head>"],
    correctAnswers: [1],
    descriptions: [
      "<h1> — заголовок на странице, не документа.",
      "<title> — заголовок вкладки/документа.",
      "<header> — шапка сайта, не заголовок документа.",
      "<head> — контейнер метаданных.",
    ],
    moduleId: "html",
    sectionTitle: "Структура HTML-документа",
    topic: "html_structure",
  },
  {
    id: "html_structure_38",
    title: "Какой элемент НЕ является частью базовой структуры?",
    options: ["<!DOCTYPE html>", "<nav>", "<html>", "<head>"],
    correctAnswers: [1],
    descriptions: [
      "<!DOCTYPE> — обязателен.",
      "<nav> — опционален (для навигации).",
      "<html> — корневой элемент.",
      "<head> — обязателен.",
    ],
    moduleId: "html",
    sectionTitle: "Структура HTML-документа",
    topic: "html_structure",
  },
  {
    id: "html_structure_39",
    title: "Какой атрибут тега <html> указывает язык документа?",
    options: ["lang", "language", "xml:lang", "locale"],
    correctAnswers: [0],
    descriptions: [
      "lang — основной атрибут (например, <html lang='ru'>).",
      "language — не существует.",
      "xml:lang — устаревший для XHTML.",
      "locale — не используется.",
    ],
    moduleId: "html",
    sectionTitle: "Структура HTML-документа",
    topic: "html_structure",
  },
  {
    id: "html_structure_40",
    title: "Какой тег НЕ должен быть пустым?",
    options: ["<head>", "<body>", "<html>", "<title>"],
    correctAnswers: [3],
    descriptions: [
      "<head> — может быть пустым (хотя обычно нет).",
      "<body> — технически может быть пустым.",
      "<html> — допустим пустым (но бессмысленно).",
      "<title> — должен содержать текст, иначе SEO-проблемы.",
    ],
    moduleId: "html",
    sectionTitle: "Структура HTML-документа",
    topic: "html_structure",
  },
];
