export const htmlAtribut = [
  {
    id: "html_attributes_1",
    title:
      "Какой атрибут используется для уникальной идентификации элемента на странице?",
    options: ["name", "id", "class", "tag"],
    correctAnswers: [1],
    descriptions: [
      "name - используется в формах, но не уникален",
      "id - правильный ответ, должен быть уникальным",
      "class - для группировки элементов",
      "tag - не является HTML атрибутом",
    ],
    moduleId: "html",
    sectionTitle: "Атрибуты элементов",
    topic: "html_attributes",
  },
  {
    id: "html_attributes_2",
    title: "Можно ли использовать один и тот же id для нескольких элементов?",
    options: [
      "Да, если они разных типов",
      "Да, если они в разных секциях страницы",
      "Нет, id должен быть уникальным",
      "Да, если они невидимы",
    ],
    correctAnswers: [2],
    descriptions: [
      "Нет, не зависит от типа элементов",
      "Нет, даже в разных секциях",
      "Правильный ответ - id должен быть уникальным",
      "Нет, видимость не влияет",
    ],
    moduleId: "html",
    sectionTitle: "Атрибуты элементов",
    topic: "html_attributes",
  },
  {
    id: "html_attributes_3",
    title:
      "Какой атрибут следует использовать для групповой стилизации элементов?",
    options: ["id", "class", "style", "group"],
    correctAnswers: [1],
    descriptions: [
      "id - для уникальных элементов",
      "class - правильный ответ",
      "style - для inline-стилей",
      "group - не является атрибутом",
    ],
    moduleId: "html",
    sectionTitle: "Атрибуты элементов",
    topic: "html_attributes",
  },
  {
    id: "html_attributes_4",
    title: "Какой CSS-селектор используется для выбора элемента по id?",
    options: [".", "#", ":", "[]"],
    correctAnswers: [1],
    descriptions: [
      ". - для классов",
      "# - правильный ответ",
      ": - для псевдоклассов",
      "[] - для атрибутов",
    ],
    moduleId: "html",
    sectionTitle: "Атрибуты элементов",
    topic: "html_attributes",
  },
  {
    id: "html_attributes_5",
    title: "Какой метод JavaScript используется для выбора элемента по id?",
    options: [
      "document.querySelector()",
      "document.getElementById()",
      "document.getElementsByClassName()",
      "document.findElement()",
    ],
    correctAnswers: [1],
    descriptions: [
      "querySelector - универсальный метод",
      "getElementById - правильный ответ",
      "getElementsByClassName - для классов",
      "findElement - не существует",
    ],
    moduleId: "html",
    sectionTitle: "Атрибуты элементов",
    topic: "html_attributes",
  },
  {
    id: "html_attributes_6",
    title:
      "Какой атрибут позволяет задавать стили непосредственно в HTML-элементе?",
    options: ["css", "class", "style", "design"],
    correctAnswers: [2],
    descriptions: [
      "css - не является атрибутом",
      "class - для классов стилей",
      "style - правильный ответ",
      "design - не существует",
    ],
    moduleId: "html",
    sectionTitle: "Атрибуты элементов",
    topic: "html_attributes",
  },
  {
    id: "html_attributes_7",
    title: "Почему не рекомендуется часто использовать атрибут style?",
    options: [
      "Он работает медленнее",
      "Трудно поддерживать и переопределять стили",
      "Он не поддерживается старыми браузерами",
      "Он не работает с JavaScript",
    ],
    correctAnswers: [1],
    descriptions: [
      "Не влияет на производительность",
      "Правильный ответ - сложность поддержки",
      "Поддерживается всеми браузерами",
      "Полностью работает с JS",
    ],
    moduleId: "html",
    sectionTitle: "Атрибуты элементов",
    topic: "html_attributes",
  },
  {
    id: "html_attributes_8",
    title: "Как правильно задать несколько классов для элемента?",
    options: [
      "class='header' 'main'",
      "class='header main'",
      "class='header, main'",
      "class='header+main'",
    ],
    correctAnswers: [1],
    descriptions: [
      "Неверный синтаксис",
      "Правильный ответ - через пробел",
      "Запятые не используются",
      "Знак + не используется",
    ],
    moduleId: "html",
    sectionTitle: "Атрибуты элементов",
    topic: "html_attributes",
  },
  {
    id: "html_attributes_9",
    title: "Какой атрибут следует использовать для связи <label> с <input>?",
    options: ["name", "id", "for", "link"],
    correctAnswers: [2],
    descriptions: [
      "name - для именования полей формы",
      "id - нужен для связи, но не в этом атрибуте",
      "for - правильный ответ, указывает на id элемента",
      "link - не используется для этой цели",
    ],
    moduleId: "html",
    sectionTitle: "Атрибуты элементов",
    topic: "html_attributes",
  },
  {
    id: "html_attributes_10",
    title:
      "Какой метод JavaScript используется для выбора всех элементов с определенным классом?",
    options: [
      "document.getElementById()",
      "document.querySelector()",
      "document.getElementsByClassName()",
      "document.findElements()",
    ],
    correctAnswers: [2],
    descriptions: [
      "getElementById - для одного элемента по id",
      "querySelector - для первого совпадения",
      "getElementsByClassName - правильный ответ",
      "findElements - не существует",
    ],
    moduleId: "html",
    sectionTitle: "Атрибуты элементов",
    topic: "html_attributes",
  },
  {
    id: "html_attributes_11",
    title: "Какой атрибут является глобальным в HTML?",
    options: ["href", "src", "title", "alt"],
    correctAnswers: [2],
    descriptions: [
      "href - только для ссылок",
      "src - только для медиа",
      "title - правильный ответ, глобальный атрибут",
      "alt - только для изображений",
    ],
    moduleId: "html",
    sectionTitle: "Атрибуты элементов",
    topic: "html_attributes",
  },
  {
    id: "html_attributes_12",
    title: "Какой атрибут НЕ является глобальным?",
    options: ["class", "style", "id", "colspan"],
    correctAnswers: [3],
    descriptions: [
      "class - глобальный атрибут",
      "style - глобальный атрибут",
      "id - глобальный атрибут",
      "colspan - правильный ответ, только для таблиц",
    ],
    moduleId: "html",
    sectionTitle: "Атрибуты элементов",
    topic: "html_attributes",
  },
  {
    id: "html_attributes_13",
    title: "Как правильно задать id для элемента?",
    options: [
      "id='123'",
      "id='my element'",
      "id='my-element'",
      "id='myElement'",
    ],
    correctAnswers: [2, 3],
    descriptions: [
      "Нельзя начинать с цифры",
      "Пробелы не допускаются",
      "Правильный вариант с дефисом",
      "Правильный вариант в camelCase",
    ],
    moduleId: "html",
    sectionTitle: "Атрибуты элементов",
    topic: "html_attributes",
  },
  {
    id: "html_attributes_14",
    title: "Какой атрибут добавляет всплывающую подсказку при наведении?",
    options: ["alt", "title", "tooltip", "hint"],
    correctAnswers: [1],
    descriptions: [
      "alt - альтернативный текст",
      "title - правильный ответ",
      "tooltip - не является атрибутом",
      "hint - не является атрибутом",
    ],
    moduleId: "html",
    sectionTitle: "Атрибуты элементов",
    topic: "html_attributes",
  },
  {
    id: "html_attributes_15",
    title: "Какой атрибут используется для изменения порядка в табуляции?",
    options: ["tabindex", "taborder", "focusindex", "tabstop"],
    correctAnswers: [0],
    descriptions: [
      "tabindex - правильный ответ",
      "taborder - не существует",
      "focusindex - не существует",
      "tabstop - не существует",
    ],
    moduleId: "html",
    sectionTitle: "Атрибуты элементов",
    topic: "html_attributes",
  },
  {
    id: "html_attributes_16",
    title: "Какой атрибут делает элемент невидимым для скринридеров?",
    options: ["invisible", "hidden", "aria-hidden", "display-none"],
    correctAnswers: [2],
    descriptions: [
      "invisible - не является атрибутом",
      "hidden - скрывает элемент полностью",
      "aria-hidden - правильный ответ",
      "display-none - CSS свойство",
    ],
    moduleId: "html",
    sectionTitle: "Атрибуты элементов",
    topic: "html_attributes",
  },
  {
    id: "html_attributes_17",
    title:
      "Какой атрибут позволяет добавлять пользовательские данные к элементу?",
    options: ["custom", "data-*", "meta", "info"],
    correctAnswers: [1],
    descriptions: [
      "custom - не является атрибутом",
      "data-* - правильный ответ",
      "meta - не для этой цели",
      "info - не является атрибутом",
    ],
    moduleId: "html",
    sectionTitle: "Атрибуты элементов",
    topic: "html_attributes",
  },
  {
    id: "html_attributes_18",
    title: "Какой атрибут указывает язык содержимого элемента?",
    options: ["lang", "language", "xml:lang", "locale"],
    correctAnswers: [0, 2],
    descriptions: [
      "lang - правильный ответ",
      "language - не является атрибутом",
      "xml:lang - также правильный ответ",
      "locale - не является атрибутом",
    ],
    moduleId: "html",
    sectionTitle: "Атрибуты элементов",
    topic: "html_attributes",
  },
  {
    id: "html_attributes_19",
    title: "Какой атрибут делает содержимое элемента редактируемым?",
    options: ["editable", "contenteditable", "edit", "input"],
    correctAnswers: [1],
    descriptions: [
      "editable - не является атрибутом",
      "contenteditable - правильный ответ",
      "edit - не является атрибутом",
      "input - тип элемента",
    ],
    moduleId: "html",
    sectionTitle: "Атрибуты элементов",
    topic: "html_attributes",
  },
  {
    id: "html_attributes_20",
    title: "Какой атрибут указывает направление текста (rtl/ltr)?",
    options: ["text-direction", "dir", "direction", "writing-mode"],
    correctAnswers: [1],
    descriptions: [
      "text-direction - не является атрибутом",
      "dir - правильный ответ",
      "direction - CSS свойство",
      "writing-mode - CSS свойство",
    ],
    moduleId: "html",
    sectionTitle: "Атрибуты элементов",
    topic: "html_attributes",
  },
  {
    id: "html_attributes_21",
    title:
      "Какой атрибут используется для указания адреса перехода при клике на ссылку?",
    options: ["src", "href", "alt", "link"],
    correctAnswers: [1],
    descriptions: [
      "src — используется для загрузки внешних ресурсов (изображений, видео, аудио).",
      "href — правильный ответ, указывает адрес перехода.",
      "alt — альтернативный текст для изображений.",
      "link — не является атрибутом тега <a>.",
    ],
    moduleId: "html",
    sectionTitle: "Атрибуты элементов",
    topic: "html_attributes",
  },
  {
    id: "html_attributes_22",
    title:
      "Какой атрибут используется для задания пути к изображению в теге <img>?",
    options: ["href", "src", "alt", "data-src"],
    correctAnswers: [1],
    descriptions: [
      "href — применяется только в ссылках (<a>).",
      "src — правильный ответ, используется для загрузки изображения.",
      "alt — это альтернативный текст для изображения.",
      "data-src — используется в lazy loading, но не является стандартным атрибутом.",
    ],
    moduleId: "html",
    sectionTitle: "Атрибуты элементов",
    topic: "html_attributes",
  },
  {
    id: "html_attributes_23",
    title:
      "Какой атрибут следует использовать для альтернативного текста изображения?",
    options: ["href", "src", "alt", "title"],
    correctAnswers: [2],
    descriptions: [
      "href — не используется в <img>.",
      "src — отвечает за путь к изображению.",
      "alt — правильный ответ, альтернативный текст для изображений.",
      "title — добавляет всплывающую подсказку.",
    ],
    moduleId: "html",
    sectionTitle: "Атрибуты элементов",
    topic: "html_attributes",
  },
  {
    id: "html_attributes_24",
    title: "Какой атрибут используется для вставки видео в HTML?",
    options: ["href", "src", "alt", "link"],
    correctAnswers: [1],
    descriptions: [
      "href — используется только в ссылках.",
      "src — правильный ответ, указывает путь к видео.",
      "alt — применим только к изображениям.",
      "link — это элемент, а не атрибут.",
    ],
    moduleId: "html",
    sectionTitle: "Атрибуты элементов",
    topic: "html_attributes",
  },
  {
    id: "html_attributes_25",
    title: "Какой атрибут позволяет открывать ссылку в новом окне?",
    options: ["target", "href", "rel", "src"],
    correctAnswers: [0],
    descriptions: [
      "target — правильный ответ, его значение '_blank' открывает ссылку в новом окне.",
      "href — задаёт путь перехода, но не открывает в новом окне.",
      "rel — используется для определения отношений между текущим документом и ссылкой.",
      "src — используется для медиа-ресурсов (картинки, видео).",
    ],
    moduleId: "html",
    sectionTitle: "Атрибуты элементов",
    topic: "html_attributes",
  },
  {
    id: "html_attributes_26",
    title:
      "Какой атрибут указывает заголовок всплывающей подсказки при наведении?",
    options: ["placeholder", "title", "alt", "label"],
    correctAnswers: [1],
    descriptions: [
      "placeholder — отображается в полях ввода.",
      "title — правильный ответ, добавляет всплывающую подсказку.",
      "alt — альтернативный текст для изображений.",
      "label — используется для связки с полем формы.",
    ],
    moduleId: "html",
    sectionTitle: "Атрибуты элементов",
    topic: "html_attributes",
  },
  {
    id: "html_attributes_27",
    title:
      "Какой атрибут используется для включения управления плеером в <video> и <audio>?",
    options: ["controls", "autoplay", "loop", "muted"],
    correctAnswers: [0],
    descriptions: [
      "controls — правильный ответ, отображает кнопки управления плеером.",
      "autoplay — запускает видео автоматически.",
      "loop — воспроизводит в цикле.",
      "muted — отключает звук по умолчанию.",
    ],
    moduleId: "html",
    sectionTitle: "Атрибуты элементов",
    topic: "html_attributes",
  },
  {
    id: "html_attributes_28",
    title:
      "Какой атрибут позволяет автоматически запустить видео при загрузке страницы?",
    options: ["autoplay", "controls", "loop", "muted"],
    correctAnswers: [0],
    descriptions: [
      "autoplay — правильный ответ, запускает видео автоматически.",
      "controls — добавляет элементы управления.",
      "loop — воспроизводит видео в цикле.",
      "muted — выключает звук при запуске.",
    ],
    moduleId: "html",
    sectionTitle: "Атрибуты элементов",
    topic: "html_attributes",
  },
  {
    id: "html_attributes_29",
    title:
      "Какой атрибут используется для отключения звука у видео или аудио по умолчанию?",
    options: ["autoplay", "controls", "loop", "muted"],
    correctAnswers: [3],
    descriptions: [
      "autoplay — запускает видео автоматически.",
      "controls — отображает элементы управления.",
      "loop — воспроизводит в цикле.",
      "muted — правильный ответ, отключает звук.",
    ],
    moduleId: "html",
    sectionTitle: "Атрибуты элементов",
    topic: "html_attributes",
  },
  {
    id: "html_attributes_30",
    title: "Какой атрибут используется для указания основного языка документа?",
    options: ["lang", "dir", "locale", "charset"],
    correctAnswers: [0],
    descriptions: [
      "lang — правильный ответ, задаёт язык для всего документа.",
      "dir — определяет направление текста.",
      "locale — не является стандартным атрибутом HTML.",
      "charset — отвечает за кодировку символов, но не за язык.",
    ],
    moduleId: "html",
    sectionTitle: "Атрибуты элементов",
    topic: "html_attributes",
  },
  {
    id: "html_attributes_31",
    title: "Какой префикс должны иметь пользовательские атрибуты в HTML?",
    options: ["user-", "custom-", "data-", "attr-"],
    correctAnswers: [2],
    descriptions: [
      "user- — не является стандартом HTML.",
      "custom- — также не является стандартом HTML.",
      "data- — правильный ответ, префикс для пользовательских атрибутов.",
      "attr- — это просто пример, не существует в спецификации.",
    ],
    moduleId: "html",
    sectionTitle: "Атрибуты элементов",
    topic: "html_attributes",
  },
  {
    id: "html_attributes_32",
    title: "Как получить значение data-* атрибута в JavaScript?",
    options: [
      "element.getAttribute('data-*')",
      "element.dataset.*",
      "element.data.*",
      "element.getDataAttribute('*')",
    ],
    correctAnswers: [1],
    descriptions: [
      "element.getAttribute('data-*') — работает, но не рекомендуется для data-*.",
      "element.dataset.* — правильный ответ, доступ к data-* через dataset.",
      "element.data.* — не существует такого свойства.",
      "element.getDataAttribute('*') — неверный способ доступа.",
    ],
    moduleId: "html",
    sectionTitle: "Атрибуты элементов",
    topic: "html_attributes",
  },
  {
    id: "html_attributes_33",
    title: "Какое название будет у data-item-id в объекте dataset?",
    options: ["itemid", "dataItemId", "itemId", "data-item-id"],
    correctAnswers: [2],
    descriptions: [
      "itemid — название должно быть в camelCase.",
      "dataItemId — 'data' префикс убирается при доступе.",
      "itemId — правильный ответ, атрибут конвертируется в camelCase.",
      "data-item-id — это оригинальный формат в HTML, но не в JavaScript.",
    ],
    moduleId: "html",
    sectionTitle: "Атрибуты элементов",
    topic: "html_attributes",
  },
  {
    id: "html_attributes_34",
    title: "Какая из строк корректно устанавливает значение data-user-name?",
    options: [
      "element.dataUserName = 'John';",
      "element.setAttribute('data-user-name', 'John');",
      "element.dataset.username = 'John';",
      "element.dataset.userName = 'John';",
    ],
    correctAnswers: [1, 3],
    descriptions: [
      "element.dataUserName = 'John'; — неверный синтаксис.",
      "element.setAttribute('data-user-name', 'John'); — правильный способ установки атрибута напрямую.",
      "element.dataset.username = 'John'; — неверное имя в dataset.",
      "element.dataset.userName = 'John'; — правильный способ через dataset.",
    ],
    moduleId: "html",
    sectionTitle: "Атрибуты элементов",
    topic: "html_attributes",
  },
  {
    id: "html_attributes_35",
    title: "Какие преимущества использования data-* атрибутов?",
    options: [
      "Хранение пользовательских данных в HTML",
      "Передача данных без использования глобальных переменных",
      "Прямая привязка к стилям CSS",
      "Доступ к данным без дополнительных запросов",
    ],
    correctAnswers: [0, 1, 3],
    descriptions: [
      "Хранение пользовательских данных в HTML — это основное назначение data-* атрибутов.",
      "Передача данных без использования глобальных переменных — это удобно и изолированно.",
      "Прямая привязка к стилям CSS — не является функцией data-* атрибутов.",
      "Доступ к данным без дополнительных запросов — data-* позволяет это делать.",
    ],
    moduleId: "html",
    sectionTitle: "Атрибуты элементов",
    topic: "html_attributes",
  },
  {
    id: "html_attributes_36",
    title:
      "Какое значение вернёт dataset, если атрибут data-price отсутствует?",
    options: ["undefined", "null", "0", "Пустая строка"],
    correctAnswers: [0],
    descriptions: [
      "undefined — правильный ответ, если атрибут не существует, dataset вернёт undefined.",
      "null — вернулось бы, если бы значение существовало, но было null.",
      "0 — возвращается только, если значение было бы '0'.",
      "Пустая строка — вернулось бы, если атрибут был бы пустым, но присутствовал.",
    ],
    moduleId: "html",
    sectionTitle: "Атрибуты элементов",
    topic: "html_attributes",
  },
  {
    id: "html_attributes_37",
    title: "Как правильно удалить data-* атрибут у элемента?",
    options: [
      "delete element.dataset.property",
      "element.removeData('property')",
      "element.removeAttribute('data-property')",
      "element.dataset.property = null",
    ],
    correctAnswers: [2],
    descriptions: [
      "delete element.dataset.property — не сработает, dataset защищён от удаления через delete.",
      "element.removeData('property') — такого метода не существует.",
      "element.removeAttribute('data-property') — правильный способ удаления атрибута.",
      "element.dataset.property = null — это просто присвоит null, но не удалит атрибут.",
    ],
    moduleId: "html",
    sectionTitle: "Атрибуты элементов",
    topic: "html_attributes",
  },
  {
    id: "html_attributes_38",
    title: "Какой формат используется для имён в dataset в JavaScript?",
    options: ["kebab-case", "snake_case", "camelCase", "PascalCase"],
    correctAnswers: [2],
    descriptions: [
      "kebab-case — используется в HTML.",
      "snake_case — не используется в dataset.",
      "camelCase — правильный ответ, используется в JavaScript для dataset.",
      "PascalCase — не используется в dataset.",
    ],
    moduleId: "html",
    sectionTitle: "Атрибуты элементов",
    topic: "html_attributes",
  },
  {
    id: "html_attributes_39",
    title: "Могут ли data-* атрибуты быть использованы в CSS?",
    options: ["Да", "Нет"],
    correctAnswers: [0],
    descriptions: [
      "Да — можно применять селекторы [data-*] в CSS для стилизации элементов.",
      "Нет — это неверное утверждение, data-* поддерживается в CSS.",
    ],
    moduleId: "html",
    sectionTitle: "Атрибуты элементов",
    topic: "html_attributes",
  },
  {
    id: "html_attributes_40",
    title: 'Какой селектор в CSS выберет элемент с data-status="active"?',
    options: [
      "[data-status='active']",
      ".data-status-active",
      "#data-status-active",
      "[data-status-active]",
    ],
    correctAnswers: [0],
    descriptions: [
      "[data-status='active'] — правильный ответ, это стандартный селектор атрибута.",
      ".data-status-active — это селектор класса, не подходит для data-*.",
      "#data-status-active — это ID-селектор, не соответствует data-*.",
      "[data-status-active] — это неверный синтаксис.",
    ],
    moduleId: "html",
    sectionTitle: "Атрибуты элементов",
    topic: "html_attributes",
  },
  {
    id: "html_attributes_41",
    title:
      "Какой атрибут делает элемент формы неактивным (нельзя взаимодействовать)?",
    options: ["readonly", "disabled", "required", "hidden"],
    correctAnswers: [1],
    descriptions: [
      "readonly — делает поле доступным только для чтения, но не отключает.",
      "disabled — правильный ответ, элемент становится неактивным и не подаёт события.",
      "required — делает поле обязательным для заполнения, но не отключает его.",
      "hidden — скрывает элемент, но не отключает его полностью.",
    ],
    moduleId: "html",
    sectionTitle: "Атрибуты элементов",
    topic: "html_attributes",
  },
  {
    id: "html_attributes_42",
    title:
      "Какой булевый атрибут используется для обязательного заполнения поля?",
    options: ["checked", "required", "readonly", "disabled"],
    correctAnswers: [1],
    descriptions: [
      "checked — используется только для <input> типа checkbox или radio.",
      "required — правильный ответ, делает поле обязательным для заполнения.",
      "readonly — поле можно просматривать, но нельзя редактировать.",
      "disabled — делает элемент неактивным, но не обязательным.",
    ],
    moduleId: "html",
    sectionTitle: "Атрибуты элементов",
    topic: "html_attributes",
  },
  {
    id: "html_attributes_43",
    title:
      "Какой булевый атрибут используется для того, чтобы сделать поле доступным только для чтения?",
    options: ["readonly", "disabled", "required", "hidden"],
    correctAnswers: [0],
    descriptions: [
      "readonly — правильный ответ, делает поле доступным только для чтения.",
      "disabled — делает элемент неактивным и недоступным для редактирования.",
      "required — требует обязательного заполнения.",
      "hidden — просто скрывает элемент, но он доступен в DOM.",
    ],
    moduleId: "html",
    sectionTitle: "Атрибуты элементов",
    topic: "html_attributes",
  },
  {
    id: "html_attributes_44",
    title:
      "Какой атрибут используется для скрытия элемента от ассистивных технологий, таких как скринридеры?",
    options: ["aria-hidden", "hidden", "aria-disabled", "aria-expanded"],
    correctAnswers: [0],
    descriptions: [
      "aria-hidden — правильный ответ, скрывает элемент от ассистивных технологий.",
      "hidden — скрывает элемент визуально, но не гарантирует скрытие от скринридеров.",
      "aria-disabled — показывает, что элемент неактивен, но не скрывает его.",
      "aria-expanded — указывает, развёрнут элемент или нет.",
    ],
    moduleId: "html",
    sectionTitle: "Атрибуты элементов",
    topic: "html_attributes",
  },
  {
    id: "html_attributes_45",
    title:
      "Какой ARIA-атрибут используется для обозначения развёрнутого или свернутого состояния элемента?",
    options: ["aria-checked", "aria-expanded", "aria-hidden", "aria-label"],
    correctAnswers: [1],
    descriptions: [
      "aria-checked — используется для состояния чекбокса или радио.",
      "aria-expanded — правильный ответ, указывает на состояние аккордеонов, списков и других компонентов.",
      "aria-hidden — скрывает элемент от ассистивных технологий.",
      "aria-label — добавляет метку для скринридеров.",
    ],
    moduleId: "html",
    sectionTitle: "Атрибуты элементов",
    topic: "html_attributes",
  },
  {
    id: "html_attributes_46",
    title:
      "Какой булевый атрибут используется для выбора чекбокса или радио-кнопки по умолчанию?",
    options: ["selected", "checked", "required", "disabled"],
    correctAnswers: [1],
    descriptions: [
      "selected — используется для <option> в <select>, но не для чекбоксов.",
      "checked — правильный ответ, выбирает чекбокс или радио-кнопку по умолчанию.",
      "required — делает поле обязательным для заполнения, но не выбирает его.",
      "disabled — отключает элемент, но не выбирает его.",
    ],
    moduleId: "html",
    sectionTitle: "Атрибуты элементов",
    topic: "html_attributes",
  },
  {
    id: "html_attributes_47",
    title:
      "Какой атрибут используется для добавления текстовой метки, видимой только для ассистивных технологий?",
    options: ["alt", "title", "aria-label", "placeholder"],
    correctAnswers: [2],
    descriptions: [
      "alt — используется только для изображений.",
      "title — отображает всплывающую подсказку при наведении.",
      "aria-label — правильный ответ, метка видима только для скринридеров.",
      "placeholder — отображает текст в поле ввода до ввода данных.",
    ],
    moduleId: "html",
    sectionTitle: "Атрибуты элементов",
    topic: "html_attributes",
  },
  {
    id: "html_attributes_48",
    title:
      "Какой атрибут делает элемент скрытым, но оставляет его в структуре DOM?",
    options: ["hidden", "aria-hidden", "display", "opacity"],
    correctAnswers: [0],
    descriptions: [
      "hidden — правильный ответ, элемент скрыт, но остаётся в DOM.",
      "aria-hidden — скрывает от ассистивных технологий, но элемент может быть видим.",
      "display — это CSS-свойство, а не атрибут.",
      "opacity — делает элемент прозрачным, но не убирает его из DOM.",
    ],
    moduleId: "html",
    sectionTitle: "Атрибуты элементов",
    topic: "html_attributes",
  },
  {
    id: "html_attributes_49",
    title:
      "Какой ARIA-атрибут можно использовать для обозначения статуса загрузки элемента (например, загрузка данных)?",
    options: ["aria-live", "aria-busy", "aria-label", "aria-expanded"],
    correctAnswers: [1],
    descriptions: [
      "aria-live — указывает, что элемент будет обновляться динамически.",
      "aria-busy — правильный ответ, используется для обозначения, что элемент в состоянии загрузки.",
      "aria-label — добавляет метку, но не указывает на статус.",
      "aria-expanded — показывает, открыт элемент или нет.",
    ],
    moduleId: "html",
    sectionTitle: "Атрибуты элементов",
    topic: "html_attributes",
  },
  {
    id: "html_attributes_50",
    title:
      "Какой ARIA-атрибут позволяет объявить элемент как динамически обновляемый, чтобы ассистивные технологии отслеживали изменения?",
    options: ["aria-live", "aria-atomic", "aria-hidden", "aria-controls"],
    correctAnswers: [0],
    descriptions: [
      "aria-live — правильный ответ, указывает, что изменения в элементе должны быть озвучены ассистивными технологиями.",
      "aria-atomic — используется для группировки обновлений в один блок.",
      "aria-hidden — скрывает элемент от скринридеров.",
      "aria-controls — указывает, какой элемент управляет другим.",
    ],
    moduleId: "html",
    sectionTitle: "Атрибуты элементов",
    topic: "html_attributes",
  },
];
