export const htmlMetaHead = [
  {
    id: "html_meta_head_01",
    title: "Какой мета-тег используется для задания кодировки страницы?",
    options: [
      "<meta charset='UTF-8'>",
      "<meta name='viewport'>",
      "<meta name='description'>",
      "<meta name='robots'>",
    ],
    correctAnswers: [0],
    descriptions: [
      "<meta charset='UTF-8'> — правильный ответ, устанавливает кодировку страницы.",
      "<meta name='viewport'> — отвечает за адаптивность страницы.",
      "<meta name='description'> — добавляет описание страницы для SEO.",
      "<meta name='robots'> — управляет поведением поисковых роботов.",
    ],
    moduleId: "html",
    sectionTitle: "Мета-теги и <head>",
    topic: "html_meta_head",
  },
  {
    id: "html_meta_head_02",
    title: "Какой мета-тег делает сайт адаптивным на мобильных устройствах?",
    options: [
      "<meta charset='UTF-8'>",
      "<meta name='viewport'>",
      "<meta name='description'>",
      "<meta name='robots'>",
    ],
    correctAnswers: [1],
    descriptions: [
      "<meta charset='UTF-8'> — отвечает за кодировку, но не за адаптивность.",
      "<meta name='viewport'> — правильный ответ, делает сайт адаптивным.",
      "<meta name='description'> — добавляет описание страницы для SEO.",
      "<meta name='robots'> — управляет поведением поисковых роботов.",
    ],
    moduleId: "html",
    sectionTitle: "Мета-теги и <head>",
    topic: "html_meta_head",
  },
  {
    id: "html_meta_head_03",
    title:
      "Какой атрибут мета-тега viewport устанавливает масштаб по умолчанию?",
    options: ["initial-scale", "width", "height", "device-width"],
    correctAnswers: [0],
    descriptions: [
      "initial-scale — правильный ответ, задаёт начальный масштаб.",
      "width — устанавливает ширину вьюпорта.",
      "height — не используется в meta viewport.",
      "device-width — устанавливает ширину в зависимости от устройства.",
    ],
    moduleId: "html",
    sectionTitle: "Мета-теги и <head>",
    topic: "html_meta_head",
  },
  {
    id: "html_meta_head_04",
    title: "Какой мета-тег используется для добавления описания страницы?",
    options: [
      "<meta name='description'>",
      "<meta name='keywords'>",
      "<meta name='robots'>",
      "<meta charset='UTF-8'>",
    ],
    correctAnswers: [0],
    descriptions: [
      "<meta name='description'> — правильный ответ, добавляет краткое описание страницы.",
      "<meta name='keywords'> — задаёт ключевые слова, но не описание.",
      "<meta name='robots'> — управляет поведением поисковых роботов.",
      "<meta charset='UTF-8'> — устанавливает кодировку страницы.",
    ],
    moduleId: "html",
    sectionTitle: "Мета-теги и <head>",
    topic: "html_meta_head",
  },
  {
    id: "html_meta_head_05",
    title: "Какой мета-тег управляет поведением поисковых роботов на странице?",
    options: [
      "<meta name='robots'>",
      "<meta name='viewport'>",
      "<meta charset='UTF-8'>",
      "<meta name='keywords'>",
    ],
    correctAnswers: [0],
    descriptions: [
      "<meta name='robots'> — правильный ответ, управляет индексацией и переходами по ссылкам.",
      "<meta name='viewport'> — отвечает за адаптивность страницы.",
      "<meta charset='UTF-8'> — задаёт кодировку страницы.",
      "<meta name='keywords'> — задаёт ключевые слова, но не влияет на поведение роботов.",
    ],
    moduleId: "html",
    sectionTitle: "Мета-теги и <head>",
    topic: "html_meta_head",
  },
  {
    id: "html_meta_head_06",
    title: "Какой атрибут мета-тега robots запрещает индексацию страницы?",
    options: ["noindex", "nofollow", "index", "nofollowindex"],
    correctAnswers: [0],
    descriptions: [
      "noindex — правильный ответ, запрещает индексацию страницы.",
      "nofollow — запрещает переходы по ссылкам, но не индексацию.",
      "index — разрешает индексацию.",
      "nofollowindex — не существует в HTML.",
    ],
    moduleId: "html",
    sectionTitle: "Мета-теги и <head>",
    topic: "html_meta_head",
  },
  {
    id: "html_meta_head_07",
    title: "Какой мета-тег используется для задания ключевых слов страницы?",
    options: [
      "<meta name='keywords'>",
      "<meta name='description'>",
      "<meta name='robots'>",
      "<meta name='author'>",
    ],
    correctAnswers: [0],
    descriptions: [
      "<meta name='keywords'> — правильный ответ, добавляет ключевые слова.",
      "<meta name='description'> — используется для описания страницы.",
      "<meta name='robots'> — управляет поведением поисковых систем.",
      "<meta name='author'> — задаёт информацию об авторе страницы.",
    ],
    moduleId: "html",
    sectionTitle: "Мета-теги и <head>",
    topic: "html_meta_head",
  },
  {
    id: "html_meta_head_08",
    title: "Какой мета-тег указывает имя автора страницы?",
    options: [
      "<meta name='author'>",
      "<meta name='creator'>",
      "<meta name='designer'>",
      "<meta name='writer'>",
    ],
    correctAnswers: [0],
    descriptions: [
      "<meta name='author'> — правильный ответ, добавляет информацию об авторе.",
      "<meta name='creator'> — не является стандартным мета-тегом.",
      "<meta name='designer'> — не существует в HTML.",
      "<meta name='writer'> — не является валидным мета-тегом.",
    ],
    moduleId: "html",
    sectionTitle: "Мета-теги и <head>",
    topic: "html_meta_head",
  },
  {
    id: "html_meta_head_09",
    title:
      "Какой мета-тег используется для предотвращения кэширования страницы?",
    options: [
      "<meta http-equiv='cache-control'>",
      "<meta name='robots'>",
      "<meta charset='UTF-8'>",
      "<meta name='viewport'>",
    ],
    correctAnswers: [0],
    descriptions: [
      "<meta http-equiv='cache-control'> — правильный ответ, управляет кэшированием.",
      "<meta name='robots'> — управляет индексацией, но не кэшем.",
      "<meta charset='UTF-8'> — определяет кодировку.",
      "<meta name='viewport'> — отвечает за адаптивность страницы.",
    ],
    moduleId: "html",
    sectionTitle: "Мета-теги и <head>",
    topic: "html_meta_head",
  },
  {
    id: "html_meta_head_10",
    title:
      "Какой атрибут в <meta> используется для перенаправления на другую страницу?",
    options: ["refresh", "redirect", "navigate", "move"],
    correctAnswers: [0],
    descriptions: [
      "refresh — правильный ответ, задаёт перенаправление.",
      "redirect — не существует в HTML.",
      "navigate — это не атрибут <meta>.",
      "move — не является валидным атрибутом.",
    ],
    moduleId: "html",
    sectionTitle: "Мета-теги и <head>",
    topic: "html_meta_head",
  },
  {
    id: "html_meta_head_21",
    title: "Какой тег используется для задания заголовка HTML-документа?",
    options: ["<title>", "<header>", "<meta>", "<head>"],
    correctAnswers: [0],
    descriptions: [
      "<title> — правильный ответ, используется для задания заголовка страницы.",
      "<header> — это семантический элемент, но не для заголовка вкладки.",
      "<meta> — отвечает за мета-информацию, но не за заголовок.",
      "<head> — это контейнер для метаинформации, но не для заголовка страницы.",
    ],
    moduleId: "html",
    sectionTitle: "Мета-теги и <head>",
    topic: "html_meta_head",
  },
  {
    id: "html_meta_head_22",
    title: "Где в структуре HTML-документа должен располагаться тег <title>?",
    options: ["Внутри <head>", "Внутри <body>", "После <html>", "Перед <meta>"],
    correctAnswers: [0],
    descriptions: [
      "Внутри <head> — правильный ответ, тег <title> должен располагаться в <head>.",
      "Внутри <body> — это ошибка, <title> должен быть в <head>.",
      "После <html> — это некорректно, тег должен быть внутри <head>.",
      "Перед <meta> — порядок внутри <head> не критичен, но <title> часто идёт после <meta>.",
    ],
    moduleId: "html",
    sectionTitle: "Мета-теги и <head>",
    topic: "html_meta_head",
  },
  {
    id: "html_meta_head_23",
    title: "Для чего используется содержимое тега <title>?",
    options: [
      "Для отображения на странице",
      "Для SEO и заголовка во вкладке браузера",
      "Для описания в социальных сетях",
      "Для задания кодировки страницы",
    ],
    correctAnswers: [1],
    descriptions: [
      "Для отображения на странице — это неверно, он не отображается на странице.",
      "Для SEO и заголовка во вкладке браузера — правильный ответ.",
      "Для описания в социальных сетях — это мета-теги Open Graph.",
      "Для задания кодировки страницы — используется <meta charset>.",
    ],
    moduleId: "html",
    sectionTitle: "Мета-теги и <head>",
    topic: "html_meta_head",
  },
  {
    id: "html_meta_head_24",
    title: "Что произойдёт, если тег <title> отсутствует в HTML-документе?",
    options: [
      "Браузер покажет ошибку",
      "Вкладка будет пустой",
      "Название вкладки будет 'Без названия'",
      "Страница не отобразится",
    ],
    correctAnswers: [2],
    descriptions: [
      "Браузер покажет ошибку — это неверно, страница загрузится.",
      "Вкладка будет пустой — браузеры обычно добавляют 'Без названия' или URL.",
      "Название вкладки будет 'Без названия' — правильный ответ.",
      "Страница не отобразится — это неверно, страница загрузится, но без заголовка.",
    ],
    moduleId: "html",
    sectionTitle: "Мета-теги и <head>",
    topic: "html_meta_head",
  },
  {
    id: "html_meta_head_25",
    title:
      "Какой максимальной длины рекомендуется делать текст внутри тега <title> для SEO?",
    options: [
      "50-60 символов",
      "30-40 символов",
      "70-80 символов",
      "100+ символов",
    ],
    correctAnswers: [0],
    descriptions: [
      "50-60 символов — правильный ответ, это оптимальная длина для SEO.",
      "30-40 символов — можно использовать, но менее эффективно для SEO.",
      "70-80 символов — возможно, но часть текста обрежется в выдаче.",
      "100+ символов — поисковые системы обрежут этот текст.",
    ],
    moduleId: "html",
    sectionTitle: "Мета-теги и <head>",
    topic: "html_meta_head",
  },
  {
    id: "html_meta_head_26",
    title: "Может ли тег <title> содержать HTML-разметку (например, <b>, <i>)?",
    options: ["Да", "Нет"],
    correctAnswers: [1],
    descriptions: [
      "Да — это неверно, HTML внутри <title> не распознаётся.",
      "Нет — правильный ответ, <title> содержит только текст, HTML не работает.",
    ],
    moduleId: "html",
    sectionTitle: "Мета-теги и <head>",
    topic: "html_meta_head",
  },
  {
    id: "html_meta_head_27",
    title: "Отображается ли содержимое тега <title> на самой странице?",
    options: ["Да", "Нет"],
    correctAnswers: [1],
    descriptions: [
      "Да — это неверно, <title> не виден на странице.",
      "Нет — правильный ответ, <title> отображается только во вкладке браузера.",
    ],
    moduleId: "html",
    sectionTitle: "Мета-теги и <head>",
    topic: "html_meta_head",
  },
  {
    id: "html_meta_head_28",
    title: "Что произойдёт, если в HTML-документе будет два тега <title>?",
    options: [
      "Браузер отобразит оба заголовка",
      "Отобразится только первый <title>",
      "Отобразится только последний <title>",
      "Будет показана ошибка",
    ],
    correctAnswers: [1],
    descriptions: [
      "Браузер отобразит оба заголовка — это неверно, можно только один.",
      "Отобразится только первый <title> — правильный ответ.",
      "Отобразится только последний <title> — браузеры читают первый заголовок.",
      "Будет показана ошибка — это неверно, HTML допускает это, но берёт первый.",
    ],
    moduleId: "html",
    sectionTitle: "Мета-теги и <head>",
    topic: "html_meta_head",
  },
  {
    id: "html_meta_head_29",
    title: "Может ли текст внутри <title> влиять на SEO продвижение сайта?",
    options: ["Да", "Нет"],
    correctAnswers: [0],
    descriptions: [
      "Да — правильный ответ, текст внутри <title> влияет на SEO.",
      "Нет — это неверно, тег <title> играет важную роль в ранжировании.",
    ],
    moduleId: "html",
    sectionTitle: "Мета-теги и <head>",
    topic: "html_meta_head",
  },
  {
    id: "html_meta_head_30",
    title:
      "Какое максимальное количество тегов <title> допустимо в одном HTML-документе?",
    options: ["Один", "Два", "Неограниченное количество", "Только в <header>"],
    correctAnswers: [0],
    descriptions: [
      "Один — правильный ответ, допустим только один <title> в <head>.",
      "Два — это нарушает спецификацию.",
      "Неограниченное количество — это неверно, стандарт разрешает только один.",
      "Только в <header> — тег <title> должен быть в <head>, а не в <header>.",
    ],
    moduleId: "html",
    sectionTitle: "Мета-теги и <head>",
    topic: "html_meta_head",
  },
  {
    id: "html_meta_head_31",
    title: "Какой тег используется для подключения фавикона к странице?",
    options: ["<link rel='icon'>", "<meta rel='icon'>", "<favicon>", "<head>"],
    correctAnswers: [0],
    descriptions: [
      "<link rel='icon'> — правильный ответ, используется для подключения фавикона.",
      "<meta rel='icon'> — неверно, тег <meta> не подключает фавиконы.",
      "<favicon> — не существует в HTML.",
      "<head> — это контейнер, но не тег для подключения фавикона.",
    ],
    moduleId: "html",
    sectionTitle: "Мета-теги и <head>",
    topic: "html_meta_head",
  },
  {
    id: "html_meta_head_32",
    title: "Какой формат файла чаще всего используется для фавиконов?",
    options: [".ico", ".png", ".svg", ".jpg"],
    correctAnswers: [0],
    descriptions: [
      ".ico — правильный ответ, это стандартный формат для фавиконов.",
      ".png — также можно использовать, но реже.",
      ".svg — возможно, но не везде поддерживается.",
      ".jpg — обычно не применяется для фавиконов.",
    ],
    moduleId: "html",
    sectionTitle: "Мета-теги и <head>",
    topic: "html_meta_head",
  },
  {
    id: "html_meta_head_33",
    title: "Какой тег используется для подключения CSS-файла?",
    options: ["<link rel='stylesheet'>", "<style>", "<script>", "<css>"],
    correctAnswers: [0],
    descriptions: [
      "<link rel='stylesheet'> — правильный ответ, подключает внешний файл стилей.",
      "<style> — используется для внутренних стилей в HTML.",
      "<script> — это тег для подключения JavaScript.",
      "<css> — не существует в HTML.",
    ],
    moduleId: "html",
    sectionTitle: "Мета-теги и <head>",
    topic: "html_meta_head",
  },
  {
    id: "html_meta_head_34",
    title:
      "Где в HTML-документе рекомендуется размещать подключение CSS-файлов?",
    options: [
      "Внутри <head>",
      "После <body>",
      "Внутри <footer>",
      "Внутри <header>",
    ],
    correctAnswers: [0],
    descriptions: [
      "Внутри <head> — правильный ответ, это оптимальное место для загрузки стилей до рендера страницы.",
      "После <body> — приводит к мерцанию стилей при загрузке.",
      "Внутри <footer> — стили не будут подгружены корректно.",
      "Внутри <header> — это не место для подключения стилей.",
    ],
    moduleId: "html",
    sectionTitle: "Мета-теги и <head>",
    topic: "html_meta_head",
  },
  {
    id: "html_meta_head_35",
    title:
      "Какой атрибут используется для указания MIME-типа при подключении стилей?",
    options: ["type", "rel", "media", "href"],
    correctAnswers: [0],
    descriptions: [
      "type — правильный ответ, указывает MIME-тип (например, text/css).",
      "rel — указывает отношение к документу, но не тип.",
      "media — определяет тип устройства, но не MIME-тип.",
      "href — задаёт путь к файлу, но не его тип.",
    ],
    moduleId: "html",
    sectionTitle: "Мета-теги и <head>",
    topic: "html_meta_head",
  },
  {
    id: "html_meta_head_36",
    title: "Какой тег используется для подключения шрифтов с Google Fonts?",
    options: ["<link>", "<style>", "<font>", "<script>"],
    correctAnswers: [0],
    descriptions: [
      "<link> — правильный ответ, используется для подключения шрифтов.",
      "<style> — используется для внутренних стилей.",
      "<font> — устаревший тег, не используется в HTML5.",
      "<script> — для подключения JavaScript, но не шрифтов.",
    ],
    moduleId: "html",
    sectionTitle: "Мета-теги и <head>",
    topic: "html_meta_head",
  },
  {
    id: "html_meta_head_37",
    title: "Какой атрибут <link> указывает, что это внешний файл стилей?",
    options: [
      "rel='stylesheet'",
      "type='text/css'",
      "media='all'",
      "href='styles.css'",
    ],
    correctAnswers: [0],
    descriptions: [
      "rel='stylesheet' — правильный ответ, определяет файл как CSS.",
      "type='text/css' — указывает MIME-тип, но не определяет, что это стили.",
      "media='all' — задаёт медиа-тип, но не указывает на CSS.",
      "href='styles.css' — указывает путь, но не тип подключения.",
    ],
    moduleId: "html",
    sectionTitle: "Мета-теги и <head>",
    topic: "html_meta_head",
  },
  {
    id: "html_meta_head_38",
    title:
      "Какое значение атрибута media позволяет загружать стили только для печати?",
    options: ["print", "screen", "all", "projection"],
    correctAnswers: [0],
    descriptions: [
      "print — правильный ответ, стили будут применяться при печати страницы.",
      "screen — используется для обычных экранов (мониторов, планшетов).",
      "all — применяется для всех типов устройств.",
      "projection — для проекционных устройств, например, проекторов.",
    ],
    moduleId: "html",
    sectionTitle: "Мета-теги и <head>",
    topic: "html_meta_head",
  },
  {
    id: "html_meta_head_39",
    title: "Можно ли подключить несколько CSS-файлов к одной странице?",
    options: ["Да", "Нет"],
    correctAnswers: [0],
    descriptions: [
      "Да — правильный ответ, можно подключить любое количество CSS-файлов.",
      "Нет — это неверно, ограничения на количество файлов нет.",
    ],
    moduleId: "html",
    sectionTitle: "Мета-теги и <head>",
    topic: "html_meta_head",
  },
  {
    id: "html_meta_head_40",
    title: "Какой из следующих тэгов позволяет подключать сторонние шрифты?",
    options: ["<link>", "<style>", "<font>", "<script>"],
    correctAnswers: [0],
    descriptions: [
      "<link> — правильный ответ, можно использовать для подключения шрифтов.",
      "<style> — это внутренние стили, не подходит для шрифтов.",
      "<font> — устаревший тег, не используется в HTML5.",
      "<script> — не связан с шрифтами.",
    ],
    moduleId: "html",
    sectionTitle: "Мета-теги и <head>",
    topic: "html_meta_head",
  },
];
