export const htmlMultimedia = [
  {
    id: "html_multimedia_01",
    title: "Какой тег используется для вставки видео на веб-страницу?",
    options: ["<video>", "<audio>", "<source>", "<media>"],
    correctAnswers: [0],
    descriptions: [
      "<video> — правильный ответ, используется для вставки видео.",
      "<audio> — это тег для вставки аудиофайлов.",
      "<source> — используется внутри <video> или <audio> для указания источников.",
      "<media> — не существует в HTML.",
    ],
    moduleId: "html",
    sectionTitle: "Мультимедиа: видео и аудио",
    topic: "html_multimedia",
  },
  {
    id: "html_multimedia_02",
    title:
      "Какой атрибут добавляет панель управления видео (пауза, воспроизведение и т.д.)?",
    options: ["controls", "autoplay", "loop", "muted"],
    correctAnswers: [0],
    descriptions: [
      "controls — правильный ответ, добавляет панель управления видео.",
      "autoplay — автоматически запускает видео при загрузке.",
      "loop — зацикливает воспроизведение видео.",
      "muted — выключает звук у видео.",
    ],
    moduleId: "html",
    sectionTitle: "Мультимедиа: видео и аудио",
    topic: "html_multimedia",
  },
  {
    id: "html_multimedia_03",
    title:
      "Какой атрибут позволяет видео воспроизводиться автоматически при загрузке страницы?",
    options: ["autoplay", "controls", "loop", "muted"],
    correctAnswers: [0],
    descriptions: [
      "autoplay — правильный ответ, запускает видео автоматически.",
      "controls — просто добавляет панель управления.",
      "loop — повторяет воспроизведение, но не запускает автоматически.",
      "muted — выключает звук, но не влияет на автозапуск.",
    ],
    moduleId: "html",
    sectionTitle: "Мультимедиа: видео и аудио",
    topic: "html_multimedia",
  },
  {
    id: "html_multimedia_04",
    title: "Какой атрибут отключает звук при воспроизведении видео?",
    options: ["muted", "controls", "autoplay", "loop"],
    correctAnswers: [0],
    descriptions: [
      "muted — правильный ответ, выключает звук.",
      "controls — добавляет панель управления, но не влияет на звук.",
      "autoplay — просто запускает видео автоматически.",
      "loop — делает воспроизведение цикличным, но не отключает звук.",
    ],
    moduleId: "html",
    sectionTitle: "Мультимедиа: видео и аудио",
    topic: "html_multimedia",
  },
  {
    id: "html_multimedia_05",
    title:
      "Какой атрибут позволяет отображать изображение-заглушку до начала воспроизведения видео?",
    options: ["poster", "preview", "thumbnail", "image"],
    correctAnswers: [0],
    descriptions: [
      "poster — правильный ответ, позволяет задать изображение-заглушку.",
      "preview — не является атрибутом HTML.",
      "thumbnail — используется для миниатюр изображений, но не в видео.",
      "image — не существует как атрибут <video>.",
    ],
    moduleId: "html",
    sectionTitle: "Мультимедиа: видео и аудио",
    topic: "html_multimedia",
  },
  {
    id: "html_multimedia_06",
    title: "Какой тег используется для указания нескольких источников видео?",
    options: ["<source>", "<video>", "<track>", "<media>"],
    correctAnswers: [0],
    descriptions: [
      "<source> — правильный ответ, используется для указания источников в <video>.",
      "<video> — это контейнер для видео, но не источник.",
      "<track> — используется для субтитров и метаданных.",
      "<media> — не существует в HTML.",
    ],
    moduleId: "html",
    sectionTitle: "Мультимедиа: видео и аудио",
    topic: "html_multimedia",
  },
  {
    id: "html_multimedia_07",
    title: "Какой формат видео наиболее совместим с современными браузерами?",
    options: ["webm", "ogg", "mp4", "avi"],
    correctAnswers: [2],
    descriptions: [
      "webm — поддерживается не всеми браузерами.",
      "ogg — поддерживается только в Firefox и Opera.",
      "mp4 — правильный ответ, поддерживается всеми современными браузерами.",
      "avi — не поддерживается в HTML5, требует сторонних плагинов.",
    ],
    moduleId: "html",
    sectionTitle: "Мультимедиа: видео и аудио",
    topic: "html_multimedia",
  },
  {
    id: "html_multimedia_08",
    title: "Какой атрибут заставит видео повторяться бесконечно?",
    options: ["loop", "autoplay", "controls", "repeat"],
    correctAnswers: [0],
    descriptions: [
      "loop — правильный ответ, делает воспроизведение цикличным.",
      "autoplay — запускает видео, но не зацикливает.",
      "controls — добавляет панель управления.",
      "repeat — не является валидным атрибутом HTML.",
    ],
    moduleId: "html",
    sectionTitle: "Мультимедиа: видео и аудио",
    topic: "html_multimedia",
  },
  {
    id: "html_multimedia_09",
    title:
      "Может ли <video> содержать альтернативный текст на случай, если браузер не поддерживает видео?",
    options: ["Да", "Нет"],
    correctAnswers: [0],
    descriptions: [
      "Да — правильный ответ, можно добавить текст между открывающим и закрывающим тегом.",
      "Нет — это неверно, поддерживается альтернативный текст.",
    ],
    moduleId: "html",
    sectionTitle: "Мультимедиа: видео и аудио",
    topic: "html_multimedia",
  },
  {
    id: "html_multimedia_10",
    title: "Какой тег внутри <video> позволяет добавить субтитры?",
    options: ["<track>", "<source>", "<subtitles>", "<caption>"],
    correctAnswers: [0],
    descriptions: [
      "<track> — правильный ответ, используется для субтитров.",
      "<source> — это источники видео, не субтитры.",
      "<subtitles> — не существует в HTML.",
      "<caption> — используется в таблицах, но не в видео.",
    ],
    moduleId: "html",
    sectionTitle: "Мультимедиа: видео и аудио",
    topic: "html_multimedia",
  },
  {
    id: "html_multimedia_11",
    title: "Какой тег используется для вставки аудиофайла на веб-страницу?",
    options: ["<audio>", "<video>", "<source>", "<media>"],
    correctAnswers: [0],
    descriptions: [
      "<audio> — правильный ответ, используется для вставки аудиофайлов.",
      "<video> — предназначен для вставки видеоконтента.",
      "<source> — используется внутри <audio> или <video> для указания источников.",
      "<media> — не существует в HTML.",
    ],
    moduleId: "html",
    sectionTitle: "Мультимедиа: видео и аудио",
    topic: "html_multimedia",
  },
  {
    id: "html_multimedia_12",
    title:
      "Какой атрибут добавляет панель управления воспроизведением к тегу <audio>?",
    options: ["controls", "autoplay", "loop", "muted"],
    correctAnswers: [0],
    descriptions: [
      "controls — правильный ответ, добавляет интерфейс управления (пауза, громкость и т.д.).",
      "autoplay — автоматически запускает аудио при загрузке страницы.",
      "loop — делает воспроизведение цикличным.",
      "muted — отключает звук.",
    ],
    moduleId: "html",
    sectionTitle: "Мультимедиа: видео и аудио",
    topic: "html_multimedia",
  },
  {
    id: "html_multimedia_13",
    title:
      "Какой атрибут заставляет аудио автоматически начинать воспроизведение при загрузке страницы?",
    options: ["autoplay", "controls", "loop", "muted"],
    correctAnswers: [0],
    descriptions: [
      "autoplay — правильный ответ, запускает аудио автоматически.",
      "controls — просто добавляет интерфейс управления.",
      "loop — зацикливает воспроизведение.",
      "muted — отключает звук, но не запускает автоматически.",
    ],
    moduleId: "html",
    sectionTitle: "Мультимедиа: видео и аудио",
    topic: "html_multimedia",
  },
  {
    id: "html_multimedia_14",
    title: "Какой атрибут отключает звук у аудиофайла?",
    options: ["muted", "controls", "autoplay", "loop"],
    correctAnswers: [0],
    descriptions: [
      "muted — правильный ответ, отключает звук.",
      "controls — добавляет панель управления, но не отключает звук.",
      "autoplay — запускает аудио автоматически, но не отключает звук.",
      "loop — делает воспроизведение цикличным.",
    ],
    moduleId: "html",
    sectionTitle: "Мультимедиа: видео и аудио",
    topic: "html_multimedia",
  },
  {
    id: "html_multimedia_15",
    title:
      "Какой тег внутри <audio> используется для указания альтернативных источников?",
    options: ["<source>", "<track>", "<media>", "<stream>"],
    correctAnswers: [0],
    descriptions: [
      "<source> — правильный ответ, позволяет указывать разные форматы аудиофайлов.",
      "<track> — используется для субтитров и текстовых треков в <video>.",
      "<media> — не существует в HTML.",
      "<stream> — не является валидным тегом HTML.",
    ],
    moduleId: "html",
    sectionTitle: "Мультимедиа: видео и аудио",
    topic: "html_multimedia",
  },
  {
    id: "html_multimedia_16",
    title:
      "Какой формат аудиофайла поддерживается всеми современными браузерами?",
    options: ["mp3", "ogg", "wav", "flac"],
    correctAnswers: [0],
    descriptions: [
      "mp3 — правильный ответ, поддерживается всеми браузерами.",
      "ogg — поддерживается не всеми браузерами.",
      "wav — поддерживается, но файлы слишком большие.",
      "flac — не поддерживается всеми браузерами по умолчанию.",
    ],
    moduleId: "html",
    sectionTitle: "Мультимедиа: видео и аудио",
    topic: "html_multimedia",
  },
  {
    id: "html_multimedia_17",
    title: "Какой атрибут позволяет зациклить воспроизведение аудиофайла?",
    options: ["loop", "controls", "autoplay", "muted"],
    correctAnswers: [0],
    descriptions: [
      "loop — правильный ответ, делает воспроизведение цикличным.",
      "controls — добавляет интерфейс управления.",
      "autoplay — автоматически запускает, но не зацикливает.",
      "muted — отключает звук, но не влияет на цикл.",
    ],
    moduleId: "html",
    sectionTitle: "Мультимедиа: видео и аудио",
    topic: "html_multimedia",
  },
  {
    id: "html_multimedia_18",
    title:
      "Какой атрибут обязателен для работы autoplay в большинстве браузеров?",
    options: ["muted", "controls", "loop", "poster"],
    correctAnswers: [0],
    descriptions: [
      "muted — правильный ответ, без него autoplay не сработает в большинстве браузеров.",
      "controls — не обязателен для autoplay.",
      "loop — влияет на повтор, но не на автозапуск.",
      "poster — используется в <video>, а не в <audio>.",
    ],
    moduleId: "html",
    sectionTitle: "Мультимедиа: видео и аудио",
    topic: "html_multimedia",
  },
  {
    id: "html_multimedia_19",
    title: "Что будет отображаться, если браузер не поддерживает аудиоформат?",
    options: [
      "Ошибка 404",
      "Пустое пространство",
      "Текст, указанный внутри <audio>",
      "Браузер автоматически подберёт другой формат",
    ],
    correctAnswers: [2],
    descriptions: [
      "Ошибка 404 — возникает при отсутствии файла, а не при неподдерживаемом формате.",
      "Пустое пространство — это неверно, текст будет отображён.",
      "Текст, указанный внутри <audio> — правильный ответ, отображается сообщение.",
      "Браузер автоматически подберёт другой формат — это не происходит без <source>.",
    ],
    moduleId: "html",
    sectionTitle: "Мультимедиа: видео и аудио",
    topic: "html_multimedia",
  },
  {
    id: "html_multimedia_20",
    title: "Можно ли добавить несколько тегов <source> внутри одного <audio>?",
    options: ["Да", "Нет"],
    correctAnswers: [0],
    descriptions: [
      "Да — правильный ответ, это позволяет браузеру выбрать поддерживаемый формат.",
      "Нет — это неверно, <audio> поддерживает несколько источников.",
    ],
    moduleId: "html",
    sectionTitle: "Мультимедиа: видео и аудио",
    topic: "html_multimedia",
  },
];
