export const htmlCoreStructureQuestions = [
  {
    id: "html_structure_51",
    title: "Какой элемент является корневым для всего HTML-документа?",
    options: ["<!DOCTYPE>", "<head>", "<html>", "<body>"],
    correctAnswers: [2],
    descriptions: [
      "<!DOCTYPE> — это директива, а не элемент.",
      "<head> — содержит метаданные, но не корневой.",
      "<html> — корневой элемент, оборачивает весь документ.",
      "<body> — вложен в <html>.",
    ],
    moduleId: "html",
    sectionTitle: "Структура HTML-документа",
    topic: "html_structure",
  },
  {
    id: "html_structure_52",
    title: "Какой атрибут тега <html> указывает язык документа?",
    options: ["language", "lang", "xml:lang", "locale"],
    correctAnswers: [1],
    descriptions: [
      "language — несуществующий атрибут.",
      "lang='ru' — стандартный атрибут (например, <html lang='en'>).",
      "xml:lang — устаревший для XHTML.",
      "locale — не используется.",
    ],
    moduleId: "html",
    sectionTitle: "Структура HTML-документа",
    topic: "html_structure",
  },
  {
    id: "html_structure_53",
    title: "Какой элемент содержит метаданные документа?",
    options: ["<body>", "<header>", "<head>", "<meta>"],
    correctAnswers: [2],
    descriptions: [
      "<body> — для контента, не метаданных.",
      "<header> — секция шапки страницы.",
      "<head> — контейнер для <title>, <meta>, <link>.",
      "<meta> — часть <head>, но не контейнер.",
    ],
    moduleId: "html",
    sectionTitle: "Структура HTML-документа",
    topic: "html_structure",
  },
  {
    id: "html_structure_54",
    title: "Где должен располагаться тег <title>?",
    options: [
      "Внутри <body>",
      "Внутри <head>",
      "Внутри <html>, но вне <head>",
      "Перед <!DOCTYPE>",
    ],
    correctAnswers: [1],
    descriptions: [
      "<body> — только для контента.",
      "<head> — единственно правильное место.",
      "Нельзя вне <head> внутри <html>.",
      "До <!DOCTYPE> — нарушение структуры.",
    ],
    moduleId: "html",
    sectionTitle: "Структура HTML-документа",
    topic: "html_structure",
  },
  {
    id: "html_structure_55",
    title: "Какой элемент НЕ должен находиться в <head>?",
    options: ["<title>", "<style>", "<h1>", "<meta>"],
    correctAnswers: [2],
    descriptions: [
      "<title> — обязателен в <head>.",
      "<style> — допустим для CSS.",
      "<h1> — контентный элемент, принадлежит <body>.",
      "<meta> — стандартный элемент <head>.",
    ],
    moduleId: "html",
    sectionTitle: "Структура HTML-документа",
    topic: "html_structure",
  },
  {
    id: "html_structure_56",
    title: "Какой тег содержит видимый пользователю контент?",
    options: ["<head>", "<main>", "<body>", "<content>"],
    correctAnswers: [2],
    descriptions: [
      "<head> — для служебной информации.",
      "<main> — смысловой контент, но вложен в <body>.",
      "<body> — основной контейнер видимого содержимого.",
      "<content> — нестандартный тег.",
    ],
    moduleId: "html",
    sectionTitle: "Структура HTML-документа",
    topic: "html_structure",
  },
  {
    id: "html_structure_57",
    title: "Какой элемент обязателен в HTML-документе?",
    options: ["<footer>", "<section>", "<head>", "<nav>"],
    correctAnswers: [2],
    descriptions: [
      "<footer> — опциональный элемент.",
      "<section> — не обязателен.",
      "<head> — обязателен (даже если пуст).",
      "<nav> — только для навигации.",
    ],
    moduleId: "html",
    sectionTitle: "Структура HTML-документа",
    topic: "html_structure",
  },
  {
    id: "html_structure_58",
    title: "Какой тег используют для подключения CSS-файла?",
    options: ["<style>", "<link rel='stylesheet'>", "<css>", "<script>"],
    correctAnswers: [1],
    descriptions: [
      "<style> — для встроенных стилей.",
      "<link rel='stylesheet'> — правильный способ.",
      "<css> — несуществующий тег.",
      "<script> — для JavaScript.",
    ],
    moduleId: "html",
    sectionTitle: "Структура HTML-документа",
    topic: "html_structure",
  },
  {
    id: "html_structure_59",
    title: "Для чего нужен атрибут <meta charset='UTF-8'>?",
    options: [
      "Для подключения шрифтов",
      "Для корректного отображения символов (например, кириллицы)",
      "Для указания автора страницы",
      "Для адаптивного дизайна",
    ],
    correctAnswers: [1],
    descriptions: [
      "Шрифты подключаются через <link>.",
      "UTF-8 обеспечивает поддержку всех языков.",
      "Автор указывается в <meta name='author'>.",
      "Адаптивность зависит от CSS.",
    ],
    moduleId: "html",
    sectionTitle: "Структура HTML-документа",
    topic: "html_structure",
  },
  {
    id: "html_structure_60",
    title: "Какой элемент НЕ является частью базовой структуры HTML?",
    options: ["<html>", "<head>", "<body>", "<article>"],
    correctAnswers: [3],
    descriptions: [
      "<html> — обязательный корневой элемент.",
      "<head> — обязателен для метаданных.",
      "<body> — обязателен для контента.",
      "<article> — семантический тег, не входит в базовую структуру.",
    ],
    moduleId: "html",
    sectionTitle: "Структура HTML-документа",
    topic: "html_structure",
  },
];
