export const htmlSemanticFormattingQuestions = [
  {
    id: "html_elements_116",
    title:
      "Какой тег следует использовать для выделения критически важного предупреждения?",
    options: [
      "<b>Пожалуйста, прочтите это!</b>",
      "<strong>Пожалуйста, прочтите это!</strong>",
      "<mark>Пожалуйста, прочтите это!</mark>",
      "<big>Пожалуйста, прочтите это!</big>",
    ],
    correctAnswers: [1],
    descriptions: [
      "<b> — только визуальное выделение без семантики.",
      "<strong> — правильный выбор для важного контента.",
      "<mark> — для подсветки, не для предупреждений.",
      "<big> — устаревший тег.",
    ],
    moduleId: "html",
    sectionTitle: "Элементы и теги",
    topic: "html_elements",
  },
  {
    id: "html_elements_117",
    title: "Какой код правильно оформляет химическую формулу?",
    options: [
      "<p>CO<up>2</up></p>",
      "<p>CO<sup>2</sup></p>",
      "<p>CO<super>2</super></p>",
      "<p>CO<high>2</high></p>",
    ],
    correctAnswers: [1],
    descriptions: [
      "<up> — несуществующий тег.",
      "<sup> — правильный тег для верхнего индекса.",
      "<super> — нестандартный тег.",
      "<high> — не существует.",
    ],
    moduleId: "html",
    sectionTitle: "Элементы и теги",
    topic: "html_elements",
  },
  {
    id: "html_elements_118",
    title: "Какой тег следует использовать для выделения результатов поиска?",
    options: [
      "<highlight>Найдено 15 результатов</highlight>",
      "<strong>Найдено 15 результатов</strong>",
      "<mark>Найдено 15 результатов</mark>",
      "<em>Найдено 15 результатов</em>",
    ],
    correctAnswers: [2],
    descriptions: [
      "<highlight> — нестандартный тег.",
      "<strong> — для важного контента, не подсветки.",
      "<mark> — специально для выделения результатов.",
      "<em> — для смыслового акцента.",
    ],
    moduleId: "html",
    sectionTitle: "Элементы и теги",
    topic: "html_elements",
  },
  {
    id: "html_elements_119",
    title: "Какой код правильно оформляет сноску в тексте?",
    options: [
      "<p>Исследование проведено в 2023 году<ref>1</ref></p>",
      "<p>Исследование проведено в 2023 году<small>1</small></p>",
      "<p>Исследование проведено в 2023 году<little>1</little></p>",
      "<p>Исследование проведено в 2023 году<footnote>1</footnote></p>",
    ],
    correctAnswers: [1],
    descriptions: [
      "<ref> — нестандартный тег.",
      "<small> — семантически правильный выбор для сносок.",
      "<little> — несуществующий тег.",
      "<footnote> — не является HTML-тегом.",
    ],
    moduleId: "html",
    sectionTitle: "Элементы и теги",
    topic: "html_elements",
  },
  {
    id: "html_elements_120",
    title:
      "Какой тег следует использовать для интонационного акцента в диалоге?",
    options: [
      "<p>Я <i>действительно</i> этого не знал</p>",
      "<p>Я <strong>действительно</strong> этого не знал</p>",
      "<p>Я <em>действительно</em> этого не знал</p>",
      "<p>Я <b>действительно</b> этого не знал</p>",
    ],
    correctAnswers: [2],
    descriptions: [
      "<i> — только визуальный курсив без семантики.",
      "<strong> — для важности, не интонации.",
      "<em> — правильный выбор для смыслового ударения.",
      "<b> — просто жирный текст.",
    ],
    moduleId: "html",
    sectionTitle: "Элементы и теги",
    topic: "html_elements",
  },
  {
    id: "html_elements_121",
    title: "Какой код правильно оформляет математическое уравнение?",
    options: [
      "<p>x<sup>2</sup> + y<sup>2</sup> = z<sup>2</sup></p>",
      "<p>x<up>2</up> + y<up>2</up> = z<up>2</up></p>",
      "<p>x<high>2</high> + y<high>2</high> = z<high>2</high></p>",
      "<p>x^2 + y^2 = z^2</p>",
    ],
    correctAnswers: [0],
    descriptions: [
      "<sup> — правильный тег для степеней.",
      "<up> — несуществующий тег.",
      "<high> — не является HTML-тегом.",
      "Текст без разметки — не семантично.",
    ],
    moduleId: "html",
    sectionTitle: "Элементы и теги",
    topic: "html_elements",
  },
  {
    id: "html_elements_122",
    title:
      "Какой тег следует использовать для юридического текста в подвале сайта?",
    options: [
      "<footer><tiny>© 2025 Все права защищены</tiny></footer>",
      "<footer><small>© 2025 Все права защищены</small></footer>",
      "<footer><legal>© 2025 Все права защищены</legal></footer>",
      "<footer><mini>© 2025 Все права защищены</mini></footer>",
    ],
    correctAnswers: [1],
    descriptions: [
      "<tiny> — нестандартный тег.",
      "<small> — семантически правильный выбор.",
      "<legal> — не существует.",
      "<mini> — не является HTML-тегом.",
    ],
    moduleId: "html",
    sectionTitle: "Элементы и теги",
    topic: "html_elements",
  },
  {
    id: "html_elements_123",
    title: "Какой код правильно оформляет подстрочное примечание?",
    options: [
      "<p>Объём воды: 250 мл<sub>*</sub></p>",
      "<p>Объём воды: 250 мл<under>*</under></p>",
      "<p>Объём воды: 250 мл<bottom>*</bottom></p>",
      "<p>Объём воды: 250 мл<inf>*</inf></p>",
    ],
    correctAnswers: [0],
    descriptions: [
      "<sub> — правильный тег для подстрочных символов.",
      "<under> — несуществующий тег.",
      "<bottom> — не является HTML-тегом.",
      "<inf> — нестандартный тег.",
    ],
    moduleId: "html",
    sectionTitle: "Элементы и теги",
    topic: "html_elements",
  },
  {
    id: "html_elements_124",
    title: "Какой тег НЕ является семантическим?",
    options: [
      "<strong>Важно!</strong>",
      "<em>Очень важно</em>",
      "<b>Просто жирный текст</b>",
      "<mark>Выделенный фрагмент</mark>",
    ],
    correctAnswers: [2],
    descriptions: [
      "<strong> — семантика важности.",
      "<em> — семантика акцента.",
      "<b> — чисто визуальное выделение.",
      "<mark> — семантика выделения.",
    ],
    moduleId: "html",
    sectionTitle: "Элементы и теги",
    topic: "html_elements",
  },
  {
    id: "html_elements_125",
    title: "Какой код правильно оформляет сноску в научном тексте?",
    options: [
      "<p>Исследование<sup>1</sup> показало интересные результаты</p>",
      "<p>Исследование<up>1</up> показало интересные результаты</p>",
      "<p>Исследование<high>1</high> показало интересные результаты</p>",
      "<p>Исследование<ref>1</ref> показало интересные результаты</p>",
    ],
    correctAnswers: [0],
    descriptions: [
      "<sup> — правильный тег для сносок.",
      "<up> — несуществующий тег.",
      "<high> — нестандартный тег.",
      "<ref> — не является HTML-тегом.",
    ],
    moduleId: "html",
    sectionTitle: "Элементы и теги",
    topic: "html_elements",
  },
  {
    id: "html_elements_126",
    title:
      "Какой тег следует использовать для выделения термина в технической документации?",
    options: [
      "<p>Элемент <term>HTML</term> используется для разметки</p>",
      "<p>Элемент <mark>HTML</mark> используется для разметки</p>",
      "<p>Элемент <strong>HTML</strong> используется для разметки</p>",
      "<p>Элемент <em>HTML</em> используется для разметки</p>",
    ],
    correctAnswers: [2],
    descriptions: [
      "<term> — нестандартный тег.",
      "<mark> — для подсветки, не терминов.",
      "<strong> — правильный выбор для ключевых терминов.",
      "<em> — для акцента, не терминологии.",
    ],
    moduleId: "html",
    sectionTitle: "Элементы и теги",
    topic: "html_elements",
  },
  {
    id: "html_elements_127",
    title:
      "Какой тег делает текст меньше и используется для юридической информации?",
    options: [
      "<legal>Условия использования</legal>",
      "<small>Условия использования</small>",
      "<fineprint>Условия использования</fineprint>",
      "<tiny>Условия использования</tiny>",
    ],
    correctAnswers: [1],
    descriptions: [
      "<legal> — несуществующий тег.",
      "<small> — семантически правильный выбор.",
      "<fineprint> — нестандартный тег.",
      "<tiny> — не является HTML-тегом.",
    ],
    moduleId: "html",
    sectionTitle: "Элементы и теги",
    topic: "html_elements",
  },
  {
    id: "html_elements_128",
    title: "Какой код правильно оформляет акцент в цитате?",
    options: [
      "<blockquote>Я <b>настоятельно</b> рекомендую</blockquote>",
      "<blockquote>Я <strong>настоятельно</strong> рекомендую</blockquote>",
      "<blockquote>Я <em>настоятельно</em> рекомендую</blockquote>",
      "<blockquote>Я <big>настоятельно</big> рекомендую</blockquote>",
    ],
    correctAnswers: [2],
    descriptions: [
      "<b> — только визуальное выделение.",
      "<strong> — для важности, не акцента.",
      "<em> — правильный выбор для интонационного ударения.",
      "<big> — устаревший тег.",
    ],
    moduleId: "html",
    sectionTitle: "Элементы и теги",
    topic: "html_elements",
  },
  {
    id: "html_elements_129",
    title:
      "Какой тег следует использовать для выделения нового контента в документе?",
    options: [
      "<new>Новый раздел</new>",
      "<mark>Новый раздел</mark>",
      "<ins>Новый раздел</ins>",
      "<strong>Новый раздел</strong>",
    ],
    correctAnswers: [2],
    descriptions: [
      "<new> — нестандартный тег.",
      "<mark> — для подсветки, не новых элементов.",
      "<ins> — семантика вставленного/нового контента.",
      "<strong> — для важности, не новизны.",
    ],
    moduleId: "html",
    sectionTitle: "Элементы и теги",
    topic: "html_elements",
  },
  {
    id: "html_elements_130",
    title: "Какой код правильно оформляет химический элемент?",
    options: [
      "<p>Формула спирта: C<sub>2</sub>H<sub>5</sub>OH</p>",
      "<p>Формула спирта: C<down>2</down>H<down>5</down>OH</p>",
      "<p>Формула спирта: C[2]H[5]OH</p>",
      "<p>Формула спирта: C(low)2(low)H(low)5(low)OH</p>",
    ],
    correctAnswers: [0],
    descriptions: [
      "<sub> — правильный тег для химических формул.",
      "<down> — несуществующий тег.",
      "Квадратные скобки — не семантично.",
      "Текст в скобках — не разметка.",
    ],
    moduleId: "html",
    sectionTitle: "Элементы и теги",
    topic: "html_elements",
  },
  {
    id: "html_elements_131",
    title:
      "Какой тег используется для длинных цитат, которые должны отображаться отдельным блоком?",
    options: ["<quote>", "<blockquote>", "<q>", "<cite>"],
    correctAnswers: [1],
    descriptions: [
      "<quote> — такого тега не существует в HTML.",
      "<blockquote> — правильный ответ, используется для длинных цитат.",
      "<q> — для коротких встроенных цитат.",
      "<cite> — для указания источника.",
    ],
    moduleId: "html",
    sectionTitle: "Элементы и теги",
    topic: "html_elements",
  },
  {
    id: "html_elements_132",
    title: "Какой тег автоматически добавляет кавычки вокруг цитаты?",
    options: ["<blockquote>", "<quotation>", "<q>", "<mark>"],
    correctAnswers: [2],
    descriptions: [
      "<blockquote> — не добавляет кавычки автоматически.",
      "<quotation> — такого тега не существует.",
      "<q> — правильный ответ, добавляет кавычки.",
      "<mark> — для выделения текста.",
    ],
    moduleId: "html",
    sectionTitle: "Элементы и теги",
    topic: "html_elements",
  },
  {
    id: "html_elements_133",
    title:
      "Какой атрибут можно добавить к тегу <blockquote> для указания URL источника?",
    options: ["source", "href", "cite", "link"],
    correctAnswers: [2],
    descriptions: [
      "source — не является валидным атрибутом.",
      "href — используется в тегах ссылок.",
      "cite — правильный ответ, указывает URL источника.",
      "link — не используется для этой цели.",
    ],
    moduleId: "html",
    sectionTitle: "Элементы и теги",
    topic: "html_elements",
  },
  {
    id: "html_elements_134",
    title: "Какой тег следует использовать для указания автора цитаты?",
    options: ["<author>", "<cite>", "<source>", "<footer>"],
    correctAnswers: [1],
    descriptions: [
      "<author> — такого тега не существует.",
      "<cite> — правильный ответ, используется для автора/источника.",
      "<source> — используется для медиа-ресурсов.",
      "<footer> — для нижнего колонтитула.",
    ],
    moduleId: "html",
    sectionTitle: "Элементы и теги",
    topic: "html_elements",
  },
  {
    id: "html_elements_135",
    title: "Какой тег следует использовать для цитаты внутри абзаца текста?",
    options: ["<blockquote>", "<q>", "<quote>", "<inlinequote>"],
    correctAnswers: [1],
    descriptions: [
      "<blockquote> — для отдельного блока цитаты.",
      "<q> — правильный ответ, для встроенной цитаты.",
      "<quote> — не является HTML тегом.",
      "<inlinequote> — такого тега не существует.",
    ],
    moduleId: "html",
    sectionTitle: "Элементы и теги",
    topic: "html_elements",
  },
  {
    id: "html_elements_136",
    title:
      "Какой из этих тегов является семантически корректным для обозначения названия книги?",
    options: ["<book>", "<cite>", "<title>", "<name>"],
    correctAnswers: [1],
    descriptions: [
      "<book> — такого тега не существует.",
      "<cite> — правильный ответ, для названий произведений.",
      "<title> — используется в head документа.",
      "<name> — не для этой цели.",
    ],
    moduleId: "html",
    sectionTitle: "Элементы и теги",
    topic: "html_elements",
  },
  {
    id: "html_elements_137",
    title: "Какой тег НЕ следует использовать для оформления цитат?",
    options: ["<blockquote>", "<q>", "<div>", "<cite>"],
    correctAnswers: [2],
    descriptions: [
      "<blockquote> — подходит для цитат.",
      "<q> — подходит для цитат.",
      "<div> — правильный ответ, не семантичен для цитат.",
      "<cite> — подходит для указания источника.",
    ],
    moduleId: "html",
    sectionTitle: "Элементы и теги",
    topic: "html_elements",
  },
  {
    id: "html_elements_138",
    title: "Где следует размещать тег <cite> при оформлении цитаты?",
    options: [
      "Перед тегом <blockquote>",
      "Внутри тега <blockquote>",
      "После закрывающего </blockquote>",
      "В атрибуте cite тега <blockquote>",
    ],
    correctAnswers: [1],
    descriptions: [
      "Перед — неправильное расположение.",
      "Внутри — правильный ответ, обычно в конце цитаты.",
      "После — не семантично.",
      "Атрибут cite — для URL, не для текста.",
    ],
    moduleId: "html",
    sectionTitle: "Элементы и теги",
    topic: "html_elements",
  },
  {
    id: "html_elements_139",
    title:
      "Какой тег следует использовать для цитаты, если нужно сохранить переносы строк и пробелы?",
    options: ["<blockquote>", "<pre>", "<q>", "<blockquote><pre>"],
    correctAnswers: [3],
    descriptions: [
      "<blockquote> — не сохраняет форматирование.",
      "<pre> — сохраняет, но не семантичен для цитат.",
      "<q> — для коротких цитат без форматирования.",
      "<blockquote><pre> — правильный ответ, сочетает семантику и форматирование.",
    ],
    moduleId: "html",
    sectionTitle: "Элементы и теги",
    topic: "html_elements",
  },
  {
    id: "html_elements_140",
    title:
      "Какой из этих примеров является корректным оформлением цитаты с источником?",
    options: [
      "<q>Цитата</q> <cite>Автор</cite>",
      "<blockquote>Цитата <source>Автор</source></blockquote>",
      "<quote>Цитата</quote> <author>Автор</author>",
      "<blockquote>Цитата <cite>Автор</cite></blockquote>",
    ],
    correctAnswers: [3],
    descriptions: [
      "<q> не сочетается с <cite> таким образом.",
      "<source> — неверный тег для автора.",
      "<quote> и <author> — не HTML теги.",
      "Правильный ответ — вложенный <cite> в <blockquote>.",
    ],
    moduleId: "html",
    sectionTitle: "Элементы и теги",
    topic: "html_elements",
  },
];
