export const js_variablesAndTypes_test = {
  id: 501,
  name: "Переменные и типы данных в JavaScript",
  category: "JavaScript",
  ques: [
    {
      id: 1,
      name: "Что такое переменная в программировании?",
      variants: [
        "Фиксированное число",
        "Именованная область памяти для хранения значения",
        "Команда для запуска программы",
      ],
      correct: [1],
    },
    {
      id: 2,
      name: "Для чего используют переменные?",
      variants: [
        "Для хранения, изменения и использования данных в программе",
        "Только для вывода сообщений",
        "Только для хранения функций",
      ],
      correct: [0],
    },
    {
      id: 3,
      name: "Какое из имён переменных корректно в JavaScript?",
      variants: ["2user", "user_name", "user-name"],
      correct: [1],
    },
    {
      id: 4,
      name: "Можно ли изменить значение переменной, объявленной с помощью let?",
      variants: ["Нет, нельзя", "Да, можно", "Только один раз"],
      correct: [1],
    },
    {
      id: 5,
      name: 'Что будет при выполнении кода: const city = "Москва"; city = "Казань";',
      variants: ["Значение изменится", "Будет ошибка", "Вернёт undefined"],
      correct: [1],
    },
    {
      id: 6,
      name: "Чем отличается let от const?",
      variants: [
        "let нельзя менять, const можно",
        "let можно менять, const нельзя переназначить",
        "let и const — это одно и то же",
      ],
      correct: [1],
    },
    {
      id: 7,
      name: "Какой ключ использовать, если переменную нельзя менять?",
      variants: ["let", "var", "const"],
      correct: [2],
    },
    {
      id: 8,
      name: "Какое утверждение про var верно?",
      variants: [
        "var имеет блочную область видимости",
        "var поднимается вверх и виден вне блока",
        "var работает так же, как let",
      ],
      correct: [1],
    },
    {
      id: 9,
      name: "Что произойдёт при выполнении: if (true) { let a = 10; } console.log(a);",
      variants: ["Выведет 10", "Ошибка: a не определена", "Выведет undefined"],
      correct: [1],
    },
    {
      id: 10,
      name: "Что произойдёт при выполнении: if (true) { var a = 10; } console.log(a);",
      variants: ["Ошибка: a не определена", "Выведет undefined", "Выведет 10"],
      correct: [2],
    },
    {
      id: 11,
      name: 'Какой тип данных у значения "Привет"?',
      variants: ["number", "string", "boolean"],
      correct: [1],
    },
    {
      id: 12,
      name: "Какой тип данных у значения 3.14?",
      variants: ["string", "number", "boolean"],
      correct: [1],
    },
    {
      id: 13,
      name: "Какой тип данных у значения true?",
      variants: ["string", "boolean", "number"],
      correct: [1],
    },
    {
      id: 14,
      name: "Что выведет typeof null?",
      variants: ['"object"', '"null"', '"undefined"'],
      correct: [0],
    },
    {
      id: 15,
      name: "Что вернёт typeof undefined?",
      variants: ['"object"', '"undefined"', '"null"'],
      correct: [1],
    },
    {
      id: 16,
      name: "Какой тип данных у переменной let user;",
      variants: ["null", "string", "undefined"],
      correct: [2],
    },
    {
      id: 17,
      name: "Как создать строку в JavaScript?",
      variants: [
        "let str = Привет;",
        'let str = "Привет";',
        "let str = [Привет];",
      ],
      correct: [1],
    },
    {
      id: 18,
      name: "Какой тип данных у значения 10 / 0?",
      variants: ["NaN", "Infinity", "undefined"],
      correct: [1],
    },
    {
      id: 19,
      name: 'Что вернёт выражение Number("abc")?',
      variants: ["0", "NaN", "undefined"],
      correct: [1],
    },
    {
      id: 20,
      name: "Какой результат будет у выражения Boolean(0)?",
      variants: ["true", "false", "null"],
      correct: [1],
    },
    {
      id: 21,
      name: "Какое из значений считается ложным (falsy)?",
      variants: ['"0"', "null", "[]"],
      correct: [1],
    },
    {
      id: 22,
      name: 'Какой тип данных у значения Symbol("id")?',
      variants: ["string", "symbol", "object"],
      correct: [1],
    },
    {
      id: 23,
      name: "Какой тип данных у значения 12345678901234567890n?",
      variants: ["bigint", "number", "string"],
      correct: [0],
    },
    {
      id: 24,
      name: "Как преобразовать число 5 в строку?",
      variants: ["String(5)", "ToString(5)", "5.toStr()"],
      correct: [0],
    },
    {
      id: 25,
      name: 'Что вернёт выражение Boolean("")?',
      variants: ["true", "false", "undefined"],
      correct: [1],
    },
    {
      id: 26,
      name: "Какой результат будет у выражения '5' + 2?",
      variants: ["7", '"52"', "NaN"],
      correct: [1],
    },
    {
      id: 27,
      name: "Какой результат будет у выражения '5' - 2?",
      variants: ["3", '"3"', "NaN"],
      correct: [0],
    },
    {
      id: 28,
      name: "Какое значение примет переменная let selectedItem = null;?",
      variants: ["null", "undefined", "false"],
      correct: [0],
    },
    {
      id: 29,
      name: "Какой результат будет у выражения Boolean([ ])?",
      variants: ["true", "false", "undefined"],
      correct: [0],
    },
    {
      id: 30,
      name: "Какое из перечисленных не является примитивным типом данных в JavaScript?",
      variants: ["object", "string", "number"],
      correct: [0],
    },
  ],
};
