import {
  js_basics_task_1,
  js_basics_task_10,
  js_basics_task_11,
  js_basics_task_12,
  js_basics_task_13,
  js_basics_task_14,
  js_basics_task_15,
  js_basics_task_2,
  js_basics_task_3,
  js_basics_task_4,
  js_basics_task_5,
  js_basics_task_6,
  js_basics_task_7,
  js_basics_task_8,
  js_basics_task_9,
  js_basics_task_16,
  js_basics_task_17,
  js_basics_task_18,
  js_basics_task_19,
  js_basics_task_20,
  js_basics_task_21,
} from "./js_basics_task";
import { js_intro_task_1, js_intro_task_2 } from "./js_intro_task";

export const taskDataJs = [
  js_basics_task_10,
  js_basics_task_11,
  js_basics_task_12,
  js_basics_task_13,
  js_basics_task_14,
  js_basics_task_15,
  js_intro_task_1,
  js_intro_task_2,
  js_basics_task_1,
  js_basics_task_2,
  js_basics_task_3,
  js_basics_task_4,
  js_basics_task_5,
  js_basics_task_6,
  js_basics_task_7,
  js_basics_task_8,
  js_basics_task_9,
  js_basics_task_16,
  js_basics_task_17,
  js_basics_task_18,
  js_basics_task_19,
  js_basics_task_20,
  js_basics_task_21,
];
