import { cssSections } from "./cssSections";

export const cssChapters = [
  {
    id: "css_intro",
    title: "Основы CSS и синтаксис",
    sections: cssSections.css_intro,
    testKeys: ["css_intro_test"],
    practiceIds: ["css_intro_task_1"],
  },
  {
    id: "css_selectors",
    title: "Стилизация текста",
    sections: cssSections.css_selectors,
    testKeys: ["css_selectors_test"],
    practiceIds: [
      "css_selectors_task_1",
      "css_selectors_task_2",
      "css_selectors_task_3",
      "css_selectors_task_4",
      "css_selectors_task_5",
      "css_selectors_task_6",
      "css_selectors_task_7",
    ],
  },
  {
    id: "css_box_model",
    title: "Блочная модель и позиционирование элементов",
    sections: cssSections.css_box_model,
    testKeys: ["css_box_model_test"],
    practiceIds: [
      "css_box_model_task_1",
      "css_box_model_task_2",
      "css_box_model_task_3",
      "css_box_model_task_4",
      "css_box_model_task_5",
      "css_box_model_task_6",
      "css_position_task_2",
      "css_box_model_task_7",
      "css_box_model_task_8",
      "css_box_model_task_9",
      "css_box_model_task_10",
    ],
  },
  {
    id: "css_block",
    title: "Стилизация  блоков",
    sections: cssSections.css_block_model,
    testKeys: ["css_block_test"],
    practiceIds: [
      "css_block_model_task_1",
      "css_block_model_task_2",
      "css_block_model_task_3",
      "css_block_model_task_4",
      "css_block_model_task_5",
    ],
  },
  {
    id: "css_pseudo",
    title: "Псевдоклассы и псевдоэлемены ",
    sections: cssSections.css_pseudo,
    testKeys: ["css_pseudo_test"],
    practiceIds: [
      "css_pseudo_task_1",
      "css_pseudoElement_task_3",
      "css_pseudo_task_8",
      "css_pseudo_task_4",
      "css_pseudo_task_5",
      "css_pseudo_task_6",
      "css_pseudo_task_7",
    ],
  },
  {
    id: "css_methodologies",
    title: "Методологии (BEM)",
    sections: cssSections.css_methodologies,
    testKeys: ["css_methodologies_test"],
    practiceIds: ["css_methodologies_task_1", "css_methodologies_task_2"],
  },
  {
    id: "css_layout",
    title: "Макеты и позиционирование",
    sections: cssSections.css_layout,
    testKeys: ["css_layout_test"],
    practiceIds: [
      "css_layout_task_1",
      "css_layout_task_2",
      "css_layout_task_3",
      "css_layout_task_4",
    ],
  },
  {
    id: "css_flexbox",
    title: "Flexbox",
    sections: cssSections.css_flexbox,
    testKeys: ["css_flexbox_test"],
    practiceIds: [
      "css_flexbox_task_1",
      "css_flexbox_task_2",
      "css_flexbox_task_3",
      "css_flexbox_task_4",
      "css_flexbox_task_5",
      "css_flexbox_task_6",
      "css_flexbox_task_7",
      "css_flexbox_task_8",
      "css_flexbox_task_9",
      "css_flexbox_task_10",
      "css_flexbox_task_11",
      "css_flexbox_task_12",
      "flex_task_6",
    ],
  },
  {
    id: "css_grid",
    title: "Grid Layout",
    sections: cssSections.css_grid,
    testKeys: ["css_grid_test"],
    practiceIds: [
      "css_grid_task_1",
      "css_grid_task_2",
      "css_grid_task_3",
      "css_grid_task_4",
      "css_grid_task_5",
      "css_grid_task_6",
      "css_grid_task_7",
      "css_grid_task_8",
      "css_grid_task_9",
      "css_grid_task_10",
      "css_grid_task_11",
    ],
  },

  {
    id: "css_images",
    title: "Работа с изображениями и фоном",
    sections: cssSections.css_images,
    testKeys: ["css_images_test"],
    practiceIds: [
      "css_images_task_1",
      "css_images_task_2",
      "css_images_task_3",
      "css_images_task_4",
    ],
  },
  {
    id: "css_responsive",
    title: "Адаптивный дизайн",
    sections: cssSections.css_responsive,
    testKeys: ["css_responsive_test"],
    practiceIds: [
      "css_responsive_task_1",
      "css_responsive_task_2",
      "css_responsive_task_3",
      "css_responsive_task_4",
    ],
  },
  {
    id: "css_animations",
    title: "Анимации и переходы",
    sections: cssSections.css_animations,
    testKeys: ["css_animations_test"],
    practiceIds: [
      "css_animations_task_1",
      "css_animations_task_2",
      "css_animations_task_3",
      "css_animations_task_4",
    ],
  },
  {
    id: "css_preprocessors",
    title: "Препроцессоры (Sass/Less)",
    sections: cssSections.css_preprocessors,
    testKeys: [],
  },

  {
    id: "css_final",
    title: "Финальный проект",
    sections: cssSections.css_final,
    final: true,
  },
];
