export const htmlDoctypeQuestions = [
  {
    id: "html_structure_41",
    title: "Что такое <!DOCTYPE html>?",
    options: [
      "HTML-тег для создания документов",
      "Директива объявления типа документа",
      "Комментарий для браузера",
      "Атрибут тега <html>",
    ],
    correctAnswers: [1],
    descriptions: [
      "Не является HTML-тегом.",
      "Это декларация типа документа, не тег.",
      "Комментарии в HTML используют <!-- -->.",
      "Не атрибут, а отдельная директива.",
    ],
    moduleId: "html",
    sectionTitle: "Структура HTML-документа",
    topic: "html_structure",
  },
  {
    id: "html_structure_42",
    title: "Где должен располагаться <!DOCTYPE html>?",
    options: [
      "После <html>",
      "Перед любым другим кодом (первой строкой)",
      "Внутри <head>",
      "В конце документа",
    ],
    correctAnswers: [1],
    descriptions: [
      "Должен быть до <html>.",
      "Первая строка — единственно правильное место.",
      "<head> начинается после <html>.",
      "В конце не будет работать.",
    ],
    moduleId: "html",
    sectionTitle: "Структура HTML-документа",
    topic: "html_structure",
  },
  {
    id: "html_structure_43",
    title: "Что произойдёт, если пропустить <!DOCTYPE html>?",
    options: [
      "Страница не загрузится",
      "Браузер включит режим совместимости (quirks mode)",
      "Контент исчезнет",
      "Ничего, это необязательно",
    ],
    correctAnswers: [1],
    descriptions: [
      "Страница загрузится, но с ошибками.",
      "Quirks mode — устаревший режим рендеринга.",
      "Контент останется, но отобразится некорректно.",
      "<!DOCTYPE> обязателен для стандартного режима.",
    ],
    moduleId: "html",
    sectionTitle: "Структура HTML-документа",
    topic: "html_structure",
  },
  {
    id: "html_structure_44",
    title: "Какой режим рендеринга включает <!DOCTYPE html>?",
    options: [
      "Quirks mode",
      "Standards mode",
      "Transitional mode",
      "Compat mode",
    ],
    correctAnswers: [1],
    descriptions: [
      "Quirks mode — устаревший, без <!DOCTYPE>.",
      "Standards mode — современный стандартный режим.",
      "Transitional — устаревший тип DTD, не режим.",
      "Compat mode — не существует.",
    ],
    moduleId: "html",
    sectionTitle: "Структура HTML-документа",
    topic: "html_structure",
  },
  {
    id: "html_structure_45",
    title: "Какой <!DOCTYPE> используется для HTML5?",
    options: [
      '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN">',
      "<!DOCTYPE html>",
      "<!DOCTYPE xhtml>",
      "<!DOCTYPE html5>",
    ],
    correctAnswers: [1],
    descriptions: [
      "HTML 4.01 — устаревший стандарт.",
      "Короткий <!DOCTYPE html> — синтаксис HTML5.",
      "XHTML — отдельный стандарт.",
      "html5 — неверный синтаксис.",
    ],
    moduleId: "html",
    sectionTitle: "Структура HTML-документа",
    topic: "html_structure",
  },
  {
    id: "html_structure_46",
    title: "Нужно ли закрывать <!DOCTYPE html>?",
    options: [
      "Да, тегом </!DOCTYPE>",
      "Да, символом />",
      "Нет, это самозакрывающаяся директива",
      "Нет, это не тег",
    ],
    correctAnswers: [3],
    descriptions: [
      "Не является тегом, закрытие не требуется.",
      "Синтаксис /> используется в XML/XHTML.",
      "Неправильная терминология — это не тег.",
      "Верно: это декларация, не требующая закрытия.",
    ],
    moduleId: "html",
    sectionTitle: "Структура HTML-документа",
    topic: "html_structure",
  },
  {
    id: "html_structure_47",
    title: "Как <!DOCTYPE> влияет на CSS?",
    options: [
      "Блокирует все стили",
      "Включает корректный расчёт box-model",
      "Отключает flexbox и grid",
      "Не влияет",
    ],
    correctAnswers: [1],
    descriptions: [
      "Стили работают, но могут отображаться некорректно.",
      "Без <!DOCTYPE> box-model может ломаться.",
      "Modern CSS работает только в standards mode.",
      "Влияет критически через режим рендеринга.",
    ],
    moduleId: "html",
    sectionTitle: "Структура HTML-документа",
    topic: "html_structure",
  },
  {
    id: "html_structure_48",
    title: "Какая была цель введения <!DOCTYPE> в ранних версиях HTML?",
    options: [
      "Для валидации документа по DTD",
      "Для подключения CSS",
      "Для объявления JavaScript",
      "Для комментариев",
    ],
    correctAnswers: [0],
    descriptions: [
      "DTD (Document Type Definition) — проверка структуры.",
      "CSS подключается через <link> или <style>.",
      "JS не зависит от <!DOCTYPE>.",
      "Комментарии используют <!-- -->.",
    ],
    moduleId: "html",
    sectionTitle: "Структура HTML-документа",
    topic: "html_structure",
  },
  {
    id: "html_structure_49",
    title:
      "Можно ли использовать HTML5-теги (например, <section>) без <!DOCTYPE html>?",
    options: [
      "Да, они всегда работают",
      "Да, но только в современных браузерах",
      "Нет, браузер не распознает их правильно",
      "Только с XHTML-документах",
    ],
    correctAnswers: [2],
    descriptions: [
      "Без <!DOCTYPE> могут обрабатываться как неизвестные элементы.",
      "Даже современные браузеры требуют <!DOCTYPE>.",
      "В quirks mode семантика новых тегов может нарушаться.",
      "XHTML использует свой <!DOCTYPE>.",
    ],
    moduleId: "html",
    sectionTitle: "Структура HTML-документа",
    topic: "html_structure",
  },
  {
    id: "html_structure_50",
    title: "Какой <!DOCTYPE> использовался для XHTML 1.0 Strict?",
    options: [
      "<!DOCTYPE html>",
      '<!DOCTYPE HTML PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">',
      "<!DOCTYPE xhtml>",
      "<!DOCTYPE html5>",
    ],
    correctAnswers: [1],
    descriptions: [
      "Это синтаксис HTML5, не XHTML.",
      "Полный синтаксис DTD для XHTML Strict.",
      "Несуществующий вариант.",
      "HTML5 не используется для XHTML.",
    ],
    moduleId: "html",
    sectionTitle: "Структура HTML-документа",
    topic: "html_structure",
  },
];
