export const html5 = [
  {
    id: "html_final_01",
    title:
      "Какой HTML5 элемент используется для отображения прогресса выполнения задачи?",
    options: ["<progress>", "<meter>", "<bar>", "<range>"],
    correctAnswers: [0],
    descriptions: [
      "<progress> — правильный ответ, используется для отображения выполнения задачи.",
      "<meter> — применяется для отображения значения в фиксированном диапазоне.",
      "<bar> — не существует в HTML5.",
      "<range> — это тип <input>, но не отдельный элемент.",
    ],
    moduleId: "html",
    sectionTitle: "Интересные вопросы",
    topic: "html_final",
  },
  {
    id: "html_final_02",
    title: "Чем отличается <section> от <article> в HTML5?",
    options: [
      "<section> используется для логических блоков, <article> для автономных частей",
      "<section> для изображений, <article> для текста",
      "<section> для заголовков, <article> для списков",
      "<section> для навигации, <article> для ссылок",
    ],
    correctAnswers: [0],
    descriptions: [
      "<section> используется для логических блоков, <article> для автономных частей — правильный ответ.",
      "<section> для изображений, <article> для текста — неверно.",
      "<section> для заголовков, <article> для списков — неверно.",
      "<section> для навигации, <article> для ссылок — неверно.",
    ],
    moduleId: "html",
    sectionTitle: "Интересные вопросы",
    topic: "html_final",
  },
  {
    id: "html_final_03",
    title:
      "Какой атрибут в HTML5 позволяет указать альтернативный источник видео при загрузке?",
    options: ["<source>", "<track>", "<video>", "<alt>"],
    correctAnswers: [0],
    descriptions: [
      "<source> — правильный ответ, позволяет указывать альтернативные источники.",
      "<track> — используется для субтитров и метаданных.",
      "<video> — контейнер для видео, но не для альтернативных источников.",
      "<alt> — это атрибут для изображений.",
    ],
    moduleId: "html",
    sectionTitle: "Интересные вопросы",
    topic: "html_final",
  },
  {
    id: "html_final_04",
    title:
      "Какой тег HTML5 используется для воспроизведения субтитров в <video>?",
    options: ["<track>", "<sub>", "<caption>", "<subtitle>"],
    correctAnswers: [0],
    descriptions: [
      "<track> — правильный ответ, добавляет субтитры, описания и метаданные.",
      "<sub> — используется для нижнего индекса в тексте.",
      "<caption> — добавляет заголовок к таблице, но не субтитры.",
      "<subtitle> — не существует в HTML5.",
    ],
    moduleId: "html",
    sectionTitle: "Интересные вопросы",
    topic: "html_final",
  },
  {
    id: "html_final_05",
    title:
      "В чём отличие атрибутов 'defer' и 'async' при подключении скриптов?",
    options: [
      "'defer' загружает скрипт после парсинга HTML, 'async' — параллельно",
      "'defer' загружает скрипт до HTML, 'async' — после",
      "'defer' нужен только для внутренних скриптов, 'async' для внешних",
      "'defer' применяется к стилям, 'async' — к скриптам",
    ],
    correctAnswers: [0],
    descriptions: [
      "'defer' загружает скрипт после парсинга HTML, 'async' — параллельно — правильный ответ.",
      "'defer' загружает скрипт до HTML, 'async' — после — это неверно.",
      "'defer' нужен только для внутренних скриптов, 'async' для внешних — неверно.",
      "'defer' применяется к стилям, 'async' — к скриптам — это неверно.",
    ],
    moduleId: "html",
    sectionTitle: "Интересные вопросы",
    topic: "html_final",
  },
  {
    id: "html_final_06",
    title:
      "Какой HTML5 атрибут позволяет браузеру загружать медиафайл только при его просмотре в области видимости?",
    options: [
      "loading='lazy'",
      "loading='eager'",
      "defer='true'",
      "async='true'",
    ],
    correctAnswers: [0],
    descriptions: [
      "loading='lazy' — правильный ответ, позволяет отложенную загрузку.",
      "loading='eager' — наоборот, загружает сразу.",
      "defer='true' — используется для скриптов, а не для изображений или видео.",
      "async='true' — тоже только для скриптов.",
    ],
    moduleId: "html",
    sectionTitle: "Интересные вопросы",
    topic: "html_final",
  },
  {
    id: "html_final_07",
    title: "Что делает атрибут 'sandbox' у тега <iframe>?",
    options: [
      "Ограничивает права доступа к ресурсам",
      "Увеличивает производительность",
      "Отключает JavaScript на странице",
      "Запрещает стилизацию вложенного контента",
    ],
    correctAnswers: [0],
    descriptions: [
      "Ограничивает права доступа к ресурсам — правильный ответ.",
      "Увеличивает производительность — это не связано с sandbox.",
      "Отключает JavaScript на странице — можно ограничить, но не отключает полностью.",
      "Запрещает стилизацию вложенного контента — это не его функция.",
    ],
    moduleId: "html",
    sectionTitle: "Интересные вопросы",
    topic: "html_final",
  },
  {
    id: "html_final_08",
    title:
      "Какой тег позволяет добавить объяснительный текст к <select>, <input> или <textarea>?",
    options: ["<label>", "<legend>", "<caption>", "<fieldset>"],
    correctAnswers: [0],
    descriptions: [
      "<label> — правильный ответ, связывает текст с элементом формы.",
      "<legend> — используется внутри <fieldset> для описания группы элементов.",
      "<caption> — это подпись для таблиц.",
      "<fieldset> — группирует элементы формы.",
    ],
    moduleId: "html",
    sectionTitle: "Интересные вопросы",
    topic: "html_final",
  },
  {
    id: "html_final_09",
    title:
      "Какой тег HTML5 позволяет создавать интерактивные элементы графики (рисование, анимация)?",
    options: ["<canvas>", "<svg>", "<graphics>", "<vector>"],
    correctAnswers: [0],
    descriptions: [
      "<canvas> — правильный ответ, используется для рисования через JavaScript.",
      "<svg> — это векторная графика, но не для интерактивных элементов.",
      "<graphics> — не существует в HTML.",
      "<vector> — не существует в HTML.",
    ],
    moduleId: "html",
    sectionTitle: "Интересные вопросы",
    topic: "html_final",
  },
];
