export const htmlHistoryQuestions = [
  {
    id: "html_intro_11",
    title: "В каком году был представлен HTML 1.0?",
    options: ["1989", "1991", "1993", "1995"],
    correctAnswers: [2],
    descriptions: [
      "1989 — Тим Бернерс-Ли предложил концепцию WWW, но HTML 1.0 ещё не существовал.",
      "1991 — Первые наброски HTML, но официальной версии не было.",
      "1993 — HTML 1.0 стал первым стандартом, предложенным IETF.",
      "1995 — Появился HTML 2.0.",
    ],
    moduleId: "html",
    sectionTitle: "Введение в HTML",
    topic: "html_intro",
  },
  {
    id: "html_intro_12",
    title: "Какая версия HTML впервые включила поддержку таблиц?",
    options: ["HTML 1.0", "HTML 2.0", "HTML 3.2", "HTML 4.0"],
    correctAnswers: [2],
    descriptions: [
      "HTML 1.0 — только базовая разметка (текст, ссылки).",
      "HTML 2.0 — стандартизировал формы, но не таблицы.",
      "HTML 3.2 (1997) — добавил таблицы, изображения с картами.",
      "HTML 4.0 — расширил возможности таблиц, но не впервые.",
    ],
    moduleId: "html",
    sectionTitle: "Введение в HTML",
    topic: "html_intro",
  },
  {
    id: "html_intro_13",
    title: "Какой орган стандартизировал HTML начиная с версии 3.2?",
    options: ["IETF", "W3C", "ECMA", "WHATWG"],
    correctAnswers: [1],
    descriptions: [
      "IETF — работал над HTML 1.0–2.0, но не 3.2.",
      "W3C (World Wide Web Consortium) —接手 стандартизацию с 1996 года.",
      "ECMA — стандартизирует JavaScript (ECMAScript).",
      "WHATWG — создан позже для разработки HTML5.",
    ],
    moduleId: "html",
    sectionTitle: "Введение в HTML",
    topic: "html_intro",
  },
  {
    id: "html_intro_14",
    title:
      "Какая версия HTML ввела разделение на Strict, Transitional и Frameset?",
    options: ["HTML 2.0", "HTML 3.2", "HTML 4.01", "XHTML 1.0"],
    correctAnswers: [2],
    descriptions: [
      "HTML 2.0 — единый стандарт без вариаций.",
      "HTML 3.2 — нет такого разделения.",
      "HTML 4.01 (1999) — три типа DTD для совместимости.",
      "XHTML 1.0 — унаследовал это, но не ввёл первым.",
    ],
    moduleId: "html",
    sectionTitle: "Введение в HTML",
    topic: "html_intro",
  },
  {
    id: "html_intro_15",
    title: "Что пришло на смену HTML4 в 2000-х годах?",
    options: ["XHTML 1.0", "HTML5", "XML", "SGML"],
    correctAnswers: [0],
    descriptions: [
      "XHTML 1.0 — строгий XML-подобный синтаксис (2000).",
      "HTML5 — появился позже (2014).",
      "XML — язык разметки, но не замена HTML.",
      "SGML — предшественник HTML, не замена.",
    ],
    moduleId: "html",
    sectionTitle: "Введение в HTML",
    topic: "html_intro",
  },
  {
    id: "html_intro_16",
    title: "Какая организация разработала первую спецификацию HTML5?",
    options: ["W3C", "IETF", "WHATWG", "Mozilla Foundation"],
    correctAnswers: [2],
    descriptions: [
      "W3C — принял HTML5 позже, после WHATWG.",
      "IETF — не участвовал в создании HTML5.",
      "WHATWG (Web Hypertext Application Technology Working Group) — начал работу в 2004.",
      "Mozilla — поддерживала, но не создавала.",
    ],
    moduleId: "html",
    sectionTitle: "Введение в HTML",
    topic: "html_intro",
  },
  {
    id: "html_intro_17",
    title: "Какой год считается официальным годом выхода HTML5?",
    options: ["2008", "2010", "2014", "2016"],
    correctAnswers: [2],
    descriptions: [
      "2008 — черновая версия.",
      "2010 — активная разработка, но не финал.",
      "2014 — W3C утвердил HTML5 как рекомендацию.",
      "2016 — вышел HTML5.1.",
    ],
    moduleId: "html",
    sectionTitle: "Введение в HTML",
    topic: "html_intro",
  },
  {
    id: "html_intro_18",
    title: "Какие элементы появились в HTML5 для семантической разметки?",
    options: [
      "<div> и <span>",
      "<table> и <tr>",
      "<header>, <footer>, <article>",
      "<font> и <center>",
    ],
    correctAnswers: [2],
    descriptions: [
      "<div> и <span> — были и раньше, не семантические.",
      "<table> — для таблиц, не новое.",
      "<header>, <footer>, <article> — семантические теги HTML5.",
      "<font> и <center> — устарели в HTML5.",
    ],
    moduleId: "html",
    sectionTitle: "Введение в HTML",
    topic: "html_intro",
  },
  {
    id: "html_intro_19",
    title: "Почему XHTML 2.0 не стал популярным?",
    options: [
      "Был слишком сложным",
      "Не поддерживал мультимедиа",
      "Несовместим с существующим вебом",
      "Требовал серверных технологий",
    ],
    correctAnswers: [2],
    descriptions: [
      "Сложность — не основная причина.",
      "Поддержка мультимедиа — не главная проблема.",
      "XHTML 2.0 отказался от обратной совместимости с HTML4.",
      "Серверные технологии — не ключевой фактор.",
    ],
    moduleId: "html",
    sectionTitle: "Введение в HTML",
    topic: "html_intro",
  },
  {
    id: "html_intro_20",
    title: "Какой технологический стек пришёл с HTML5?",
    options: [
      "Flash + Silverlight",
      "CSS2 + JavaScript ES3",
      "WebSocket, Geolocation, Canvas",
      "jQuery + PHP",
    ],
    correctAnswers: [2],
    descriptions: [
      "Flash и Silverlight — устарели с приходом HTML5.",
      "CSS2 и ES3 — старые версии.",
      "HTML5 принёс API для графики (Canvas), связи (WebSocket) и геолокации.",
      "jQuery и PHP — не часть HTML5.",
    ],
    moduleId: "html",
    sectionTitle: "Введение в HTML",
    topic: "html_intro",
  },
];
