export const htmlTables = [
  {
    id: "html_tables_01",
    title: "Какой тег используется для создания таблицы в HTML?",
    options: ["<table>", "<tr>", "<td>", "<th>"],
    correctAnswers: [0],
    descriptions: [
      "<table> — правильный ответ, используется для создания таблицы.",
      "<tr> — определяет строку внутри таблицы.",
      "<td> — создаёт ячейку данных в таблице.",
      "<th> — создаёт заголовочную ячейку в таблице.",
    ],
    moduleId: "html",
    sectionTitle: "HTML-таблицы",
    topic: "html_tables",
  },
  {
    id: "html_tables_02",
    title: "Какой тег используется для создания строки в таблице?",
    options: ["<table>", "<tr>", "<td>", "<th>"],
    correctAnswers: [1],
    descriptions: [
      "<table> — это контейнер всей таблицы.",
      "<tr> — правильный ответ, определяет строку таблицы.",
      "<td> — создаёт ячейку данных в строке.",
      "<th> — это заголовок, а не строка.",
    ],
    moduleId: "html",
    sectionTitle: "HTML-таблицы",
    topic: "html_tables",
  },
  {
    id: "html_tables_03",
    title: "Какой тег создаёт заголовочную ячейку в таблице?",
    options: ["<table>", "<tr>", "<td>", "<th>"],
    correctAnswers: [3],
    descriptions: [
      "<table> — создаёт таблицу, но не заголовок.",
      "<tr> — определяет строку таблицы.",
      "<td> — это обычная ячейка данных.",
      "<th> — правильный ответ, создаёт заголовок в таблице.",
    ],
    moduleId: "html",
    sectionTitle: "HTML-таблицы",
    topic: "html_tables",
  },
  {
    id: "html_tables_04",
    title: "Какой тег используется для ячейки с данными в таблице?",
    options: ["<table>", "<tr>", "<td>", "<th>"],
    correctAnswers: [2],
    descriptions: [
      "<table> — это контейнер всей таблицы.",
      "<tr> — определяет строку таблицы.",
      "<td> — правильный ответ, создаёт ячейку с данными.",
      "<th> — это заголовочная ячейка.",
    ],
    moduleId: "html",
    sectionTitle: "HTML-таблицы",
    topic: "html_tables",
  },
  {
    id: "html_tables_05",
    title: "Какой атрибут используется для объединения ячеек по горизонтали?",
    options: ["rowspan", "colspan", "merge", "span"],
    correctAnswers: [1],
    descriptions: [
      "rowspan — используется для объединения по вертикали.",
      "colspan — правильный ответ, объединяет ячейки по горизонтали.",
      "merge — не является валидным атрибутом HTML.",
      "span — не используется в таблицах для объединения ячеек.",
    ],
    moduleId: "html",
    sectionTitle: "HTML-таблицы",
    topic: "html_tables",
  },
  {
    id: "html_tables_06",
    title: "Какой тег используется для заголовка таблицы?",
    options: ["<thead>", "<caption>", "<header>", "<title>"],
    correctAnswers: [1],
    descriptions: [
      "<thead> — используется для группировки заголовков строк.",
      "<caption> — правильный ответ, отображает заголовок таблицы.",
      "<header> — не используется в таблицах.",
      "<title> — отображается в заголовке страницы, а не в таблице.",
    ],
    moduleId: "html",
    sectionTitle: "HTML-таблицы",
    topic: "html_tables",
  },
  {
    id: "html_tables_07",
    title: "Какой тег используется для группировки заголовочных строк таблицы?",
    options: ["<thead>", "<tbody>", "<tfoot>", "<header>"],
    correctAnswers: [0],
    descriptions: [
      "<thead> — правильный ответ, группирует заголовки строк таблицы.",
      "<tbody> — содержит основное тело данных таблицы.",
      "<tfoot> — содержит нижнюю часть таблицы (например, итоговые значения).",
      "<header> — не используется в таблицах.",
    ],
    moduleId: "html",
    sectionTitle: "HTML-таблицы",
    topic: "html_tables",
  },
  {
    id: "html_tables_08",
    title: "Какой тег используется для основного содержимого таблицы?",
    options: ["<thead>", "<tbody>", "<tfoot>", "<tr>"],
    correctAnswers: [1],
    descriptions: [
      "<thead> — содержит заголовочные строки.",
      "<tbody> — правильный ответ, содержит основное содержимое таблицы.",
      "<tfoot> — используется для итоговых строк.",
      "<tr> — это строка, а не контейнер данных.",
    ],
    moduleId: "html",
    sectionTitle: "HTML-таблицы",
    topic: "html_tables",
  },
  {
    id: "html_tables_09",
    title:
      "Какой тег определяет нижнюю часть таблицы, например, для итоговых значений?",
    options: ["<tfoot>", "<tbody>", "<thead>", "<footer>"],
    correctAnswers: [0],
    descriptions: [
      "<tfoot> — правильный ответ, используется для отображения итоговых значений внизу таблицы.",
      "<tbody> — это основное содержимое, а не подвал.",
      "<thead> — это верхняя часть, а не нижняя.",
      "<footer> — не используется в таблицах.",
    ],
    moduleId: "html",
    sectionTitle: "HTML-таблицы",
    topic: "html_tables",
  },
  {
    id: "html_tables_10",
    title: "Какой атрибут объединяет ячейки по вертикали?",
    options: ["colspan", "rowspan", "merge", "span"],
    correctAnswers: [1],
    descriptions: [
      "colspan — используется для объединения по горизонтали.",
      "rowspan — правильный ответ, объединяет ячейки по вертикали.",
      "merge — не является валидным атрибутом HTML.",
      "span — не используется в таблицах для объединения ячеек.",
    ],
    moduleId: "html",
    sectionTitle: "HTML-таблицы",
    topic: "html_tables",
  },
  {
    id: "html_tables_11",
    title: "Какой тег используется для определения заголовка (шапки) таблицы?",
    options: ["<thead>", "<tbody>", "<tfoot>", "<header>"],
    correctAnswers: [0],
    descriptions: [
      "<thead> — правильный ответ, используется для шапки таблицы.",
      "<tbody> — это основное содержимое таблицы.",
      "<tfoot> — определяет подвал таблицы.",
      "<header> — не используется в таблицах, а только в семантической разметке.",
    ],
    moduleId: "html",
    sectionTitle: "HTML-таблицы",
    topic: "html_tables",
  },
  {
    id: "html_tables_12",
    title: "Какой тег используется для основного содержимого таблицы?",
    options: ["<thead>", "<tbody>", "<tfoot>", "<content>"],
    correctAnswers: [1],
    descriptions: [
      "<thead> — это заголовочная часть таблицы.",
      "<tbody> — правильный ответ, содержит основное содержимое таблицы.",
      "<tfoot> — используется для итогов или примечаний.",
      "<content> — не существует в HTML.",
    ],
    moduleId: "html",
    sectionTitle: "HTML-таблицы",
    topic: "html_tables",
  },
  {
    id: "html_tables_13",
    title: "Какой тег используется для отображения итогов или подвала таблицы?",
    options: ["<thead>", "<tbody>", "<tfoot>", "<footer>"],
    correctAnswers: [2],
    descriptions: [
      "<thead> — это заголовок таблицы.",
      "<tbody> — это основное содержимое таблицы.",
      "<tfoot> — правильный ответ, используется для итогов или примечаний.",
      "<footer> — не используется в HTML-таблицах.",
    ],
    moduleId: "html",
    sectionTitle: "HTML-таблицы",
    topic: "html_tables",
  },
  {
    id: "html_tables_14",
    title: "Может ли тег <tfoot> располагаться в коде перед <tbody>?",
    options: ["Да", "Нет"],
    correctAnswers: [0],
    descriptions: [
      "Да — правильный ответ. В HTML-спецификации <tfoot> можно размещать перед <tbody>.",
      "Нет — это неверно, порядок тегов <thead>, <tfoot>, <tbody> не критичен.",
    ],
    moduleId: "html",
    sectionTitle: "HTML-таблицы",
    topic: "html_tables",
  },
  {
    id: "html_tables_15",
    title: "Какой тег содержит строки с данными внутри <tbody>?",
    options: ["<thead>", "<tr>", "<th>", "<tfoot>"],
    correctAnswers: [1],
    descriptions: [
      "<thead> — это заголовок таблицы, не используется в теле.",
      "<tr> — правильный ответ, определяет строки данных.",
      "<th> — используется для заголовков ячеек, но не для строк.",
      "<tfoot> — это подвал таблицы.",
    ],
    moduleId: "html",
    sectionTitle: "HTML-таблицы",
    topic: "html_tables",
  },
  {
    id: "html_tables_16",
    title:
      "Какой тег можно использовать для фиксации шапки таблицы при вертикальной прокрутке (в сочетании с CSS)?",
    options: ["<thead>", "<tbody>", "<tfoot>", "<header>"],
    correctAnswers: [0],
    descriptions: [
      "<thead> — правильный ответ, можно зафиксировать шапку при прокрутке.",
      "<tbody> — это тело таблицы, его нельзя фиксировать стандартными средствами.",
      "<tfoot> — отображает подвал, но не фиксируется.",
      "<header> — это семантический элемент, не используется в таблицах.",
    ],
    moduleId: "html",
    sectionTitle: "HTML-таблицы",
    topic: "html_tables",
  },
  {
    id: "html_tables_17",
    title: "Для чего предназначен тег <tfoot>?",
    options: [
      "Для отображения основной информации",
      "Для фиксирования заголовков",
      "Для вывода итогов или сумм",
      "Для разметки колонок",
    ],
    correctAnswers: [2],
    descriptions: [
      "Для отображения основной информации — это задача <tbody>.",
      "Для фиксирования заголовков — это задача <thead>.",
      "Для вывода итогов или сумм — правильный ответ.",
      "Для разметки колонок — это делается через <col> или CSS.",
    ],
    moduleId: "html",
    sectionTitle: "HTML-таблицы",
    topic: "html_tables",
  },
  {
    id: "html_tables_18",
    title: "Может ли в <thead> находиться тег <td>?",
    options: ["Да", "Нет"],
    correctAnswers: [1],
    descriptions: [
      "Да — это неверно, <thead> предназначен только для <th>.",
      "Нет — правильный ответ, <td> не допускается в <thead>, только <th>.",
    ],
    moduleId: "html",
    sectionTitle: "HTML-таблицы",
    topic: "html_tables",
  },
  {
    id: "html_tables_19",
    title:
      "Как правильно структурировать таблицу с заголовком, основным телом и итогами?",
    options: [
      "<thead>, <tbody>, <tfoot>",
      "<tbody>, <thead>, <tfoot>",
      "<tfoot>, <thead>, <tbody>",
      "<thead>, <tfoot>, <tbody>",
    ],
    correctAnswers: [0],
    descriptions: [
      "<thead>, <tbody>, <tfoot> — правильный ответ, это стандартная структура.",
      "<tbody>, <thead>, <tfoot> — нарушает логический порядок.",
      "<tfoot>, <thead>, <tbody> — некорректный порядок.",
      "<thead>, <tfoot>, <tbody> — неверно, итоги должны идти после тела.",
    ],
    moduleId: "html",
    sectionTitle: "HTML-таблицы",
    topic: "html_tables",
  },
  {
    id: "html_tables_20",
    title: "Можно ли добавить несколько тегов <tbody> в одну таблицу?",
    options: ["Да", "Нет"],
    correctAnswers: [0],
    descriptions: [
      "Да — правильный ответ, в одной таблице можно использовать несколько <tbody> для логической группировки.",
      "Нет — это неверно, стандарт допускает несколько <tbody>.",
    ],
    moduleId: "html",
    sectionTitle: "HTML-таблицы",
    topic: "html_tables",
  },
  {
    id: "html_tables_21",
    title: "Какой атрибут используется для объединения ячеек по горизонтали?",
    options: ["colspan", "rowspan", "merge", "span"],
    correctAnswers: [0],
    descriptions: [
      "colspan — правильный ответ, объединяет ячейки по горизонтали.",
      "rowspan — объединяет ячейки по вертикали.",
      "merge — не является валидным атрибутом HTML.",
      "span — это часть других элементов, но не в таблицах.",
    ],
    moduleId: "html",
    sectionTitle: "HTML-таблицы",
    topic: "html_tables",
  },
  {
    id: "html_tables_22",
    title: "Какой атрибут используется для объединения ячеек по вертикали?",
    options: ["colspan", "rowspan", "merge", "span"],
    correctAnswers: [1],
    descriptions: [
      "colspan — объединяет ячейки по горизонтали.",
      "rowspan — правильный ответ, объединяет ячейки по вертикали.",
      "merge — не существует в HTML.",
      "span — это часть других элементов, но не в таблицах.",
    ],
    moduleId: "html",
    sectionTitle: "HTML-таблицы",
    topic: "html_tables",
  },
  {
    id: "html_tables_23",
    title:
      "Какой минимально допустимый размер можно указать в атрибуте colspan?",
    options: ["0", "1", "2", "неограниченно"],
    correctAnswers: [1],
    descriptions: [
      "0 — невозможно, значение должно быть положительным.",
      "1 — правильный ответ, это минимальное значение, равное одной ячейке.",
      "2 — минимально допустимое значение — это 1.",
      "неограниченно — максимальное значение существует, но не минимальное.",
    ],
    moduleId: "html",
    sectionTitle: "HTML-таблицы",
    topic: "html_tables",
  },
  {
    id: "html_tables_24",
    title: "Какой атрибут позволяет объединить ячейку на две строки?",
    options: ["colspan='2'", "rowspan='2'", "colspan='1'", "rowspan='1'"],
    correctAnswers: [1],
    descriptions: [
      "colspan='2' — объединяет на два столбца, но не строки.",
      "rowspan='2' — правильный ответ, объединяет на две строки.",
      "colspan='1' — не объединяет, оставляет одну ячейку.",
      "rowspan='1' — оставляет одну ячейку, не объединяет.",
    ],
    moduleId: "html",
    sectionTitle: "HTML-таблицы",
    topic: "html_tables",
  },
  {
    id: "html_tables_25",
    title:
      "Какой тег можно использовать для объединения ячеек по горизонтали и вертикали одновременно?",
    options: ["<tr>", "<td>", "<th>", "<table>"],
    correctAnswers: [1],
    descriptions: [
      "<tr> — определяет строку, не объединяет ячейки.",
      "<td> — правильный ответ, можно задать одновременно colspan и rowspan.",
      "<th> — используется для заголовков, но тоже можно объединять.",
      "<table> — это контейнер таблицы, не объединяет ячейки напрямую.",
    ],
    moduleId: "html",
    sectionTitle: "HTML-таблицы",
    topic: "html_tables",
  },
  {
    id: "html_tables_26",
    title:
      "Что произойдёт, если сумма colspan всех ячеек в строке превышает количество столбцов в таблице?",
    options: [
      "Таблица сломается",
      "Браузер автоматически добавит недостающие столбцы",
      "Браузер игнорирует лишние colspan",
      "Возникнет ошибка рендеринга",
    ],
    correctAnswers: [1],
    descriptions: [
      "Таблица сломается — это неправда, браузер просто добавит колонки.",
      "Браузер автоматически добавит недостающие столбцы — правильный ответ.",
      "Браузер игнорирует лишние colspan — это неверно, он добавит колонки.",
      "Возникнет ошибка рендеринга — браузеры адаптируют отображение.",
    ],
    moduleId: "html",
    sectionTitle: "HTML-таблицы",
    topic: "html_tables",
  },
  {
    id: "html_tables_27",
    title:
      "Может ли значение атрибута rowspan быть больше, чем количество строк в <tbody>?",
    options: ["Да", "Нет"],
    correctAnswers: [0],
    descriptions: [
      "Да — правильный ответ, браузер создаст пустые строки при необходимости.",
      "Нет — это неправда, браузер автоматически добавляет недостающие строки.",
    ],
    moduleId: "html",
    sectionTitle: "HTML-таблицы",
    topic: "html_tables",
  },
  {
    id: "html_tables_28",
    title: "Может ли ячейка одновременно содержать атрибуты colspan и rowspan?",
    options: ["Да", "Нет"],
    correctAnswers: [0],
    descriptions: [
      "Да — правильный ответ, можно объединить как по строкам, так и по столбцам одновременно.",
      "Нет — это неверно, HTML позволяет использовать оба атрибута одновременно.",
    ],
    moduleId: "html",
    sectionTitle: "HTML-таблицы",
    topic: "html_tables",
  },
  {
    id: "html_tables_29",
    title: "Что произойдёт, если указать colspan='0' на <td> в таблице?",
    options: [
      "Ячейка будет скрыта",
      "Будет ошибка рендеринга",
      "Ячейка займёт все оставшиеся столбцы",
      "Ячейка будет занимать одну колонку",
    ],
    correctAnswers: [2],
    descriptions: [
      "Ячейка будет скрыта — это неверно.",
      "Будет ошибка рендеринга — браузер обработает это корректно.",
      "Ячейка займёт все оставшиеся столбцы — правильный ответ.",
      "Ячейка будет занимать одну колонку — это неверно при colspan='0'.",
    ],
    moduleId: "html",
    sectionTitle: "HTML-таблицы",
    topic: "html_tables",
  },
  {
    id: "html_tables_30",
    title:
      "Какой результат будет, если значение rowspan превышает количество оставшихся строк в таблице?",
    options: [
      "Браузер покажет ошибку",
      "Ячейка выйдет за пределы таблицы",
      "Браузер автоматически добавит недостающие строки",
      "Таблица отобразится некорректно",
    ],
    correctAnswers: [2],
    descriptions: [
      "Браузер покажет ошибку — это неправда.",
      "Ячейка выйдет за пределы таблицы — это невозможно.",
      "Браузер автоматически добавит недостающие строки — правильный ответ.",
      "Таблица отобразится некорректно — браузер справится с этим автоматически.",
    ],
    moduleId: "html",
    sectionTitle: "HTML-таблицы",
    topic: "html_tables",
  },
];
