export const htmlbBestPractices = [
  {
    id: "html_best_practices_01",
    title: "Какие новые семантические теги появились в HTML5?",
    options: [
      "<header>, <footer>, <section>, <article>",
      "<div>, <span>, <b>, <i>",
      "<blink>, <marquee>, <font>",
      "<table>, <tr>, <td>, <th>",
    ],
    correctAnswers: [0],
    descriptions: [
      "<header>, <footer>, <section>, <article> — правильный ответ, это новые семантические теги HTML5.",
      "<div>, <span>, <b>, <i> — существовали до HTML5, это не новые теги.",
      "<blink>, <marquee>, <font> — устаревшие теги, они не поддерживаются в HTML5.",
      "<table>, <tr>, <td>, <th> — это теги для таблиц, которые существовали до HTML5.",
    ],
    moduleId: "html",
    sectionTitle: "Современные практики и доступность",
    topic: "html_best_practices",
  },
  {
    id: "html_best_practices_02",
    title:
      "Какой тег в HTML5 используется для вставки видеофайлов без плагинов?",
    options: ["<video>", "<media>", "<embed>", "<object>"],
    correctAnswers: [0],
    descriptions: [
      "<video> — правильный ответ, это новый тег HTML5 для вставки видео.",
      "<media> — не существует в HTML.",
      "<embed> — используется для встраивания объектов, но не является частью HTML5.",
      "<object> — поддерживает объекты, но не рекомендуется для видео в HTML5.",
    ],
    moduleId: "html",
    sectionTitle: "Современные практики и доступность",
    topic: "html_best_practices",
  },
  {
    id: "html_best_practices_03",
    title:
      "Какой из следующих атрибутов HTML5 позволяет добавить валидацию email без JavaScript?",
    options: ["type='email'", "type='text'", "type='url'", "type='number'"],
    correctAnswers: [0],
    descriptions: [
      "type='email' — правильный ответ, HTML5 валидирует email-адрес.",
      "type='text' — это просто текстовое поле, валидации нет.",
      "type='url' — проверяет формат URL, но не email.",
      "type='number' — используется для ввода чисел.",
    ],
    moduleId: "html",
    sectionTitle: "Современные практики и доступность",
    topic: "html_best_practices",
  },
  {
    id: "html_best_practices_04",
    title: "Какой API HTML5 позволяет сохранять данные локально в браузере?",
    options: ["localStorage", "sessionStorage", "cookies", "cache"],
    correctAnswers: [0],
    descriptions: [
      "localStorage — правильный ответ, позволяет сохранять данные в браузере без истечения срока действия.",
      "sessionStorage — сохраняет данные до закрытия вкладки.",
      "cookies — это механизм хранения данных, но он не связан с HTML5 API.",
      "cache — это не метод HTML5 для хранения данных.",
    ],
    moduleId: "html",
    sectionTitle: "Современные практики и доступность",
    topic: "html_best_practices",
  },
  {
    id: "html_best_practices_05",
    title: "Какой HTML5 API позволяет определить местоположение пользователя?",
    options: ["Geolocation API", "Web Workers API", "File API", "Canvas API"],
    correctAnswers: [0],
    descriptions: [
      "Geolocation API — правильный ответ, используется для определения местоположения.",
      "Web Workers API — позволяет выполнять фоновые задачи.",
      "File API — даёт доступ к файловой системе пользователя.",
      "Canvas API — предназначен для рисования в HTML5.",
    ],
    moduleId: "html",
    sectionTitle: "Современные практики и доступность",
    topic: "html_best_practices",
  },
  {
    id: "html_best_practices_06",
    title: "Какой из следующих тегов считается устаревшим в HTML5?",
    options: ["<font>", "<header>", "<section>", "<footer>"],
    correctAnswers: [0],
    descriptions: [
      "<font> — правильный ответ, этот тег устарел в HTML5.",
      "<header> — это новый семантический тег HTML5.",
      "<section> — это новый семантический тег HTML5.",
      "<footer> — это новый семантический тег HTML5.",
    ],
    moduleId: "html",
    sectionTitle: "Современные практики и доступность",
    topic: "html_best_practices",
  },
  {
    id: "html_best_practices_07",
    title:
      "Какой тег в HTML5 позволяет рисовать графику на странице без использования плагинов?",
    options: ["<canvas>", "<drawing>", "<svg>", "<image>"],
    correctAnswers: [0],
    descriptions: [
      "<canvas> — правильный ответ, позволяет рисовать на странице.",
      "<drawing> — не существует в HTML.",
      "<svg> — используется для векторной графики, но это не часть <canvas>.",
      "<image> — это просто тег для изображений.",
    ],
    moduleId: "html",
    sectionTitle: "Современные практики и доступность",
    topic: "html_best_practices",
  },
  {
    id: "html_best_practices_08",
    title:
      "Какой атрибут в HTML5 позволяет включить автозапуск видео при загрузке страницы?",
    options: ["autoplay", "controls", "loop", "muted"],
    correctAnswers: [0],
    descriptions: [
      "autoplay — правильный ответ, автоматически запускает видео.",
      "controls — добавляет панель управления.",
      "loop — зацикливает воспроизведение.",
      "muted — отключает звук, но не запускает видео автоматически.",
    ],
    moduleId: "html",
    sectionTitle: "Современные практики и доступность",
    topic: "html_best_practices",
  },
  {
    id: "html_best_practices_09",
    title:
      "Какой из тегов HTML5 заменяет устаревший <b> для выделения важного текста?",
    options: ["<strong>", "<em>", "<header>", "<highlight>"],
    correctAnswers: [0],
    descriptions: [
      "<strong> — правильный ответ, используется для выделения важного текста.",
      "<em> — выделяет текст курсивом, но не указывает на важность.",
      "<header> — это семантический тег для заголовков.",
      "<highlight> — не существует в HTML.",
    ],
    moduleId: "html",
    sectionTitle: "Современные практики и доступность",
    topic: "html_best_practices",
  },
  {
    id: "html_best_practices_10",
    title:
      "Какой тег HTML5 используется для создания разметки статьи или записи в блоге?",
    options: ["<article>", "<div>", "<section>", "<main>"],
    correctAnswers: [0],
    descriptions: [
      "<article> — правильный ответ, используется для автономного контента.",
      "<div> — это контейнер, но не семантический элемент.",
      "<section> — это логическая группа, но не отдельная статья.",
      "<main> — используется для основного содержимого страницы.",
    ],
    moduleId: "html",
    sectionTitle: "Современные практики и доступность",
    topic: "html_best_practices",
  },
  {
    id: "html_best_practices_21",
    title:
      "Какой тег HTML рекомендуется использовать для создания семантической навигации на сайте?",
    options: ["<nav>", "<div>", "<footer>", "<header>"],
    correctAnswers: [0],
    descriptions: [
      "<nav> — правильный ответ, используется для обертки основного меню навигации.",
      "<div> — это просто контейнер, он не семантический.",
      "<footer> — используется для подвала страницы, но не для навигации.",
      "<header> — предназначен для шапки страницы или раздела.",
    ],
    moduleId: "html",
    sectionTitle: "Современные практики и доступность",
    topic: "html_best_practices",
  },
  {
    id: "html_best_practices_22",
    title: "Какой атрибут используется для скрытия элемента от скринридеров?",
    options: [
      "aria-hidden='true'",
      "role='hidden'",
      "hidden='true'",
      "display='none'",
    ],
    correctAnswers: [0],
    descriptions: [
      "aria-hidden='true' — правильный ответ, скрывает элемент от скринридеров.",
      "role='hidden' — не существует в спецификации HTML.",
      "hidden='true' — скрывает элемент, но скринридеры всё равно могут его прочитать.",
      "display='none' — скрывает визуально, но скринридеры могут его озвучить.",
    ],
    moduleId: "html",
    sectionTitle: "Современные практики и доступность",
    topic: "html_best_practices",
  },
  {
    id: "html_best_practices_23",
    title: "Какой тег HTML помогает связать метку <label> с полем ввода?",
    options: ["id и for", "name и for", "class и id", "id и name"],
    correctAnswers: [0],
    descriptions: [
      "id и for — правильный ответ. Атрибут 'for' указывает на id поля.",
      "name и for — это неверно, 'for' работает с id, а не с name.",
      "class и id — классы не связаны с <label>.",
      "id и name — name используется для отправки формы, но не для связи с <label>.",
    ],
    moduleId: "html",
    sectionTitle: "Современные практики и доступность",
    topic: "html_best_practices",
  },
  {
    id: "html_best_practices_24",
    title:
      "Какой атрибут ARIA используется для задания текстовой подписи элементу?",
    options: ["aria-label", "aria-hidden", "aria-role", "aria-live"],
    correctAnswers: [0],
    descriptions: [
      "aria-label — правильный ответ, добавляет текстовую метку для элемента.",
      "aria-hidden — скрывает элемент от скринридеров.",
      "aria-role — это неверно, правильно 'role'.",
      "aria-live — управляет озвучиванием изменений в реальном времени.",
    ],
    moduleId: "html",
    sectionTitle: "Современные практики и доступность",
    topic: "html_best_practices",
  },
  {
    id: "html_best_practices_25",
    title: "Какие теги HTML помогают скринридерам понять структуру страницы?",
    options: [
      "<header>, <nav>, <main>, <footer>",
      "<div>, <span>, <b>, <i>",
      "<marquee>, <blink>, <center>",
      "<img>, <a>, <br>",
    ],
    correctAnswers: [0],
    descriptions: [
      "<header>, <nav>, <main>, <footer> — правильный ответ, это семантические теги HTML5.",
      "<div>, <span>, <b>, <i> — это обертки, но не семантические теги.",
      "<marquee>, <blink>, <center> — устаревшие теги, не рекомендуется использовать.",
      "<img>, <a>, <br> — важные элементы, но они не влияют на структуру страницы.",
    ],
    moduleId: "html",
    sectionTitle: "Современные практики и доступность",
    topic: "html_best_practices",
  },
  {
    id: "html_best_practices_26",
    title:
      "Какой HTML-элемент позволяет пользователям перемещаться по странице с помощью клавиши Tab?",
    options: [
      "<a>, <button>, <input>",
      "<div>, <span>, <ul>",
      "<main>, <section>, <header>",
      "<footer>, <nav>, <aside>",
    ],
    correctAnswers: [0],
    descriptions: [
      "<a>, <button>, <input> — правильный ответ, эти элементы фокусируются при нажатии Tab.",
      "<div>, <span>, <ul> — не фокусируются по умолчанию.",
      "<main>, <section>, <header> — являются контейнерами, но не фокусируются сами по себе.",
      "<footer>, <nav>, <aside> — семантические обертки, но не интерактивные.",
    ],
    moduleId: "html",
    sectionTitle: "Современные практики и доступность",
    topic: "html_best_practices",
  },
  {
    id: "html_best_practices_27",
    title:
      "Какой атрибут ARIA используется для обозначения элемента в роли кнопки?",
    options: [
      "role='button'",
      "aria-button='true'",
      "type='button'",
      "aria-role='button'",
    ],
    correctAnswers: [0],
    descriptions: [
      "role='button' — правильный ответ, задаёт роль кнопки.",
      "aria-button='true' — не существует в ARIA-спецификации.",
      "type='button' — используется только на <button> или <input>.",
      "aria-role='button' — неверный синтаксис, должно быть просто 'role'.",
    ],
    moduleId: "html",
    sectionTitle: "Современные практики и доступность",
    topic: "html_best_practices",
  },
  {
    id: "html_best_practices_28",
    title:
      "Какой уровень контраста текста по отношению к фону рекомендует WCAG 2.1?",
    options: ["4.5:1", "2.5:1", "5.5:1", "3.0:1"],
    correctAnswers: [0],
    descriptions: [
      "4.5:1 — правильный ответ, это рекомендуемый уровень контраста для текста.",
      "2.5:1 — недостаточный контраст для большинства пользователей.",
      "5.5:1 — допустимо, но минимально нужно 4.5:1.",
      "3.0:1 — не соответствует рекомендациям WCAG 2.1.",
    ],
    moduleId: "html",
    sectionTitle: "Современные практики и доступность",
    topic: "html_best_practices",
  },
  {
    id: "html_best_practices_29",
    title:
      "Какой атрибут ARIA позволяет скрыть элемент только от скринридеров, но оставить видимым на странице?",
    options: [
      "aria-hidden='true'",
      "role='presentation'",
      "display='none'",
      "visibility='hidden'",
    ],
    correctAnswers: [0],
    descriptions: [
      "aria-hidden='true' — правильный ответ, скрывает элемент от скринридеров.",
      "role='presentation' — убирает семантику, но не скрывает.",
      "display='none' — полностью скрывает элемент и из DOM.",
      "visibility='hidden' — скрывает элемент, но он остаётся в DOM.",
    ],
    moduleId: "html",
    sectionTitle: "Современные практики и доступность",
    topic: "html_best_practices",
  },
  {
    id: "html_best_practices_30",
    title:
      "Какой HTML-тег следует использовать для обозначения основного содержимого страницы?",
    options: ["<main>", "<div>", "<section>", "<header>"],
    correctAnswers: [0],
    descriptions: [
      "<main> — правильный ответ, используется для основного контента.",
      "<div> — это обертка, но не семантический элемент.",
      "<section> — используется для разделения смысловых блоков.",
      "<header> — это шапка страницы или раздела.",
    ],
    moduleId: "html",
    sectionTitle: "Современные практики и доступность",
    topic: "html_best_practices",
  },
];
