export const browserIntro = [
  {
    id: "browser_intro_01",
    title: "Что такое браузер?",
    options: [
      "Программа для просмотра и взаимодействия с веб-страницами",
      "Редактор кода для веб-разработки",
      "Среда выполнения для серверного кода",
      "Программа для создания веб-страниц",
    ],
    correctAnswers: [0],
    descriptions: [
      "Программа для просмотра и взаимодействия с веб-страницами — правильный ответ.",
      "Редактор кода для веб-разработки — это IDE или текстовый редактор.",
      "Среда выполнения для серверного кода — это, например, Node.js или Java.",
      "Программа для создания веб-страниц — это редактор или конструктор сайтов.",
    ],
    moduleId: "browser",
    sectionTitle: "Введение в работу браузера",
    topic: "browser_intro",
  },
  {
    id: "browser_intro_02",
    title: "Какие задачи выполняет браузер при загрузке страницы?",
    options: [
      "Отправляет HTTP-запрос к серверу и отображает полученный HTML",
      "Компилирует JavaScript в машинный код",
      "Создаёт базу данных на клиенте",
      "Запускает серверные процессы",
    ],
    correctAnswers: [0],
    descriptions: [
      "Отправляет HTTP-запрос к серверу и отображает полученный HTML — правильный ответ.",
      "Компилирует JavaScript в машинный код — это делает JavaScript Engine, но не компилирует в машинный код.",
      "Создаёт базу данных на клиенте — это может делать IndexedDB, но это не основная задача браузера.",
      "Запускает серверные процессы — это задача серверной части, а не браузера.",
    ],
    moduleId: "browser",
    sectionTitle: "Введение в работу браузера",
    topic: "browser_intro",
  },
  {
    id: "browser_intro_03",
    title: "Какие браузеры считаются наиболее популярными на рынке?",
    options: [
      "Google Chrome, Mozilla Firefox, Safari, Microsoft Edge, Opera",
      "Internet Explorer, Netscape, Opera Mini",
      "Vivaldi, Brave, Midori",
      "UC Browser, Maxthon, Pale Moon",
    ],
    correctAnswers: [0],
    descriptions: [
      "Google Chrome, Mozilla Firefox, Safari, Microsoft Edge, Opera — правильный ответ, это наиболее распространённые браузеры.",
      "Internet Explorer, Netscape, Opera Mini — IE устарел, Netscape больше не поддерживается.",
      "Vivaldi, Brave, Midori — это менее популярные решения.",
      "UC Browser, Maxthon, Pale Moon — это редкие браузеры, популярные в отдельных странах.",
    ],
    moduleId: "browser",
    sectionTitle: "Введение в работу браузера",
    topic: "browser_intro",
  },
  {
    id: "browser_intro_04",
    title:
      "Как называется механизм в браузере, отвечающий за выполнение JavaScript?",
    options: [
      "JavaScript Engine",
      "Rendering Engine",
      "Browser Engine",
      "Networking Module",
    ],
    correctAnswers: [0],
    descriptions: [
      "JavaScript Engine — правильный ответ, это компонент браузера, который исполняет JS-код.",
      "Rendering Engine — отвечает за отображение HTML и CSS.",
      "Browser Engine — координирует взаимодействие между UI и рендерингом.",
      "Networking Module — отвечает за сетевые запросы, но не за выполнение кода.",
    ],
    moduleId: "browser",
    sectionTitle: "Введение в работу браузера",
    topic: "browser_intro",
  },
  {
    id: "browser_intro_05",
    title:
      "Какой компонент браузера отвечает за отображение HTML и CSS на экране?",
    options: [
      "Rendering Engine",
      "JavaScript Engine",
      "Browser Engine",
      "Data Storage",
    ],
    correctAnswers: [0],
    descriptions: [
      "Rendering Engine — правильный ответ, это механизм, который преобразует HTML и CSS в визуальную картину.",
      "JavaScript Engine — отвечает за выполнение JS.",
      "Browser Engine — управляет взаимодействием между компонентами.",
      "Data Storage — это механизм для хранения данных, а не рендеринга.",
    ],
    moduleId: "browser",
    sectionTitle: "Введение в работу браузера",
    topic: "browser_intro",
  },
  {
    id: "browser_intro_06",
    title: "Как называется процесс преобразования HTML-кода в DOM-дерево?",
    options: ["Парсинг", "Рендеринг", "Кэширование", "Декомпиляция"],
    correctAnswers: [0],
    descriptions: [
      "Парсинг — правильный ответ, это процесс разбора HTML в структуру данных (DOM).",
      "Рендеринг — это отображение данных, а не их разбор.",
      "Кэширование — это сохранение данных в локальной памяти.",
      "Декомпиляция — это обратный процесс из машинного кода в исходный.",
    ],
    moduleId: "browser",
    sectionTitle: "Введение в работу браузера",
    topic: "browser_intro",
  },
  {
    id: "browser_intro_07",
    title: "Для чего используется кэш браузера?",
    options: [
      "Для ускорения загрузки ресурсов при повторных обращениях",
      "Для хранения данных пользователей",
      "Для работы с серверными скриптами",
      "Для защиты от XSS-атак",
    ],
    correctAnswers: [0],
    descriptions: [
      "Для ускорения загрузки ресурсов при повторных обращениях — правильный ответ.",
      "Для хранения данных пользователей — это делает localStorage или cookies.",
      "Для работы с серверными скриптами — это серверная сторона.",
      "Для защиты от XSS-атак — это задача Content Security Policy (CSP).",
    ],
    moduleId: "browser",
    sectionTitle: "Введение в работу браузера",
    topic: "browser_intro",
  },
  {
    id: "browser_intro_08",
    title:
      "Какой протокол обеспечивает защищённое соединение между браузером и сервером?",
    options: ["HTTPS", "FTP", "HTTP", "SMTP"],
    correctAnswers: [0],
    descriptions: [
      "HTTPS — правильный ответ, это защищённый протокол передачи данных.",
      "FTP — это протокол передачи файлов, он не шифруется по умолчанию.",
      "HTTP — это незащищённый протокол.",
      "SMTP — это протокол отправки электронной почты.",
    ],
    moduleId: "browser",
    sectionTitle: "Введение в работу браузера",
    topic: "browser_intro",
  },
  {
    id: "browser_intro_09",
    title:
      "Какие технологии используются для хранения данных на клиентской стороне в браузере?",
    options: [
      "localStorage, sessionStorage, cookies",
      "FTP, HTTP, SMTP",
      "AJAX, REST, GraphQL",
      "CSS, HTML, JavaScript",
    ],
    correctAnswers: [0],
    descriptions: [
      "localStorage, sessionStorage, cookies — правильный ответ.",
      "FTP, HTTP, SMTP — это сетевые протоколы.",
      "AJAX, REST, GraphQL — это механизмы обмена данными, но не хранения.",
      "CSS, HTML, JavaScript — это технологии верстки и логики, но не хранилища.",
    ],
    moduleId: "browser",
    sectionTitle: "Введение в работу браузера",
    topic: "browser_intro",
  },
  {
    id: "browser_intro_10",
    title: "Что такое IP-адрес в интернете?",
    options: [
      "Уникальный числовой идентификатор устройства в сети",
      "Имя домена веб-сайта",
      "Метод шифрования данных",
      "Тип соединения между сервером и клиентом",
    ],
    correctAnswers: [0],
    descriptions: [
      "Уникальный числовой идентификатор устройства в сети — правильный ответ.",
      "Имя домена веб-сайта — это адрес в формате текста, который преобразуется в IP.",
      "Метод шифрования данных — это SSL или HTTPS.",
      "Тип соединения между сервером и клиентом — это TCP или UDP.",
    ],
    moduleId: "browser",
    sectionTitle: "Введение в работу браузера",
    topic: "browser_intro",
  },
  {
    id: "browser_intro_11",
    title: "Какую задачу выполняет DNS (Domain Name System)?",
    options: [
      "Преобразует доменное имя в IP-адрес",
      "Шифрует данные при передаче",
      "Оптимизирует загрузку изображений",
      "Управляет подключениями к локальной сети",
    ],
    correctAnswers: [0],
    descriptions: [
      "Преобразует доменное имя в IP-адрес — правильный ответ.",
      "Шифрует данные при передаче — это задача HTTPS.",
      "Оптимизирует загрузку изображений — это не связано с DNS.",
      "Управляет подключениями к локальной сети — это делает роутер.",
    ],
    moduleId: "browser",
    sectionTitle: "Введение в работу браузера",
    topic: "browser_intro",
  },
  {
    id: "browser_intro_12",
    title:
      "Какой протокол используется для безопасной передачи данных в интернете?",
    options: ["HTTPS", "HTTP", "FTP", "SMTP"],
    correctAnswers: [0],
    descriptions: [
      "HTTPS — правильный ответ, это безопасная версия HTTP с шифрованием.",
      "HTTP — это незащищённый протокол.",
      "FTP — это протокол передачи файлов, но без шифрования.",
      "SMTP — это протокол отправки электронной почты.",
    ],
    moduleId: "browser",
    sectionTitle: "Введение в работу браузера",
    topic: "browser_intro",
  },
  {
    id: "browser_intro_13",
    title: "Что означает HTTP-запрос с методом GET?",
    options: [
      "Запрос данных с сервера без изменений",
      "Отправка данных на сервер для создания ресурса",
      "Удаление данных на сервере",
      "Обновление данных на сервере",
    ],
    correctAnswers: [0],
    descriptions: [
      "Запрос данных с сервера без изменений — правильный ответ.",
      "Отправка данных на сервер для создания ресурса — это POST.",
      "Удаление данных на сервере — это DELETE.",
      "Обновление данных на сервере — это PUT или PATCH.",
    ],
    moduleId: "browser",
    sectionTitle: "Введение в работу браузера",
    topic: "browser_intro",
  },
  {
    id: "browser_intro_14",
    title: "Для чего используется протокол TCP?",
    options: [
      "Гарантирует доставку пакетов данных в правильном порядке",
      "Преобразует IP-адрес в доменное имя",
      "Шифрует данные при передаче",
      "Оптимизирует изображения на странице",
    ],
    correctAnswers: [0],
    descriptions: [
      "Гарантирует доставку пакетов данных в правильном порядке — правильный ответ.",
      "Преобразует IP-адрес в доменное имя — это задача DNS.",
      "Шифрует данные при передаче — это делает HTTPS.",
      "Оптимизирует изображения на странице — это задача frontend-оптимизации.",
    ],
    moduleId: "browser",
    sectionTitle: "Введение в работу браузера",
    topic: "browser_intro",
  },
  {
    id: "browser_intro_15",
    title: "Что делает браузер после получения HTML-кода от сервера?",
    options: [
      "Парсит HTML в DOM-дерево и отображает на экране",
      "Сразу сохраняет в кэш браузера",
      "Отправляет HTML на сервер для обработки",
      "Шифрует HTML-код для безопасности",
    ],
    correctAnswers: [0],
    descriptions: [
      "Парсит HTML в DOM-дерево и отображает на экране — правильный ответ.",
      "Сразу сохраняет в кэш браузера — это зависит от настроек кэша.",
      "Отправляет HTML на сервер для обработки — это неверно.",
      "Шифрует HTML-код для безопасности — это не делается на уровне браузера.",
    ],
    moduleId: "browser",
    sectionTitle: "Введение в работу браузера",
    topic: "browser_intro",
  },
  {
    id: "browser_intro_16",
    title:
      "Какой метод HTTP-запроса используется для отправки данных формы на сервер?",
    options: ["POST", "GET", "DELETE", "PUT"],
    correctAnswers: [0],
    descriptions: [
      "POST — правильный ответ, отправляет данные формы на сервер.",
      "GET — используется для получения данных, но данные видны в URL.",
      "DELETE — используется для удаления данных.",
      "PUT — используется для обновления данных.",
    ],
    moduleId: "browser",
    sectionTitle: "Введение в работу браузера",
    topic: "browser_intro",
  },
  {
    id: "browser_intro_17",
    title: "Что такое CDN (Content Delivery Network)?",
    options: [
      "Сеть серверов для ускоренной доставки контента",
      "Система управления базами данных",
      "Механизм шифрования данных в браузере",
      "Программа для отладки сетевых подключений",
    ],
    correctAnswers: [0],
    descriptions: [
      "Сеть серверов для ускоренной доставки контента — правильный ответ.",
      "Система управления базами данных — это, например, MySQL или MongoDB.",
      "Механизм шифрования данных в браузере — это HTTPS.",
      "Программа для отладки сетевых подключений — это DevTools или Wireshark.",
    ],
    moduleId: "browser",
    sectionTitle: "Введение в работу браузера",
    topic: "browser_intro",
  },
  {
    id: "browser_intro_18",
    title: "Какой протокол используется для передачи электронной почты?",
    options: ["SMTP", "HTTP", "HTTPS", "FTP"],
    correctAnswers: [0],
    descriptions: [
      "SMTP — правильный ответ, используется для отправки электронной почты.",
      "HTTP — это протокол для загрузки веб-страниц.",
      "HTTPS — защищённый вариант HTTP.",
      "FTP — используется для передачи файлов.",
    ],
    moduleId: "browser",
    sectionTitle: "Введение в работу браузера",
    topic: "browser_intro",
  },
  {
    id: "browser_intro_19",
    title: "Что такое HTTP?",
    options: [
      "Протокол для обмена данными между клиентом и сервером",
      "Формат хранения данных в браузере",
      "Язык программирования для веб-приложений",
      "Метод шифрования данных",
    ],
    correctAnswers: [0],
    descriptions: [
      "Протокол для обмена данными между клиентом и сервером — правильный ответ.",
      "Формат хранения данных в браузере — это LocalStorage или cookies.",
      "Язык программирования для веб-приложений — это JavaScript.",
      "Метод шифрования данных — это задача HTTPS, но не HTTP.",
    ],
    moduleId: "browser",
    sectionTitle: "Введение в работу браузера",
    topic: "browser_intro",
  },
  {
    id: "browser_intro_20",
    title:
      "Какой метод HTTP-запроса используется для получения данных с сервера?",
    options: ["GET", "POST", "PUT", "DELETE"],
    correctAnswers: [0],
    descriptions: [
      "GET — правильный ответ, используется для получения данных.",
      "POST — используется для отправки данных на сервер.",
      "PUT — используется для изменения данных.",
      "DELETE — используется для удаления данных.",
    ],
    moduleId: "browser",
    sectionTitle: "Введение в работу браузера",
    topic: "browser_intro",
  },
  {
    id: "browser_intro_21",
    title: "Чем отличается HTTPS от HTTP?",
    options: [
      "HTTPS шифрует данные, HTTP — нет",
      "HTTP быстрее, чем HTTPS",
      "HTTPS используется только на мобильных устройствах",
      "HTTP работает только с текстовыми файлами",
    ],
    correctAnswers: [0],
    descriptions: [
      "HTTPS шифрует данные, HTTP — нет — правильный ответ.",
      "HTTP быстрее, чем HTTPS — это не всегда так, различие минимально.",
      "HTTPS используется только на мобильных устройствах — неверно.",
      "HTTP работает только с текстовыми файлами — неверно, HTTP поддерживает любой тип данных.",
    ],
    moduleId: "browser",
    sectionTitle: "Введение в работу браузера",
    topic: "browser_intro",
  },
  {
    id: "browser_intro_22",
    title: "Какой HTTP-метод используется для отправки данных на сервер?",
    options: ["POST", "GET", "DELETE", "PUT"],
    correctAnswers: [0],
    descriptions: [
      "POST — правильный ответ, используется для отправки данных на сервер.",
      "GET — используется для получения данных.",
      "DELETE — используется для удаления данных.",
      "PUT — используется для изменения данных.",
    ],
    moduleId: "browser",
    sectionTitle: "Введение в работу браузера",
    topic: "browser_intro",
  },
  {
    id: "browser_intro_23",
    title: "Что означает статус-код 404 в ответе сервера?",
    options: [
      "Страница не найдена",
      "Сервер перегружен",
      "Запрос успешно выполнен",
      "Доступ запрещён",
    ],
    correctAnswers: [0],
    descriptions: [
      "Страница не найдена — правильный ответ.",
      "Сервер перегружен — это 503.",
      "Запрос успешно выполнен — это 200.",
      "Доступ запрещён — это 403.",
    ],
    moduleId: "browser",
    sectionTitle: "Введение в работу браузера",
    topic: "browser_intro",
  },
  {
    id: "browser_intro_24",
    title: "Какой заголовок HTTP отвечает за указание типа контента?",
    options: ["Content-Type", "Accept", "Authorization", "Cookie"],
    correctAnswers: [0],
    descriptions: [
      "Content-Type — правильный ответ, он указывает тип данных (JSON, HTML, XML и т.д.).",
      "Accept — сообщает серверу, какой тип данных ожидается в ответе.",
      "Authorization — используется для передачи токенов авторизации.",
      "Cookie — отправляет сохранённые cookies на сервер.",
    ],
    moduleId: "browser",
    sectionTitle: "Введение в работу браузера",
    topic: "browser_intro",
  },
  {
    id: "browser_intro_25",
    title: "Какой статус-код HTTP означает 'Успех'?",
    options: ["200", "404", "500", "403"],
    correctAnswers: [0],
    descriptions: [
      "200 — правильный ответ, он означает успешное выполнение запроса.",
      "404 — страница не найдена.",
      "500 — внутренняя ошибка сервера.",
      "403 — доступ запрещён.",
    ],
    moduleId: "browser",
    sectionTitle: "Введение в работу браузера",
    topic: "browser_intro",
  },
  {
    id: "browser_intro_26",
    title: "Для чего используется метод HTTP DELETE?",
    options: [
      "Для удаления ресурса на сервере",
      "Для обновления ресурса",
      "Для отправки данных на сервер",
      "Для шифрования данных",
    ],
    correctAnswers: [0],
    descriptions: [
      "Для удаления ресурса на сервере — правильный ответ.",
      "Для обновления ресурса — это метод PUT или PATCH.",
      "Для отправки данных на сервер — это метод POST.",
      "Для шифрования данных — это не задача HTTP.",
    ],
    moduleId: "browser",
    sectionTitle: "Введение в работу браузера",
    topic: "browser_intro",
  },
  {
    id: "browser_intro_27",
    title:
      "Какой метод HTTP-запроса лучше использовать для частичного обновления данных?",
    options: ["PATCH", "PUT", "POST", "GET"],
    correctAnswers: [0],
    descriptions: [
      "PATCH — правильный ответ, применяется для частичного обновления ресурса.",
      "PUT — используется для полного замещения ресурса.",
      "POST — создаёт новый ресурс, но не обновляет.",
      "GET — запрашивает данные, но не изменяет их.",
    ],
    moduleId: "browser",
    sectionTitle: "Введение в работу браузера",
    topic: "browser_intro",
  },
  {
    id: "browser_intro_28",
    title: "Какой статус-код указывает на 'Переадресацию'?",
    options: ["301", "200", "500", "403"],
    correctAnswers: [0],
    descriptions: [
      "301 — правильный ответ, это постоянная переадресация.",
      "200 — успешное выполнение запроса.",
      "500 — внутренняя ошибка сервера.",
      "403 — доступ запрещён.",
    ],
    moduleId: "browser",
    sectionTitle: "Введение в работу браузера",
    topic: "browser_intro",
  },
  {
    id: "browser_intro_29",
    title:
      "Как называется компонент браузера, отвечающий за отображение HTML и CSS на экране?",
    options: [
      "Rendering Engine",
      "Browser Engine",
      "JavaScript Engine",
      "Data Storage",
    ],
    correctAnswers: [0],
    descriptions: [
      "Rendering Engine — правильный ответ, это компонент, который преобразует HTML и CSS в визуальный интерфейс.",
      "Browser Engine — управляет взаимодействием между интерфейсом пользователя и рендерингом.",
      "JavaScript Engine — исполняет JavaScript-код.",
      "Data Storage — это локальное хранилище данных (localStorage, cookies).",
    ],
    moduleId: "browser",
    sectionTitle: "Введение в работу браузера",
    topic: "browser_intro",
  },
  {
    id: "browser_intro_30",
    title: "Какой движок рендеринга используется в браузере Google Chrome?",
    options: ["Blink", "WebKit", "Gecko", "Trident"],
    correctAnswers: [0],
    descriptions: [
      "Blink — правильный ответ, это движок рендеринга Google Chrome.",
      "WebKit — используется в Safari.",
      "Gecko — используется в Firefox.",
      "Trident — это старый движок, использовавшийся в Internet Explorer.",
    ],
    moduleId: "browser",
    sectionTitle: "Введение в работу браузера",
    topic: "browser_intro",
  },
  {
    id: "browser_intro_31",
    title: "Какой компонент браузера отвечает за выполнение JavaScript-кода?",
    options: [
      "JavaScript Engine",
      "Rendering Engine",
      "Browser Engine",
      "Networking",
    ],
    correctAnswers: [0],
    descriptions: [
      "JavaScript Engine — правильный ответ, это компонент, который исполняет JavaScript.",
      "Rendering Engine — рендерит HTML и CSS.",
      "Browser Engine — управляет взаимодействием между компонентами.",
      "Networking — отвечает за сетевые запросы.",
    ],
    moduleId: "browser",
    sectionTitle: "Введение в работу браузера",
    topic: "browser_intro",
  },
  {
    id: "browser_intro_32",
    title: "Какой компонент браузера отвечает за выполнение сетевых запросов?",
    options: [
      "Networking",
      "Rendering Engine",
      "Browser Engine",
      "JavaScript Engine",
    ],
    correctAnswers: [0],
    descriptions: [
      "Networking — правильный ответ, он отвечает за отправку и получение данных по сети.",
      "Rendering Engine — обрабатывает HTML и CSS.",
      "Browser Engine — управляет взаимодействием между интерфейсом пользователя и рендерингом.",
      "JavaScript Engine — исполняет JavaScript.",
    ],
    moduleId: "browser",
    sectionTitle: "Введение в работу браузера",
    topic: "browser_intro",
  },
  {
    id: "browser_intro_33",
    title:
      "Какой компонент браузера управляет взаимодействием между интерфейсом пользователя и рендерингом страницы?",
    options: [
      "Browser Engine",
      "Rendering Engine",
      "JavaScript Engine",
      "Data Storage",
    ],
    correctAnswers: [0],
    descriptions: [
      "Browser Engine — правильный ответ, он управляет взаимодействием между компонентами браузера.",
      "Rendering Engine — обрабатывает HTML и CSS.",
      "JavaScript Engine — отвечает за выполнение JS-кода.",
      "Data Storage — это локальное хранилище данных.",
    ],
    moduleId: "browser",
    sectionTitle: "Введение в работу браузера",
    topic: "browser_intro",
  },
  {
    id: "browser_intro_34",
    title: "Какой компонент браузера отвечает за локальное хранение данных?",
    options: [
      "Data Storage",
      "Networking",
      "Rendering Engine",
      "JavaScript Engine",
    ],
    correctAnswers: [0],
    descriptions: [
      "Data Storage — правильный ответ, отвечает за хранение данных в localStorage, cookies, IndexedDB.",
      "Networking — занимается сетевыми запросами.",
      "Rendering Engine — отображает HTML и CSS.",
      "JavaScript Engine — исполняет JavaScript.",
    ],
    moduleId: "browser",
    sectionTitle: "Введение в работу браузера",
    topic: "browser_intro",
  },
  {
    id: "browser_intro_35",
    title: "Какой движок JavaScript используется в Google Chrome?",
    options: ["V8", "SpiderMonkey", "JavaScriptCore", "WebKit"],
    correctAnswers: [0],
    descriptions: [
      "V8 — правильный ответ, это движок JavaScript, используемый в Chrome.",
      "SpiderMonkey — используется в Firefox.",
      "JavaScriptCore — используется в Safari.",
      "WebKit — это движок рендеринга, а не JavaScript.",
    ],
    moduleId: "browser",
    sectionTitle: "Введение в работу браузера",
    topic: "browser_intro",
  },
  {
    id: "browser_intro_36",
    title: "Для чего используется localStorage в браузере?",
    options: [
      "Хранение данных на стороне клиента в формате ключ-значение",
      "Сохранение кэша браузера",
      "Оптимизация загрузки изображений",
      "Хранение логов ошибок",
    ],
    correctAnswers: [0],
    descriptions: [
      "Хранение данных на стороне клиента в формате ключ-значение — правильный ответ.",
      "Сохранение кэша браузера — это задача Cache API.",
      "Оптимизация загрузки изображений — это задача frontend-оптимизации.",
      "Хранение логов ошибок — это не относится к localStorage.",
    ],
    moduleId: "browser",
    sectionTitle: "Введение в работу браузера",
    topic: "browser_intro",
  },
  {
    id: "browser_intro_37",
    title: "Что происходит в браузере на этапе парсинга HTML-документа?",
    options: [
      "Формируется DOM-дерево",
      "Загружаются стили",
      "Выполняется JavaScript",
      "Обновляется localStorage",
    ],
    correctAnswers: [0],
    descriptions: [
      "Формируется DOM-дерево — правильный ответ.",
      "Загружаются стили — это параллельный процесс, но не является парсингом.",
      "Выполняется JavaScript — это происходит, но не в момент парсинга HTML.",
      "Обновляется localStorage — это вообще не связано с парсингом.",
    ],
    moduleId: "browser",
    sectionTitle: "Введение в работу браузера",
    topic: "browser_intro",
  },
  {
    id: "browser_intro_38",
    title:
      "Какой компонент браузера отвечает за кэширование данных на клиенте?",
    options: [
      "Data Storage",
      "Rendering Engine",
      "Browser Engine",
      "Networking",
    ],
    correctAnswers: [0],
    descriptions: [
      "Data Storage — правильный ответ, он отвечает за localStorage, sessionStorage, cookies, IndexedDB.",
      "Rendering Engine — отображает HTML и CSS.",
      "Browser Engine — управляет взаимодействием компонентов.",
      "Networking — отвечает за сетевые запросы.",
    ],
    moduleId: "browser",
    sectionTitle: "Введение в работу браузера",
    topic: "browser_intro",
  },
  {
    id: "browser_intro_39",
    title: "Какой движок рендеринга используется в браузере Google Chrome?",
    options: ["Blink", "Gecko", "WebKit", "Trident"],
    correctAnswers: [0],
    descriptions: [
      "Blink — правильный ответ, это движок рендеринга в Chrome.",
      "Gecko — используется в Firefox.",
      "WebKit — используется в Safari.",
      "Trident — устаревший движок, использовавшийся в Internet Explorer.",
    ],
    moduleId: "browser",
    sectionTitle: "Введение в работу браузера",
    topic: "browser_intro",
  },
  {
    id: "browser_intro_40",
    title: "Какой движок рендеринга используется в браузере Mozilla Firefox?",
    options: ["Gecko", "Blink", "WebKit", "EdgeHTML"],
    correctAnswers: [0],
    descriptions: [
      "Gecko — правильный ответ, это движок Firefox.",
      "Blink — используется в Chrome, Edge, Opera.",
      "WebKit — используется в Safari.",
      "EdgeHTML — это старый движок Microsoft Edge, сейчас он на Blink.",
    ],
    moduleId: "browser",
    sectionTitle: "Введение в работу браузера",
    topic: "browser_intro",
  },
  {
    id: "browser_intro_41",
    title: "Какой браузер использует движок WebKit?",
    options: ["Safari", "Firefox", "Chrome", "Edge"],
    correctAnswers: [0],
    descriptions: [
      "Safari — правильный ответ, WebKit является его основным движком.",
      "Firefox — использует Gecko.",
      "Chrome — использует Blink.",
      "Edge — использует Blink.",
    ],
    moduleId: "browser",
    sectionTitle: "Введение в работу браузера",
    topic: "browser_intro",
  },
  {
    id: "browser_intro_42",
    title: "Какой движок JavaScript используется в браузере Safari?",
    options: ["JavaScriptCore", "V8", "SpiderMonkey", "Chakra"],
    correctAnswers: [0],
    descriptions: [
      "JavaScriptCore — правильный ответ, используется в Safari.",
      "V8 — используется в Chrome и Edge.",
      "SpiderMonkey — используется в Firefox.",
      "Chakra — использовался в старом Microsoft Edge.",
    ],
    moduleId: "browser",
    sectionTitle: "Введение в работу браузера",
    topic: "browser_intro",
  },
  {
    id: "browser_intro_43",
    title: "Какой движок JavaScript используется в браузере Google Chrome?",
    options: ["V8", "JavaScriptCore", "SpiderMonkey", "Chakra"],
    correctAnswers: [0],
    descriptions: [
      "V8 — правильный ответ, это движок JavaScript для Chrome.",
      "JavaScriptCore — используется в Safari.",
      "SpiderMonkey — используется в Firefox.",
      "Chakra — использовался в старом Microsoft Edge.",
    ],
    moduleId: "browser",
    sectionTitle: "Введение в работу браузера",
    topic: "browser_intro",
  },
  {
    id: "browser_intro_44",
    title: "Какой движок рендеринга использует Яндекс.Браузер?",
    options: ["Blink", "Gecko", "WebKit", "Presto"],
    correctAnswers: [0],
    descriptions: [
      "Blink — правильный ответ, Яндекс.Браузер использует этот движок.",
      "Gecko — используется в Firefox.",
      "WebKit — используется в Safari.",
      "Presto — устаревший движок, ранее использовался в старом Opera.",
    ],
    moduleId: "browser",
    sectionTitle: "Введение в работу браузера",
    topic: "browser_intro",
  },
  {
    id: "browser_intro_45",
    title: "Какой браузер перешёл с движка EdgeHTML на Blink в 2020 году?",
    options: ["Microsoft Edge", "Opera", "Safari", "Firefox"],
    correctAnswers: [0],
    descriptions: [
      "Microsoft Edge — правильный ответ, в 2020 году он перешёл на движок Blink.",
      "Opera всегда использовала Blink после отказа от Presto.",
      "Safari остаётся на WebKit.",
      "Firefox остаётся на Gecko.",
    ],
    moduleId: "browser",
    sectionTitle: "Введение в работу браузера",
    topic: "browser_intro",
  },
  {
    id: "browser_intro_46",
    title: "Какие браузеры используют движок Blink?",
    options: [
      "Chrome, Edge, Opera, Яндекс.Браузер",
      "Firefox, Safari, Opera",
      "Safari, Edge, Brave",
      "Firefox, Chrome, Edge",
    ],
    correctAnswers: [0],
    descriptions: [
      "Chrome, Edge, Opera, Яндекс.Браузер — правильный ответ, все они используют Blink.",
      "Firefox использует Gecko, Safari — WebKit.",
      "Safari остаётся на WebKit, Brave — на Blink.",
      "Firefox использует Gecko, Chrome и Edge — Blink.",
    ],
    moduleId: "browser",
    sectionTitle: "Введение в работу браузера",
    topic: "browser_intro",
  },
  {
    id: "browser_intro_47",
    title:
      "Какой движок использовался в старых версиях браузера Opera до перехода на Blink?",
    options: ["Presto", "WebKit", "Trident", "EdgeHTML"],
    correctAnswers: [0],
    descriptions: [
      "Presto — правильный ответ, это был старый движок Opera.",
      "WebKit — используется в Safari.",
      "Trident — использовался в Internet Explorer.",
      "EdgeHTML — использовался в старых версиях Edge.",
    ],
    moduleId: "browser",
    sectionTitle: "Введение в работу браузера",
    topic: "browser_intro",
  },
  {
    id: "browser_intro_48",
    title: "Какой браузер является основным на iOS и использует движок WebKit?",
    options: ["Safari", "Chrome", "Firefox", "Edge"],
    correctAnswers: [0],
    descriptions: [
      "Safari — правильный ответ, он основной на iOS и использует WebKit.",
      "Chrome на iOS также использует WebKit, но это требование Apple.",
      "Firefox на iOS также вынужден использовать WebKit.",
      "Edge на iOS также использует WebKit из-за ограничений Apple.",
    ],
    moduleId: "browser",
    sectionTitle: "Введение в работу браузера",
    topic: "browser_intro",
  },
];
