import { jsSections } from "./jsSections";

export const jsChapters = [
  {
    id: "js_start",
    title: "Знакомство с JavaScript",
    sections: jsSections.js_start,
    testKeys: ["js_start_test"],
    practiceIds: ["js_start_task_1", "js_start_task_2", "js_start_task_3"],
  },
  {
    id: "js_variablesAndTypes",
    title: "Переменные и типы данных",
    sections: jsSections.js_variablesAndTypes,
    testKeys: ["js_variablesAndTypes_test"],
    practiceIds: [],
  },
  {
    id: "js_operatorsAndExpressions",
    title: "Операторы и выражения",
    sections: jsSections.js_operatorsAndExpressions,
    testKeys: ["js_operatorsAndExpressions_test"],
    practiceIds: [],
  },
  {
    id: "js_conditionsAndBranches",
    title: "Условия и ветвления",
    sections: jsSections.js_conditionsAndBranches,
    testKeys: ["js_conditionsAndBranches_test"],
    practiceIds: [],
  },
  {
    id: "js_cycles",
    title: "Циклы",
    sections: jsSections.js_cycles,
    testKeys: ["js_cycles_test"],
    practiceIds: [],
  },
  {
    id: "js_functions",
    title: "Функции",
    sections: jsSections.js_functions,
    testKeys: ["js_functions_test"],
    practiceIds: [],
  },
  {
    id: "js_objects",
    title: "Обьекты",
    sections: jsSections.js_objects,
    testKeys: ["js_objects_test"],
    practiceIds: [],
  },
  {
    id: "js_arrays",
    title: "Массивы",
    sections: jsSections.js_arrays,
    testKeys: ["js_arrays_test"],
    practiceIds: [],
  },
  {
    id: "js_error",
    title: "Введение в отладку и ошибки",
    sections: jsSections.js_error,
    testKeys: ["js_errors_test"],
    practiceIds: [],
  },
  {
    id: "js_json",
    title: "Работа с JSON",
    sections: jsSections.js_json,
    testKeys: ["js_json_test"],
    practiceIds: [],
  },
  {
    id: "js_localStorage",
    title: "localStorage и sessionStorage",
    sections: jsSections.js_localStorage,
    testKeys: ["js_localStorage_test"],
    practiceIds: [],
  },
  {
    id: "js_data",
    title: "Работа с датами",
    sections: jsSections.js_data,
    testKeys: ["js_date_test"],
    practiceIds: [],
  },
  {
    id: "js_async",
    title: "Асинхронный код",
    sections: jsSections.js_async,
    testKeys: ["js_async_test"],
    practiceIds: [],
  },
  {
    id: "js_errorHandling",
    title: "Обработка ошибок (расширенно)",
    sections: jsSections.js_errorHandling,
    testKeys: ["js_errorHandling_test"],
    practiceIds: [],
  },
  {
    id: "js_API",
    title: "Работа с API",
    sections: jsSections.js_API,
    testKeys: ["js_api_test"],
    practiceIds: [],
  },
  {
    id: "js_DOM",
    title: "Работа с DOM",
    sections: jsSections.js_DOM,
    testKeys: ["js_dom_test"],
    practiceIds: [],
  },
  {
    id: "js_import",
    title: "Модули JavaScript (расширенно)",
    sections: jsSections.js_import,
    testKeys: ["js_import_test"],
    practiceIds: [],
  },
  {
    id: "js_this",
    title: "Контекст выполнения и this",
    sections: jsSections.js_this,
    testKeys: ["js_this_test"],
    practiceIds: [],
  },
  {
    id: "js_OOP",
    title: "Основы объектно-ориентированного программирования (ООП)",
    sections: jsSections.js_OOP,
    testKeys: ["js_OOP_test"],
    practiceIds: [],
  },
  {
    id: "js_map_set",
    title: "Коллекции Set и Map",
    sections: jsSections.js_map_set,
    testKeys: ["js_map_set_test"],
    practiceIds: [],
  },
  {
    id: "js_bestPractices",
    title: "Безопасность и best practices",
    sections: jsSections.js_bestPractices,
    testKeys: ["js_bestPractices_test"],
    practiceIds: [],
  },
];
