export const cssAnimationsQuestions = [
  {
    id: "css_animations_1",
    title:
      "Какое свойство определяет, какие CSS-свойства будут анимироваться при переходе?",
    options: [
      "transition-property",
      "transition-duration",
      "transition-timing-function",
      "transition-delay",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: transition-property задаёт, какие свойства будут меняться.",
      "transition-duration определяет длительность, а не сами свойства.",
      "transition-timing-function управляет функцией ускорения, а не выбором свойств.",
      "transition-delay задаёт задержку начала, а не выбор свойств.",
    ],
    moduleId: "css",
    sectionTitle: "Анимации и переходы",
    topic: "css_animations",
  },
  {
    id: "css_animations_2",
    title: "Какое свойство задаёт длительность анимации перехода?",
    options: [
      "transition-duration",
      "transition-delay",
      "transition-property",
      "transition-timing-function",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: transition-duration определяет длительность эффекта.",
      "transition-delay задаёт задержку перед началом анимации.",
      "transition-property определяет, какие свойства анимировать.",
      "transition-timing-function задаёт кривую ускорения, а не длительность.",
    ],
    moduleId: "css",
    sectionTitle: "Анимации и переходы",
    topic: "css_animations",
  },
  {
    id: "css_animations_3",
    title: "Какой синтаксис задаст задержку начала перехода в 0.5 секунды?",
    options: [
      "transition-delay: 0.5s;",
      "transition-duration: 0.5s;",
      "transition-timing-function: 0.5s;",
      "transition-property: 0.5s;",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: transition-delay добавляет паузу перед началом анимации.",
      "transition-duration задаёт общую длительность, а не задержку.",
      "transition-timing-function задаёт кривую, а не задержку.",
      "transition-property указывает, какие свойства анимировать, а не время.",
    ],
    moduleId: "css",
    sectionTitle: "Анимации и переходы",
    topic: "css_animations",
  },
  {
    id: "css_animations_4",
    title: "Какой параметр определяет кривую ускорения для перехода?",
    options: [
      "transition-timing-function",
      "transition-duration",
      "transition-delay",
      "transition-property",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: transition-timing-function задаёт easing (кривую ускорения).",
      "transition-duration определяет длительность, а не кривую.",
      "transition-delay задаёт отложенный старт, а не кривую.",
      "transition-property указывает свойства, а не кривую ускорения.",
    ],
    moduleId: "css",
    sectionTitle: "Анимации и переходы",
    topic: "css_animations",
  },
  {
    id: "css_animations_5",
    title:
      "Какой из вариантов правильно задаёт все параметры перехода в одной строке?",
    options: [
      "transition: opacity 0.3s ease-in 0.1s;",
      "transition: 0.3s opacity ease-in 0.1s;",
      "transition: ease-in 0.3s opacity 0.1s;",
      "transition: 0.1s ease-in 0.3s opacity;",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: порядок shorthand — property duration timing-function delay.",
      "Неверный порядок: нужно сначала property, затем duration.",
      "Неверный порядок аргументов.",
      "Неверный порядок аргументов.",
    ],
    moduleId: "css",
    sectionTitle: "Анимации и переходы",
    topic: "css_animations",
  },
  {
    id: "css_animations_6",
    title:
      "Как установить плавный переход при наведении на элемент для свойства background-color?",
    options: [
      ".box { transition: background-color 0.2s ease; } .box:hover { background-color: red; }",
      ".box { background-color: red; } .box:hover { transition: background-color 0.2s ease; }",
      ".box:hover { transition: background-color 0.2s ease; } .box { background-color: red; }",
      ".box { transition-property: all; } .box:hover { background-color: red; }",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: задаём transition на изначальном состоянии, а в :hover меняем background-color.",
      "Нужно указать transition на исходном селекторе, а не в :hover.",
      "Transition в :hover не работает до наведения.",
      "transition-property: all анимирует все свойства, но недостаточно задать duration.",
    ],
    moduleId: "css",
    sectionTitle: "Анимации и переходы",
    topic: "css_animations",
  },
  {
    id: "css_animations_7",
    title:
      "Какое значение transition-timing-function задаёт линейную анимацию без ускорений?",
    options: ["linear", "ease-in", "ease-out", "ease-in-out"],
    correctAnswers: [0],
    descriptions: [
      "Правильно: linear обеспечивает равномерную скорость анимации.",
      "ease-in ускоряется в начале.",
      "ease-out замедляется в конце.",
      "ease-in-out замедляется и ускоряется.",
    ],
    moduleId: "css",
    sectionTitle: "Анимации и переходы",
    topic: "css_animations",
  },
  {
    id: "css_animations_8",
    title:
      "Какой вариант timing-function замедляется в начале и в конце (двусторонний easing)?",
    options: ["ease-in-out", "linear", "ease-in", "step-start"],
    correctAnswers: [0],
    descriptions: [
      "Правильно: ease-in-out замедляется сначала и в конце.",
      "linear — без ускорений.",
      "ease-in — ускоряется в начале.",
      "step-start — ступенчатая функция, а не плавная.",
    ],
    moduleId: "css",
    sectionTitle: "Анимации и переходы",
    topic: "css_animations",
  },
  {
    id: "css_animations_9",
    title:
      "Как установить несколько переходов для разных свойств одновременно?",
    options: [
      "transition: width 0.3s, height 0.3s;",
      "transition: 0.3s width height;",
      "transition: width height 0.3s;",
      "transition-multiple: width 0.3s, height 0.3s;",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: перечисляем каждый переход через запятую.",
      "Неверный синтаксис: duration нужно после каждого property.",
      "Нужно перечислять через запятую.",
      "transition-multiple не является валидным.",
    ],
    moduleId: "css",
    sectionTitle: "Анимации и переходы",
    topic: "css_animations",
  },
  {
    id: "css_animations_10",
    title: "Что будет, если указать transition-property: all?",
    options: [
      "Все изменяемые свойства будут анимироваться",
      "Никакие свойства не анимируются",
      "Будет анимироваться только цвет текста",
      "Анимируется только background-color",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: all означает все свойства, поддерживающие анимацию.",
      "Настройка all анимирует максимальное число свойств, а не отключает.",
      "only text-color — неверно; анимируются все.",
      "Не только background-color, а все свойства.",
    ],
    moduleId: "css",
    sectionTitle: "Анимации и переходы",
    topic: "css_animations",
  },
  {
    id: "css_animations_11",
    title:
      "Какой параметр transition задаёт время, через которое начнётся анимация после вызова?",
    options: [
      "transition-delay",
      "transition-duration",
      "transition-property",
      "transition-timing-function",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: delay задаёт задержку перед началом анимации.",
      "duration задаёт длительность, а не задержку.",
      "property указывает, что анимировать, а не время.",
      "timing-function задаёт кривую ускорения.",
    ],
    moduleId: "css",
    sectionTitle: "Анимации и переходы",
    topic: "css_animations",
  },
  {
    id: "css_animations_12",
    title:
      "Какой синтаксис задаёт только два параметра: длительность 0.4s и свойство opacity?",
    options: [
      "transition: opacity 0.4s;",
      "transition: 0.4s;",
      "transition-duration: 0.4s opacity;",
      "transition-property: 0.4s;",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: shorthand transition: property duration.",
      "Нужно указать свойство, иначе будет default all.",
      "Неверный синтаксис: нужно разделять опции.",
      "Неверный синтаксис: property должно содержать название свойства, а не время.",
    ],
    moduleId: "css",
    sectionTitle: "Анимации и переходы",
    topic: "css_animations",
  },
  {
    id: "css_animations_13",
    title:
      "Что будет, если не указать transition-duration в shorthand transition?",
    options: [
      "По умолчанию длительность = 0s (никакой анимации)",
      "По умолчанию длительность = 1s",
      "Будет использовано значение из transition-delay",
      "Анимация будет бесконечной",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: если duration не указан, анимация не будет, duration = 0s.",
      "По умолчанию не 1s, а 0s.",
      "transition-delay не заменяет duration.",
      "Нет бесконечной анимации без явного keyframes.",
    ],
    moduleId: "css",
    sectionTitle: "Анимации и переходы",
    topic: "css_animations",
  },
  {
    id: "css_animations_14",
    title:
      "Какой способ задаёт мгновенное прекращение анимации (без плавного перехода) для свойства color?",
    options: [
      "transition: color 0s;",
      "transition: color 1s;",
      "transition: none;",
      "transition: all 0s;",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: duration 0s означает отсутствие плавности для color.",
      "1s — задаёт плавную смену в течение секунды, а не мгновенный.",
      "transition:none отменяет все переходы, но вопрос про только color.",
      "all 0s отменит все, но корректнее указать конкретно property 0s.",
    ],
    moduleId: "css",
    sectionTitle: "Анимации и переходы",
    topic: "css_animations",
  },
  {
    id: "css_animations_15",
    title: "Как отменить все переходы для элемента?",
    options: [
      "transition: none;",
      "transition: all 0s ease;",
      "transition: off;",
      "transition: stop;",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: transition:none отключает все переходы.",
      "all 0s ease тоже приводит к мгновенным сменам, но shorthand none более наглядно.",
      "off не является валидным значением.",
      "stop не является валидным значением.",
    ],
    moduleId: "css",
    sectionTitle: "Анимации и переходы",
    topic: "css_animations",
  },
  {
    id: "css_animations_16",
    title: "Как задать плавное изменение ширины и высоты одновременно?",
    options: [
      "transition: width 0.5s, height 0.5s;",
      "transition: size 0.5s;",
      "transition: both 0.5s;",
      "transition: width height 0.5s;",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: перечисляем каждый свойство отдельно через запятую.",
      "size не является валидным свойством.",
      "both не является допустимым значением для transition-property.",
      "Неверный синтаксис: нужно использовать запятую.",
    ],
    moduleId: "css",
    sectionTitle: "Анимации и переходы",
    topic: "css_animations",
  },
  {
    id: "css_animations_17",
    title: "Что будет, если указать transition: all 0.3s ease 0.2s;",
    options: [
      "Все свойства при изменении будут анимироваться 0.3s с задержкой 0.2s и функцией ease",
      "Никакие свойства не анимируются",
      "Будет анимироваться только первый указанной элемент",
      "Будет работать только после второй смены стиля",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: all означает все свойства, duration 0.3s, timing-function ease и delay 0.2s.",
      "Анимация будет работать для любого изменяющегося свойства.",
      "Нет понятия «первый элемент»; all охватывает все.",
      "Анимация начнётся после задержки сразу при первом изменении.",
    ],
    moduleId: "css",
    sectionTitle: "Анимации и переходы",
    topic: "css_animations",
  },
  {
    id: "css_animations_18",
    title: "Какое свойство невозможно анимировать с помощью transition?",
    options: ["display", "opacity", "transform", "background-color"],
    correctAnswers: [0],
    descriptions: [
      "Правильно: display не анимируется, изменение будет мгновенным.",
      "opacity можно плавно анимировать.",
      "transform поддерживается и отлично анимируется.",
      "background-color можно плавно анимировать.",
    ],
    moduleId: "css",
    sectionTitle: "Анимации и переходы",
    topic: "css_animations",
  },
  {
    id: "css_animations_19",
    title: "Как применить переход к псевдоэлементу ::before?",
    options: [
      ".element::before { transition: opacity 0.3s; } .element:hover::before { opacity: 1; }",
      ".element:hover::before { transition: opacity 0.3s; }",
      ".element { transition: ::before opacity 0.3s; }",
      ".element::before:hover { transition: opacity 0.3s; }",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: transition задаётся в селекторе псевдоэлемента, а изменение — в hover.",
      "Нужно задать transition вне состояния hover.",
      "transition: ::before ... — неверный синтаксис.",
      "::before:hover не сработает, потому что псевдоэлемент не независимый элемент.",
    ],
    moduleId: "css",
    sectionTitle: "Анимации и переходы",
    topic: "css_animations",
  },
  {
    id: "css_animations_20",
    title:
      "Как задать плавный переход при изменении transform: scale() элемента?",
    options: [
      ".box { transition: transform 0.4s ease; } .box:hover { transform: scale(1.2); }",
      ".box { transition: scale 0.4s ease; }",
      ".box:hover { transition: transform 0.4s ease; }",
      ".box { transition: all 0s; }",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: указываем transition:transform, а затем изменяем transform в hover.",
      "scale не является отдельным свойством, нужно transform.",
      "transition внутри hover не срабатывает заранее.",
      "transition:all 0s — отключает любой переход.",
    ],
    moduleId: "css",
    sectionTitle: "Анимации и переходы",
    topic: "css_animations",
  },
  {
    id: "css_animations_21",
    title:
      "Какой синтаксис использования функции translate для сдвига элемента на 50px вправо и 20px вниз?",
    options: [
      "transform: translate(50px, 20px);",
      "transform: translateX(20px) translateY(50px);",
      "transform: translateY(50px, 20px);",
      "transform: move(50px, 20px);",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: translate(X, Y) сдвигает на X по горизонтали и на Y по вертикали.",
      "Неверный порядок: translateX принимает только один аргумент (50px по горизонтали), а translateY (20px по вертикали).",
      "Неверный порядок аргументов в translateY.",
      "move не является функцией CSS.",
    ],
    moduleId: "css",
    sectionTitle: "Анимации и переходы",
    topic: "css_animations",
  },
  {
    id: "css_animations_22",
    title: "Как задать масштабирование элемента в два раза по обеим осям?",
    options: [
      "transform: scale(2);",
      "transform: scaleX(2);",
      "transform: scaleY(0.5);",
      "transform: zoom(2);",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: scale(2) увеличит элемент в два раза и по X, и по Y.",
      "scaleX(2) увеличит только по горизонтали.",
      "scaleY(0.5) уменьшит только по вертикали в 2 раза.",
      "zoom не является стандартной функцией CSS.",
    ],
    moduleId: "css",
    sectionTitle: "Анимации и переходы",
    topic: "css_animations",
  },
  {
    id: "css_animations_23",
    title: "Как повернуть элемент на 45 градусов по часовой стрелке?",
    options: [
      "transform: rotate(45deg);",
      "transform: rotateX(45deg);",
      "transform: spin(45deg);",
      "transform: skew(45deg);",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: rotate(45deg) повёрнёт элемент на 45° в плоскости Z.",
      "rotateX выполняет 3D-поворот вокруг оси X.",
      "spin не является функцией CSS.",
      "skew деформирует (наклоняет), а не поворачивает.",
    ],
    moduleId: "css",
    sectionTitle: "Анимации и переходы",
    topic: "css_animations",
  },
  {
    id: "css_animations_24",
    title: "Как наклонить элемент по оси X на 30 градусов?",
    options: [
      "transform: skewX(30deg);",
      "transform: skewY(30deg);",
      "transform: inclineX(30deg);",
      "transform: rotateX(30deg);",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: skewX(30deg) наклоняет элемент по горизонтали.",
      "skewY(30deg) наклоняет по вертикали.",
      "inclineX не является функцией CSS.",
      "rotateX выполняет вращение в 3D, а не наклон.",
    ],
    moduleId: "css",
    sectionTitle: "Анимации и переходы",
    topic: "css_animations",
  },
  {
    id: "css_animations_25",
    title: "Как задать точку опоры (transform-origin) в центре элемента?",
    options: [
      "transform-origin: center center;",
      "transform-origin: 0 0;",
      "transform-origin: left top;",
      "transform-origin: 100% 100%;",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: center center размещает точку опоры по середине по обеим осям.",
      "0 0 соответствует левому верхнему углу, а не центру.",
      "left top тоже левый верхний угол.",
      "100% 100% соответствует правому нижнему углу.",
    ],
    moduleId: "css",
    sectionTitle: "Анимации и переходы",
    topic: "css_animations",
  },
  {
    id: "css_animations_26",
    title: "Как сдвинуть элемент на 100px вправо без изменения по вертикали?",
    options: [
      "transform: translateX(100px);",
      "transform: translate(100px, 0);",
      "transform: translateY(100px);",
      "transition: translateX(100px);",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: translateX сдвигает только по горизонтали.",
      "translate(100px, 0) тоже верно, но первый вариант более точен для одного аргумента.",
      "translateY перемещает только по вертикали.",
      "transition — не функция трансформации.",
    ],
    moduleId: "css",
    sectionTitle: "Анимации и переходы",
    topic: "css_animations",
  },
  {
    id: "css_animations_27",
    title: "Как уменьшить элемент вдвое по оси Y?",
    options: [
      "transform: scaleY(0.5);",
      "transform: scale(0.5);",
      "transform: scaleX(0.5);",
      "transform: shrinkY(0.5);",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: scaleY(0.5) уменьшит высоту в 2 раза, не касаясь ширины.",
      "scale(0.5) уменьшит и ширину, и высоту.",
      "scaleX(0.5) влияет только на ширину.",
      "shrinkY не является функцией CSS.",
    ],
    moduleId: "css",
    sectionTitle: "Анимации и переходы",
    topic: "css_animations",
  },
  {
    id: "css_animations_28",
    title: "Как повернуть элемент вокруг оси Z на 180 градусов?",
    options: [
      "transform: rotateZ(180deg);",
      "transform: rotate(180deg);",
      "transform: spinZ(180deg);",
      "transform: rotateY(180deg);",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: rotateZ(180deg) поворачивает в плоскости экрана (ось Z).",
      "rotate(180deg) эквивалентно rotateZ(180deg), но первый вариант точнее задаёт ось.",
      "spinZ не является функцией CSS.",
      "rotateY выполняет 3D-поворот вокруг оси Y.",
    ],
    moduleId: "css",
    sectionTitle: "Анимации и переходы",
    topic: "css_animations",
  },
  {
    id: "css_animations_29",
    title:
      "Как объединить несколько трансформаций (сдвиг и масштаб) в одном свойстве?",
    options: [
      "transform: translate(20px, 10px) scale(1.5);",
      "transform: translate(20px, 10px), scale(1.5);",
      "transform: (translate(20px, 10px) scale(1.5));",
      "transform: both translate scale;",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: несколько функций перечисляются через пробел без запятых.",
      "Запятая разделяет несколько transform деклараций, а не функции в одной.",
      "Неправильный синтаксис: не нужны скобки вокруг всего выражения.",
      "Неверный синтаксис, отсутствуют конкретные значения.",
    ],
    moduleId: "css",
    sectionTitle: "Анимации и переходы",
    topic: "css_animations",
  },
  {
    id: "css_animations_30",
    title: "Как задать базовое значение transform для элемента без изменений?",
    options: [
      "transform: none;",
      "transform: zero;",
      "transform: identity;",
      "transform: 0;",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: none сбрасывает любые трансформации.",
      "zero не является валидным значением.",
      "identity не поддерживается в CSS.",
      "0 не является корректным значением для transform.",
    ],
    moduleId: "css",
    sectionTitle: "Анимации и переходы",
    topic: "css_animations",
  },
  {
    id: "css_animations_31",
    title: "Как задать 3D-поворот вокруг оси Y на 60 градусов?",
    options: [
      "transform: rotateY(60deg);",
      "transform: rotate(60deg);",
      "transform: rotateX(60deg);",
      "transform: skewY(60deg);",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: rotateY(60deg) выполняет 3D-поворот вокруг вертикальной оси.",
      "rotate(60deg) — 2D-поворот вокруг оси Z.",
      "rotateX поворачивает вокруг горизонтальной оси.",
      "skewY — наклон, а не поворот.",
    ],
    moduleId: "css",
    sectionTitle: "Анимации и переходы",
    topic: "css_animations",
  },
  {
    id: "css_animations_32",
    title:
      "Как установить точку опоры при 3D-трансформации в левом верхнем углу?",
    options: [
      "transform-origin: top left;",
      "transform-origin: 0 100%;",
      "transform-origin: center center;",
      "transform-origin: 100% 0;",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: top left соответствует координатам (0%, 0%).",
      "0 100% означает нижний левый угол.",
      "center center — центр элемента, а не левый верхний.",
      "100% 0 соответствует правому верхнему углу.",
    ],
    moduleId: "css",
    sectionTitle: "Анимации и переходы",
    topic: "css_animations",
  },
  {
    id: "css_animations_33",
    title:
      "Как задать комбинированный 3D-трансформ: сдвиг и вращение вокруг оси X?",
    options: [
      "transform: translateZ(50px) rotateX(30deg);",
      "transform: translateZ(50px), rotateX(30deg);",
      "transform3d: translateZ(50px) rotateX(30deg);",
      "transform: move3d(50px) spinX(30deg);",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: translateZ(50px) сдвигает по оси Z, а rotateX(30deg) поворачивает вокруг оси X.",
      "Запятая не нужна между функциями.",
      "transform3d не существует, используется просто transform.",
      "move3d и spinX не являются функциями CSS.",
    ],
    moduleId: "css",
    sectionTitle: "Анимации и переходы",
    topic: "css_animations",
  },
  {
    id: "css_animations_34",
    title: "Как задать наклон элемента одновременно по осям X и Y?",
    options: [
      "transform: skew(20deg, 10deg);",
      "transform: skewX(20deg) skewY(10deg);",
      "transform: skewXY(20deg, 10deg);",
      "transform: tilt(20deg, 10deg);",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: skew(X, Y) задаёт наклон по горизонтали и вертикали одновременно.",
      "Тоже корректно, но первый вариант использует одну функцию для обеих осей.",
      "skewXY не является функцией в CSS.",
      "tilt не поддерживается в CSS.",
    ],
    moduleId: "css",
    sectionTitle: "Анимации и переходы",
    topic: "css_animations",
  },
  {
    id: "css_animations_35",
    title:
      "Как изменить порядок трансформаций, если нужно сначала вращение, а затем перенос?",
    options: [
      "transform: rotate(45deg) translateX(30px);",
      "transform: translateX(30px) rotate(45deg);",
      "transform: translate(45deg, 30px);",
      "transform: rotate-then-translate(45deg, 30px);",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: порядок функций определяет последовательность: сначала rotate, потом translate.",
      "Неверный порядок: это перенос, затем вращение.",
      "translate принимает два значения смещения, а не функций.",
      "rotate-then-translate не является валидным.",
    ],
    moduleId: "css",
    sectionTitle: "Анимации и переходы",
    topic: "css_animations",
  },
  {
    id: "css_animations_36",
    title: "Как сбросить все 3D-трансформации у элемента?",
    options: [
      "transform: none;",
      "transform: reset3d;",
      "transform: clear;",
      "transform: 0 0 0;",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: none сбрасывает все трансформации, включая 3D.",
      "reset3d не поддерживается.",
      "clear не является значением transform.",
      "0 0 0 не является валидным значением.",
    ],
    moduleId: "css",
    sectionTitle: "Анимации и переходы",
    topic: "css_animations",
  },
  {
    id: "css_animations_37",
    title:
      "Как установить перспективу (perspective) для дочерних 3D-трансформаций?",
    options: [
      "perspective: 800px;",
      "transform-perspective: 800px;",
      "perspective3d: 800px;",
      "transform: perspective(800px);",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: свойство perspective применяется к родителю, создавая эффект перспективы для потомков.",
      "transform-perspective не поддерживается.",
      "perspective3d не является корректным.",
      "perspective() — функция transform, но чтобы установить перспективу, нужно свойство perspective.",
    ],
    moduleId: "css",
    sectionTitle: "Анимации и переходы",
    topic: "css_animations",
  },
  {
    id: "css_animations_38",
    title: "Как задать перспективу непосредственно через transform?",
    options: [
      "transform: perspective(800px);",
      "transform: set-perspective(800px);",
      "transform: perspective3d(800px);",
      "perspective: transform(800px);",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: perspective(800px) можно задать в функции transform, хотя рекомендуется использовать свойство perspective.",
      "set-perspective не существует.",
      "perspective3d не является функцией CSS.",
      "Неверный синтаксис для perspective.",
    ],
    moduleId: "css",
    sectionTitle: "Анимации и переходы",
    topic: "css_animations",
  },
  {
    id: "css_animations_39",
    title:
      "Как повернуть элемент вокруг оси X и при этом установить origin в нижней части?",
    options: [
      "transform-origin: bottom center; transform: rotateX(60deg);",
      "transform-origin: center bottom; transform: rotateX(60deg);",
      "transform-origin: bottom left; transform: rotateX(60deg);",
      "transform-origin: center top; transform: rotateX(60deg);",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: bottom center — точка опоры в нижней центральной точке, затем поворот вокруг X.",
      "center bottom эквивалентно bottom center, но порядок записи обычно bottom center.",
      "bottom left смещает точку опоры в левый нижний угол, а не в центр.",
      "center top устанавливает точку в верхней части.",
    ],
    moduleId: "css",
    sectionTitle: "Анимации и переходы",
    topic: "css_animations",
  },
  {
    id: "css_animations_40",
    title:
      "Как задать 2D-трансформацию сдвига, масштабирования и вращения одновременно?",
    options: [
      "transform: translate(10px, 20px) scale(1.2) rotate(15deg);",
      "transform: rotate(15deg) translate(10px, 20px) scale(1.2);",
      "transform: scale(1.2) rotate(15deg) translate(10px, 20px);",
      "Все варианты верны",
    ],
    correctAnswers: [3],
    descriptions: [
      "Все варианты корректны, так как порядок функций влияет на итоговый результат, но каждая запись является валидным выражением CSS.",
      "Неверно: не только первый вариант валиден.",
      "Неверно: не только второй вариант валиден.",
      "Неверно: не только третий вариант валиден.",
    ],
    moduleId: "css",
    sectionTitle: "Анимации и переходы",
    topic: "css_animations",
  },
];
