export const cssBoxModelQuestions = [
  {
    id: "css_box_model_1",
    title: "Что входит в состав CSS Box Model?",
    options: [
      "Только контент и отступы",
      "Контент, padding, border, margin",
      "Content и Grid",
      "Padding и Flex",
    ],
    correctAnswers: [1],
    descriptions: [
      "Неполный ответ: в модель входят ещё границы и margin.",
      "Правильно: контент (content), внутренние отступы (padding), границы (border) и внешние отступы (margin).",
      "Grid — это часть layout, не Box Model.",
      "Flex — это метод компоновки, не элемент модели.",
    ],
    moduleId: "css",
    sectionTitle: "Блочная модель и позиционирование элементов",
    topic: "css_box_model",
  },
  {
    id: "css_box_model_2",
    title: "Какой код задаёт внутренний отступ слева в 20px?",
    options: [
      "margin-left: 20px;",
      "padding-left: 20px;",
      "border-left: 20px;",
      "content-left: 20px;",
    ],
    correctAnswers: [1],
    descriptions: [
      "margin-left — это внешний отступ.",
      "Правильно: padding-left задаёт внутренний отступ слева.",
      "border-left задаёт ширину границы, а не отступ.",
      "content-left не является свойством.",
    ],
    moduleId: "css",
    sectionTitle: "Блочная модель и позиционирование элементов",
    topic: "css_box_model",
  },
  {
    id: "css_box_model_3",
    title: "Что делает свойство box-sizing: border-box;?",
    options: [
      "Включает padding и border в вычисление width и height",
      "Отключает margin для элемента",
      "Устанавливает границу вокруг padding",
      "Задаёт отступы равными ширине элемента",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: при border-box ширина и высота включают padding и border.",
      "margin не отключается этим свойством.",
      "Оно не создаёт границу вокруг padding, а влияет на расчёт размеров.",
      "Отступы не зависят от box-sizing.",
    ],
    moduleId: "css",
    sectionTitle: "Блочная модель и позиционирование элементов",
    topic: "css_box_model",
  },
  {
    id: "css_box_model_4",
    title:
      "Какой итоговый размер блока width: 200px; padding: 10px; border: 5px; при box-sizing: content-box;?",
    options: ["200px", "210px", "230px", "240px"],
    correctAnswers: [3],
    descriptions: [
      "200px — только контент, без padding и border.",
      "210px — учтён только один padding.",
      "230px — учтён padding (10px*2) и border (5px*2) составляет 200 + 20 + 10 = 230, но забыт ещё один border.",
      "Правильно: итоговая ширина = 200 (контент) + 10*2 (padding) + 5*2 (border) = 240px.",
    ],
    moduleId: "css",
    sectionTitle: "Блочная модель и позиционирование элементов",
    topic: "css_box_model",
  },
  {
    id: "css_box_model_5",
    title:
      "При каком box-sizing итоговая ширина блока равна объявленной width?",
    options: ["content-box", "padding-box", "border-box", "margin-box"],
    correctAnswers: [2],
    descriptions: [
      "content-box — ширина относится только к контенту, padding и border добавляются.",
      "padding-box не является стандартным значением.",
      "Правильно: при border-box padding и border включаются в width, итоговая ширина = объявленная.",
      "margin-box — несуществующее значение.",
    ],
    moduleId: "css",
    sectionTitle: "Блочная модель и позиционирование элементов",
    topic: "css_box_model",
  },
  {
    id: "css_box_model_6",
    title: "Что создаёт внешние отступы margin между двумя блоками?",
    options: ["padding", "border", "margin", "content"],
    correctAnswers: [2],
    descriptions: [
      "padding — внутренний отступ, не создаёт gap между блоками внешне.",
      "border — граница, не создаёт пространства между блоками.",
      "Правильно: margin — внешний отступ, создаёт пространство между соседними элементами.",
      "content — область содержимого, не влияет на gap.",
    ],
    moduleId: "css",
    sectionTitle: "Блочная модель и позиционирование элементов",
    topic: "css_box_model",
  },
  {
    id: "css_box_model_7",
    title:
      "Что произойдёт при установке margin-top: 20px; на первый элемент в контейнере?",
    options: [
      "Отступ 20px сверху от контейнера",
      "Отступ 20px внутри элемента от контента",
      "Создаст границу толщиной 20px",
      "Ничего не изменится, margin влияет только на соседний элемент",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: margin-top создаёт внешний отступ сверху, отступясь от родительского контейнера.",
      "Это padding-top, а не margin-top.",
      "border создаёт границу, margin не создаёт рамку.",
      "margin влияет на положение элемента относительно родителей или соседей.",
    ],
    moduleId: "css",
    sectionTitle: "Блочная модель и позиционирование элементов",
    topic: "css_box_model",
  },
  {
    id: "css_box_model_8",
    title: "Какой результат у padding: 10px 20px 30px 40px;?",
    options: [
      "top 10px, right 20px, bottom 30px, left 40px",
      "top 40px, right 30px, bottom 20px, left 10px",
      "все стороны 10px",
      "top/bottom 10px, left/right 20px",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: сокращённая запись padding: top right bottom left.",
      "Это обратный порядок (left, bottom, right, top).",
      "Это был бы padding: 10px.",
      "Это было бы padding: 10px 20px.",
    ],
    moduleId: "css",
    sectionTitle: "Блочная модель и позиционирование элементов",
    topic: "css_box_model",
  },
  {
    id: "css_box_model_9",
    title: "Что создаёт border: 2px solid #000;?",
    options: [
      "внутреннюю рамку толщиной 2px",
      "внешнюю тень",
      "рамку вокруг padding и content толщиной 2px черного цвета",
      "отступ вокруг элемента",
    ],
    correctAnswers: [2],
    descriptions: [
      "border — это не внутренняя рамка, а граница вокруг содержимого+padding.",
      "box-shadow создаёт тень, border — рамку.",
      "Правильно: рамка вокруг содержимого (и padding) толщиной 2px, цвет #000.",
      "margin задаёт отступ вокруг элемента, border — рамку.",
    ],
    moduleId: "css",
    sectionTitle: "Блочная модель и позиционирование элементов",
    topic: "css_box_model",
  },
  {
    id: "css_box_model_10",
    title: "Что происходит, если задать width без указания box-sizing?",
    options: [
      "Используется padding-box по умолчанию",
      "Используется content-box по умолчанию",
      "Используется border-box по умолчанию",
      "Используется margin-box по умолчанию",
    ],
    correctAnswers: [1],
    descriptions: [
      "padding-box — не стандартное значение.",
      "Правильно: по умолчанию box-sizing: content-box, width применяется к контенту.",
      "border-box не является значением по умолчанию.",
      "margin-box — несуществующее значение.",
    ],
    moduleId: "css",
    sectionTitle: "Блочная модель и позиционирование элементов",
    topic: "css_box_model",
  },
  {
    id: "css_box_model_11",
    title:
      "Как задать одновременно горизонтальные margin и вертикальные padding?",
    options: [
      "margin: 10px 20px; padding: 5px 15px;",
      "margin: 10px 0 10px 0; padding: 0 15px;",
      "margin: 10px 20px 10px 20px; padding: 5px 15px 5px 15px;",
      "margin-top:10px; margin-bottom:10px; padding-left:15px; padding-right:15px;",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: margin: вертикаль горизонталь, padding: вертикаль горизонталь.",
      "margin: 10px 0 10px 0 задаёт только горизонтальные 0, не 20px.",
      "Дублирование, но поочередность неверна для данного вопроса.",
      "Работает, но вопрос просил сокращённую запись.",
    ],
    moduleId: "css",
    sectionTitle: "Блочная модель и позиционирование элементов",
    topic: "css_box_model",
  },
  {
    id: "css_box_model_12",
    title:
      "Какой код приведёт к схлопыванию вертикальных margin двух соседних блоков?",
    options: [
      "display: inline-block;",
      "margin-top: 20px; margin-bottom: 20px;",
      "border-top: 1px solid #000;",
      "padding: 0;",
    ],
    correctAnswers: [1],
    descriptions: [
      "inline-block не схлопывает margin по-вертикали, схлопывается только у блочных соседей.",
      "Правильно: соседние вертикальные margin схлопываются до максимального значения (20px).",
      "border между блоками предотвращает схлопывание margin.",
      "padding не влияет на схлопывание margin.",
    ],
    moduleId: "css",
    sectionTitle: "Блочная модель и позиционирование элементов",
    topic: "css_box_model",
  },
  {
    id: "css_box_model_13",
    title:
      "Как предотвратить схлопывание margin между родителем и первым дочерним блоком?",
    options: [
      "Задать padding-top родителю",
      "Задать border-top родителю",
      "Задать overflow: hidden родителю",
      "Любой из вышеуказанных способов",
    ],
    correctAnswers: [3],
    descriptions: [
      "Правильно: padding-top создаёт новый контекст и предотвращает схлопывание.",
      "Правильно: border-top тоже предотвращает схлопывание.",
      "Правильно: overflow:hidden создаёт новый контекст блока и тоже предотвращает схлопывание.",
      "Все перечисленные способы работают.",
    ],
    moduleId: "css",
    sectionTitle: "Блочная модель и позиционирование элементов",
    topic: "css_box_model",
  },
  {
    id: "css_box_model_14",
    title: "Что делает свойство overflow: auto; при недостатке места?",
    options: [
      "Добавляет скроллбар, если содержимое выходит за пределы блока",
      "Обрезает содержимое без скролла",
      "Ничего не делает",
      "Добавляет отступы вокруг содержимого",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: overflow:auto добавляет при необходимости полосы прокрутки.",
      "Обрезание без скролла — это overflow:hidden.",
      "auto не игнорируется, он реагирует на переполнение.",
      "Отступы — это margin или padding, а не overflow.",
    ],
    moduleId: "css",
    sectionTitle: "Блочная модель и позиционирование элементов",
    topic: "css_box_model",
  },
  {
    id: "css_box_model_15",
    title:
      "Как задать фиксированную высоту и ширину блока, чтобы padding не увеличивал его итоговый размер при box-sizing: border-box;?",
    options: [
      "width: 200px; height: 100px; padding: 20px;",
      "box-sizing: content-box; width: 200px; height: 100px; padding: 20px;",
      "box-sizing: border-box; width: 200px; height: 100px; padding: 20px;",
      "padding: 20px; border: 1px solid; width: 200px; height: 100px;",
    ],
    correctAnswers: [2],
    descriptions: [
      "padding без border-box увеличит итоговый размер сверх 200×100.",
      "content-box добавит padding вне указанных размеров.",
      "Правильно: при border-box padding входит в общие 200×100px.",
      "padding без указания box-sizing изменит фактический размер.",
    ],
    moduleId: "css",
    sectionTitle: "Блочная модель и позиционирование элементов",
    topic: "css_box_model",
  },
  {
    id: "css_box_model_16",
    title: "Как задать границу в 5px только снизу элемента?",
    options: [
      "border-bottom-width: 5px;",
      "border-width: 0 0 5px 0;",
      "border-bottom: 5px solid;",
      "Любой из вышеупомянутых",
    ],
    correctAnswers: [3],
    descriptions: [
      "border-bottom-width задаёт только ширину границы, но без стиля и цвета не отобразится.",
      "border-width: 0 0 5px 0 задаст ширину всех сторон, но без стиля и цвета не отобразится.",
      "border-bottom: 5px solid; задаст ширину и стиль, но без цвета не отобразится полностью.",
      "Чтобы граница отображалась, нужно задать как width, так и стиль и цвет. Любой из способов можно дополнить стилем и цветом.",
    ],
    moduleId: "css",
    sectionTitle: "Блочная модель и позиционирование элементов",
    topic: "css_box_model",
  },
  {
    id: "css_box_model_17",
    title:
      "Как задать минимальную ширину блока 150px, но разрешить расширяться до 100%?",
    options: [
      "min-width: 150px; width: 100%;",
      "width: 100% min-width: 150px;",
      "max-width: 150px; width: 100%;",
      "width: clamp(150px, 100%, 100%);",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: min-width:150px; width:100%;.",
      "Неправильный порядок свойств, но при корректном синтаксисе это работает.",
      "max-width ограничивает сверху, а не задаёт минимум.",
      "clamp требует три значения, здесь указаны два.",
    ],
    moduleId: "css",
    sectionTitle: "Блочная модель и позиционирование элементов",
    topic: "css_box_model",
  },
  {
    id: "css_box_model_18",
    title:
      "Что произойдет, если задать margin: 20px auto; для блочного элемента с width: 300px;?",
    options: [
      "Горизонтальные отступы станут автоматическими, и элемент центрируется",
      "Вертикальные отступы задаются автоматически",
      "Элемент растянется на всю ширину родителя",
      "Элемент обрежется",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: margin:20px auto; задаёт 20px сверху/снизу, auto слева/справа, что центрирует блок.",
      "auto применяется только к горизонтальным отступам в этом случае.",
      "width явно задан: 300px, он не растянется.",
      "Обрезание происходит при overflow:hidden, не при auto margin.",
    ],
    moduleId: "css",
    sectionTitle: "Блочная модель и позиционирование элементов",
    topic: "css_box_model",
  },
  {
    id: "css_box_model_19",
    title: "Какой результат у margin: -10px; на блоке?",
    options: [
      "Создаст отрицательный внешний отступ, элемент сдвинется на 10px",
      "Ничего не изменится, отрицательные отступы не поддерживаются",
      "margin: -10px; эквивалентен margin: 10px;",
      "Элемент станет невидимым",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: отрицательное значение сдвинет элемент на 10px навстречу соседям.",
      "Отрицательные margin поддерживаются в CSS.",
      "Отрицательное значение не эквивалентно положительному.",
      "Невидимость достигается opacity или display:none.",
    ],
    moduleId: "css",
    sectionTitle: "Блочная модель и позиционирование элементов",
    topic: "css_box_model",
  },
  {
    id: "css_box_model_20",
    title:
      "Какой код задаст тень вокруг блока (box shadow) с отступом 5px и размерами 10px?",
    options: [
      "box-shadow: 5px 5px 10px #000;",
      "box-shadow: offset(5px,5px) blur(10px);",
      "shadow-box: 5px 5px 10px #000;",
      "box-shadow: 5 5 10 #000;",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: box-shadow: 5px 5px 10px #000; задаёт смещение по X/Y и размытие.",
      "offset() и blur() не являются синтаксисом CSS.",
      "shadow-box — несуществующее свойство.",
      "px обязательны для чисел в CSS.",
    ],
    moduleId: "css",
    sectionTitle: "Блочная модель и позиционирование элементов",
    topic: "css_box_model",
  },
  {
    id: "css_box_model_21",
    title: "Какое значение display делает элемент блочным?",
    options: ["inline", "block", "inline-block", "flex"],
    correctAnswers: [1],
    descriptions: [
      "inline — строчно-уровневый элемент.",
      "Правильно: block — блочный элемент занимает всю ширину контейнера.",
      "inline-block — строчно-блочный элемент, но не полностью блочный.",
      "flex — гибкий контейнер, но всё ещё дисплей flex.",
    ],
    moduleId: "css",
    sectionTitle: "Блочная модель и позиционирование элементов",
    topic: "css_box_model",
  },
  {
    id: "css_box_model_22",
    title: "Что делает display: inline-block;?",
    options: [
      "Делает элемент блочным и переносит на новую строку",
      "Делает элемент строчно-блочным, позволяя устанавливать width и height",
      "Делает элемент строчно-уровневым без возможности задавать размеры",
      "Переключает элемент в режим таблицы",
    ],
    correctAnswers: [1],
    descriptions: [
      "Это больше похоже на display:block.",
      "Правильно: inline-block сочетает особенности inline и block: элемент остаётся в одном ряду, но его можно задавать размер.",
      "inline — только строчно-уровневый без размеров.",
      "display: table — это таблица, а не inline-block.",
    ],
    moduleId: "css",
    sectionTitle: "Блочная модель и позиционирование элементов",
    topic: "css_box_model",
  },
  {
    id: "css_box_model_23",
    title: "Какое значение display создаёт гибкий контейнер?",
    options: ["grid", "table", "flex", "block"],
    correctAnswers: [2],
    descriptions: [
      "grid — сеточный контейнер, не гибкий.",
      "table — создает таблицу, а не flex-контейнер.",
      "Правильно: flex — создаёт flex-контейнер для управления расположением потомков.",
      "block — просто блочный, без flex-возможностей.",
    ],
    moduleId: "css",
    sectionTitle: "Блочная модель и позиционирование элементов",
    topic: "css_box_model",
  },
  {
    id: "css_box_model_24",
    title: "Какое значение display создаёт сеточный контейнер?",
    options: ["flex", "grid", "inline", "none"],
    correctAnswers: [1],
    descriptions: [
      "flex — гибкий контейнер, не сеточный.",
      "Правильно: grid — создает CSS Grid Layout.",
      "inline — строчно-уровневый, без сетки.",
      "none — скрывает элемент, без layout.",
    ],
    moduleId: "css",
    sectionTitle: "Блочная модель и позиционирование элементов",
    topic: "css_box_model",
  },
  {
    id: "css_box_model_25",
    title: "Что происходит при display: none;?",
    options: [
      "Элемент остаётся на странице, но невидим",
      "Элемент занимает место, но не отображается",
      "Элемент удаляется из потока и не занимает места",
      "Элемент становится абсолютным",
    ],
    correctAnswers: [2],
    descriptions: [
      "visibility: hidden — скрывает, но оставляет место.",
      "visibility: hidden — скрывает, но пространство остается.",
      "Правильно: display:none полностью убирает элемент из потока, он не занимает места.",
      "absolute — позиционирование, не связано с display:none.",
    ],
    moduleId: "css",
    sectionTitle: "Блочная модель и позиционирование элементов",
    topic: "css_box_model",
  },
  {
    id: "css_box_model_26",
    title: "Какое значение display делает элемент строчно-уровневым?",
    options: ["inline", "block", "flex", "grid"],
    correctAnswers: [0],
    descriptions: [
      "Правильно: inline — строчно-уровневый элемент.",
      "block — блочный элемент, переносит на новую строку.",
      "flex — гибкий контейнер, блочный по умолчанию.",
      "grid — сеточный контейнер, блочный по умолчанию.",
    ],
    moduleId: "css",
    sectionTitle: "Блочная модель и позиционирование элементов",
    topic: "css_box_model",
  },
  {
    id: "css_box_model_27",
    title: "Что делает display: table;?",
    options: [
      "Создает элемент как таблицу, а потомков как строки/ячейки",
      "Преобразует элемент в flex-контейнер",
      "Скрывает элемент с анимацией",
      "Привязывает элемент к сетке",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: display:table делает элемент табличным контейнером, а потомков с display: table-row и table-cell можно стилизовать как строки и ячейки.",
      "flex — другой вид layout, не table.",
      "none и opacity управляют видимостью, а не display:table.",
      "grid — для сетки, не table.",
    ],
    moduleId: "css",
    sectionTitle: "Блочная модель и позиционирование элементов",
    topic: "css_box_model",
  },
  {
    id: "css_box_model_28",
    title:
      "Какое значение display ведёт себя как элемент-исключение из нормального потока (не влияет на соседей)?",
    options: ["absolute", "fixed", "relative", "static"],
    correctAnswers: [0],
    descriptions: [
      "Правильно: position:absolute извлекает элемент из нормального потока, но важно не путать с display.",
      "fixed — похож на absolute, но привязан к окну, тоже извлекает из потока.",
      "relative — остается в потоке, смещается относительно себя.",
      "static — поведение по умолчанию, в потоке.",
    ],
    moduleId: "css",
    sectionTitle: "Блочная модель и позиционирование элементов",
    topic: "css_box_model",
  },
  {
    id: "css_box_model_29",
    title: "Как сделать элемент невидимым, но сохраняющим место в макете?",
    options: [
      "display: none;",
      "visibility: visible;",
      "visibility: hidden;",
      "opacity: 0;",
    ],
    correctAnswers: [2],
    descriptions: [
      "display:none — убирает из потока, не сохраняет место.",
      "visible — делает элемент видимым.",
      "Правильно: visibility:hidden скрывает элемент, но он продолжает занимать место.",
      "opacity:0 — делает невидимым, но элемент по-прежнему реагирует на события.",
    ],
    moduleId: "css",
    sectionTitle: "Блочная модель и позиционирование элементов",
    topic: "css_box_model",
  },
  {
    id: "css_box_model_30",
    title:
      "Какое значение display позволяет использовать элемент как flex-рядок?",
    options: ["inline-flex", "block-flex", "flex-row", "flex-inline"],
    correctAnswers: [0],
    descriptions: [
      "Правильно: inline-flex создает строчно-флекс контейнер, расположенный в строке с соседними элементами.",
      "block-flex не существует.",
      "flex-row — значение свойства flex-direction, но не display.",
      "flex-inline — неверное значение.",
    ],
    moduleId: "css",
    sectionTitle: "Блочная модель и позиционирование элементов",
    topic: "css_box_model",
  },
  {
    id: "css_box_model_31",
    title:
      "Какое значение display делает элемент строчно-сеточным контейнером?",
    options: ["inline-grid", "grid-inline", "grid-block", "inline-table"],
    correctAnswers: [0],
    descriptions: [
      "Правильно: inline-grid создает строчно-сеточный контейнер.",
      "grid-inline — неверное значение.",
      "grid-block — несуществующее.",
      "inline-table — строчно-табличный, не сеточный.",
    ],
    moduleId: "css",
    sectionTitle: "Блочная модель и позиционирование элементов",
    topic: "css_box_model",
  },
  {
    id: "css_box_model_32",
    title: "Что делает display: contents;?",
    options: [
      "Убирает сам элемент, оставляя его потомков в потоке",
      "Превращает элемент в блок без отступов",
      "Скрывает элемент и всех потомков",
      "Меняет элемент на flex-контейнер",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: display:contents делает сам контейнер невидимым, но сохраняет и показывает содержимое как часть родителя.",
      "display:block создаёт блочный элемент, но не убирает его.",
      "display:none скрывает и элемент, и потомков.",
      "display:flex создаёт flex-контейнер, а не удаляет его.",
    ],
    moduleId: "css",
    sectionTitle: "Блочная модель и позиционирование элементов",
    topic: "css_box_model",
  },
  {
    id: "css_box_model_33",
    title:
      "Какое значение display применяется по умолчанию для элемента <span>?",
    options: ["block", "inline", "inline-block", "flex"],
    correctAnswers: [1],
    descriptions: [
      "div, p — display:block, но span — inline.",
      "Правильно: span — строчно-уровневый элемент (inline) по умолчанию.",
      "inline-block — не по умолчанию для span.",
      "flex — не по умолчанию.",
    ],
    moduleId: "css",
    sectionTitle: "Блочная модель и позиционирование элементов",
    topic: "css_box_model",
  },
  {
    id: "css_box_model_34",
    title:
      "Какое значение display применяется по умолчанию для элемента <div>?",
    options: ["inline", "block", "flex", "none"],
    correctAnswers: [1],
    descriptions: [
      "inline — для span, a, и т.д.",
      "Правильно: div — блочный элемент (block) по умолчанию.",
      "flex — не по умолчанию для div.",
      "none — скрывает элемент, не используется по умолчанию.",
    ],
    moduleId: "css",
    sectionTitle: "Блочная модель и позиционирование элементов",
    topic: "css_box_model",
  },
  {
    id: "css_box_model_35",
    title:
      "Какое значение display убирает элемент из макета, но оставляет место для псевдоэлементов?",
    options: [
      "visibility: hidden;",
      "display: none;",
      "opacity: 0;",
      "position: absolute;",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: visibility:hidden скрывает содержимое, но сохраняет место, и псевдоэлементы могут отображаться.",
      "display:none убирает элемент из потока и скрывает псевдоэлементы.",
      "opacity:0 делает элемент невидимым, но он по-прежнему занимает место и обрабатывается в потоке.",
      "position:absolute вынесет элемент из потока, но не скроет его.",
    ],
    moduleId: "css",
    sectionTitle: "Блочная модель и позиционирование элементов",
    topic: "css_box_model",
  },
  {
    id: "css_box_model_36",
    title:
      "Какое значение display используется для элементов формы <label> по умолчанию?",
    options: ["inline", "block", "inline-block", "flex"],
    correctAnswers: [0],
    descriptions: [
      "Правильно: label — строчно-уровневый элемент (inline) по умолчанию.",
      "block — не по умолчанию.",
      "inline-block — не по умолчанию для label.",
      "flex — не по умолчанию.",
    ],
    moduleId: "css",
    sectionTitle: "Блочная модель и позиционирование элементов",
    topic: "css_box_model",
  },
  {
    id: "css_box_model_37",
    title:
      "Какое значение display нужно для создания областей для grid-а внутри <div>?",
    options: ["inline-grid", "grid", "flex", "block"],
    correctAnswers: [1],
    descriptions: [
      "inline-grid создаёт строчно-сеточный контейнер, но вопрос именно про grid внутри div без сохранения inline.",
      "Правильно: display:grid превращает элемент в сеточный контейнер.",
      "flex — не grid.",
      "block — не grid.",
    ],
    moduleId: "css",
    sectionTitle: "Блочная модель и позиционирование элементов",
    topic: "css_box_model",
  },
  {
    id: "css_box_model_38",
    title:
      "Как сделать элемент невидимым, но оставить его «поведение» в flex-контейнере?",
    options: [
      "display: none;",
      "visibility: hidden;",
      "opacity: 0;",
      "pointer-events: none;",
    ],
    correctAnswers: [2],
    descriptions: [
      "display:none удалит элемент из flex-потока.",
      "visibility:hidden сохранит место, но элемент всё ещё может влиять на layout (должно: opacity).",
      "Правильно: opacity:0 сделает элемент невидимым, но он сохранит размеры и положение в flex.",
      "pointer-events:none только отключает события, но не скрывает.",
    ],
    moduleId: "css",
    sectionTitle: "Блочная модель и позиционирование элементов",
    topic: "css_box_model",
  },
  {
    id: "css_box_model_39",
    title:
      "Какое значение display позволяет наследовать контекст inline для <svg>?",
    options: ["block", "inline", "inline-block", "contents"],
    correctAnswers: [1],
    descriptions: [
      "block — превратит svg в блочный элемент.",
      "Правильно: inline сохранит поведение SVG как строчного контента внутри текста.",
      "inline-block — позволяет размер, но не сохраняет полностью inline-особенности.",
      "contents — удалит сам элемент, оставив содержимое.",
    ],
    moduleId: "css",
    sectionTitle: "Блочная модель и позиционирование элементов",
    topic: "css_box_model",
  },
  {
    id: "css_box_model_40",
    title:
      "Какое значение display используется для скрытия элемента, но с сохранением его потомков в документе?",
    options: [
      "display: contents;",
      "visibility: collapse;",
      "opacity: 0;",
      "display: none;",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: display:contents удаляет контейнер, но сохраняет и отображает потомков в потоке.",
      "visibility:collapse — для элементов таблицы убирает строку/колонку, но не применяется к любым элементам.",
      "opacity:0 скрывает визуально, остаётся контейнер.",
      "display:none удаляет контейнер и потомков.",
    ],
    moduleId: "css",
    sectionTitle: "Блочная модель и позиционирование элементов",
    topic: "css_box_model",
  },
  {
    id: "css_box_model_41",
    title:
      "Какое свойство смещает элемент сверху относительно его обычного положения при position: relative;?",
    options: ["top", "right", "bottom", "left"],
    correctAnswers: [0],
    descriptions: [
      "Правильно: top смещает элемент вниз (если значение положительное) или вверх (если отрицательное) от его обычного положения.",
      "right смещает элемент слева направо.",
      "bottom смещает элемент снизу вверх.",
      "left смещает элемент справа налево.",
    ],
    moduleId: "css",
    sectionTitle: "Блочная модель и позиционирование элементов",
    topic: "css_box_model",
  },
  {
    id: "css_box_model_42",
    title:
      "При каком значении position можно использовать свойства top, right, bottom, left?",
    options: ["static", "relative", "absolute", "all вышеуказанные"],
    correctAnswers: [3],
    descriptions: [
      "static — элементы со статическим позиционированием не реагируют на top/right/etc.",
      "relative — можно смещать относительно исходного положения.",
      "absolute — можно смещать относительно ближайшего позиционированного предка.",
      "Правильно: top/right/bottom/left работают для relative, absolute и fixed.",
    ],
    moduleId: "css",
    sectionTitle: "Блочная модель и позиционирование элементов",
    topic: "css_box_model",
  },
  {
    id: "css_box_model_43",
    title: "Какое поведение у значения top: 20px; при position: absolute;?",
    options: [
      "Смещение вниз на 20px от родительского элемента",
      "Смещение вниз на 20px от ближайшего позиционированного предка",
      "Сдвигает элемент вверх на 20px от текущего положения",
      "Не работает без указания left/right/bottom",
    ],
    correctAnswers: [1],
    descriptions: [
      "Для relative offset относительно самого себя, не родителя.",
      "Правильно: absolute смещает элемент относительно ближайшего предка с position отличным от static.",
      "top со значением положительным всегда смещает вниз, а не вверх.",
      "Свойства top/right/bottom/left работают независимо друг от друга.",
    ],
    moduleId: "css",
    sectionTitle: "Блочная модель и позиционирование элементов",
    topic: "css_box_model",
  },
  {
    id: "css_box_model_44",
    title: "Что значит right: 10px; при position: fixed;?",
    options: [
      "Смещение элемента вниз на 10px",
      "Смещение элемента вправо на 10px",
      "Смещение элемента влево на 10px от правого края окна",
      "Смещение элемента сверху на 10px",
    ],
    correctAnswers: [2],
    descriptions: [
      "right не смещает вниз.",
      "right при fixed не смещает вправо, а задаёт дистанцию от правого края.",
      "Правильно: fixed с right:10px прижимает элемент к правому краю окна с отступом 10px.",
      "right не связано со смещением сверху.",
    ],
    moduleId: "css",
    sectionTitle: "Блочная модель и позиционирование элементов",
    topic: "css_box_model",
  },
  {
    id: "css_box_model_45",
    title: "Какое смещение применится для bottom: 0; при position: absolute;?",
    options: [
      "Элемент прикрепится к нижней границе ближайшего позиционированного предка",
      "Элемент прикрепится к нижней границе окна браузера",
      "Элемент прикрепится к нижней границе документа",
      "Ничего не изменится, если не указать top",
    ],
    correctAnswers: [0],
    descriptions: [
      "bottom:0 при absolute не прикрепляет к окну, а к позиции родителя.",
      "Только fixed прикрепляет к окну.",
      "Документ не влияет, поскольку absolute привязан к предку.",
      "bottom работает самостоятельно без top.",
    ],
    moduleId: "css",
    sectionTitle: "Блочная модель и позиционирование элементов",
    topic: "css_box_model",
  },
  {
    id: "css_box_model_46",
    title: "Что произойдёт при left: -20px; для position: relative;?",
    options: [
      "Элемент сдвинется вправо на 20px",
      "Элемент сдвинется влево на 20px",
      "Элемент перекроет соседей без смещения",
      "Ничего, т.к. relative не поддерживает отрицательные значения",
    ],
    correctAnswers: [1],
    descriptions: [
      "Положительное значение left смещает вправо, но здесь значение отрицательное.",
      "Правильно: отрицательное left у relative сдвигает элемент влево.",
      "Элемент действительно может перекрывать, но при этом сдвигается.",
      "relative поддерживает отрицательные смещения.",
    ],
    moduleId: "css",
    sectionTitle: "Блочная модель и позиционирование элементов",
    topic: "css_box_model",
  },
  {
    id: "css_box_model_47",
    title:
      "Какое поведение у свойств top/right/bottom/left при position: static;?",
    options: [
      "Работают нормально",
      "Игнорируются, т.к. элемент остаётся в потоке",
      "Смещают элемент как absolute",
      "Переписывают margin",
    ],
    correctAnswers: [1],
    descriptions: [
      "static не применяет смещение, как relative/absolute.",
      "Правильно: static игнорирует top/right/bottom/left, элемент остаётся в нормальном потоке.",
      "Смещение как absolute работает только при соответствующем position.",
      "top/right/bottom/left не переписывают margin.",
    ],
    moduleId: "css",
    sectionTitle: "Блочная модель и позиционирование элементов",
    topic: "css_box_model",
  },
  {
    id: "css_box_model_48",
    title:
      "Что означает bottom: 50%; при position: absolute; относительно контейнера высотой 200px?",
    options: [
      "Смещение вниз на 100px",
      "Смещение вверх на 100px",
      "Смещение вниз на 50px",
      "Смещение вверх на 50px",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: percentage при absolute считается от высоты предка, 50% от 200px = 100px вниз.",
      "Не вверх, поскольку positive bottom смещает вверх только при relative и от собственного положения.",
      "50px — это 25%.",
      "50px — неверное вычисление.",
    ],
    moduleId: "css",
    sectionTitle: "Блочная модель и позиционирование элементов",
    topic: "css_box_model",
  },
  {
    id: "css_box_model_49",
    title:
      "Какое значение left при absolute прижимает элемент к левому краю родителя?",
    options: ["left: 0;", "left: auto;", "left: 100%;", "left: -100%;"],
    correctAnswers: [0],
    descriptions: [
      "Правильно: left:0 при absolute прижимает к левой границе предка.",
      "auto — оставляет текущую позицию без смещения.",
      "100% — прижимает к правому краю плюс ширина элемента.",
      "-100% — смещает за пределы влево на ширину родителя.",
    ],
    moduleId: "css",
    sectionTitle: "Блочная модель и позиционирование элементов",
    topic: "css_box_model",
  },
  {
    id: "css_box_model_50",
    title:
      "Какой результат у сочетания position: absolute; top: 0; right: 0; при расположении внутри position: relative; контейнера?",
    options: [
      "Элемент прижмётся к верхней левой границе контейнера",
      "Элемент прижмётся к верхней правой границе контейнера",
      "Элемент прижмётся к нижней левой границе контейнера",
      "Элемент прижмётся к нижней правой границе контейнера",
    ],
    correctAnswers: [1],
    descriptions: [
      "top:0 + right:0 означает верх и правую сторону.",
      "Правильно: элемент прижимается к верхней правой границе родителя.",
      "bottom не указан, а top:0 прижимает к верху, не к низу.",
      "Нижний угол — комбинация bottom and right.",
    ],
    moduleId: "css",
    sectionTitle: "Блочная модель и позиционирование элементов",
    topic: "css_box_model",
  },
  {
    id: "css_box_model_51",
    title:
      "Что произойдёт, если задать left: 50%; transform: translateX(-50%); для position: absolute;?",
    options: [
      "Элемент будет горизонтально центрирован внутри родителя",
      "Элемент будет смещён влево на 50% от своей ширины",
      "Элемент будет смещён вправо на 50% от родительской ширины",
      "Элемент не изменит положение",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: left:50% смещает левую границу элемента к середине родителя, а translateX(-50%) смещает его на половину собственной ширины обратно, центрируя.",
      "Обратный эффект дополняется translateX, но итоговый эффект — центрирование.",
      "translateX(-50%) учитывает собственную ширину, а не родителя.",
      "Сочетание свойств изменяет положение.",
    ],
    moduleId: "css",
    sectionTitle: "Блочная модель и позиционирование элементов",
    topic: "css_box_model",
  },
  {
    id: "css_box_model_52",
    title: "Какой эффект имеет top: auto; при absolute?",
    options: [
      "Смещение к верху контейнера",
      "Ничего, оставляет текущее положение по вертикали",
      "Прижимает к низу контейнера",
      "Ошибка, auto нельзя использовать",
    ],
    correctAnswers: [1],
    descriptions: [
      "top:auto не смещает, а оставляет текущее координатное положение.",
      "Правильно: auto просто означает «не задавать смещение, сохранить текущее».",
      "bottom используется для прижатия к низу.",
      "auto допустимое значение.",
    ],
    moduleId: "css",
    sectionTitle: "Блочная модель и позиционирование элементов",
    topic: "css_box_model",
  },
  {
    id: "css_box_model_53",
    title: "Что будет, если указать bottom: 0; right: 0; position: fixed;?",
    options: [
      "Элемент прижмётся к нижнему левому углу окна",
      "Элемент прижмётся к нижнему правому углу окна",
      "Элемент прижмётся к верхнему правому углу окна",
      "Элемент прижмётся к верхнему левому углу окна",
    ],
    correctAnswers: [1],
    descriptions: [
      "bottom:0 + right:0 при fixed означает нижнюю правую границу окна.",
      "Правильно: элемент будет прикреплён к нижнему правому углу окна браузера.",
      "top не указан, используется bottom, поэтому прижим к низу, а не к верху.",
      "Для прижатия влево используется left.",
    ],
    moduleId: "css",
    sectionTitle: "Блочная модель и позиционирование элементов",
    topic: "css_box_model",
  },
  {
    id: "css_box_model_54",
    title: "Какой результат у position: relative; top: 10px; left: 20px;?",
    options: [
      "Элемент прижмётся к левому верхнему углу родителя",
      "Элемент сместится вниз на 10px и вправо на 20px от исходного положения",
      "Элемент будет по-прежнему занимать своё место без смещения",
      "Элемент исчезнет",
    ],
    correctAnswers: [1],
    descriptions: [
      "relative не прижимает, а смещает относительно собственного положения.",
      "Правильно: элемент остаётся в потоке, но визуально перемещается вниз и вправо.",
      "relative сдвигает элемент, его место остаётся зарезервированным, но он смещается.",
      "Элемент остаётся видимым.",
    ],
    moduleId: "css",
    sectionTitle: "Блочная модель и позиционирование элементов",
    topic: "css_box_model",
  },
  {
    id: "css_box_model_55",
    title: "Какой эффект у left: 0; при position: fixed;?",
    options: [
      "Прижимает элемент к левому краю документа",
      "Прижимает элемент к левому краю окна браузера",
      "Сдвигает элемент на ширину окна",
      "Удаляет элемент из DOM",
    ],
    correctAnswers: [1],
    descriptions: [
      "fixed привязан к окну, а не к документу.",
      "Правильно: fixed + left:0 прижимает к левому краю окна.",
      "Не смещает относительно окна вправо.",
      "fixed не удаляет элемент.",
    ],
    moduleId: "css",
    sectionTitle: "Блочная модель и позиционирование элементов",
    topic: "css_box_model",
  },
  {
    id: "css_box_model_56",
    title:
      "Как избежать смещения элемента при использовании top/left для position: relative; с выходом за пределы контейнера?",
    options: [
      "Использовать overflow: hidden на родителе",
      "Использовать position: static",
      "Использовать margin вместо top/left",
      "Невозможно избежать",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: overflow:hidden обрежет видимую часть, выходящую за границы.",
      "static не позволит смещать элемент с помощью top/left.",
      "margin создаёт пространство без абсолютного смещения.",
      "overflow:hidden позволяет скрыть выходящую часть.",
    ],
    moduleId: "css",
    sectionTitle: "Блочная модель и позиционирование элементов",
    topic: "css_box_model",
  },
  {
    id: "css_box_model_57",
    title: "Что достигнет задавание right: auto; при absolute?",
    options: [
      "Элемент прижмётся к левой стороне контейнера",
      "Элемент прижмётся к правой стороне контейнера",
      "Ничего не изменится, так как auto просто сбрасывает смещение",
      "Элемент прижмётся к центру контейнера",
    ],
    correctAnswers: [2],
    descriptions: [
      "Для прижима к левой стороне используют left:0.",
      "auto не прижимает к правой стороне.",
      "Правильно: auto означает «не задавать смещение» и оставляет текущее расположение.",
      "center достигается transform или margin auto.",
    ],
    moduleId: "css",
    sectionTitle: "Блочная модель и позиционирование элементов",
    topic: "css_box_model",
  },
  {
    id: "css_box_model_58",
    title:
      "Какое сочетание свойств position и offset используется для создания прилипающего заголовка при скролле?",
    options: [
      "position: sticky; top: 0;",
      "position: relative; top: 0;",
      "position: absolute; bottom: 0;",
      "position: fixed; bottom: 0;",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: sticky + top:0 делает элемент прилипающим при прокрутке в пределах контейнера.",
      "relative просто смещает, не делает прилипание.",
      "absolute привязывает к предку, а не к прокрутке.",
      "fixed привязывает к окну, но не делает «прилипание» при скролле внутри контейнера.",
    ],
    moduleId: "css",
    sectionTitle: "Блочная модель и позиционирование элементов",
    topic: "css_box_model",
  },
  {
    id: "css_box_model_59",
    title: "Что произойдёт при задании top: 50vh; position: fixed;?",
    options: [
      "Элемент сместится на 50% от высоты окна вниз",
      "Элемент сместится на 50% от высины родителя вниз",
      "Элемент сместится на 50px вниз",
      "Ничего, vh не совместим с fixed",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: 50vh — 50% от высоты окна браузера, при fixed от окна.",
      "vh относится к окну, а не к родителю.",
      "50px — это фиксированное число, не vh.",
      "vh корректно работает с любым position.",
    ],
    moduleId: "css",
    sectionTitle: "Блочная модель и позиционирование элементов",
    topic: "css_box_model",
  },
  {
    id: "css_box_model_60",
    title:
      "Какое значение left задаёт смещение на половину ширины экрана справа при fixed?",
    options: ["left: 50vw;", "left: 50%;", "left: auto;", "left: 100%;"],
    correctAnswers: [0],
    descriptions: [
      "Правильно: 50vw — 50% от ширины окна браузера.",
      "50% при fixed считается относительно родителя (обычно body, но не надежно).",
      "auto не задаёт смещение.",
      "100% при fixed сместит элемент на полную ширину экрана.",
    ],
    moduleId: "css",
    sectionTitle: "Блочная модель и позиционирование элементов",
    topic: "css_box_model",
  },
  {
    id: "css_box_model_61",
    title: "Что делает position: relative; для элемента?",
    options: [
      "Извлекает элемент из нормального потока",
      "Оставляет элемент в потоке, позволяя смещать его относительно исходного положения",
      "Прикрепляет элемент к окну браузера",
      "Превращает элемент в flex-контейнер",
    ],
    correctAnswers: [1],
    descriptions: [
      "Правильно: relative не извлекает элемент из потока, он смещается, но его исходное место сохраняется.",
      "Отлично: элемент остаётся на своём месте, но визуально смещается.",
      "fixed прикрепляет к окну, а не relative.",
      "flex-контейнер создаётся display: flex, а не position.",
    ],
    moduleId: "css",
    sectionTitle: "Блочная модель и позиционирование элементов",
    topic: "css_box_model",
  },
  {
    id: "css_box_model_62",
    title: "Какое поведение у position: absolute;?",
    options: [
      "Сохраняет исходное место, смещает элемент относительно окна",
      "Извлекает элемент из потока и смещает относительно ближайшего позиционированного предка",
      "Фиксирует элемент на экране при прокрутке",
      "Сделает элемент блочным без смещения",
    ],
    correctAnswers: [1],
    descriptions: [
      "relative сохраняет место; absolute извлекает.",
      "Правильно: absolute удаляет из потока и позиционирует относительно ближайшего предка с position не static.",
      "fixed фиксирует при прокрутке, а не absolute.",
      "display:block делает элемент блочным, а не position.",
    ],
    moduleId: "css",
    sectionTitle: "Блочная модель и позиционирование элементов",
    topic: "css_box_model",
  },
  {
    id: "css_box_model_63",
    title:
      "Какое значение position закрепляет элемент относительно окна браузера?",
    options: ["static", "relative", "absolute", "fixed"],
    correctAnswers: [3],
    descriptions: [
      "static — поведение по умолчанию.",
      "relative — смещает в потоке.",
      "absolute — относительно предка, а не окна.",
      "Правильно: fixed прикрепляет элемент к окну независимо от прокрутки.",
    ],
    moduleId: "css",
    sectionTitle: "Блочная модель и позиционирование элементов",
    topic: "css_box_model",
  },
  {
    id: "css_box_model_64",
    title:
      "Какое значение position позволяет элементу прилипать при прокрутке в пределах родителя?",
    options: ["sticky", "fixed", "relative", "static"],
    correctAnswers: [0],
    descriptions: [
      "Правильно: sticky сочетает поведение static до пересечения точки, затем фиксируется.",
      "fixed фиксирует относительно окна, а не родителя.",
      "relative — просто смещает.",
      "static — по умолчанию, без смещения.",
    ],
    moduleId: "css",
    sectionTitle: "Блочная модель и позиционирование элементов",
    topic: "css_box_model",
  },
  {
    id: "css_box_model_65",
    title: "Каков эффект z-index при позиционировании элемента?",
    options: [
      "Задаёт прозрачность элемента",
      "Определяет порядок наложения элементов с position не static",
      "Изменяет размеры элемента",
      "Устанавливает отступы между элементами",
    ],
    correctAnswers: [1],
    descriptions: [
      "opacity контролирует прозрачность.",
      "Правильно: z-index определяет порядок отображения в трёхмерном контексте.",
      "width/height контролируют размеры, не z-index.",
      "margin/padding управляют отступами, не z-index.",
    ],
    moduleId: "css",
    sectionTitle: "Блочная модель и позиционирование элементов",
    topic: "css_box_model",
  },
  {
    id: "css_box_model_66",
    title: "Что необходимо для работы z-index?",
    options: [
      "display: flex;",
      "position отличное от static",
      "opacity менее 1",
      "overflow: hidden",
    ],
    correctAnswers: [1],
    descriptions: [
      "display:flex не влияет напрямую на z-index.",
      "Правильно: z-index работает только у элементов с position: relative, absolute, fixed или sticky.",
      "opacity управляет прозрачностью, не z-index.",
      "overflow:hidden обрезает содержимое, не меняет контекст наложения.",
    ],
    moduleId: "css",
    sectionTitle: "Блочная модель и позиционирование элементов",
    topic: "css_box_model",
  },
  {
    id: "css_box_model_67",
    title: "Как создать новый контекст наложения для дочерних элементов?",
    options: [
      "position: static;",
      "position: relative; z-index: 1;",
      "display: inline;",
      "margin: auto;",
    ],
    correctAnswers: [1],
    descriptions: [
      "static не создаёт контекста.",
      "Правильно: relative + z-index отличное от auto создаёт контекст.",
      "inline не влияет на наложение.",
      "margin не касается контекстов наложения.",
    ],
    moduleId: "css",
    sectionTitle: "Блочная модель и позиционирование элементов",
    topic: "css_box_model",
  },
  {
    id: "css_box_model_68",
    title:
      "Что будет, если у родителя position: relative; у ребёнка position: absolute; без offset-свойств?",
    options: [
      "Ребёнок прижмётся к левому верхнему углу родителя",
      "Ребёнок останется на исходном месте, но может перекрыть содержимое",
      "Ребёнок прижмётся к правому нижнему углу родителя",
      "Ребёнок исчезнет",
    ],
    correctAnswers: [1],
    descriptions: [
      "При отсутствии top/left элемент не смещается.",
      "Правильно: без указания top/right/bottom/left absolute не смещается, остаётся в исходной позиции.",
      "Чтобы прижаться вниз вправо, нужно bottom и right.",
      "Без display:none или visibility:hidden элемент остаётся видимым.",
    ],
    moduleId: "css",
    sectionTitle: "Блочная модель и позиционирование элементов",
    topic: "css_box_model",
  },
  {
    id: "css_box_model_69",
    title:
      "Какое свойство понадобится, чтобы дочерний элемент position: absolute; выровнялся по центру родителя?",
    options: [
      "margin: auto;",
      "left: 50%; top: 50%; transform: translate(-50%, -50%);",
      "text-align: center;",
      "display: grid; place-items: center;",
    ],
    correctAnswers: [1],
    descriptions: [
      "margin:auto не центрирует абсолютно позиционированный элемент без указания размеров.",
      "Правильно: сочетание left, top и transform центрирует.",
      "text-align влияет на строчный текст, не на абсолютный.",
      "display:grid на родителе тоже центрирует, но вопрос про offset-свойства.",
    ],
    moduleId: "css",
    sectionTitle: "Блочная модель и позиционирование элементов",
    topic: "css_box_model",
  },
  {
    id: "css_box_model_70",
    title: "Что будет, если у элемента position: fixed; и offset-свойств нет?",
    options: [
      "Элемент останется в качестве static",
      "Элемент прикрепится к левому верхнему углу окна по умолчанию",
      "Элемент растянется на весь экран",
      "Элемент исчезнет",
    ],
    correctAnswers: [1],
    descriptions: [
      "fixed всегда извлекает из потока.",
      "Правильно: без top/left браузер прижимает fixed к верхнему левому краю.",
      "width/height должны быть заданы отдельно.",
      "fixed не удаляет элемент.",
    ],
    moduleId: "css",
    sectionTitle: "Блочная модель и позиционирование элементов",
    topic: "css_box_model",
  },
  {
    id: "css_box_model_71",
    title:
      "Какое значение top установит элемент position: absolute; ровно по середине родителя по вертикали?",
    options: ["top: 50%;", "top: 100%;", "top: 0;", "top: auto;"],
    correctAnswers: [0],
    descriptions: [
      "Правильно: 50% смещает верхний край элемента к середине родителя.",
      "100% прижмёт к нижнему краю.",
      "0 прижимает к верхнему краю.",
      "auto не задаёт смещение.",
    ],
    moduleId: "css",
    sectionTitle: "Блочная модель и позиционирование элементов",
    topic: "css_box_model",
  },
  {
    id: "css_box_model_72",
    title:
      "Какое значение bottom при position: fixed; прижимает элемент к нижнему краю экрана?",
    options: ["bottom: 0;", "bottom: auto;", "bottom: 100%;", "bottom: 50%;"],
    correctAnswers: [0],
    descriptions: [
      "Правильно: bottom:0 при fixed прижимает к нижнему краю окна.",
      "auto сохраняет текущую позицию.",
      "100% прижимет ниже экрана.",
      "50% сместит вверх от нижнего края, но не прижмёт.",
    ],
    moduleId: "css",
    sectionTitle: "Блочная модель и позиционирование элементов",
    topic: "css_box_model",
  },
  {
    id: "css_box_model_73",
    title: "Что будет, если задано position: sticky; top: 20px;?",
    options: [
      "Элемент всегда прикреплён к 20px от верха окна",
      "Элемент прилипнет при прокрутке, когда его топ достигнет 20px от окна",
      "Элемент останется static",
      "Ничего, sticky не поддерживается",
    ],
    correctAnswers: [1],
    descriptions: [
      "sticky не всегда «всегда прикреплён», только после точки прилипания.",
      "Правильно: элемент становится фиксированным, когда доходит до 20px от верха при прокрутке.",
      "sticky меняет поведение от static после прокрутки.",
      "Большинство современных браузеров поддерживают sticky.",
    ],
    moduleId: "css",
    sectionTitle: "Блочная модель и позиционирование элементов",
    topic: "css_box_model",
  },
  {
    id: "css_box_model_74",
    title:
      "Какой эффект у position: absolute; bottom: 0; right: 0; при родителе, у которого нет position отличного от static?",
    options: [
      "Прижмёт к нижнему правому углу родителя по умолчанию",
      "Прижмёт к нижнему правому углу окна",
      "Элемент не сместится, так как нет позиционированного предка",
      "Элемент исчезнет",
    ],
    correctAnswers: [1],
    descriptions: [
      "При отсутствии предка с position!=static, absolute привязан к документу/окну.",
      "Правильно: привязка идёт к body/document (по умолчанию) или ближайшему ancestor с position.",
      "Если предка нет, привязка идёт к viewport.",
      "Элемент остаётся видимым.",
    ],
    moduleId: "css",
    sectionTitle: "Блочная модель и позиционирование элементов",
    topic: "css_box_model",
  },
  {
    id: "css_box_model_75",
    title:
      "Как задать блок, который будет перекрывать все остальные (самый высокий z-index)?",
    options: [
      "position: static; z-index: 999;",
      "position: relative; z-index: -1;",
      "position: absolute; z-index: 0;",
      "position: relative; z-index: 2147483647;",
    ],
    correctAnswers: [3],
    descriptions: [
      "static не создаёт контекста для z-index.",
      "z-index:-1 отправит элемент на задний план.",
      "z-index:0 не гарантирует самый верхний слой.",
      "Правильно: большое положительное значение z-index при relative позволит перекрыть другие элементы.",
    ],
    moduleId: "css",
    sectionTitle: "Блочная модель и позиционирование элементов",
    topic: "css_box_model",
  },
  {
    id: "css_box_model_76",
    title: "Что необходимо, чтобы position: sticky; корректно работало?",
    options: [
      "Родительский элемент должен иметь overflow: visible",
      "Элемент должен находиться внутри scrollable контейнера",
      "Элемент должен иметь z-index > 0",
      "sticky работает всегда независимо от контекста",
    ],
    correctAnswers: [1],
    descriptions: [
      "overflow: visible — не обязательно.",
      "Правильно: sticky требует, чтобы элемент находился внутри контейнера с прокруткой.",
      "z-index не требуется для работы sticky.",
      "sticky действует только внутри scrollable родителя.",
    ],
    moduleId: "css",
    sectionTitle: "Блочная модель и позиционирование элементов",
    topic: "css_box_model",
  },
  {
    id: "css_box_model_77",
    title:
      "Какое значение position подходит для создания полноэкранного фона под всеми элементами?",
    options: [
      "fixed; top:0; left:0; width:100%; height:100%; z-index:-1;",
      "absolute; top:0; left:0; width:100%; height:100%; z-index:0;",
      "relative; top:0; left:0; width:100%; height:100%;",
      "static;",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: fixed вместе с отрицательным z-index поместит фон позади всего, полностью охватит окно.",
      "absolute привязан к предку, может не охватить весь экран.",
      "relative не извлекает из потока, не подойдёт.",
      "static не позволяет сместить.",
    ],
    moduleId: "css",
    sectionTitle: "Блочная модель и позиционирование элементов",
    topic: "css_box_model",
  },
  {
    id: "css_box_model_78",
    title:
      "Как предотвратить выход абсолютно позиционированного элемента за границы родителя?",
    options: [
      "Добавить overflow: hidden; родителю",
      "Задать position: static; ребёнку",
      "Использовать margin вместо top/left",
      "Нельзя предотвратить",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: overflow:hidden скрывает часть, выходящую за пределы.",
      "static не позволит смещать с помощью top/left.",
      "margin не решит проблему абсолютного позиционирования.",
      "overflow:hidden позволяет скрыть выход.",
    ],
    moduleId: "css",
    sectionTitle: "Блочная модель и позиционирование элементов",
    topic: "css_box_model",
  },
  {
    id: "css_box_model_79",
    title:
      "Какое значение position используют для создания бокового меню, которое остаётся на экране при прокрутке?",
    options: ["absolute", "fixed", "sticky", "relative"],
    correctAnswers: [2],
    descriptions: [
      "absolute — привязан к предку, не к экрану при прокрутке.",
      "fixed — прикреплён к экрану независимо от прокрутки.",
      "Правильно: sticky прилипает внутри контейнера, но остаётся видимым при прокрутке.",
      "relative — смещает только в потоке.",
    ],
    moduleId: "css",
    sectionTitle: "Блочная модель и позиционирование элементов",
    topic: "css_box_model",
  },
  {
    id: "css_box_model_80",
    title:
      "Что будет, если задать position: absolute; top: 50%; left: 50%; без transform?",
    options: [
      "Элемент центрируется идеально",
      "Элемент сместится так, что его верхний левый угол окажется в центре контейнера",
      "Ничего не изменится",
      "Элемент исчезнет",
    ],
    correctAnswers: [1],
    descriptions: [
      "Правильно: без transform смещение учитывает только саму точку, не учитывая размеры элемента.",
      "Именно: верхний левый угол элемента окажется в центре.",
      "Смещение применится, поэтому положение изменится.",
      "Элемент остаётся видимым.",
    ],
    moduleId: "css",
    sectionTitle: "Блочная модель и позиционирование элементов",
    topic: "css_box_model",
  },
  {
    id: "css_box_model_81",
    title: "Что такое stacking context (контекст наложения)?",
    options: [
      "Контекст, в котором элементы располагаются по порядку DOM",
      "Контекст, в котором задаётся собственный порядок наложения z-index",
      "Контекст, управляющий свойством opacity",
      "Контекст, отвечающий за прокрутку",
    ],
    correctAnswers: [1],
    descriptions: [
      "DOM-структура не определяет контекст наложения.",
      "Правильно: каждый stacking context создаёт новый контекст для z-index, изолируя потомков.",
      "opacity влияет на прозрачность, но не сам контекст наложения.",
      "Прокрутка управляется overflow, а не stacking context.",
    ],
    moduleId: "css",
    sectionTitle: "Блочная модель и позиционирование элементов",
    topic: "css_box_model",
  },
  {
    id: "css_box_model_82",
    title: "Какой из критериев НЕ создаёт новый stacking context?",
    options: [
      "position: relative; z-index: 0;",
      "position: absolute; z-index: 1;",
      "opacity: 0.9;",
      "transform: scale(1)",
    ],
    correctAnswers: [2],
    descriptions: [
      "Да: любой position с z-index создаёт новый контекст.",
      "Да: position:absolute с z-index тоже создаёт.",
      "opacity меньше 1 не создаёт контекст, только transform, filter и т.д.",
      "Да: transform создаёт новый stacking context.",
    ],
    moduleId: "css",
    sectionTitle: "Блочная модель и позиционирование элементов",
    topic: "css_box_model",
  },
  {
    id: "css_box_model_83",
    title: "Какое значение opacity создаёт новый stacking context?",
    options: ["opacity: 1;", "opacity: 0;", "opacity: 0.999;", "opacity: 0.5;"],
    correctAnswers: [3],
    descriptions: [
      "opacity:1 — не создаёт контекст, полная непрозрачность.",
      "opacity:0 — полностью прозрачный, но нет условия для нового контекста.",
      "0.999 — почти 1, но всё ещё не создаёт нового контекста.",
      "Правильно: любое значение менее 1 создаёт новый stacking context.",
    ],
    moduleId: "css",
    sectionTitle: "Блочная модель и позиционирование элементов",
    topic: "css_box_model",
  },
  {
    id: "css_box_model_84",
    title: "Что делает свойство overflow: auto; для контейнера?",
    options: [
      "Всегда добавляет скроллбар",
      "Добавляет скроллбар только при переполнении",
      "Всегда обрезает содержимое без скролла",
      "Никак не влияет на прокрутку",
    ],
    correctAnswers: [1],
    descriptions: [
      "auto не всегда показывает скролл, только при необходимости.",
      "Правильно: overflow:auto показывает прокрутку, когда содержимого больше.",
      "overflow:hidden обрезает без скролла, а не overflow:auto.",
      "overflow влияет на прокрутку, поэтому влияет.",
    ],
    moduleId: "css",
    sectionTitle: "Блочная модель и позиционирование элементов",
    topic: "css_box_model",
  },
  {
    id: "css_box_model_85",
    title: "Чем отличается overflow: scroll; от overflow: auto;?",
    options: [
      "scroll — всегда показывает полосы прокрутки, auto — только при необходимости",
      "scroll — обрезает содержимое, auto — сглаживает",
      "scroll — создает новый stacking context, auto — нет",
      "scroll — работает только по вертикали",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: overflow:scroll всегда рисует скроллбары, auto — лишь при переполнении.",
      "scroll не обрезает, он отображает скролл.",
      "overflow не создаёт контекст наложения.",
      "overflow:scroll работает и по горизонтали, и по вертикали.",
    ],
    moduleId: "css",
    sectionTitle: "Блочная модель и позиционирование элементов",
    topic: "css_box_model",
  },
  {
    id: "css_box_model_86",
    title:
      "Как добиться, чтобы внутренний скроллбар не сдвигал элементы соседей?",
    options: [
      "overflow: hidden;",
      "overflow: overlay;",
      "overflow: auto; scrollbar-width: none;",
      "Использовать padding вместо margin",
    ],
    correctAnswers: [1],
    descriptions: [
      "overflow:hidden убирает прокрутку, но не решает проблему соседей.",
      "Правильно: overflow:overlay (в поддерживающих браузерах) накладывает скролл поверх содержимого.",
      "scrollbar-width работает в Firefox, но не во всех браузерах.",
      "padding не влияет на прокрутку.",
    ],
    moduleId: "css",
    sectionTitle: "Блочная модель и позиционирование элементов",
    topic: "css_box_model",
  },
  {
    id: "css_box_model_87",
    title: "Что делает свойство scrollbar-width: thin; в Firefox?",
    options: [
      "Устанавливает минимальную ширину scrollbara",
      "Уменьшает ширину scrollbara",
      "Убирает scrollbara совсем",
      "Меняет цвет scrollbara",
    ],
    correctAnswers: [1],
    descriptions: [
      "thin не задаёт минимальную, а уменьшает относительно стандартной.",
      "Правильно: thin делает прокрутку более узкой.",
      "thin не убирает, а только сужает.",
      "color свойства scrollbar-color меняет цвет, а не width.",
    ],
    moduleId: "css",
    sectionTitle: "Блочная модель и позиционирование элементов",
    topic: "css_box_model",
  },
  {
    id: "css_box_model_88",
    title: "Какое свойство влияет на сглаживание прокрутки в Chrome?",
    options: [
      "scroll-behavior: smooth;",
      "scroll-snap-type: none;",
      "scrollbar-color: auto;",
      "scroll-snap-align: start;",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: scroll-behavior:smooth позволяет плавную прокрутку.",
      "scroll-snap-type контролирует момент прилипания.",
      "scrollbar-color меняет цвет scrollbar.",
      "scroll-snap-align влияет на привязку.",
    ],
    moduleId: "css",
    sectionTitle: "Блочная модель и позиционирование элементов",
    topic: "css_box_model",
  },
  {
    id: "css_box_model_89",
    title: "Что делает scroll-snap-type: x mandatory;?",
    options: [
      "Запрещает прокрутку по горизонтали",
      "Включает обязательную фиксацию при прокрутке по оси X",
      "Включает плавную прокрутку",
      "Отключает вертикальную прокрутку",
    ],
    correctAnswers: [1],
    descriptions: [
      "scroll-snap-type не запрещает полностью, а задаёт правила.",
      "Правильно: x mandatory заставляет содержимое «прилипать» к ближайшему пункту по X.",
      "scroll-behavior управляет плавностью, а не snap.",
      "scroll-snap не отключает вертикальную прокрутку.",
    ],
    moduleId: "css",
    sectionTitle: "Блочная модель и позиционирование элементов",
    topic: "css_box_model",
  },
  {
    id: "css_box_model_90",
    title: "Какое свойство управляет непрозрачностью элемента?",
    options: ["visibility", "opacity", "display", "filter"],
    correctAnswers: [1],
    descriptions: [
      "visibility управляет видимостью, но не непрозрачностью.",
      "Правильно: opacity задаёт уровень прозрачности от 0 до 1.",
      "display управляет отображением, а не прозрачностью.",
      "filter:opacity(X%) работает, но сам filter — не direct свойство.",
    ],
    moduleId: "css",
    sectionTitle: "Блочная модель и позиционирование элементов",
    topic: "css_box_model",
  },
  {
    id: "css_box_model_91",
    title: "Что будет, если задать opacity: 0; элементу?",
    options: [
      "Элемент станет невидимым и не будет занимать место",
      "Элемент станет полностью прозрачным, но сохранит место",
      "Элемент исчезнет из DOM",
      "Произойдёт ошибка",
    ],
    correctAnswers: [1],
    descriptions: [
      "display:none убирает из потока, а opacity:0 просто делает невидимым.",
      "Правильно: opacity:0 делает элемент прозрачным, но он остаётся в потоке.",
      "opacity не удаляет элемент из DOM.",
      "opacity:0 — валидное значение.",
    ],
    moduleId: "css",
    sectionTitle: "Блочная модель и позиционирование элементов",
    topic: "css_box_model",
  },
  {
    id: "css_box_model_92",
    title: "Какое значение filter: blur(5px); сделает?",
    options: [
      "Сдвинет элемент на 5px вниз",
      "Добавит размытие 5px к элементу",
      "Сделает элемент прозрачным на 5%",
      "Изменит цветовой тон",
    ],
    correctAnswers: [1],
    descriptions: [
      "blur не сдвигает, а размазывает изображение.",
      "Правильно: blur(5px) применяет размытие вокруг элементов.",
      "opacity управляет прозрачностью, не blur.",
      "hue-rotate фильтр меняет цветовой тон.",
    ],
    moduleId: "css",
    sectionTitle: "Блочная модель и позиционирование элементов",
    topic: "css_box_model",
  },
  {
    id: "css_box_model_93",
    title:
      "Что происходит с дочерними элементами при opacity: 0.5; на родителе?",
    options: [
      "Только родитель станет полупрозрачным",
      "Все потомки унаследуют прозрачность 0.5",
      "Прозрачность применяется только к фоновому цвету",
      "Произойдёт сброс прозрачности",
    ],
    correctAnswers: [1],
    descriptions: [
      "opacity действует на весь элемент и всех его потомков.",
      "Правильно: детям также будет назначена та же прозрачность.",
      "opacity влияет на весь рендер, а не только фон.",
      "opacity:0.5 — валидное значение, без сброса.",
    ],
    moduleId: "css",
    sectionTitle: "Блочная модель и позиционирование элементов",
    topic: "css_box_model",
  },
  {
    id: "css_box_model_94",
    title: "Что делает filter: grayscale(100%);?",
    options: [
      "Делает элемент полностью прозрачным",
      "Переводит изображение в чёрно-белый режим",
      "Увеличивает контраст на 100%",
      "Размывает изображение",
    ],
    correctAnswers: [1],
    descriptions: [
      "opacity делает прозрачным, а не grayscale.",
      "Правильно: grayscale(100%) конвертирует в чёрно-белый.",
      "contrast фильтр управляет контрастом.",
      "blur фильтр размывает.",
    ],
    moduleId: "css",
    sectionTitle: "Блочная модель и позиционирование элементов",
    topic: "css_box_model",
  },
  {
    id: "css_box_model_95",
    title:
      "Как задать фиксированное полупрозрачное белое перекрытие сверху элемента?",
    options: [
      "background: rgba(255,255,255,0.5); position:absolute; top:0; left:0; width:100%; height:100%;",
      "background: #FFFFFF50; position:relative; width:100%; height:100%;",
      "background: rgba(255,255,255,0.5); display:inline-block;",
      "background: transparent; opacity: 0.5;",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: rgba с alpha=0.5 создаёт полупрозрачный белый, absolute накрывает весь элемент.",
      "#FFFFFF50 означает похожий, но shorthand с alpha не везде поддерживается; relative не накроет дочерние.",
      "display:inline-block не растянет на весь элемент.",
      "transparent не даст белого перекрытия.",
    ],
    moduleId: "css",
    sectionTitle: "Блочная модель и позиционирование элементов",
    topic: "css_box_model",
  },
  {
    id: "css_box_model_96",
    title: "Как скрыть скроллбар, сохранив возможность прокрутки?",
    options: [
      "overflow: hidden;",
      "overflow: auto; scrollbar-width: none; -ms-overflow-style: none;",
      "display: none;",
      "visibility: hidden;",
    ],
    correctAnswers: [1],
    descriptions: [
      "overflow:hidden убирает прокрутку вовсе.",
      "Правильно: специальные свойства убирают скроллбар, оставляя прокрутку.",
      "display:none убирает элемент полностью.",
      "visibility:hidden скрывает содержимое, не только скроллбар.",
    ],
    moduleId: "css",
    sectionTitle: "Блочная модель и позиционирование элементов",
    topic: "css_box_model",
  },
  {
    id: "css_box_model_97",
    title: "Что делает pointer-events: none; при наличии opacity?",
    options: [
      "Делает элемент полупрозрачным",
      "Отключает события клика по элементу",
      "Скрывает элемент",
      "Увеличивает z-index",
    ],
    correctAnswers: [1],
    descriptions: [
      "opacity управляет прозрачностью, а не pointer-events.",
      "Правильно: pointer-events:none отключает все события указателя (клик, hover).",
      "display или visibility скрывают, pointer-events нет.",
      "z-index не меняется при pointer-events.",
    ],
    moduleId: "css",
    sectionTitle: "Блочная модель и позиционирование элементов",
    topic: "css_box_model",
  },
  {
    id: "css_box_model_98",
    title: "Как задать фон элемента с плавным переходом opacity при наведении?",
    options: [
      "background: rgba(0,0,0,0.5); transition: opacity 0.3s; &:hover { opacity: 1; }",
      "background-opacity: 0.5; transition: bg 0.3s; &:hover { background-opacity: 1; }",
      "background: #000; transition: background 0.3s; &:hover { background: #000; }",
      "background: rgba(0,0,0,0.5); &:hover { opacity: 1; }",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: background в RGBA и transition:opacity анимирует прозрачность.",
      "background-opacity не является валидным свойством.",
      "transition:background не изменит прозрачность, а цвет.",
      "transition отсутствует, поэтому не будет плавного перехода.",
    ],
    moduleId: "css",
    sectionTitle: "Блочная модель и позиционирование элементов",
    topic: "css_box_model",
  },
  {
    id: "css_box_model_99",
    title: "Как задать прокрутку только по горизонтали?",
    options: [
      "overflow-x: scroll; overflow-y: hidden;",
      "overflow: scroll-x;",
      "overflow: hidden; scroll-x: auto;",
      "overflow-y: scroll; overflow-x: hidden;",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: overflow-x контролирует горизонтальный скролл, overflow-y отключает вертикальный.",
      "overflow: scroll-x не является правильным синтаксисом.",
      "scroll-x не существует.",
      "swap направлений: этот код даёт вертикальный скролл, а не горизонтальный.",
    ],
    moduleId: "css",
    sectionTitle: "Блочная модель и позиционирование элементов",
    topic: "css_box_model",
  },
  {
    id: "css_box_model_100",
    title:
      "Что делает backdrop-filter: blur(10px); при наличии полупрозрачного фона?",
    options: [
      "Размывает сам элемент на 10px",
      "Размывает фон позади элемента на 10px",
      "Сглаживает края элемента",
      "Добавляет тень в 10px",
    ],
    correctAnswers: [1],
    descriptions: [
      "filter:blur размывает содержимое самого элемента, а не фон позади.",
      "Правильно: backdrop-filter применяет эффект к тому, что позади элемента (при наличии прозрачности).",
      "backdrop-filter не сглаживает края, а размывает фон.",
      "box-shadow добавляет тень, а не backdrop-filter.",
    ],
    moduleId: "css",
    sectionTitle: "Блочная модель и позиционирование элементов",
    topic: "css_box_model",
  },
];
