export const cssBlockModelQuestions = [
  {
    id: "css_block_model_1",
    title: "Какое свойство задаёт внешний отступ элемента?",
    options: ["padding", "margin", "border", "gap"],
    correctAnswers: [1],
    descriptions: [
      "padding задаёт внутренний отступ, а не внешний.",
      "Правильно: margin управляет внешними отступами вокруг элемента.",
      "border создаёт границу, но не отступ.",
      "gap используется для промежутков в flex/grid, а не для внешних отступов.",
    ],
    moduleId: "css",
    sectionTitle: "Стилизация  блоков",
    topic: "css_block",
  },
  {
    id: "css_block_model_2",
    title: "Как задать одинаковые отступы по всем сторонам в 20px?",
    options: [
      "padding: 20px 0 0 0;",
      "margin: 20px;",
      "padding: 0 20px 20px 20px;",
      "margin: 20px 20px;",
    ],
    correctAnswers: [1],
    descriptions: [
      "padding:20px 0 0 0 задаёт отступ только сверху.",
      "Правильно: margin:20px; применяет 20px ко всем четырём сторонам.",
      "padding:0 20px 20px 20px задаёт разные значения, а не одинаковые.",
      "margin:20px 20px задаёт 20px сверху/снизу и 20px слева/справа, но это не единичное значение для всех сторон.",
    ],
    moduleId: "css",
    sectionTitle: "Стилизация  блоков",
    topic: "css_block",
  },
  {
    id: "css_block_model_3",
    title:
      "В каком порядке задаются значения в shorthand margin: top right bottom left;?",
    options: [
      "top, left, bottom, right",
      "right, bottom, left, top",
      "top, right, bottom, left",
      "bottom, left, top, right",
    ],
    correctAnswers: [2],
    descriptions: [
      "Неверно: это порядок top, left, bottom, right.",
      "Неверно: это зеркальный порядок, а не стандартный.",
      "Правильно: сокращённая запись принимает значения в порядке верх, право, низ, лево.",
      "Неверно: это не соответствует ни одному варианту.",
    ],
    moduleId: "css",
    sectionTitle: "Стилизация  блоков",
    topic: "css_block",
  },
  {
    id: "css_block_model_4",
    title: "Что произойдёт при margin: 10px 20px;?",
    options: [
      "10px сверху/снизу, 20px слева/справа",
      "10px слева/справа, 20px сверху/снизу",
      "10px всем сторонам, 20px игнорируется",
      "margin:20px; будет применён",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: при двухзначной записи первое значение — сверху и снизу, второе — слева и справа.",
      "Неверно: это обратный порядок.",
      "Неверно: оба значения учитываются.",
      "Неверно: второе значение не игнорируется.",
    ],
    moduleId: "css",
    sectionTitle: "Стилизация  блоков",
    topic: "css_block",
  },
  {
    id: "css_block_model_5",
    title: "Какой эффект у отрицательного margin?",
    options: [
      "Увеличивает пространство за границы",
      "Накладывает элементы друг на друга, уменьшая пространство",
      "Увеличивает padding",
      "Превращает margin в padding",
    ],
    correctAnswers: [1],
    descriptions: [
      "Неверно: отрицательный margin не увеличивает пространство.",
      "Правильно: отрицательные значения margin сдвигают элементы внутрь, уменьшая расстояние или заставляя перекрывать.",
      "padding не изменяется отрицательным margin.",
      "margin остаётся margin, padding не затрагивается.",
    ],
    moduleId: "css",
    sectionTitle: "Стилизация  блоков",
    topic: "css_block",
  },
  {
    id: "css_block_model_6",
    title: "Как задать внутренний отступ слева в 15px и справа в 5px?",
    options: [
      "padding: 0 5px 0 15px;",
      "padding-left:15px; padding-right:5px;",
      "padding: 15px 5px;",
      "padding: 5px 15px;",
    ],
    correctAnswers: [1],
    descriptions: [
      "padding:0 5px 0 15px; задаёт именно то, но сокращённая запись с двумя значениями проще.",
      "Правильно: указаны отдельно свойства padding-left и padding-right.",
      "padding:15px 5px; задаёт 15px сверху/снизу, 5px слева/справа.",
      "padding:5px 15px; задаёт 5px сверху/снизу, 15px слева/справа.",
    ],
    moduleId: "css",
    sectionTitle: "Стилизация  блоков",
    topic: "css_block",
  },
  {
    id: "css_block_model_7",
    title: "Что означает margin: 10px 20px 30px;?",
    options: [
      "top 10px, right/left 20px, bottom 30px",
      "top/bottom 10px, left/right 20px, 30px игнорируется",
      "top 10px, right 20px, bottom 30px, left 20px",
      "все стороны 10px, кроме bottom",
    ],
    correctAnswers: [2],
    descriptions: [
      "Правильно: при трёхзначной записи порядок: top, right/left, bottom. Здесь right и left оба 20px.",
      "Неверно: bottom не игнорируется.",
      "Неверно: это не правило;",
      "Неверно: left не равен 10px.",
    ],
    moduleId: "css",
    sectionTitle: "Стилизация  блоков",
    topic: "css_block",
  },
  {
    id: "css_block_model_8",
    title:
      "Какой синтаксис задаёт одинаковый vertical padding и разный horizontal padding?",
    options: [
      "padding: 10px 20px 10px 20px;",
      "padding: 10px 20px;",
      "padding: 20px 10px;",
      "padding: 10px;",
    ],
    correctAnswers: [1],
    descriptions: [
      "Это задаёт разные значения, а не одинаковые верт/гор.",
      "Правильно: сокращённая запись pad:вертальный горизонтальный: 10px сверху/снизу и 20px слева/справа.",
      "padding:20px 10px задаёт 20px сверху/снизу, 10px слева/справа — не тот порядок.",
      "padding:10px задаёт по 10px ко всем сторонам.",
    ],
    moduleId: "css",
    sectionTitle: "Стилизация  блоков",
    topic: "css_block",
  },
  {
    id: "css_block_model_9",
    title:
      "Какой эффект у свойства padding при задании box-sizing: border-box;?",
    options: [
      "padding добавляется к width/height",
      "padding вычитается из content area",
      "padding преобразуется в margin",
      "padding удаляется",
    ],
    correctAnswers: [1],
    descriptions: [
      "В border-box padding не увеличивает общие размеры, он вычитается из области содержимого.",
      "Правильно: при border-box внутренний отступ учитывается внутри заданного размера, уменьшая area для контента.",
      "padding остаётся padding, не превращается в margin.",
      "padding не удаляется.",
    ],
    moduleId: "css",
    sectionTitle: "Стилизация  блоков",
    topic: "css_block",
  },
  {
    id: "css_block_model_10",
    title: "Что такое margin collapsing?",
    options: [
      "Складирование padding между элементами",
      "Объединение вертикальных внешних отступов соседних блоков",
      "Смешивание border между двумя элементами",
      "Уменьшение margin при overflow",
    ],
    correctAnswers: [1],
    descriptions: [
      "padding не складируется.",
      "Правильно: когда два смежных блока имеют вертикальные margin, между ними остаётся только максимум из этих значений.",
      "border не участвует в collapsing margin.",
      "overflow не влияет на collapse margin напрямую.",
    ],
    moduleId: "css",
    sectionTitle: "Стилизация  блоков",
    topic: "css_block",
  },
  {
    id: "css_block_model_11",
    title:
      "Как предотвратить схлопывание margin между родителем и первым дочерним элементом?",
    options: [
      "Задать padding-top родителю",
      "Задать border-top родителю",
      "Задать overflow: hidden родителю",
      "Любой из перечисленных",
    ],
    correctAnswers: [3],
    descriptions: [
      "Правильно: padding-top родителя создаёт новый контекст и предотвращает схлопывание.",
      "Правильно: border-top тоже предотвращает схлопывание.",
      "Правильно: overflow:hidden создаёт блок-формирующий контекст, прерывая collapse.",
      "Все перечисленные способы работают.",
    ],
    moduleId: "css",
    sectionTitle: "Стилизация  блоков",
    topic: "css_block",
  },
  {
    id: "css_block_model_12",
    title:
      "Что будет, если задать margin: auto; блочному элементу с фиксированной шириной?",
    options: [
      "Элемент растянется на всю ширину контейнера",
      "Элемент будет центрирован по горизонтали",
      "margin сбросится в 0",
      "Элемент исчезнет",
    ],
    correctAnswers: [1],
    descriptions: [
      "margin:auto не растягивает элемент, а центрирует.",
      "Правильно: auto слева и справа, фиксированная ширина, элемент центрируется.",
      "margin:auto не сбрасывается в 0.",
      "Элемент остаётся видимым.",
    ],
    moduleId: "css",
    sectionTitle: "Стилизация  блоков",
    topic: "css_block",
  },
  {
    id: "css_block_model_13",
    title: "Как задать процентный margin: 10%; чему он будет равен?",
    options: [
      "10% от высоты родителя",
      "10% от ширины родителя",
      "10% от ширины элемента",
      "10% от высоты элемента",
    ],
    correctAnswers: [1],
    descriptions: [
      "Процентный vertical margin считается от ширины родительского блока.",
      "Правильно: margin (%) всегда берётся от ширины родителя, независимо от ориентации.",
      "Не от ширины самого элемента.",
      "Не от высоты элемента.",
    ],
    moduleId: "css",
    sectionTitle: "Стилизация  блоков",
    topic: "css_block",
  },
  {
    id: "css_block_model_14",
    title: "Какой итог у padding: 10% on элемент с width: 200px;",
    options: [
      "padding равен 20px",
      "padding равен 10px",
      "padding равен 200px",
      "padding равен 2px",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: 10% от width (200px) = 20px.",
      "Неверно: 10px = 5%.",
      "200px — это 100%.",
      "2px — это 1%.",
    ],
    moduleId: "css",
    sectionTitle: "Стилизация  блоков",
    topic: "css_block",
  },
  {
    id: "css_block_model_15",
    title: "Какой эффект у padding: 0 auto;?",
    options: [
      "Устанавливает авто-отступы сверху/снизу",
      "Не является валидным: auto не применим к padding",
      "Устанавливает автоматический padding для всех сторон",
      "center-align оказывает эффект",
    ],
    correctAnswers: [1],
    descriptions: [
      "padding:auto не применяется к вертикальным padding.",
      "Правильно: padding не принимает значение auto, это значение для margin.",
      "padding:auto не задаёт отступ.",
      "padding не центрирует, для этого margin:auto.",
    ],
    moduleId: "css",
    sectionTitle: "Стилизация  блоков",
    topic: "css_block",
  },
  {
    id: "css_block_model_16",
    title: "Что делает свойство padding-inline: 10px;?",
    options: [
      "Задаёт 10px слева и справа в левосторонних языках",
      "Задаёт 10px сверху и снизу",
      "Задаёт 10px только слева",
      "Не является валидным свойством",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: padding-inline применяется к стартовой и конечной стороне блока, обычно слева/справа.",
      "padding-block отвечает за вертикальные отступы.",
      "padding-inline задаёт обе inline-стороны, а не одну.",
      "padding-inline — валидное свойство в современных CSS.",
    ],
    moduleId: "css",
    sectionTitle: "Стилизация  блоков",
    topic: "css_block",
  },
  {
    id: "css_block_model_17",
    title: "Как задать отступ сверху 20px и снизу 10px без изменения боковых?",
    options: [
      "margin: 20px 0 10px 0;",
      "margin: 20px 10px;",
      "margin-top:20px; margin-bottom:10px;",
      "Любой из 1 и 3",
    ],
    correctAnswers: [3],
    descriptions: [
      "margin:20px 0 10px 0; ставит 20px сверху, 10px снизу, боковые 0.",
      "margin:20px 10px; задаёт 20px сверху/снизу и 10px слева/справа.",
      "margin-top и margin-bottom задают нужные отступы независимо от боковых.",
      "Правильно: оба варианта (1 и 3) корректны.",
    ],
    moduleId: "css",
    sectionTitle: "Стилизация  блоков",
    topic: "css_block",
  },
  {
    id: "css_block_model_18",
    title:
      "Как задать padding для вертикали 5px и горизонтали 10px с учётом логического направления (inline/block)?",
    options: [
      "padding: 5px 10px;",
      "padding-inline: 10px; padding-block: 5px;",
      "padding-left:10px; padding-top:5px;",
      "padding-horizontal:10px; padding-vertical:5px;",
    ],
    correctAnswers: [1],
    descriptions: [
      "padding:5px 10px задаёт верт/гор, но не учитывает направление письма.",
      "Правильно: padding-inline и padding-block учитывают направление текста.",
      "Заданы конкретные стороны, а не логические направления.",
      "padding-horizontal/vertical не являются валидными.",
    ],
    moduleId: "css",
    sectionTitle: "Стилизация  блоков",
    topic: "css_block",
  },
  {
    id: "css_block_model_19",
    title: "Какой итог у `padding: 5px 10px 15px;`?",
    options: [
      "top 5px, right/left 10px, bottom 15px",
      "top/bottom 5px, left/right 10px",
      "top 5px, right 10px, bottom 15px, left 10px",
      "all sides 5px, ignoring other values",
    ],
    correctAnswers: [2],
    descriptions: [
      "Неверно: три значения означают top, right/left, bottom.",
      "Неверно: это для двухзначной записи.",
      "Правильно: три значения => top 5px, right 10px, bottom 15px, left 10px.",
      "Неверно: другие значения учитываются.",
    ],
    moduleId: "css",
    sectionTitle: "Стилизация  блоков",
    topic: "css_block",
  },
  {
    id: "css_block_model_20",
    title:
      "Какое свойство предотвращает схлопывание margin у соседних элементов?",
    options: ["padding", "border", "overflow", "box-shadow"],
    correctAnswers: [2],
    descriptions: [
      "padding не влияет на схлопывание margin между элементами.",
      "border также предотвращает collapse margin, но вопрос в общем случае.",
      "Правильно: overflow (например, hidden) создаёт новый контекст и предотвращает схлопывание.",
      "box-shadow не влияет на схлопывание margin.",
    ],
    moduleId: "css",
    sectionTitle: "Стилизация  блоков",
    topic: "css_block",
  },
  {
    id: "css_block_model_21",
    title: "Какое свойство задаёт толщину рамки вокруг элемента?",
    options: ["border-width", "border-style", "border-color", "border-radius"],
    correctAnswers: [0],
    descriptions: [
      "border-style задаёт тип линии, а не толщину.",
      "border-width правильно задаёт толщину рамки.",
      "border-color задаёт цвет, а не толщину.",
      "border-radius задаёт скругление, не толщину.",
    ],
    moduleId: "css",
    sectionTitle: "Стилизация  блоков",
    topic: "css_block",
  },
  {
    id: "css_block_model_22",
    title: "Какое значение border-style создаёт сплошную линию?",
    options: ["dashed", "solid", "dotted", "double"],
    correctAnswers: [1],
    descriptions: [
      "dashed создаёт пунктирную линию.",
      "Правильно: solid — сплошная линия.",
      "dotted создаёт точечную линию.",
      "double создаёт двойную линию.",
    ],
    moduleId: "css",
    sectionTitle: "Стилизация  блоков",
    topic: "css_block",
  },
  {
    id: "css_block_model_23",
    title: "Как задать красную рамку толщиной 2px с двоичным стилем (double)?",
    options: [
      "border: 2px double red;",
      "border: red double 2px;",
      "border: double 2px red;",
      "border: 2px red double;",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: сокращённая запись border: [ширина] [стиль] [цвет].",
      "Неправильно: порядок должен быть ширина, стиль, цвет.",
      "Неправильно: порядок неверен.",
      "Неправильно: порядок неверен.",
    ],
    moduleId: "css",
    sectionTitle: "Стилизация  блоков",
    topic: "css_block",
  },
  {
    id: "css_block_model_24",
    title: "Какое свойство используется для скругления углов рамки?",
    options: [
      "border-curve",
      "border-radius",
      "corner-radius",
      "radius-border",
    ],
    correctAnswers: [1],
    descriptions: [
      "border-curve не существует в CSS.",
      "Правильно: border-radius задаёт скругление углов.",
      "corner-radius не является валидным свойством.",
      "radius-border не существует.",
    ],
    moduleId: "css",
    sectionTitle: "Стилизация  блоков",
    topic: "css_block",
  },
  {
    id: "css_block_model_25",
    title: "Как задать скругление только для верхнего левого угла (10px)?",
    options: [
      "border-top-left-radius: 10px;",
      "border-radius: 0 10px 0 0;",
      "border-tl-radius: 10px;",
      "corner-top-left-radius: 10px;",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: border-top-left-radius задаёт скругление одного угла.",
      "Неправильно: порядок значений border-radius отличается.",
      "border-tl-radius не является валидным.",
      "corner-top-left-radius не существует.",
    ],
    moduleId: "css",
    sectionTitle: "Стилизация  блоков",
    topic: "css_block",
  },
  {
    id: "css_block_model_26",
    title: "Какой синтаксис задаёт одинаковое скругление 5px для всех углов?",
    options: [
      "border-radius: 5px;",
      "border-radius: 5px 5px;",
      "border-radius: 5px 5px 5px;",
      "border-radius: 5px 5px 5px 5px;",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: одно значение распространяется на все четыре угла.",
      "Неверно: два значения задают vertical/horizontal скругления.",
      "Неверно: три значения задают top-left, top-right/bottom-left, bottom-right.",
      "Правильно, но достаточно одного значения — это эквивалентно.",
    ],
    moduleId: "css",
    sectionTitle: "Стилизация  блоков",
    topic: "css_block",
  },
  {
    id: "css_block_model_27",
    title: "Какой эффект у border-radius: 50%;?",
    options: [
      "Создаёт квадратный элемент",
      "Создаёт кружок при равных ширине и высоте",
      "Снижает прозрачность рамки",
      "Меняет цвет рамки на градиент",
    ],
    correctAnswers: [1],
    descriptions: [
      "border-radius не делает элемент квадратным.",
      "Правильно: при совпадающих width и height создаёт круг.",
      "opacity управляет прозрачностью, а не border-radius.",
      "Градиент задаётся background-image, а не border-radius.",
    ],
    moduleId: "css",
    sectionTitle: "Стилизация  блоков",
    topic: "css_block",
  },
  {
    id: "css_block_model_28",
    title: "Как задать фоновое изображение, повторяющееся по горизонтали?",
    options: [
      "background-repeat: repeat-x;",
      "background-repeat: repeat-y;",
      "background-repeat: no-repeat;",
      "background-repeat: repeat;",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: repeat-x повторяет фон по горизонтали.",
      "repeat-y повторяет по вертикали.",
      "no-repeat не повторяет фон.",
      "repeat повторяет по обеим осям.",
    ],
    moduleId: "css",
    sectionTitle: "Стилизация  блоков",
    topic: "css_block",
  },
  {
    id: "css_block_model_29",
    title: "Как задать цвет фона элемента в синий (#0000FF)?",
    options: [
      "background: #0000FF;",
      "background-color: blue;",
      "background-color: #0000FF;",
      "Все варианты верны",
    ],
    correctAnswers: [3],
    descriptions: [
      "background: #0000FF правильно задаёт цвет фона.",
      "background-color: blue задаёт CSS-имя цвета.",
      "background-color: #0000FF задаёт HEX-значение.",
      "Все перечисленные способы корректны.",
    ],
    moduleId: "css",
    sectionTitle: "Стилизация  блоков",
    topic: "css_block",
  },
  {
    id: "css_block_model_30",
    title: "Какой результат у background-size: cover;?",
    options: [
      "Фон растягивается, сохраняя пропорции и полностью закрывает элемент",
      "Фон располагается в центре без масштабирования",
      "Фон растягивается по ширине, не сохраняя пропорции",
      "Фон разбивается на плитки",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: cover масштабирует фоновое изображение так, чтобы закрыть весь элемент.",
      "background-position контролирует выравнивание, а не размер.",
      "contain масштабирует по большей стороне, но сохраняет пропорции без полного покрытия.",
      "repeat разбивает фон на плитки.",
    ],
    moduleId: "css",
    sectionTitle: "Стилизация  блоков",
    topic: "css_block",
  },
  {
    id: "css_block_model_31",
    title: "Как задать позицию фонового изображения в правом верхнем углу?",
    options: [
      "background-position: top right;",
      "background-position: right top;",
      "background-position: 0% 0%;",
      "background-position: center;",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: top right ставит фон в правый верхний угол.",
      "right top тоже работает (перестановка аналогична), но standard – top right.",
      "0% 0% ставит фон в левый верхний угол.",
      "center центрирует фон.",
    ],
    moduleId: "css",
    sectionTitle: "Стилизация  блоков",
    topic: "css_block",
  },
  {
    id: "css_block_model_32",
    title:
      "Какое свойство задаёт фон без изображения, используя цвет и URL вместе?",
    options: [
      "background-image: linear-gradient(#fff, #000);",
      "background: url('img.jpg') no-repeat #f0f0f0;",
      "background-color: #f0f0f0 url('img.jpg');",
      "background-url: img.jpg #f0f0f0;",
    ],
    correctAnswers: [1],
    descriptions: [
      "linear-gradient задаёт градиент, а не URL + цвет.",
      "Правильно: background шорткат объединяет цвет, изображение и repeat.",
      "background-color не принимает URL.",
      "background-url не существует.",
    ],
    moduleId: "css",
    sectionTitle: "Стилизация  блоков",
    topic: "css_block",
  },
  {
    id: "css_block_model_33",
    title:
      "Как задать фон так, чтобы он не повторялся и был фиксирован при прокрутке?",
    options: [
      "background: url('img.jpg') no-repeat fixed;",
      "background: url('img.jpg') repeat scroll;",
      "background: url('img.jpg') scroll no-repeat;",
      "background: url('img.jpg') no-repeat;",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: fixed фиксирует фон, no-repeat запрещает повторение.",
      "repeat scroll повторяет фон и прокручивает его вместе со страницей.",
      "scroll отвечает за поведение при прокрутке, но не фиксирует фон.",
      "no-repeat запрещает повторение, но фон не фиксирован.",
    ],
    moduleId: "css",
    sectionTitle: "Стилизация  блоков",
    topic: "css_block",
  },
  {
    id: "css_block_model_34",
    title: "Что делает свойство background-clip: content-box;?",
    options: [
      "Обрезает фон по границам padding",
      "Обрезает фон по границам контента",
      "Обрезает фон по границам border",
      "Не влияет на фон",
    ],
    correctAnswers: [1],
    descriptions: [
      "padding-box обрезает по padding.",
      "Правильно: content-box заставляет фон виден только внутри области содержимого.",
      "border-box обрезает по краю рамки.",
      "background-clip всегда влияет на отображение фона.",
    ],
    moduleId: "css",
    sectionTitle: "Стилизация  блоков",
    topic: "css_block",
  },
  {
    id: "css_block_model_35",
    title:
      "Как задать цвет рамки и фон разными свойствами (пример: красная рамка, жёлтый фон)?",
    options: [
      "border-color: red; background-color: yellow;",
      "border: red; background: yellow;",
      "border-style: red; background-style: yellow;",
      "border: 1px solid red background-color: yellow;",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: border-color задаёт цвет рамки, background-color — цвет фона.",
      "border:red — недостаточно, нужен стиль и толщина.",
      "border-style — задаёт стиль, а не цвет.",
      "Неверный синтаксис — пропущена точка с запятой.",
    ],
    moduleId: "css",
    sectionTitle: "Стилизация  блоков",
    topic: "css_block",
  },
  {
    id: "css_block_model_36",
    title: "Как задать рамку только снизу толщиной 3px и синего цвета?",
    options: [
      "border-bottom: 3px solid blue;",
      "border: bottom 3px solid blue;",
      "border-bottom-width: 3px; border-color: blue;",
      "border-bottom-style: solid; border-width: 3px; border-color: blue;",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: сокращённая запись border-bottom: [ширина] [тип] [цвет].",
      "Неверный синтаксис: border не принимает сторону.",
      "Нужно дополнительно указать border-bottom-style.",
      "Непростой вариант; не указан side для width.",
    ],
    moduleId: "css",
    sectionTitle: "Стилизация  блоков",
    topic: "css_block",
  },
  {
    id: "css_block_model_37",
    title: "Что задаёт свойство background-origin: border-box;?",
    options: [
      "Начальную точку фона по краю рамки",
      "Начальную точку фона по краю padding",
      "Начальную точку фона по краю контента",
      "Убирает фон",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: border-box заставляет фон начинаться за пределами рамки.",
      "padding-box задаёт по внутренней границе padding.",
      "content-box задаёт по краю контента.",
      "background-origin не удаляет фон.",
    ],
    moduleId: "css",
    sectionTitle: "Стилизация  блоков",
    topic: "css_block",
  },
  {
    id: "css_block_model_38",
    title: "Как задать прозрачный фон с 50% непрозрачности?",
    options: [
      "background-color: rgba(0, 0, 0, 0.5);",
      "background-color: #0000FF50;",
      "background-opacity: 0.5;",
      "opacity: background 0.5;",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: rgba позволяет задать прозрачность фона.",
      "#0000FF50 — shorthand HEX с прозрачностью, но не все браузеры поддерживают.",
      "background-opacity не существует.",
      "opacity управляет прозрачностью всего элемента, а не только фона.",
    ],
    moduleId: "css",
    sectionTitle: "Стилизация  блоков",
    topic: "css_block",
  },
  {
    id: "css_block_model_39",
    title: "Как задать несколько фоновых изображений через shorthand?",
    options: [
      "background: url('a.png'), url('b.png');",
      "background-image: url('a.png') & url('b.png');",
      "background: url('a.png' 'b.png');",
      "background: img(a.png), img(b.png);",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: через запятую перечисляются URL.",
      "& не используется для разделения URL.",
      "Неверный синтаксис.",
      "Неверный синтаксис.",
    ],
    moduleId: "css",
    sectionTitle: "Стилизация  блоков",
    topic: "css_block",
  },
  {
    id: "css_block_model_40",
    title: "Как задать плавный переход между двумя цветами фона (градиент)?",
    options: [
      "background: linear-gradient(to right, red, blue);",
      "background: gradient(red, blue);",
      "background-gradient: red to blue;",
      "background: url('gradient(red,blue)');",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: linear-gradient задаёт плавный переход от red к blue.",
      "Неправильный синтаксис — gradient() не работает.",
      "background-gradient не является валидным свойством.",
      "url используется для изображений, а не для градиентов.",
    ],
    moduleId: "css",
    sectionTitle: "Стилизация  блоков",
    topic: "css_block",
  },
];
