export const cssImagesBackgroundQuestions = [
  {
    id: "css_images_1",
    title: "Как задать фоновое изображение для элемента?",
    options: [
      "background-image: url('image.jpg');",
      "background: 'image.jpg';",
      "img-background: image.jpg;",
      "bg-image: url(image.jpg);",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: background-image вместе с url() задаёт фоновое изображение.",
      "background: 'image.jpg' — неверный синтаксис, нужно url().",
      "img-background не является валидным свойством CSS.",
      "bg-image не поддерживается; правильное свойство background-image.",
    ],
    moduleId: "css",
    sectionTitle: "Работа с изображениями и фоном",
    topic: "css_images",
  },
  {
    id: "css_images_2",
    title: "Как отключить повторение фонового изображения?",
    options: [
      "background-repeat: no-repeat;",
      "background-repeat: none;",
      "background: repeat off;",
      "background-repeat: 0;",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: background-repeat: no-repeat отключает повторение.",
      "no-repeat — верное значение, а none — не существует.",
      "repeat off — неверный синтаксис.",
      "numeric значение (0) не применяется для background-repeat.",
    ],
    moduleId: "css",
    sectionTitle: "Работа с изображениями и фоном",
    topic: "css_images",
  },
  {
    id: "css_images_3",
    title: "Как задать фоновый цвет элемента?",
    options: [
      "background-color: #ff0000;",
      "bgcolor: red;",
      "color: #ff0000;",
      "background: color red;",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: background-color задаёт фоновый цвет.",
      "bgcolor не является CSS-свойством (HTML-атрибут).",
      "color задаёт цвет текста, а не фона.",
      "background: color red — неверный синтаксис.",
    ],
    moduleId: "css",
    sectionTitle: "Работа с изображениями и фоном",
    topic: "css_images",
  },
  {
    id: "css_images_4",
    title:
      "Как задать размер фонового изображения на всю ширину и высоту элемента?",
    options: [
      "background-size: cover;",
      "background-size: contain;",
      "background-scale: 100%;",
      "background-size: 100% 100%;",
    ],
    correctAnswers: [3],
    descriptions: [
      "cover масштабирует, сохраняя пропорции, может обрезать.",
      "contain масштабирует, сохраняя пропорции, без обрезки.",
      "background-scale не существует.",
      "Правильно: background-size:100% 100% растягивает на весь элемент.",
    ],
    moduleId: "css",
    sectionTitle: "Работа с изображениями и фоном",
    topic: "css_images",
  },
  {
    id: "css_images_5",
    title: "Чем отличается background-size: cover от contain?",
    options: [
      "cover обрезает для заполнения, contain полностью показывает изображение",
      "contain обрезает, cover полностью показывает",
      "cover повторяет изображение, contain отключает повтор",
      "Нет отличий, оба идентичны",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: cover заполняет весь элемент с возможным обрезом, contain показывает полностью без обреза.",
      "Перепутаны определения.",
      "cover/contain управляют масштабом, не повторением.",
      "Это разные значения с разным поведением.",
    ],
    moduleId: "css",
    sectionTitle: "Работа с изображениями и фоном",
    topic: "css_images",
  },
  {
    id: "css_images_6",
    title: "Как задать позицию фонового изображения в правом нижнем углу?",
    options: [
      "background-position: right bottom;",
      "background-position: 100% 100%;",
      "background-position: bottom right;",
      "Все варианты верны",
    ],
    correctAnswers: [3],
    descriptions: [
      "Правильно: любые варианты (right bottom или 100% 100%) задают правый нижний угол.",
      "100% 100% соответствует правому нижнему углу.",
      "bottom right — эквивалентно right bottom.",
      "Все перечисленные синтаксисы корректны.",
    ],
    moduleId: "css",
    sectionTitle: "Работа с изображениями и фоном",
    topic: "css_images",
  },
  {
    id: "css_images_7",
    title: "Как задать несколько фоновых изображений для одного элемента?",
    options: [
      "background-image: url('a.png'), url('b.png');",
      "background: url('a.png') + url('b.png');",
      "background-images: url(a.png), url(b.png);",
      "background: images('a.png','b.png');",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: перечисление через запятую задаёт несколько изображений.",
      "'+' не используется для перечисления фоновых изображений.",
      "background-images не является валидным.",
      "background: images() — неверный синтаксис.",
    ],
    moduleId: "css",
    sectionTitle: "Работа с изображениями и фоном",
    topic: "css_images",
  },
  {
    id: "css_images_8",
    title: "Как задать фоновое изображение, которое фиксируется при прокрутке?",
    options: [
      "background-attachment: fixed;",
      "background-position: fixed;",
      "background-clip: fixed;",
      "background-size: fixed;",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: background-attachment: fixed фиксирует фон в окне браузера.",
      "background-position управляет позиционированием, не прикреплением.",
      "background-clip контролирует область отрисовки, не фиксацию.",
      "background-size управляет размером, а не фиксацией.",
    ],
    moduleId: "css",
    sectionTitle: "Работа с изображениями и фоном",
    topic: "css_images",
  },
  {
    id: "css_images_9",
    title: "Как сделать фон прозрачным поверх фонового цвета?",
    options: [
      "background: rgba(0,0,0,0.5) url('image.png');",
      "background: transparent url('image.png');",
      "background-color: transparent; background-image: url('image.png');",
      "Все варианты верны",
    ],
    correctAnswers: [3],
    descriptions: [
      "Правильно: rgba задаёт полупрозрачный цвет, за ним указывают изображение.",
      "transparent не даёт полупрозрачности, просто прозрачность.",
      "transparent + url() тоже работает, но не показывает полупрозрачный цвет поверх.",
      "Каждый вариант корректен в своём контексте.",
    ],
    moduleId: "css",
    sectionTitle: "Работа с изображениями и фоном",
    topic: "css_images",
  },
  {
    id: "css_images_10",
    title: "Как задать фоновое изображение без смешения с фоновым цветом?",
    options: [
      "background-blend-mode: normal;",
      "background: no-blend url('img.jpg');",
      "background: url('img.jpg') background-color;",
      "background-blend: none;",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: background-blend-mode: normal отключает смешение фонового цвета и изображения.",
      "no-blend не является корректным значением.",
      "Неверный синтаксис: порядок и комбинация свойств некорректны.",
      "background-blend не является валидным свойством.",
    ],
    moduleId: "css",
    sectionTitle: "Работа с изображениями и фоном",
    topic: "css_images",
  },
  {
    id: "css_images_11",
    title:
      "Как задать область показа фонового изображения, ограничив её элементом?",
    options: [
      "background-clip: content-box;",
      "background-clip: border-box;",
      "background-clip: padding-box;",
      "background-clip: local;",
    ],
    correctAnswers: [2],
    descriptions: [
      "content-box обрезает изображение по содержимому, но padding-box более распространён.",
      "border-box обрезает по границе элемента (включая бордеры).",
      "Правильно: padding-box обрезает фон по области внутри полей (padding).",
      "local работает только для градиентов, а не изображений.",
    ],
    moduleId: "css",
    sectionTitle: "Работа с изображениями и фоном",
    topic: "css_images",
  },
  {
    id: "css_images_12",
    title:
      "Какой синтаксис задаёт фоновое изображение и цвет вместе через shorthand?",
    options: [
      "background: #fff url('img.png') no-repeat center center;",
      "background: url('img.png') #fff no-repeat center center;",
      "background: #fff center center no-repeat url('img.png');",
      "Все варианты верны",
    ],
    correctAnswers: [3],
    descriptions: [
      "Правильно: порядок не важен при перечислении через shorthand, все варианты работают.",
      "Корректно использовать цвет до или после url().",
      "Шорткэт background допускает любую комбинацию упорядоченных значений.",
      "Любой из приведённых вариантов корректен.",
    ],
    moduleId: "css",
    sectionTitle: "Работа с изображениями и фоном",
    topic: "css_images",
  },
  {
    id: "css_images_13",
    title:
      "Как задать фон прокрутки с сохранением позиции при прокрутке содержимого?",
    options: [
      "background-attachment: fixed;",
      "background-attachment: scroll;",
      "background-attachment: local;",
      "background-attachment: inherit;",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: fixed фиксирует фон относительно окна браузера.",
      "scroll (по умолчанию) прокручивает фон вместе с содержимым.",
      "local привязывает фон к элементу с прокруткой, а не сохраняет позицию.",
      "inherit унаследует свойство у родителя, но не задаёт фиксированность.",
    ],
    moduleId: "css",
    sectionTitle: "Работа с изображениями и фоном",
    topic: "css_images",
  },
  {
    id: "css_images_14",
    title:
      "Как задать фоновое изображение, которое центрируется по горизонтали и вертикали?",
    options: [
      "background-position: center center;",
      "background-position: 50% 50%;",
      "background-position: center;",
      "Все варианты верны",
    ],
    correctAnswers: [3],
    descriptions: [
      "center center центрирует по обеим осям.",
      "50% 50% эквивалентно по центру по горизонтали и вертикали.",
      "center без указания второй координаты центрирует по горизонтали и вертикали по-умолчанию.",
      "Все перечисленные синтаксисы корректны.",
    ],
    moduleId: "css",
    sectionTitle: "Работа с изображениями и фоном",
    topic: "css_images",
  },
  {
    id: "css_images_15",
    title: "Как задать повтор фонового изображения только по горизонтали?",
    options: [
      "background-repeat: repeat-x;",
      "background-repeat: repeat-y;",
      "background-repeat: no-repeat;",
      "background-repeat: mirror;",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: repeat-x повторяет фон только по горизонтали.",
      "repeat-y повторяет только по вертикали.",
      "no-repeat отключает повтор вообще.",
      "mirror не является валидным значением.",
    ],
    moduleId: "css",
    sectionTitle: "Работа с изображениями и фоном",
    topic: "css_images",
  },
  {
    id: "css_images_16",
    title:
      "Как задать фоновое изображение, которое повторяется в обоих направлениях с шагом 20px?",
    options: [
      "background-repeat: space;",
      "background-repeat: round;",
      "background-repeat: repeat;",
      "background-repeat: no-repeat;",
    ],
    correctAnswers: [2],
    descriptions: [
      "space распределяет изображения с равными отступами, но шаг 20px не задаётся напрямую.",
      "round масштабирует изображение, чтобы поместилось целое число раз.",
      "Правильно: repeat повторяет с оригинальным шагом (20px задан в размере изображения).",
      "no-repeat отключает повтор.",
    ],
    moduleId: "css",
    sectionTitle: "Работа с изображениями и фоном",
    topic: "css_images",
  },
  {
    id: "css_images_17",
    title: "Как свойство background-origin влияет на фоновое изображение?",
    options: [
      "Определяет область, относительно которой располагается фон (border-box, padding-box, content-box)",
      "Устанавливает прозрачность изображения",
      "Задает отступы вокруг фона",
      "Определяет цвет фона",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: background-origin указывает, отсюда считать начало фоновой позиции.",
      "Прозрачность задаётся через rgba() или opacity.",
      "Отступы задаются padding, а не background-origin.",
      "Цвет фона задаётся background-color.",
    ],
    moduleId: "css",
    sectionTitle: "Работа с изображениями и фоном",
    topic: "css_images",
  },
  {
    id: "css_images_18",
    title: "Как задать прозрачный фон поверх фонового изображения?",
    options: [
      "Использовать rgba() в background-color поверх background-image",
      "background-opacity: 0.5;",
      "background: transparent-image;",
      "background-blend-mode: alpha;",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: задаётся фоновый цвет в rgba(..., alpha) и фон-изображение, например: background: rgba(0,0,0,0.5) url('img.png');",
      "background-opacity не является валидным свойством.",
      "transparent-image не является действительным значением.",
      "background-blend-mode управляет смешением, но не задаёт прозрачность.",
    ],
    moduleId: "css",
    sectionTitle: "Работа с изображениями и фоном",
    topic: "css_images",
  },
  {
    id: "css_images_19",
    title:
      "Как сделать фоновое изображение чередующимся зеркально при повторении?",
    options: [
      "background-repeat: repeat; background-image: url('img.png'); background-position: center; background-size: auto; background-repeat: repeat; background-origin: content-box; background-clip: content-box; background-attachment: scroll; background-color: transparent; background-blend-mode: normal; background-image: url('img.png'); background-repeat: repeat; background-size: auto; background-position: center; background-attachment: fixed; background-clip: padding-box; background-origin: border-box; background-repeat: space; background-blend-mode: multiply;",
      "background-repeat: repeat-y;",
      "background-repeat: repeat-x;",
      "background-repeat: space;",
    ],
    correctAnswers: [3],
    descriptions: [
      "round указывает на масштабирование, но mirror не является валидным значением.</p>",
      "repeat-y повторит только по вертикали, а не зеркально.",
      "repeat-x повторит по горизонтали, а не зеркально.",
      "space распределяет изображения с отступами, а не зеркально.",
    ],
    moduleId: "css",
    sectionTitle: "Работа с изображениями и фоном",
    topic: "css_images",
  },
  {
    id: "css_images_20",
    title:
      "Как задать фоновое изображение, чтобы оно было зафиксировано и занимало всю ширину?",
    options: [
      "background: url('img.jpg') no-repeat center center fixed; background-size: cover;",
      "background: url('img.jpg') fixed;",
      "background-image: fixed cover;",
      "background: cover fixed url('img.jpg');",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: shorthand background с fixed и background-size: cover масштабирует и фиксирует фон.",
      "Нужно указать no-repeat и позицию, а также cover для растяжения.",
      "Неверный синтаксис: нельзя комбинировать флаги и cover в background-image.",
      "Неправильный порядок shorthand, нужно указать url(), repeat, позицию, флаг fixed.",
    ],
    moduleId: "css",
    sectionTitle: "Работа с изображениями и фоном",
    topic: "css_images",
  },
  {
    id: "css_images_21",
    title:
      "Какой тег HTML следует использовать для важного контентного изображения, которое несет смысловую нагрузку?",
    options: [
      "<img>",
      "background-image",
      "<picture>",
      '<div style="background-image">',
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: <img> используется для семантических изображений, имеющих смысл и контентное значение.",
      "background-image не является тегом и не подходит для контентных изображений.",
      "<picture> может использоваться для адаптивных изображений, но основным семантическим тегом остается <img>.",
      "div с background-image не передает семантику изображения и не доступен для чтения скринридерами.",
    ],
    moduleId: "css",
    sectionTitle: "Работа с изображениями и фоном",
    topic: "css_images",
  },
  {
    id: "css_images_22",
    title: "Когда лучше использовать CSS background-image для изображения?",
    options: [
      "Когда изображение является декоративным",
      "Когда нужно передать альтернативный текст",
      "Когда важно SEO",
      "Когда нужно поддерживать задержку загрузки изображения",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: background-image подходит для декоративных изображений, которые не влияют на смысл контента.",
      "Альтернативный текст возможен только с <img> и alt-атрибутом, что нужно для доступности.",
      "SEO учитывает <img> с alt, а background-image не улучшает SEO.",
      "Задержку загрузки (lazy loading) можно применять к <img>, а к background-image – сложнее управлять.",
    ],
    moduleId: "css",
    sectionTitle: "Работа с изображениями и фоном",
    topic: "css_images",
  },
  {
    id: "css_images_23",
    title:
      "Какое преимущество <img> перед background-image в плане доступности?",
    options: [
      "Возможность указать alt-текст для скринридеров",
      "Автоматическое масштабирование по ширине",
      "Лучшее кэширование браузером",
      "Автоматическое позиционирование",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: alt-атрибут у <img> позволяет скринридерам озвучивать содержимое изображения.",
      "background-image можно масштабировать через CSS, но отсутствие alt ухудшает доступность.",
      "Кэширование зависит от настроек сервера и HTTP-заголовков, не от способа вставки.",
      "Позиционирование контролируется CSS для обоих методов.",
    ],
    moduleId: "css",
    sectionTitle: "Работа с изображениями и фоном",
    topic: "css_images",
  },
  {
    id: "css_images_24",
    title:
      "Какой способ более уместен, если нужно часто менять изображение через CSS классы?",
    options: [
      "background-image в CSS-классе",
      "<img> с динамическим src",
      "<picture> с медиа-запросами",
      "<svg> с изображением",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: background-image удобно менять через переключение классов без изменения HTML.",
      "Динамический src у <img> требует изменения атрибута в HTML или через JS.",
      "<picture> используется для адаптивных изображений, а не для простого переключения через классы.",
      "<svg> не относится к растровым фоновым изображениям и требует особой структуры.",
    ],
    moduleId: "css",
    sectionTitle: "Работа с изображениями и фоном",
    topic: "css_images",
  },
  {
    id: "css_images_25",
    title:
      "Что позволит легче контролировать позиционирование изображения поверх других элементов?",
    options: [
      "background-image с background-position",
      "<img> с absolute-позиционированием",
      "<picture> с CSS Grid",
      "<canvas> с рисованием",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: background-position вместе с background-size упрощает точное позиционирование фона внутри элемента.",
      "Абсолютное позиционирование <img> требует обертки и дополнительных CSS-свойств.",
      "<picture> не дает преимуществ в позиционировании по сравнению с background-image.",
      "<canvas> предназначен для программной графики, а не для статических фонов.",
    ],
    moduleId: "css",
    sectionTitle: "Работа с изображениями и фоном",
    topic: "css_images",
  },
  {
    id: "css_images_26",
    title:
      "В каком случае фонового изображения с помощью CSS может не хватить, а нужен именно <img>?",
    options: [
      "Нужно предоставить адаптивный srcset и разные форматы",
      "Нужно установить фон фиксированного цвета",
      "Нужно повторять изображение по обеим осям",
      "Нужно создать градиент поверх фона",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: <img> с srcset/picture поддерживает адаптивные изображения и WebP, лучше для экономии трафика.",
      "Фоновый цвет задается background-color без <img>.",
      "Фон можно повторять через background-repeat, без <img>.",
      "Градиенты накладываются через CSS поверх фонового изображения.",
    ],
    moduleId: "css",
    sectionTitle: "Работа с изображениями и фоном",
    topic: "css_images",
  },
  {
    id: "css_images_27",
    title:
      "Какой способ позволит изображению влиять на размер контейнера согласно относительно размера изображения?",
    options: [
      "<img> внутри контейнера",
      "background-image",
      '<div style="background-image"> без указания размеров',
      "<svg> фон",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: <img> по умолчанию задает размеры родительскому контейнеру, основываясь на естественном размере.",
      "background-image не влияет на размеры контейнера; нужно задавать width/height вручную.",
      "Без указания размеров div не подстроится под изображение, фон лишь заполняет контейнер.",
      "<svg>-фон тоже не задает размер контейнера; нужно явное позиционирование.",
    ],
    moduleId: "css",
    sectionTitle: "Работа с изображениями и фоном",
    topic: "css_images",
  },
  {
    id: "css_images_28",
    title: "Какое преимущество имеет <img> при работе с резиновыми макетами?",
    options: [
      "Возможность использовать width: 100% и height: auto для адаптивности",
      "Возможность задавать background-position",
      "Возможность задавать background-repeat",
      "Возможность задавать background-color",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: у <img> легко задавать width: 100% и height: auto, чтобы изображение масштабировалось по ширине контейнера.",
      "background-position относится к CSS-фону, а не <img>.",
      "background-repeat тоже относится к CSS-фону.",
      "background-color задается для фонов, а не для <img>.",
    ],
    moduleId: "css",
    sectionTitle: "Работа с изображениями и фоном",
    topic: "css_images",
  },
  {
    id: "css_images_29",
    title:
      "Какой метод предпочтителен для добавления маленьких декоративных иконок рядом с текстом?",
    options: [
      "background-image у псевдоэлемента ::before или ::after",
      "<img> как inline-элемент",
      "<picture> с media-запросами",
      "<canvas> с отрисовкой иконки",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: background-image на ::before позволяет вставлять декоративные иконки без изменения HTML.",
      "<img> можно, но это увеличит количество тегов и усложнит верстку текста.",
      "<picture> не нужен для мелких декоративных иконок.",
      "<canvas> избыточен для простых иконок.",
    ],
    moduleId: "css",
    sectionTitle: "Работа с изображениями и фоном",
    topic: "css_images",
  },
  {
    id: "css_images_30",
    title: "Какое ограничение есть у background-image по сравнению с <img>?",
    options: [
      "Отсутствие атрибута alt для доступности",
      "Невозможность масштабировать",
      "Отсутствие поддержки формата JPEG",
      "Невозможность повторения изображения",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: background-image не поддерживает alt-атрибут, что ухудшает доступность.",
      "Фон можно масштабировать через background-size.",
      "Фон поддерживает все веб-форматы, включая JPEG.",
      "Фон можно повторять через background-repeat.",
    ],
    moduleId: "css",
    sectionTitle: "Работа с изображениями и фоном",
    topic: "css_images",
  },
  {
    id: "css_images_31",
    title:
      "В каком случае стоит использовать background-image для фонового видео-подобного эффекта?",
    options: [
      "Когда нужно статичное изображение, а не видео",
      "Когда нужно SEO-оптимизированное видео",
      "Когда нужно содержание видео для скринридеров",
      "Когда нужно управлять кадрами через JS",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: для фонового видео-подобного эффекта часто используют статическое фоновое изображение с background-size: cover.",
      "SEO-оптимизация видео требует <video> или <iframe>, а не background-image.",
      "Background-image не передает содержимое для скринридеров.",
      "JS-управление кадрами требует <video> или <canvas>, а не фон.",
    ],
    moduleId: "css",
    sectionTitle: "Работа с изображениями и фоном",
    topic: "css_images",
  },
  {
    id: "css_images_32",
    title:
      "Что лучше использовать для создания CSS-спрайта с множеством маленьких изображений?",
    options: [
      "background-image с background-position",
      "<img> c SVG-спрайтом",
      "<picture> с несколькими источниками",
      "<canvas> с динамической отрисовкой",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: CSS-спрайты используют одно изображение и background-position для отображения разных иконок.",
      "SVG-спрайт – отдельный подход, но не классический CSS-спрайт.",
      "<picture> не подходит для спрайтов, а для адаптивных изображений.",
      "<canvas> можно рисовать, но проще использовать background-image для спрайтов.",
    ],
    moduleId: "css",
    sectionTitle: "Работа с изображениями и фоном",
    topic: "css_images",
  },
  {
    id: "css_images_33",
    title:
      "Какой способ предпочтителен, если нужно обеспечить кэширование фоновой текстуры сайта?",
    options: ["background-image", "<img>", "<svg>", "<canvas>"],
    correctAnswers: [0],
    descriptions: [
      "Правильно: фоновые текстуры через background-image кэшируются браузером, как любой ресурс CSS.",
      "<img> тоже кэшируется, но чаще фоновая текстура задается CSS, чтобы не нагружать DOM.",
      "SVG можно кэшировать, но для текстуры проще использовать изображение.",
      "<canvas> не сохраняет изображение в CSS и требует JS.",
    ],
    moduleId: "css",
    sectionTitle: "Работа с изображениями и фоном",
    topic: "css_images",
  },
  {
    id: "css_images_34",
    title:
      "Какой метод позволит добавить фоновое изображение для элемента, который не содержит контент?",
    options: [
      "background-image на пустом <div>",
      "<img> внутри пустого элемента",
      "<picture> внутри пустого элемента",
      "<canvas> внутри пустого элемента",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: пустой <div> с background-image создаёт фон без дополнительного контента.",
      "<img> внутри пустого элемента создаст тег с контентом, а не фон.",
      "<picture> аналогично добавит контентный элемент.",
      "<canvas> рисует через JS, а не устанавливает фон.",
    ],
    moduleId: "css",
    sectionTitle: "Работа с изображениями и фоном",
    topic: "css_images",
  },
  {
    id: "css_images_35",
    title:
      "Что использовать, если нужно подгружать изображения только при отображении элемента на экране (ленивая загрузка)?",
    options: [
      '<img loading="lazy">',
      "background-image CSS без JS",
      '<picture loading="lazy">',
      "<img srcset>",
    ],
    correctAnswers: [0],
    descriptions: [
      'Правильно: атрибут loading="lazy" у <img> обеспечивает ленивую загрузку изображения.',
      "CSS background-image без JS не поддерживает ленивую загрузку автоматически.",
      'loading="lazy" у <picture> пока не поддерживается повсеместно, лучше <img>.',
      "srcset решает адаптивность, а не ленивую загрузку.",
    ],
    moduleId: "css",
    sectionTitle: "Работа с изображениями и фоном",
    topic: "css_images",
  },
  {
    id: "css_images_36",
    title:
      "Какой способ более удобен для смены фонового изображения через медиа-запросы?",
    options: [
      "background-image в блоке @media",
      "динамическая смена src у <img> через JS",
      "<picture> с разными source",
      "<svg> с viewBox",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: background-image внутри @media позволяет легко менять фон в зависимости от размера экрана.",
      "JS-решение сложнее, чем чистый CSS.",
      "<picture> предназначен для контентных <img>, а не фоновых изображений.",
      "SVG с viewBox не применяется для растровых фонов.",
    ],
    moduleId: "css",
    sectionTitle: "Работа с изображениями и фоном",
    topic: "css_images",
  },
  {
    id: "css_images_37",
    title:
      "Когда следует предпочесть <img> перед background-image для логотипа компании?",
    options: [
      "Когда логотип важен для SEO и доступности",
      "Когда логотип должен повторяться как текстура",
      "Когда логотип используется в hover-эффектах",
      "Когда логотип — просто декоративный элемент",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: логотип компании важен семантически и для SEO, нужно использовать <img> с alt-атрибутом.",
      "Повторение текстуры лучше делать через background-image.",
      "Hover-эффекты возможны и для <img>, но семантика важнее.",
      "Если логотип просто декоративный, можно использовать background-image.",
    ],
    moduleId: "css",
    sectionTitle: "Работа с изображениями и фоном",
    topic: "css_images",
  },
  {
    id: "css_images_38",
    title:
      "Что упрощает работу дизайнеру при использовании background-image вместо <img>?",
    options: [
      "Быстрая смена фона через CSS без правки HTML",
      "Автоматическая оптимизация изображения",
      "Добавление alt-текста",
      "Использование srcset",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: дизайнер может изменить фон через CSS, не разрабатывая или изменяя HTML.",
      "Оптимизация зависит от инструментов сборки и серверной части, не от background-image.",
      "Alt-текст доступен только у <img>.",
      "srcset поддерживается только для <img> и <picture>.",
    ],
    moduleId: "css",
    sectionTitle: "Работа с изображениями и фоном",
    topic: "css_images",
  },
  {
    id: "css_images_39",
    title:
      "Какой метод позволяет легче анимировать плавную смену фонового изображения?",
    options: [
      "Использовать background-image с transition для opacity",
      "Изменить src у <img> с transition",
      "Использовать <video> фон",
      "Использовать <canvas>",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: можно наложить два элемента с разными фонами и анимировать их opacity в CSS.",
      "Изменение src у <img> не анимируется плавно через CSS.",
      "Видео-фон сложнее для плавных переходов между изображениями.",
      "canvas требует JS и не так удобно для простых анимаций.",
    ],
    moduleId: "css",
    sectionTitle: "Работа с изображениями и фоном",
    topic: "css_images",
  },
  {
    id: "css_images_40",
    title:
      "Какой метод предпочтителен для добавления фоновых градиентов поверх изображения?",
    options: [
      "background: linear-gradient(), url()",
      "<img> с градиентом в изображении",
      "<picture> с градиентом",
      "<canvas> с отрисовкой градиента",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: комбинированная запись background позволяет накладывать градиент поверх фонового изображения.",
      "Градиент непосредственно в файле изображения не дает гибкости CSS.",
      "<picture> не предназначен для наложения CSS-градиентов.",
      "<canvas> потребует JS и более сложных решений.",
    ],
    moduleId: "css",
    sectionTitle: "Работа с изображениями и фоном",
    topic: "css_images",
  },
  {
    id: "css_images_41",
    title:
      "Какое свойство используется в теге <img> для указания альтернативных размеров изображения?",
    options: ["srcset", "sizes", "responsive", "picture"],
    correctAnswers: [0],
    descriptions: [
      "Правильно: атрибут srcset у <img> задаёт набор изображений разного разрешения.",
      "sizes определяет размер вёрстки, а не набор файлов.",
      "responsive не является валидным атрибутом для <img>.",
      "picture — это не атрибут, а отдельный HTML-тег.",
    ],
    moduleId: "css",
    sectionTitle: "Работа с изображениями и фоном",
    topic: "css_images",
  },
  {
    id: "css_images_42",
    title: "Что делает атрибут sizes в теге <img>?",
    options: [
      "Указывает, какую ширину будет занимать изображение в макете",
      "Задаёт несколько источников изображений",
      "Подключает CSS-файл с адаптивными стилями",
      "Определяет alt-текст для разных размеров",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: sizes описывает, какова реальная ширина элемента в макете для расчёта нужного варианта из srcset.",
      "srcset указывает источники, а sizes — размеры в макете.",
      "sizes не подключает CSS-файлы.",
      "alt-текст задаётся только атрибутом alt.",
    ],
    moduleId: "css",
    sectionTitle: "Работа с изображениями и фоном",
    topic: "css_images",
  },
  {
    id: "css_images_43",
    title:
      "Какой тег позволяет использовать несколько источников изображений с учётом медиа-запросов?",
    options: ["<picture>", "<source>", "<imgset>", "<responsive>"],
    correctAnswers: [0],
    descriptions: [
      "Правильно: <picture> вместе с вложенными <source> позволяет выбрать файл по медиа-запросу.",
      "<source> используется внутри <picture>, но сам по себе не работает.",
      "<imgset> не является валидным тегом.",
      "<responsive> не существует в HTML.",
    ],
    moduleId: "css",
    sectionTitle: "Работа с изображениями и фоном",
    topic: "css_images",
  },
  {
    id: "css_images_44",
    title: "Какой атрибут у тега <source> задаёт условие медиа-запроса?",
    options: ["media", "src", "sizes", "width"],
    correctAnswers: [0],
    descriptions: [
      "Правильно: атрибут media у <source> указывает условие медиа-запроса.",
      "src задаёт путь к файлу, но не условие медиа.",
      "sizes воздействует на выбор в srcset, а не задаёт медиа-условие.",
      "width не используется для медиа-условий у <source>.",
    ],
    moduleId: "css",
    sectionTitle: "Работа с изображениями и фоном",
    topic: "css_images",
  },
  {
    id: "css_images_45",
    title: "Какой атрибут у <source> указывает путь к изображению?",
    options: ["srcset", "src", "href", "data-src"],
    correctAnswers: [0],
    descriptions: [
      "Правильно: у тега <source> для <picture> используется srcset для указания путей.",
      "src не является корректным атрибутом у <source> внутри <picture>.",
      "href используется для ссылок, а не для <source>.",
      "data-src — нестандартный атрибут, используется JS.",
    ],
    moduleId: "css",
    sectionTitle: "Работа с изображениями и фоном",
    topic: "css_images",
  },
  {
    id: "css_images_46",
    title:
      "Как правильно написать базовый пример тега <picture> с двумя источниками?",
    options: [
      `<picture>
  <source media="(min-width: 800px)" srcset="large.jpg">
  <img src="small.jpg" alt="Пример">
</picture>`,
      `<picture>
  <img src="small.jpg" alt="Пример">
  <source media="(min-width: 800px)" srcset="large.jpg">
</picture>`,
      `<picture>
  <source src="large.jpg">
  <source src="small.jpg">
</picture>`,
      `<picture>
  <img srcset="small.jpg" alt="Пример">
  <source media="(min-width: 800px)" src="large.jpg">
</picture>`,
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: сначала <source> с медиа и srcset, затем <img> как fallback.",
      "Неправильный порядок: <img> должен быть последним.",
      "<source> без медиа не гарантирует адаптивность.",
      "Неправильное использование src/srcset у <source> и <img>.",
    ],
    moduleId: "css",
    sectionTitle: "Работа с изображениями и фоном",
    topic: "css_images",
  },
  {
    id: "css_images_47",
    title: "Что будет, если браузер не поддерживает тег <picture>?",
    options: [
      "Будет отображён <img> внутри <picture>",
      "Ничего не покажется",
      "Будет использован первый <source>",
      "Произойдёт ошибка загрузки",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: браузер покажет содержимое <img> как запасной вариант.",
      "Изображение всё равно отобразится через <img>.",
      "<source> игнорируется старым браузером.",
      "Ошибка не возникнет, т.к. <img> обрабатывается.",
    ],
    moduleId: "css",
    sectionTitle: "Работа с изображениями и фоном",
    topic: "css_images",
  },
  {
    id: "css_images_48",
    title: "Как указать несколько разрешений в srcset для <img>?",
    options: [
      `srcset="small.jpg 480w, medium.jpg 800w, large.jpg 1200w"`,
      `srcset="small.jpg, medium.jpg, large.jpg"`,
      `sizes="480w,800w,1200w"`,
      `srcset="audio-small.mp3 480w, audio-large.mp3 1200w"`,
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: после пути через пробел указывается ширина в пикселях (w).",
      "Без указания ширины браузер не знает, когда выбирать файл.",
      "sizes задаёт размеры в макете, а не набор файлов.",
      "mp3 не является изображением.",
    ],
    moduleId: "css",
    sectionTitle: "Работа с изображениями и фоном",
    topic: "css_images",
  },
  {
    id: "css_images_49",
    title:
      "Что сообщает браузеру атрибут 2x в srcset, например: img@2x.jpg 2x?",
    options: [
      "Использовать изображение при устройстве с высокой плотностью пикселей",
      "Выводить изображение в два раза шире",
      "Загружать две копии изображения",
      "Уменьшать изображение в два раза",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: 2x означает, что файл предназначен для экранов с DPR=2.",
      "Ширина задаётся CSS, не маркером 2x.",
      "Нельзя загрузить две копии одновременно.",
      "Не связано с уменьшением размера.",
    ],
    moduleId: "css",
    sectionTitle: "Работа с изображениями и фоном",
    topic: "css_images",
  },
  {
    id: "css_images_50",
    title: "Как атрибут sizes влияет на выбор файла из srcset?",
    options: [
      "Сообщает браузеру реальную отображаемую ширину изображения",
      "Указывает alt-текст для разных версий",
      "Задаёт ширину исходного файла",
      "Указывает порядок загрузки",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: sizes описывает, какой размер будет у изображения в CSS-верстке.",
      "alt-текст задаётся атрибутом alt, а не sizes.",
      "sizes не влияет на размер исходного файла.",
      "sizes не задаёт порядок загрузки.",
    ],
    moduleId: "css",
    sectionTitle: "Работа с изображениями и фоном",
    topic: "css_images",
  },
  {
    id: "css_images_51",
    title: "Какой синтаксис задаёт изображение для экранов с DPR=1 и DPR=2?",
    options: [
      `srcset="img.jpg 1x, img@2x.jpg 2x"`,
      `srcset="img.jpg 1w, img@2x.jpg 2w"`,
      `src="img.jpg" src@2x="img@2x.jpg"`,
      `srcset="img.png 1dpi, img@2x.png 2dpi"`,
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: указание 1x и 2x позволяет браузеру выбирать файл в зависимости от DPR.",
      "w обозначает ширину, а не множитель плотности.",
      "Неверные атрибуты, нет стандарта src@2x.",
      "dpi не используется в srcset, нужно x.",
    ],
    moduleId: "css",
    sectionTitle: "Работа с изображениями и фоном",
    topic: "css_images",
  },
  {
    id: "css_images_52",
    title: "Что произойдёт, если указаны и srcset, и src без sizes?",
    options: [
      "Браузер выберет изображение по умолчанию согласно src",
      "Браузер не загрузит изображение",
      "Браузер выберет наименьший файл из srcset",
      "Браузер выберет первый файл из srcset",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: без sizes браузер использует src в качестве запаски.",
      "Изображение всё равно загрузится через src.",
      "Без sizes браузер не знает, когда выбирать из srcset.",
      "srcset без sizes игнорируется, используется src.",
    ],
    moduleId: "css",
    sectionTitle: "Работа с изображениями и фоном",
    topic: "css_images",
  },
  {
    id: "css_images_53",
    title:
      "Какой элемент следует использовать вместе с <source> для SVG-файлов?",
    options: ["<picture>", "<svgset>", "<img>", "<src>"],
    correctAnswers: [0],
    descriptions: [
      "Правильно: <picture> поддерживает <source> и позволяет указать SVG для разных устройств.",
      "<svgset> не существует.",
      "<img> можно также использовать, но без <source> внутри <picture> нет гибкости медиа.",
      "<src> не является тегом.",
    ],
    moduleId: "css",
    sectionTitle: "Работа с изображениями и фоном",
    topic: "css_images",
  },
  {
    id: "css_images_54",
    title: "Как задать адаптивное изображение через CSS без изменения HTML?",
    options: [
      "Использовать background-image с медиа-запросами",
      "Использовать srcset на <img>",
      "Использовать <canvas>",
      "Использовать <picture>",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: медиа-запросы в CSS могут менять background-image в зависимости от ширины экрана.",
      "srcset — изменение HTML, а не только CSS.",
      "<canvas> требует JavaScript.",
      "<picture> меняет HTML.",
    ],
    moduleId: "css",
    sectionTitle: "Работа с изображениями и фоном",
    topic: "css_images",
  },
  {
    id: "css_images_55",
    title: "Какое преимущество дает использование WebP в srcset?",
    options: [
      "Меньший размер при сохранении качества",
      "Поддержка SVG-анимации",
      "Авто-оптимизация браузером",
      "Невозможность загрузки fallback",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: WebP обеспечивает лучшее сжатие, чем JPEG или PNG.",
      "SVG-анимация не связана с WebP.",
      "Браузер не оптимизирует WebP автоматически сверх встроенного формата.",
      "Можно указать fallback в srcset или через <picture>.",
    ],
    moduleId: "css",
    sectionTitle: "Работа с изображениями и фоном",
    topic: "css_images",
  },
  {
    id: "css_images_56",
    title:
      "Какой атрибут у <img> позволяет отложить загрузку до появления в области просмотра?",
    options: ['loading="lazy"', "defer", "async", "delayed"],
    correctAnswers: [0],
    descriptions: [
      'Правильно: loading="lazy" у <img> включает ленивую загрузку.',
      "defer и async применяются к скриптам, а не к изображениям.",
      "async — только для <script>.",
      "delayed не является валидным атрибутом.",
    ],
    moduleId: "css",
    sectionTitle: "Работа с изображениями и фоном",
    topic: "css_images",
  },
  {
    id: "css_images_57",
    title:
      "Что делать, если нужно fallback для браузеров, не поддерживающих WebP?",
    options: [
      "Указать несколько <source> внутри <picture> с WebP и JPEG",
      "Использовать только WebP — современные браузеры поддерживают",
      "Указывать PNG в srcset вместо WebP",
      "Использовать CSS background-image",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: в <picture> первый <source> с WebP, второй <source> или <img> с JPEG.",
      "Некоторые старые браузеры не поддерживают WebP.",
      "Можно, но лучше через <picture> обеспечить fallback.",
      "CSS background-image не даёт семантического fallback.",
    ],
    moduleId: "css",
    sectionTitle: "Работа с изображениями и фоном",
    topic: "css_images",
  },
  {
    id: "css_images_58",
    title:
      "Какой атрибут <img> используется для показа изображения с определенной плотностью пикселей?",
    options: ["srcset с указанием x", "sizes", "media", "density"],
    correctAnswers: [0],
    descriptions: [
      'Правильно: srcset="img@2x.png 2x" указывает плотность DPR.',
      "sizes описывает макет, а не плотность пикселей.",
      "media не применяется к <img> напрямую.",
      "density не является валидным.",
    ],
    moduleId: "css",
    sectionTitle: "Работа с изображениями и фоном",
    topic: "css_images",
  },
  {
    id: "css_images_59",
    title:
      "Какой элемент внутри <picture> рекомендуется располагать последним?",
    options: ["<img>", "<source>", "<video>", "<canvas>"],
    correctAnswers: [0],
    descriptions: [
      "Правильно: <img> располагаться последним, служит fallback для неподдерживаемых <source>.",
      "<source> должен быть перед <img>.",
      "<video> не используется внутри <picture>.",
      "<canvas> не используется внутри <picture>.",
    ],
    moduleId: "css",
    sectionTitle: "Работа с изображениями и фоном",
    topic: "css_images",
  },
  {
    id: "css_images_60",
    title:
      "Какое значение атрибута sizes соответствует 50vw (половина ширины вьюпорта)?",
    options: ['sizes="50vw"', 'sizes="50%"', 'sizes="100px"', 'sizes="auto"'],
    correctAnswers: [0],
    descriptions: [
      "Правильно: 50vw означает 50% ширины viewport.",
      "50% относится к родительскому элементу, а не к viewport.",
      "100px — фиксированное значение, а не процент viewport.",
      "auto позволяет браузеру выбирать размер, но не явно 50vw.",
    ],
    moduleId: "css",
    sectionTitle: "Работа с изображениями и фоном",
    topic: "css_images",
  },
];
