export const cssQuestions = [
  {
    id: "css_intro_1",
    title: "Что такое CSS?",
    options: [
      "Язык программирования",
      "Язык таблиц стилей",
      "База данных",
      "Фреймворк для бэкенда",
    ],
    correctAnswers: [1],
    descriptions: [
      "CSS не является языком программирования.",
      "CSS (Cascading Style Sheets) — язык таблиц стилей для оформления HTML.",
      "Базы данных — это отдельные технологии, например MySQL.",
      "CSS используется для стилизации фронтенда, не относится к бэкенду.",
    ],
    moduleId: "css",
    sectionTitle: "Основы CSS и синтаксис",
    topic: "css_intro",
  },
  {
    id: "css_intro_2",
    title: "Какой тег используется для подключения CSS в HTML?",
    options: ["<script>", "<style>", "<link>", "<css>"],
    correctAnswers: [2],
    descriptions: [
      "Тег <script> используется для подключения JavaScript.",
      "Тег <style> используется для встроенных стилей, а не внешних файлов.",
      "Правильный ответ: <link rel='stylesheet' href='styles.css'>.",
      "Тега <css> не существует в HTML.",
    ],
    moduleId: "css",
    sectionTitle: "Основы CSS и синтаксис",
    topic: "css_intro",
  },
  {
    id: "css_intro_3",
    title: "Какой символ используется для обозначения ID в CSS?",
    options: [".", "#", "@", "%"],
    correctAnswers: [1],
    descriptions: [
      "Точка используется для обозначения классов.",
      "Решетка # используется для ID (например #header).",
      "Символ @ используется для директив вроде @media.",
      "Символ % используется в CSS препроцессорах.",
    ],
    moduleId: "css",
    sectionTitle: "Основы CSS и синтаксис",
    topic: "css_intro",
  },
  {
    id: "css_intro_4",
    title: "Какое свойство изменяет цвет текста?",
    options: ["text-color", "font-color", "color", "text-style"],
    correctAnswers: [2],
    descriptions: [
      "Свойства text-color не существует.",
      "Свойства font-color не существует.",
      "Правильное свойство: color (например: color: red;).",
      "text-style не отвечает за цвет текста.",
    ],
    moduleId: "css",
    sectionTitle: "Основы CSS и синтаксис",
    topic: "css_intro",
  },
  {
    id: "css_intro_5",
    title: "Как комментируется код в CSS?",
    options: [
      "// Комментарий",
      "/* Комментарий */",
      "<!-- Комментарий -->",
      "# Комментарий",
    ],
    correctAnswers: [1],
    descriptions: [
      "// используется в JavaScript, но не в CSS.",
      "Правильный синтаксис: /* Комментарий */.",
      "<!-- --> используется в HTML.",
      "# используется для комментариев в некоторых языках, но не в CSS.",
    ],
    moduleId: "css",
    sectionTitle: "Основы CSS и синтаксис",
    topic: "css_intro",
  },
  {
    id: "css_intro_6",
    title: "Как задать полужирное начертание текста?",
    options: [
      "font-style: bold;",
      "text-weight: bold;",
      "font-weight: bold;",
      "text-style: bold;",
    ],
    correctAnswers: [2],
    descriptions: [
      "font-style отвечает за курсив, а не за жирность.",
      "Свойства text-weight не существует.",
      "Правильное свойство: font-weight: bold;.",
      "text-style не управляет жирностью текста.",
    ],
    moduleId: "css",
    sectionTitle: "Основы CSS и синтаксис",
    topic: "css_intro",
  },
  {
    id: "css_intro_7",
    title: "Какой селектор имеет наибольшую специфичность?",
    options: ["div", ".class", "#id", "tag:hover"],
    correctAnswers: [2],
    descriptions: [
      "Селекторы тегов имеют низкую специфичность.",
      "Классы имеют среднюю специфичность.",
      "ID имеют наивысшую специфичность среди этих вариантов.",
      "Псевдоклассы (как :hover) имеют специфичность как у класса.",
    ],
    moduleId: "css",
    sectionTitle: "Основы CSS и синтаксис",
    topic: "css_intro",
  },
  {
    id: "css_intro_8",
    title: "Как подключить CSS напрямую в HTML-документе?",
    options: [
      "Через атрибут style элемента",
      "Через тег <style> в <head>",
      "Через @import в CSS-файле",
      "Через JavaScript",
    ],
    correctAnswers: [1],
    descriptions: [
      "Атрибут style — это inline-стили, а не подключение CSS.",
      "Правильный ответ: <style> в <head> позволяет писать CSS прямо в HTML.",
      "@import подключает один CSS-файл в другой.",
      "JavaScript может динамически менять стили, но это не подключение CSS.",
    ],
    moduleId: "css",
    sectionTitle: "Основы CSS и синтаксис",
    topic: "css_intro",
  },
  {
    id: "css_intro_9",
    title: "Какое свойство отвечает за внешние отступы?",
    options: ["padding", "margin", "spacing", "indent"],
    correctAnswers: [1],
    descriptions: [
      "padding — внутренние отступы элемента.",
      "margin — правильный ответ (внешние отступы).",
      "Свойства spacing не существует.",
      "Свойства indent не существует в CSS.",
    ],
    moduleId: "css",
    sectionTitle: "Основы CSS и синтаксис",
    topic: "css_intro",
  },
  {
    id: "css_intro_10",
    title: "Как сделать текст курсивным?",
    options: [
      "font-weight: italic;",
      "font-style: italic;",
      "text-decoration: italic;",
      "text-style: italic;",
    ],
    correctAnswers: [1],
    descriptions: [
      "font-weight управляет жирностью, а не курсивом.",
      "Правильное свойство: font-style: italic;.",
      "text-decoration отвечает за подчеркивание и т.д.",
      "Свойства text-style не существует.",
    ],
    moduleId: "css",
    sectionTitle: "Основы CSS и синтаксис",
    topic: "css_intro",
  },
  {
    id: "css_intro_11",
    title: "Что делает свойство display: none;?",
    options: [
      "Делает элемент прозрачным",
      "Скрывает элемент с сохранением места",
      "Полностью удаляет элемент из DOM",
      "Скрывает элемент без сохранения места",
    ],
    correctAnswers: [3],
    descriptions: [
      "Прозрачность управляется opacity.",
      "Это поведение visibility: hidden.",
      "Элемент остается в DOM, но полностью удаляется из отображения.",
      "Правильный ответ: элемент скрывается и не занимает место.",
    ],
    moduleId: "css",
    sectionTitle: "Основы CSS и синтаксис",
    topic: "css_intro",
  },
  {
    id: "css_intro_12",
    title: "Как изменить цвет фона элемента?",
    options: [
      "background-color",
      "color-background",
      "bgcolor",
      "element-background",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильное свойство: background-color.",
      "Свойства color-background не существует.",
      "bgcolor — устаревший HTML-атрибут, не CSS-свойство.",
      "Свойства element-background не существует.",
    ],
    moduleId: "css",
    sectionTitle: "Основы CSS и синтаксис",
    topic: "css_intro",
  },
  {
    id: "css_intro_13",
    title: "Какой псевдокласс применяется к наведенному курсору?",
    options: [":active", ":hover", ":focus", ":visited"],
    correctAnswers: [1],
    descriptions: [
      ":active — состояние нажатия элемента.",
      "Правильный ответ: :hover (наведение курсора).",
      ":focus — состояние фокуса (например, в input).",
      ":visited — посещенные ссылки.",
    ],
    moduleId: "css",
    sectionTitle: "Основы CSS и синтаксис",
    topic: "css_intro",
  },
  {
    id: "css_intro_14",
    title: "Как задать тень для блока?",
    options: ["block-shadow", "element-shadow", "box-shadow", "shadow-effect"],
    correctAnswers: [2],
    descriptions: [
      "Свойства block-shadow не существует.",
      "Свойства element-shadow не существует.",
      "Правильное свойство: box-shadow.",
      "Свойства shadow-effect не существует.",
    ],
    moduleId: "css",
    sectionTitle: "Основы CSS и синтаксис",
    topic: "css_intro",
  },
  {
    id: "css_intro_15",
    title: "Какой единицей лучше задавать размеры шрифта?",
    options: ["px", "em", "rem", "pt"],
    correctAnswers: [2],
    descriptions: [
      "px — фиксированный размер, не масштабируется.",
      "em — зависит от родительского шрифта, может вызывать проблемы.",
      "rem — лучший вариант (зависит от корневого элемента).",
      "pt — типографские пункты, не рекомендуется для веба.",
    ],
    moduleId: "css",
    sectionTitle: "Основы CSS и синтаксис",
    topic: "css_intro",
  },
  {
    id: "css_intro_16",
    title: "Как сделать все буквы заглавными через CSS?",
    options: [
      "text-transform: uppercase;",
      "font-style: uppercase;",
      "text-uppercase: true;",
      "letter-case: upper;",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильное свойство: text-transform: uppercase;.",
      "font-style не управляет регистром букв.",
      "Свойства text-uppercase не существует.",
      "Свойства letter-case не существует.",
    ],
    moduleId: "css",
    sectionTitle: "Основы CSS и синтаксис",
    topic: "css_intro",
  },
  {
    id: "css_intro_17",
    title: "Какое свойство отвечает за порядок наложения элементов?",
    options: ["z-position", "stack-order", "z-index", "layer-index"],
    correctAnswers: [2],
    descriptions: [
      "Свойства z-position не существует.",
      "Свойства stack-order не существует.",
      "Правильное свойство: z-index.",
      "Свойства layer-index не существует.",
    ],
    moduleId: "css",
    sectionTitle: "Основы CSS и синтаксис",
    topic: "css_intro",
  },
  {
    id: "css_intro_18",
    title: "Как сделать границу элемента?",
    options: ["element-border", "border-style", "frame-border", "outline"],
    correctAnswers: [1],
    descriptions: [
      "Свойства element-border не существует.",
      "Правильный ответ: border-style с другими border-свойствами.",
      "Свойства frame-border не существует.",
      "outline — контур вокруг элемента, отличается от border.",
    ],
    moduleId: "css",
    sectionTitle: "Основы CSS и синтаксис",
    topic: "css_intro",
  },
  {
    id: "css_intro_19",
    title: "Какой селектор выберет все элементы <p> внутри <div>?",
    options: ["div + p", "div > p", "div p", "div ~ p"],
    correctAnswers: [2],
    descriptions: [
      "div + p — соседний элемент (первый p после div).",
      "div > p — только непосредственные потомки.",
      "div p — правильный ответ (все p внутри div любого уровня).",
      "div ~ p — все соседние p после div.",
    ],
    moduleId: "css",
    sectionTitle: "Основы CSS и синтаксис",
    topic: "css_intro",
  },
  {
    id: "css_intro_20",
    title: "Как сделать flex-контейнер?",
    options: [
      "display: flexbox;",
      "display: flex;",
      "display: inline-flex;",
      "flex-container: true;",
    ],
    correctAnswers: [1],
    descriptions: [
      "Значения flexbox не существует.",
      "Правильное значение: display: flex;.",
      "inline-flex делает контейнер строчным, но не основной способ.",
      "Свойства flex-container не существует.",
    ],
    moduleId: "css",
    sectionTitle: "Основы CSS и синтаксис",
    topic: "css_intro",
  },
  {
    id: "css_intro_21",
    title: "Какое свойство изменяет прозрачность элемента?",
    options: ["transparency", "opacity", "visibility", "alpha"],
    correctAnswers: [1],
    descriptions: [
      "Свойства transparency не существует.",
      "Правильное свойство: opacity (от 0 до 1).",
      "visibility управляет видимостью, но не прозрачностью.",
      "Свойства alpha не существует (есть в rgba, но отдельно нет).",
    ],
    moduleId: "css",
    sectionTitle: "Основы CSS и синтаксис",
    topic: "css_intro",
  },
  {
    id: "css_intro_22",
    title: "Как задать анимацию в CSS?",
    options: [
      "@animation",
      "@keyframes + animation-* свойства",
      "animate-rule",
      "css-animation",
    ],
    correctAnswers: [1],
    descriptions: [
      "Директивы @animation не существует.",
      "Правильный ответ: @keyframes для определения + animation для применения.",
      "Правила animate-rule не существует.",
      "Свойства css-animation не существует.",
    ],
    moduleId: "css",
    sectionTitle: "Основы CSS и синтаксис",
    topic: "css_intro",
  },
  {
    id: "css_intro_23",
    title: "Какой псевдоэлемент создает содержимое после элемента?",
    options: ["::before", "::after", "::content", "::append"],
    correctAnswers: [1],
    descriptions: [
      "::before — вставляет содержимое перед элементом.",
      "Правильный ответ: ::after (после элемента).",
      "Псевдоэлемента ::content не существует.",
      "Псевдоэлемента ::append не существует.",
    ],
    moduleId: "css",
    sectionTitle: "Основы CSS и синтаксис",
    topic: "css_intro",
  },
  {
    id: "css_intro_24",
    title: "Как сделать первую букву текста особого стиля?",
    options: [
      "::first-character",
      "::first-letter",
      "::start-letter",
      "::initial-letter",
    ],
    correctAnswers: [1],
    descriptions: [
      "Псевдоэлемента ::first-character не существует.",
      "Правильный ответ: ::first-letter.",
      "Псевдоэлемента ::start-letter не существует.",
      "Псевдоэлемента ::initial-letter не существует (есть initial-letter, но это другое).",
    ],
    moduleId: "css",
    sectionTitle: "Основы CSS и синтаксис",
    topic: "css_intro",
  },
  {
    id: "css_intro_25",
    title: "Как сделать адаптивный дизайн?",
    options: [
      "Использовать абсолютные единицы (px)",
      "Использовать медиазапросы (@media)",
      "Писать отдельный CSS для мобильных",
      "Использовать только flexbox",
    ],
    correctAnswers: [1],
    descriptions: [
      "Абсолютные единицы препятствуют адаптивности.",
      "Правильный ответ: медиазапросы позволяют адаптировать стили под разные устройства.",
      "Хотя можно, но это неэффективно по сравнению с медиазапросами.",
      "Flexbox помогает, но без медиазапросов недостаточен.",
    ],
    moduleId: "css",
    sectionTitle: "Основы CSS и синтаксис",
    topic: "css_intro",
  },
  {
    id: "css_intro_26",
    title: "Какой селектор выберет элементы с атрибутом title?",
    options: ["[title]", ".title", "#title", "title"],
    correctAnswers: [0],
    descriptions: [
      "Правильный ответ: [title] (селектор по атрибуту).",
      ".title — селектор по классу.",
      "#title — селектор по ID.",
      "title — селектор по тегу.",
    ],
    moduleId: "css",
    sectionTitle: "Основы CSS и синтаксис",
    topic: "css_intro",
  },
  {
    id: "css_intro_27",
    title: "Как центрировать блок по горизонтали с margin?",
    options: [
      "margin-center: auto;",
      "margin: auto;",
      "margin: 0 center;",
      "margin-horizontal: auto;",
    ],
    correctAnswers: [1],
    descriptions: [
      "Свойства margin-center не существует.",
      "Правильный ответ: margin: 0 auto; (или просто margin: auto;).",
      "Такой синтаксис не поддерживается.",
      "Свойства margin-horizontal не существует.",
    ],
    moduleId: "css",
    sectionTitle: "Основы CSS и синтаксис",
    topic: "css_intro",
  },
  {
    id: "css_intro_28",
    title: "Как сделать все элементы <li> красными?",
    options: [
      "li.all { color: red; }",
      "li * { color: red; }",
      "li { color: red; }",
      "ul > li { color: red; }",
    ],
    correctAnswers: [2],
    descriptions: [
      "Селектора .all не существует.",
      "li * выберет все внутри li, а не сами li.",
      "Правильный ответ: li { color: red; }.",
      "ul > li выберет только непосредственные li внутри ul.",
    ],
    moduleId: "css",
    sectionTitle: "Основы CSS и синтаксис",
    topic: "css_intro",
  },
  {
    id: "css_intro_29",
    title: "Как скруглить углы у элемента?",
    options: [
      "border-radius",
      "corner-radius",
      "border-round",
      "round-corners",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильное свойство: border-radius.",
      "Свойства corner-radius не существует.",
      "Свойства border-round не существует.",
      "Свойства round-corners не существует.",
    ],
    moduleId: "css",
    sectionTitle: "Основы CSS и синтаксис",
    topic: "css_intro",
  },
  {
    id: "css_intro_30",
    title: "Какой псевдокласс выберет первый дочерний элемент?",
    options: [":first", ":first-child", ":child-first", ":first-of-type"],
    correctAnswers: [1],
    descriptions: [
      "Псевдокласса :first не существует.",
      "Правильный ответ: :first-child (первый ребенок своего родителя).",
      "Псевдокласса :child-first не существует.",
      ":first-of-type выберет первый элемент своего типа, но не обязательно первый вообще.",
    ],
    moduleId: "css",
    sectionTitle: "Основы CSS и синтаксис",
    topic: "css_intro",
  },
];
