export const cssMethodologiesQuestions = [
  {
    id: "css_methodologies_1",
    title: "Что в общем смысле обозначает термин «CSS-методология»?",
    options: [
      "Набор готовых CSS-фреймворков",
      "Практики и правила организации CSS-кода",
      "Инструменты для автоматической сборки CSS",
      "Специальные CSS-свойства",
    ],
    correctAnswers: [1],
    descriptions: [
      "CSS-фреймворки — это отдельная тема, не методология.",
      "Правильно: методология описывает, как структурировать и организовать CSS для удобства поддержки.",
      "Сборщики (Webpack, Gulp) — это инструменты, а не методологии.",
      "CSS-свойства — это синтаксис, а не методология.",
    ],
    moduleId: "css",
    sectionTitle: "Методологии (BEM)",
    topic: "css_methodologies",
  },
  {
    id: "css_methodologies_2",
    title: "Зачем применяются CSS-методологии в проектах?",
    options: [
      "Для уменьшения размера CSS-файлов",
      "Для упрощения поддержки и масштабируемости стилей",
      "Для автоматического написания CSS-кода",
      "Для ускорения загрузки страницы",
    ],
    correctAnswers: [1],
    descriptions: [
      "Методологии могут косвенно сократить код, но это не основная цель.",
      "Правильно: основной смысл методологий — структурировать код, чтобы было проще поддерживать и развивать проект.",
      "Автоматизация — это задача препроцессоров и сборщиков, а не методологий.",
      "Методологии не влияют напрямую на скорость загрузки.",
    ],
    moduleId: "css",
    sectionTitle: "Методологии (BEM)",
    topic: "css_methodologies",
  },
  {
    id: "css_methodologies_3",
    title:
      "Какая из приведённых методологий является одной из самых популярных?",
    options: ["OOCSS", "BEM", "SMACSS", "Все вышеперечисленные"],
    correctAnswers: [3],
    descriptions: [
      "OOCSS — популярная, но не единственная.",
      "BEM — очень популярна, но есть и другие.",
      "SMACSS тоже используется, но не единственная.",
      "Правильно: все перечисленные методологии применяются на практике.",
    ],
    moduleId: "css",
    sectionTitle: "Методологии (BEM)",
    topic: "css_methodologies",
  },
  {
    id: "css_methodologies_4",
    title: "Что расшифровывается как BEM?",
    options: [
      "Block, Element, Modifier",
      "Base, Extend, Mix",
      "Bind, Emulate, Merge",
      "Bootstrap, Emmet, Media",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: BEM расшифровывается как Block, Element, Modifier.",
      "Base, Extend, Mix — не относится к BEM.",
      "Bind, Emulate, Merge — не связано с BEM.",
      "Bootstrap, Emmet, Media — не расшифровка BEM.",
    ],
    moduleId: "css",
    sectionTitle: "Методологии (BEM)",
    topic: "css_methodologies",
  },
  {
    id: "css_methodologies_5",
    title: "Что такое «блок» (Block) в BEM?",
    options: [
      "Файл с набором CSS-переменных",
      "Независимый компонент интерфейса",
      "CSS-класс для сетки страницы",
      "Глобальный селектор типа body",
    ],
    correctAnswers: [1],
    descriptions: [
      "Переменные — не блок.",
      "Правильно: блок — это самостоятельный компонент, например, карточка, меню, форма.",
      "Сетка может быть блоком, но понятие блока шире — это любой компонент.",
      "body — это глобальный объект, а не конкретный блок.",
    ],
    moduleId: "css",
    sectionTitle: "Методологии (BEM)",
    topic: "css_methodologies",
  },
  {
    id: "css_methodologies_6",
    title: "Что такое «элемент» (Element) в BEM?",
    options: [
      "Часть блока, зависящая от него",
      "Отдельный CSS-файл",
      "Независимый компонент, как блок",
      "Свойство CSS",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: элемент — это составная часть блока, например, кнопка в карточке.",
      "Файл не является элементом BEM.",
      "Элемент не существует автономно без блока.",
      "Свойство — это часть синтаксиса, а не элемент в BEM.",
    ],
    moduleId: "css",
    sectionTitle: "Методологии (BEM)",
    topic: "css_methodologies",
  },
  {
    id: "css_methodologies_7",
    title: "Что такое «модификатор» (Modifier) в BEM?",
    options: [
      "Изменяемое состояние или вариация блока/элемента",
      "Файл с темами оформления",
      "Стили для адаптивной верстки",
      "Переменная SCSS",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: модификатор меняет внешний вид или поведение блока/элемента, например, .button--primary.",
      "Файл тем — не модификатор.",
      "Адаптивные стили — отдельная тема.",
      "Переменная SCSS — не модификатор.",
    ],
    moduleId: "css",
    sectionTitle: "Методологии (BEM)",
    topic: "css_methodologies",
  },
  {
    id: "css_methodologies_8",
    title: "Какой вариант имени соответствует элементу в BEM?",
    options: [
      ".block__element",
      ".block-element",
      ".Block.Element",
      ".block--element",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: синтаксис .block__element указывает элемент «element» внутри блока «block».",
      "Без двойного подчеркивания не соответствует BEM.",
      "В BEM не используются точки в именах классов.",
      ".block--element — синтаксис для модификатора, а не элемента.",
    ],
    moduleId: "css",
    sectionTitle: "Методологии (BEM)",
    topic: "css_methodologies",
  },
  {
    id: "css_methodologies_9",
    title: "Какой вариант имени соответствует модификатору в BEM?",
    options: [
      ".block--modifier",
      ".block_modifier",
      ".block__modifier",
      ".block.modifier",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: синтаксис .block--modifier указывает модификатор для блока «block».",
      "Неверно: одинарное подчеркивание не соответствует BEM-модификатору.",
      "__ предназначен для элементов, не для модификаторов.",
      ".block.modifier применяется для вложенных селекторов, а не BEM-модификатора.",
    ],
    moduleId: "css",
    sectionTitle: "Методологии (BEM)",
    topic: "css_methodologies",
  },
  {
    id: "css_methodologies_10",
    title: "Что рекомендуется делать при создании нового блока в BEM?",
    options: [
      "Дублировать CSS из других блоков",
      "Дать блоку самообъясняющееся имя",
      "Использовать id вместо классов",
      "Привязываться к структуре HTML",
    ],
    correctAnswers: [1],
    descriptions: [
      "Дублирование кода приводит к сложности поддержки.",
      "Правильно: осмысленное имя блока облегчает понимание назначения компонента.",
      "BEM используют классы, а не id.",
      "Структура HTML не должна определять имена BEM-классов.",
    ],
    moduleId: "css",
    sectionTitle: "Методологии (BEM)",
    topic: "css_methodologies",
  },
  {
    id: "css_methodologies_11",
    title:
      "Можно ли использовать вложенность селекторов при написании BEM-классов?",
    options: [
      "Да, но только до 2 уровней",
      "Да, но рекомендуется избегать избыточной вложенности",
      "Нет, вложенность запрещена",
      "Вложенность заменена псевдоклассами",
    ],
    correctAnswers: [1],
    descriptions: [
      "Нет жёсткого ограничения по уровням, но избыточная вложенность нежелательна.",
      "Правильно: вложенность возможна в SCSS, но нужно избегать глубоких селекторов, чтобы сохранить независимость блоков.",
      "Вложенность не запрещена, но её следует минимизировать.",
      "Псевдоклассы не заменяют вложенность.",
    ],
    moduleId: "css",
    sectionTitle: "Методологии (BEM)",
    topic: "css_methodologies",
  },
  {
    id: "css_methodologies_12",
    title:
      "Какой синтаксис используют для описания состояния с помощью модификатора BEM?",
    options: [
      ".button--active",
      ".button_state_active",
      ".button__active",
      ".button-active",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: .button--active — корректный синтаксис модификатора состояния.",
      "Неправильно: одинарное подчеркивание не соответствует BEM.",
      "__ предназначено для элементов, а не для состояний.",
      "- используется в некоторых методологиях, но не BEM.",
    ],
    moduleId: "css",
    sectionTitle: "Методологии (BEM)",
    topic: "css_methodologies",
  },
  {
    id: "css_methodologies_13",
    title:
      "Какой из подходов упрощает поиск и переиспользование стилей при увеличении команды разработчиков?",
    options: [
      "Жёсткие вложенные селекторы",
      "BEM-именование с понятной структурой",
      "Использование глобальных селекторов body *",
      "Отсутствие методологии",
    ],
    correctAnswers: [1],
    descriptions: [
      "Глубокая вложенность усложняет поддержку.",
      "Правильно: BEM-структура повышает читаемость и переиспользуемость, особенно в больших командах.",
      "Глобальные селекторы ведут к конфликтам стилей.",
      "Без методологии код быстро становится хаотичным.",
    ],
    moduleId: "css",
    sectionTitle: "Методологии (BEM)",
    topic: "css_methodologies",
  },
  {
    id: "css_methodologies_14",
    title: "В чем преимущество явного разделения на Block и Element в BEM?",
    options: [
      "CSS-файл становится меньше",
      "Избегается конфликт имен и облегчается переиспользование",
      "Производительность браузера улучшается",
      "Шрифты подключаются автоматически",
    ],
    correctAnswers: [1],
    descriptions: [
      "Размер файла зависит от объема кода, а не от структуры.",
      "Правильно: разделение предотвращает пересечение стилей и упрощает повторное использование компонентов.",
      "Производительность зависит от оптимизации, а не от разделения имен.",
      "Шрифты не зависят от BEM.",
    ],
    moduleId: "css",
    sectionTitle: "Методологии (BEM)",
    topic: "css_methodologies",
  },
  {
    id: "css_methodologies_15",
    title: "Что такое «Flat structure» в контексте CSS-методологий?",
    options: [
      "Иерархия папок в проекте",
      "Минимизация вложенности селекторов",
      "Особый вид препроцессора",
      "Метод сокращения имен классов",
    ],
    correctAnswers: [1],
    descriptions: [
      "Flat structure не описывает организацию папок.",
      "Правильно: Flat structure означает избегать глубокой вложенности селекторов для упрощения кода.",
      "Препроцессор — это инструмент, а не структура.",
      "Сокращение имен — не Flat structure.",
    ],
    moduleId: "css",
    sectionTitle: "Методологии (BEM)",
    topic: "css_methodologies",
  },
  {
    id: "css_methodologies_16",
    title:
      "Как называется подход, где стили привязаны к структуре HTML с помощью атрибутов data-?",
    options: ["OOCSS", "SMACSS", "Data-attribute методология", "Atomic CSS"],
    correctAnswers: [2],
    descriptions: [
      "OOCSS основывается на объектоориентированном CSS, а не data-атрибутах.",
      "SMACSS не привязан к data-атрибутам.",
      "Правильно: в таком подходе часто используют data-атрибуты для обозначения компонента/блока.",
      "Atomic CSS использует одиночные классы для каждого свойства, а не data-атрибуты.",
    ],
    moduleId: "css",
    sectionTitle: "Методологии (BEM)",
    topic: "css_methodologies",
  },
  {
    id: "css_methodologies_17",
    title: "Какой из элементов BEM нельзя использовать без блока?",
    options: ["__element", "--modifier", "body", "container"],
    correctAnswers: [0],
    descriptions: [
      "Правильно: элемент обозначается как block__element и без блока не существует.",
      "Модификатор может применяться к блоку, но без блока бессмысленен.",
      "body — это тег HTML, не элемент BEM.",
      "container — это произвольное имя, не BEM-элемент.",
    ],
    moduleId: "css",
    sectionTitle: "Методологии (BEM)",
    topic: "css_methodologies",
  },
  {
    id: "css_methodologies_18",
    title:
      "Что рекомендуется делать при переопределении стилей одного блока в другом по BEM?",
    options: [
      "Использовать !important",
      "Создать новый блок с собственными именами классов",
      "Добавить вложенный селектор",
      "Использовать ID",
    ],
    correctAnswers: [1],
    descriptions: [
      "!important усложняет поддержку и не рекомендуется.",
      "Правильно: если блок нужно существенно переопределить, лучше создать новый блок, а не перекрывать стили.",
      "Вложенность приведёт к слишком специфичным селекторам.",
      "ID приоритетнее, но не решает задачу переопределения BEM.",
    ],
    moduleId: "css",
    sectionTitle: "Методологии (BEM)",
    topic: "css_methodologies",
  },
  {
    id: "css_methodologies_19",
    title:
      "Какой из подходов предполагает разделение стилей на объекты и модули, а не блоки?",
    options: ["BEM", "OOCSS", "SMACSS", "Atomic CSS"],
    correctAnswers: [2],
    descriptions: [
      "BEM работает с блоками, элементами и модификаторами.",
      "OOCSS фокусируется на объектов, но не разделяет на модули.",
      "Правильно: SMACSS разделяет стили на Base, Layout, Module, State, Theme, акцентируя объекты и модули.",
      "Atomic CSS использует утилитарные классы, а не объекты-модули.",
    ],
    moduleId: "css",
    sectionTitle: "Методологии (BEM)",
    topic: "css_methodologies",
  },
  {
    id: "css_methodologies_20",
    title:
      "Какой подход рекомендует делить CSS на категории, такие как «Base», «Layout» и «Module»?",
    options: ["OOCSS", "BEM", "SMACSS", "ITCSS"],
    correctAnswers: [2],
    descriptions: [
      "OOCSS фокусируется на объектно-ориентированном подходе, но не на категориях Base/Layout.",
      "BEM описывает именование, а не категорию файлов.",
      "Правильно: SMACSS предлагает категorizовать стили на Base, Layout, Module, State, Theme.",
      "ITCSS — это другая методология, организующая по слоям, но не точно так.",
    ],
    moduleId: "css",
    sectionTitle: "Методологии (BEM)",
    topic: "css_methodologies",
  },
  {
    id: "css_methodologies_21",
    title: "Какой синтаксис корректен для блока в BEM?",
    options: [".button", ".button__icon", ".button--large", ".button_icon"],
    correctAnswers: [0],
    descriptions: [
      "Правильно: .button — это блок в BEM.",
      ".button__icon — это элемент блока, а не сам блок.",
      ".button--large — это модификатор блока, а не сам блок.",
      ".button_icon — не соответствует синтаксису BEM.",
    ],
    moduleId: "css",
    sectionTitle: "Методологии (BEM)",
    topic: "css_methodologies",
  },
  {
    id: "css_methodologies_22",
    title: "Какой синтаксис корректен для элемента блока в BEM?",
    options: [".button__icon", ".button-icon", ".button--icon", ".button_icon"],
    correctAnswers: [0],
    descriptions: [
      "Правильно: .button__icon — элемент icon внутри блока button.",
      ".button-icon — не BEM-синтаксис.",
      ".button--icon — это модификатор, а не элемент.",
      ".button_icon — не соответствует правилам BEM.",
    ],
    moduleId: "css",
    sectionTitle: "Методологии (BEM)",
    topic: "css_methodologies",
  },
  {
    id: "css_methodologies_23",
    title: "Какой синтаксис корректен для модификатора блока в BEM?",
    options: [
      ".button--large",
      ".button_large",
      ".button__large",
      ".button-large",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: .button--large — модификатор large для блока button.",
      ".button_large — не BEM-синтаксис.",
      ".button__large — это синтаксис для элементов, а не модификаторов.",
      ".button-large — не соответствует BEM.",
    ],
    moduleId: "css",
    sectionTitle: "Методологии (BEM)",
    topic: "css_methodologies",
  },
  {
    id: "css_methodologies_24",
    title: "Чему соответствует .card__header--dark в BEM?",
    options: [
      "Элемент header блока card с модификатором dark",
      "Блок header с модификатором dark внутри карточки",
      "Модификатор dark для элемента card__header",
      "Неверный синтаксис",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: .card__header--dark — это элемент header блока card с модификатором dark.",
      "Нет: header не является блоком, а элементом блока card.",
      "Технически верно, но корректнее понимать полную структуру: элемент header внутри блока card получает состояние dark.",
      "Синтаксис верный, так что этот вариант неверен.",
    ],
    moduleId: "css",
    sectionTitle: "Методологии (BEM)",
    topic: "css_methodologies",
  },
  {
    id: "css_methodologies_25",
    title: "Какой из вариантов НЕ соответствует правилам BEM?",
    options: [
      ".menu__item--active",
      ".menu-item__active",
      ".menu__item_active",
      ".menu--active",
    ],
    correctAnswers: [2],
    descriptions: [
      ".menu__item--active — корректный элемент menu__item с модификатором active.",
      ".menu-item__active — неверно, дефис перед __ не соответствует BEM.",
      "Правильно: .menu__item_active — неверный синтаксис, используется _ вместо --.",
      ".menu--active — корректный модификатор active блока menu.",
    ],
    moduleId: "css",
    sectionTitle: "Методологии (BEM)",
    topic: "css_methodologies",
  },
  {
    id: "css_methodologies_26",
    title: "В каком порядке располагаются части имени в классе BEM?",
    options: [
      "блок__элемент--модификатор",
      "элемент__блок--модификатор",
      "блок--модификатор__элемент",
      "модификатор--блок__элемент",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: правильный синтаксис — имя блока, затем __элемент, затем --модификатор.",
      "Неверно: элемент не может идти перед блоком.",
      "Неверно: модификатор идёт после элемента, а не перед.",
      "Неверно: порядок частей должен быть блок → элемент → модификатор.",
    ],
    moduleId: "css",
    sectionTitle: "Методологии (BEM)",
    topic: "css_methodologies",
  },
  {
    id: "css_methodologies_27",
    title: "Как нужно именовать класс, если элемент имеет два модификатора?",
    options: [
      ".button--primary--large",
      ".button__icon--small--dark",
      ".button__icon--small.button__icon--dark",
      ".button__icon-small-dark",
    ],
    correctAnswers: [2],
    descriptions: [
      "Неверно: два модификатора разделяются через точку, а не цепочкой.",
      "Неправильно: блок__элемент--m1--m2 не соответствует BEM.",
      "Правильно: для двух модификаторов используется два отдельных класса: .button__icon--small и .button__icon--dark.",
      "Неверно: отсутствуют разделители __ и --, синтаксис неправильный.",
    ],
    moduleId: "css",
    sectionTitle: "Методологии (BEM)",
    topic: "css_methodologies",
  },
  {
    id: "css_methodologies_28",
    title: "Какой из вариантов правильнее для элемента без модификатора?",
    options: [".header", ".header__", ".header__title", ".header--title"],
    correctAnswers: [2],
    descriptions: [
      "Неверно: .header может быть блоком, но вопрос об элементе.",
      "Неверно: '__' без имени элемента невалидно.",
      "Правильно: .header__title — элемент title внутри блока header.",
      "Неверно: -- используется для модификаторов, а не для элементов.",
    ],
    moduleId: "css",
    sectionTitle: "Методологии (BEM)",
    topic: "css_methodologies",
  },
  {
    id: "css_methodologies_29",
    title: "Как именуется элемент, если сам блок называется .navigation-menu?",
    options: [
      ".navigation-menu__item",
      ".navigation__menu-item",
      ".navigation-menu-item",
      ".navigation-menu--item",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: .navigation-menu__item — элемент item внутри блока navigation-menu.",
      "Неверно: имя блока разбито неправильно, двойное слово navigation-menu должно оставаться единым.",
      "Неверно: отсутствует разделитель __ перед именем элемента.",
      "Неверно: модификатор обозначается --, а не __.",
    ],
    moduleId: "css",
    sectionTitle: "Методологии (BEM)",
    topic: "css_methodologies",
  },
  {
    id: "css_methodologies_30",
    title:
      "Как корректно задать два элемента последовательно внутри одного блока?",
    options: [
      ".card__header__title",
      ".card__header .card__title",
      ".card__header__title--large",
      ".card__header--title__large",
    ],
    correctAnswers: [1],
    descriptions: [
      "Неверно: двойное __ для вложенных элементов не по BEM.",
      "Правильно: элементы находятся на одном уровне, используются два класса c элементами блока card.",
      "Неверно: содержит и элемент, и модификатор, а не два элемента.",
      "Неверно: нарушение порядка частей BEM (модификатор располагается неправильно).",
    ],
    moduleId: "css",
    sectionTitle: "Методологии (BEM)",
    topic: "css_methodologies",
  },
  {
    id: "css_methodologies_31",
    title: "Что означает класс .form__input--disabled в BEM?",
    options: [
      "Блок form, элемент input с состоянием disabled",
      "Элемент input блока form удалён",
      "Модификатор disabled для блока form",
      "Неверный синтаксис",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: .form__input--disabled — элемент input внутри блока form в состоянии disabled.",
      "Неправильно: это не указывает удаление элемента.",
      "Неправильно: disabled — модификатор для элемента, а не для блока.",
      "Синтаксис корректен, значит вариант неверен.",
    ],
    moduleId: "css",
    sectionTitle: "Методологии (BEM)",
    topic: "css_methodologies",
  },
  {
    id: "css_methodologies_32",
    title:
      "Как лучше всего изменить цвет фона блока .card при модификаторе error?",
    options: [
      ".card_error { background: red; }",
      ".card--error { background: red; }",
      ".card__error { background: red; }",
      ".card.error { background: red; }",
    ],
    correctAnswers: [1],
    descriptions: [
      "Неверно: одинарное подчеркивание не по BEM.",
      "Правильно: .card--error — модификатор error для блока card.",
      "Неверно: __ используется для элементов, а не модификаторов.",
      "Неправильно: класс .card.error означает блок card и отдельный класс error, а не BEM-модификатор.",
    ],
    moduleId: "css",
    sectionTitle: "Методологии (BEM)",
    topic: "css_methodologies",
  },
  {
    id: "css_methodologies_33",
    title:
      "Какой из вариантов определяет элемент title, принадлежащий блоку header, и модификатор large?",
    options: [
      ".header__title--large",
      ".header__title_large",
      ".header--title__large",
      ".header_title--large",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: .header__title--large — элемент title внутри блока header с модификатором large.",
      "Неверно: одинарное подчеркивание не по BEM.",
      "Неверно: порядок частей нарушен (модификатор должен идти после __element).",
      "Неверно: лишнее подчеркивание в имени блока.",
    ],
    moduleId: "css",
    sectionTitle: "Методологии (BEM)",
    topic: "css_methodologies",
  },
  {
    id: "css_methodologies_34",
    title:
      "Какой класс соответствует блоку card, если карточка имеет состояние selected?",
    options: [
      ".card_selected",
      ".card--selected",
      ".card__selected",
      ".card-selected",
    ],
    correctAnswers: [1],
    descriptions: [
      "Неверно: одинарное подчеркивание не по стандарту.",
      "Правильно: .card--selected — модификатор selected для блока card.",
      "Неверно: __ используется для элементов, а не модификаторов.",
      "Неверно: дефис вместо -- не соответствует BEM.",
    ],
    moduleId: "css",
    sectionTitle: "Методологии (BEM)",
    topic: "css_methodologies",
  },
  {
    id: "css_methodologies_35",
    title:
      "Что произойдёт, если у элемента .list__item не указать родительский блок в имени класса?",
    options: [
      "CSS все равно найдёт родительский блок",
      "Стили элемента могут примениться к любому элементу с таким классом",
      "Будет синтаксическая ошибка",
      "Элемент станет глобальным",
    ],
    correctAnswers: [1],
    descriptions: [
      "CSS не распознаёт BEM-иерархию без блока в имени.",
      "Правильно: .list__item без упоминания родительского блока становится просто классом list__item и применяется к любому элементу с таким именем.",
      "Нет: синтаксически это допустимый класс.",
      "Неправильно: глобальность не зависит от имени BEM.",
    ],
    moduleId: "css",
    sectionTitle: "Методологии (BEM)",
    topic: "css_methodologies",
  },
  {
    id: "css_methodologies_36",
    title:
      "Какое правило рекомендуют соблюдать, чтобы избежать «спагетти»-кода в BEM?",
    options: [
      "Каждому блоку заводить отдельный SCSS-файл",
      "Стараться не более чем два уровня вложенности",
      "Использовать только один модификатор на блок",
      "Не использовать элементы",
    ],
    correctAnswers: [1],
    descriptions: [
      "Правило количество файлов не обязательное, но часто используется.",
      "Правильно: избегая глубокой вложенности, сохраняется понятность и независимость блоков.",
      "Можно использовать несколько модификаторов, это не является ошибкой.",
      "Элементы — ключевая часть BEM, их нельзя игнорировать.",
    ],
    moduleId: "css",
    sectionTitle: "Методологии (BEM)",
    topic: "css_methodologies",
  },
  {
    id: "css_methodologies_37",
    title:
      "Какой из вариантов класса описывает два элемента списка внутри одного блока без дублирования блока?",
    options: [
      ".menu__item, .menu__link",
      ".menu_item, .menu_link",
      ".menu__item__link",
      ".menu--item--link",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: .menu__item и .menu__link — два отдельных элемента menu.",
      "Неверно: подписи не соответствуют BEM-синтаксису.",
      "Неверно: двойное __ не поддерживается для вложенных элементов разных типов.",
      "Неверно: -- предназначен для модификаторов, а не для элементов.",
    ],
    moduleId: "css",
    sectionTitle: "Методологии (BEM)",
    topic: "css_methodologies",
  },
  {
    id: "css_methodologies_38",
    title: "Что обозначает класс .form__input--error?",
    options: [
      "Модификатор error для элемента form__input",
      "Новый блок input внутри form",
      "Узел дерева form с классом input-error",
      "Элемент input со свойством error",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: .form__input--error указывает, что элемент input в блоке form находится в состоянии error.",
      "Неверно: input — это элемент, а не блок.",
      "Неверно: это не дерево узлов, а BEM-иерархия.",
      "Неверно: error — не свойство, а модификатор BEM.",
    ],
    moduleId: "css",
    sectionTitle: "Методологии (BEM)",
    topic: "css_methodologies",
  },
  {
    id: "css_methodologies_39",
    title:
      "Какой вариант правильно отражает вложенность элементов внутри блока согласно BEM?",
    options: [
      ".card__header, .card__body, .card__footer",
      ".card__header__title, .card__header__subtitle",
      ".card__header__title--large, .card__header__subtitle--small",
      ".card--header__title, .card--header__subtitle",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: элементы header, body и footer внутри блока card перечисляются отдельно.",
      "Неверно: двойное __ для вложенного элемента некорректно.",
      "Неверно: модификаторы применяются к элементам, но вложенный синтаксис с двойным __ неверен.",
      "Неверно: модификатор должен идти после блока или элемента, а не перед __element.",
    ],
    moduleId: "css",
    sectionTitle: "Методологии (BEM)",
    topic: "css_methodologies",
  },
  {
    id: "css_methodologies_40",
    title: "Какой способ рекомендуют для создания темы (theme) в BEM?",
    options: [
      "Использовать модификаторы, например .button--dark, .button--light",
      "Создавать новые блоки с префиксом theme-",
      "Вложенные селекторы .theme .button",
      "Использовать ID для темы",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: темы часто реализуют через модификаторы BEM, например .button--dark и .button--light.",
      "Неверно: блок theme- создаёт лишнюю сущность, не по BEM.",
      "Неверно: вложенность усложняет поддержку и не соответствует BEM.",
      "Неверно: использование ID не является частью BEM.",
    ],
    moduleId: "css",
    sectionTitle: "Методологии (BEM)",
    topic: "css_methodologies",
  },
];
