export const cssPreprocessorsQuestions = [
  {
    id: "css_preprocessors_1",
    title: "Что такое CSS-препроцессор?",
    options: [
      "Инструмент, преобразующий расширенный синтаксис CSS в обычный CSS",
      "Браузерный плагин для ускорения CSS",
      "Фреймворк для создания UI",
      "Серверное приложение для хостинга файлов",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: препроцессор принимает вложенный и расширенный синтаксис и компилирует в стандартный CSS.",
      "Плагин браузера не преобразует код перед загрузкой.",
      "UI-фреймворки (Bootstrap, Material) — другое.",
      "Серверное приложение не относится к препроцессорам.",
    ],
    moduleId: "css",
    sectionTitle: "Препроцессоры (Sass/Less)",
    topic: "css_preprocessors",
  },
  {
    id: "css_preprocessors_2",
    title: "Какой из перечисленных является популярным CSS-препроцессором?",
    options: ["Sass", "React", "Webpack", "Node.js"],
    correctAnswers: [0],
    descriptions: [
      "Правильно: Sass — один из наиболее распространённых препроцессоров.",
      "React — библиотека JavaScript для UI, не препроцессор.",
      "Webpack — сборщик модулей, не препроцессор.",
      "Node.js — среда выполнения JavaScript, не препроцессор.",
    ],
    moduleId: "css",
    sectionTitle: "Препроцессоры (Sass/Less)",
    topic: "css_preprocessors",
  },
  {
    id: "css_preprocessors_3",
    title: "Какой файл является корректным Sass-файлом в синтаксисе SCSS?",
    options: ["styles.scss", "styles.sass", "styles.css", "styles.scs"],
    correctAnswers: [0],
    descriptions: [
      "Правильно: .scss — синтаксис Sass, совместимый с CSS.",
      ".sass — другая разновидность синтаксиса (Sass без фигурных скобок).",
      ".css — чистый CSS, а не Sass.",
      ".scs — несуществующее расширение.",
    ],
    moduleId: "css",
    sectionTitle: "Препроцессоры (Sass/Less)",
    topic: "css_preprocessors",
  },
  {
    id: "css_preprocessors_4",
    title:
      "Какое расширение файла используется для синтаксиса Sass без фигурных скобок?",
    options: [".sass", ".scss", ".less", ".styl"],
    correctAnswers: [0],
    descriptions: [
      "Правильно: .sass — исходный синтаксис Sass без фигур и точек с запятой.",
      ".scss — более популярный синтаксис с фигурными скобками.",
      ".less — расширение для Less-препроцессора.",
      ".styl — расширение для Stylus-препроцессора.",
    ],
    moduleId: "css",
    sectionTitle: "Препроцессоры (Sass/Less)",
    topic: "css_preprocessors",
  },
  {
    id: "css_preprocessors_5",
    title: "Какая команда устанавливает Sass через npm?",
    options: [
      "npm install -g sass",
      "npm install -g css",
      "npm install -g postcss",
      "npm install -g bootstrap",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: npm install -g sass устанавливает Dart Sass глобально.",
      "css не является пакетным менеджером для препроцессора.",
      "postcss — плагинный инструмент, а не сам Sass.",
      "bootstrap — это фреймворк, не препроцессор.",
    ],
    moduleId: "css",
    sectionTitle: "Препроцессоры (Sass/Less)",
    topic: "css_preprocessors",
  },
  {
    id: "css_preprocessors_6",
    title: "Какой синтаксис правильно объявляет переменную в SCSS?",
    options: [
      "$primary-color: #3498db;",
      "@primary-color: #3498db;",
      "%primary-color: #3498db;",
      "&primary-color: #3498db;",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: в SCSS переменные начинаются с $.",
      "@ используется для директив, а не переменных.",
      "% используется для placeholder-селекторов, а не переменных.",
      "& применяется внутри вложенности для родительского селектора.",
    ],
    moduleId: "css",
    sectionTitle: "Препроцессоры (Sass/Less)",
    topic: "css_preprocessors",
  },
  {
    id: "css_preprocessors_7",
    title: "Какой синтаксис позволяет вложить селектор .nav внутри .header?",
    options: [
      ".header { .nav { ... } }",
      ".header .nav { ... }",
      ".header > .nav { ... }",
      "nest(.nav) in .header",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: в SCSS можно написать селектор внутри другого блока.",
      "Это обычный CSS-селектор без вложенности.",
      "Это CSS-селектор c комбинацией child, не SCSS-вложенность.",
      "nest(...) не является валидным SCSS.",
    ],
    moduleId: "css",
    sectionTitle: "Препроцессоры (Sass/Less)",
    topic: "css_preprocessors",
  },
  {
    id: "css_preprocessors_8",
    title: "Как импортировать файл _variables.scss в main.scss?",
    options: [
      "@import 'variables';",
      "@import '_variables.scss';",
      "import 'variables';",
      "@include 'variables';",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: в SCSS при импорте не указывают подчёркивание и расширение.",
      "Нужно опустить подчёркивание и расширение.",
      "import — не валидная директива в SCSS.",
      "@include используется для миксинов, а не для файлов.",
    ],
    moduleId: "css",
    sectionTitle: "Препроцессоры (Sass/Less)",
    topic: "css_preprocessors",
  },
  {
    id: "css_preprocessors_9",
    title: "Какой синтаксис задаёт миксин button-styles с параметром $color?",
    options: [
      "@mixin button-styles($color) { ... }",
      ".mixin button-styles($color) { ... }",
      "@include mixin button-styles($color) { ... }",
      "@mixin button-styles color { ... }",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: @mixin имя(параметры) { ... }.",
      ".mixin не является корректным ключевым словом.",
      "@include используется для вызова, а не объявления.",
      "Нужно заключать параметр в круглые скобки.",
    ],
    moduleId: "css",
    sectionTitle: "Препроцессоры (Sass/Less)",
    topic: "css_preprocessors",
  },
  {
    id: "css_preprocessors_10",
    title: "Как подключить миксин button-styles к селектору .btn?",
    options: [
      ".btn { @include button-styles(#e74c3c); }",
      ".btn { @mixin button-styles(#e74c3c); }",
      ".btn { include button-styles #e74c3c; }",
      ".btn { @call button-styles(#e74c3c); }",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: для вызова миксина используют @include имя(аргументы).",
      "@mixin используется для объявления, а не вызова.",
      "include без @ не является валидным.",
      "@call не является синтаксисом SCSS.",
    ],
    moduleId: "css",
    sectionTitle: "Препроцессоры (Sass/Less)",
    topic: "css_preprocessors",
  },
  {
    id: "css_preprocessors_11",
    title: "Что делает оператор & внутри вложенного селектора?",
    options: [
      "Ссылается на родительский селектор",
      "Ссылается на корневой селектор html",
      "Отключает вложенность",
      "Применяет стили только при hover",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: & используется для подстановки полного родительского селектора.",
      "& не ссылается на html, а на непосредственный родитель.",
      "& не отключает вложенность, а уточняет её.",
      "& не связан с hover-псевдоклассом напрямую.",
    ],
    moduleId: "css",
    sectionTitle: "Препроцессоры (Sass/Less)",
    topic: "css_preprocessors",
  },
  {
    id: "css_preprocessors_12",
    title:
      "Какой синтаксис объявляет функцию my-func в SCSS, возвращающую значение $x * 2?",
    options: [
      "@function my-func($x) { @return $x * 2; }",
      "@mixin my-func($x) { @return $x * 2; }",
      "@function my-func $x { return $x * 2; }",
      "@return my-func($x) { $x * 2; }",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: @function имя(параметры) { @return выражение; }.",
      "@mixin не возвращает значение, а вставляет стили.",
      "Нужно использовать скобки и @return.",
      "Неверный синтаксис: return должно идти внутри функции.",
    ],
    moduleId: "css",
    sectionTitle: "Препроцессоры (Sass/Less)",
    topic: "css_preprocessors",
  },
  {
    id: "css_preprocessors_13",
    title:
      "Как использовать возвращённое значение из функции my-func в свойстве width?",
    options: [
      ".box { width: my-func(10px); }",
      ".box { width: call(my-func, 10px); }",
      ".box { width: func(my-func(10px)); }",
      ".box { width: $my-func(10px); }",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: при вызове функции просто указываем её имя с аргументом.",
      "call() не является валидным в SCSS.",
      "func() не поддерживается.",
      "Нельзя вызывать функцию через $.",
    ],
    moduleId: "css",
    sectionTitle: "Препроцессоры (Sass/Less)",
    topic: "css_preprocessors",
  },
  {
    id: "css_preprocessors_14",
    title: "Как импортировать несколько файлов в одном @import?",
    options: [
      "@import 'variables', 'mixins';",
      "@import 'variables' 'mixins';",
      "@import ( 'variables', 'mixins' );",
      "@import all 'variables', 'mixins';",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: перечисляем имена через запятую внутри @import.",
      "Нужно ставить запятую между строками.",
      "Неправильный синтаксис, не нужны скобки.",
      "no such syntax",
    ],
    moduleId: "css",
    sectionTitle: "Препроцессоры (Sass/Less)",
    topic: "css_preprocessors",
  },
  {
    id: "css_preprocessors_15",
    title: "Что такое partial-файл в контексте Sass?",
    options: [
      "Файл, имя которого начинается с подчёркивания и который импортируется, а не компилируется отдельно",
      "Файл, который самостоятельно компилируется в CSS",
      "Файл формата .css с расширенным синтаксисом",
      "Полный стиль, не требующий дополнительных импортов",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: partial (начинается с _) предназначен только для импорта в другие файлы.",
      "partial-файлы не компилируются отдельно.",
      ".css-файл не является Sass partial.",
      "Partial-файл не содержит полный набор стилей.",
    ],
    moduleId: "css",
    sectionTitle: "Препроцессоры (Sass/Less)",
    topic: "css_preprocessors",
  },
  {
    id: "css_preprocessors_16",
    title: "Какой флаг командной строки запускает watch-режим для Sass?",
    options: [
      "sass --watch input.scss:output.css",
      "sass --compile input.scss:output.css",
      "sass --serve input.scss:output.css",
      "sass --live input.scss:output.css",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: --watch следит за изменениями и перекомпилирует.",
      "--compile (нет такого флага) компиляция выполняется по умолчанию.",
      "--serve не является стандартным флагом Sass.",
      "--live не поддерживается Sass.",
    ],
    moduleId: "css",
    sectionTitle: "Препроцессоры (Sass/Less)",
    topic: "css_preprocessors",
  },
  {
    id: "css_preprocessors_17",
    title:
      "Какой девелоперский инструмент позволяет сжимать итоговый CSS при компиляции Sass?",
    options: [
      "--style compressed",
      "--minify true",
      "--compress-css",
      "--optimize",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: --style compressed задаёт минификацию.",
      "--minify не является валидным флагом для Dart Sass.",
      "--compress-css не поддерживается.",
      "--optimize не используется в Sass CLI.",
    ],
    moduleId: "css",
    sectionTitle: "Препроцессоры (Sass/Less)",
    topic: "css_preprocessors",
  },
  {
    id: "css_preprocessors_18",
    title: "Что делает директива @extend в Sass?",
    options: [
      "Позволяет одному селектору перенять стили другого селектора",
      "Изменяет цвет текста на расширенный",
      "Добавляет новый миксин",
      "Импортирует CSS из внешнего файла",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: @extend переносит блок свойств из указанного селектора.",
      "Неверно: цвет текста не связан с extend.",
      "extend не создаёт миксин, он наследует стили.",
      "@extend не импортирует файлы.",
    ],
    moduleId: "css",
    sectionTitle: "Препроцессоры (Sass/Less)",
    topic: "css_preprocessors",
  },
  {
    id: "css_preprocessors_19",
    title: "Как заставить Sass компилировать без sourcemap?",
    options: [
      "sass input.scss output.css --no-source-map",
      "sass input.scss output.css --skip-map",
      "sass input.scss output.css --disable-sourcemap",
      "sass input.scss output.css --no-map",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: --no-source-map отключает генерацию sourcemap.",
      "--skip-map не поддерживается Sass CLI.",
      "--disable-sourcemap не является валидным флагом.",
      "--no-map не распознаётся Sass.",
    ],
    moduleId: "css",
    sectionTitle: "Препроцессоры (Sass/Less)",
    topic: "css_preprocessors",
  },
  {
    id: "css_preprocessors_20",
    title: "Почему стоит использовать препроцессоры вместо чистого CSS?",
    options: [
      "Для удобного управления переменными, вложенности и логикой",
      "Для ускорения загрузки страниц на сервере",
      "Для замены JavaScript в браузере",
      "Для создания адаптивных изображений",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: препроцессоры дают переменные, функции, вложенность и упрощают поддержку.",
      "Препроцессоры не влияют напрямую на время загрузки на сервере.",
      "Препроцессоры не заменяют JavaScript.",
      "Работа с изображениями — не задача препроцессоров.",
    ],
    moduleId: "css",
    sectionTitle: "Препроцессоры (Sass/Less)",
    topic: "css_preprocessors",
  },
];
