export const cssPseudoQuestions = [
  {
    id: "css_pseudo_1",
    title: "Какой псевдокласс применяется при наведении курсора на элемент?",
    options: [":active", ":hover", ":focus", ":visited"],
    correctAnswers: [1],
    descriptions: [
      ":active активируется при нажатии мыши, а не при наведении.",
      "Правильно: :hover применяется, когда курсор находится над элементом.",
      ":focus активируется при фокусе (например, при табе), но не при наведении.",
      ":visited применяется к ссылкам, которые уже были посещены.",
    ],
    moduleId: "css",
    sectionTitle: "Псевдоклассы и псевдоэлемены",
    topic: "css_pseudo",
  },
  {
    id: "css_pseudo_2",
    title:
      "Какой псевдокласс применяется к элементу формы, когда он активен (например, нажат)?",
    options: [":focus", ":hover", ":active", ":checked"],
    correctAnswers: [2],
    descriptions: [
      ":focus означает, что элемент получил фокус, но не обязательно нажат.",
      ":hover активируется при наведении курсора.",
      "Правильно: :active активируется в момент удержания кнопки мыши на элементе.",
      ":checked применяется к отмеченным элементам (checkbox, radio).",
    ],
    moduleId: "css",
    sectionTitle: "Псевдоклассы и псевдоэлемены",
    topic: "css_pseudo",
  },
  {
    id: "css_pseudo_3",
    title:
      "Какой псевдокласс используется, чтобы стилизовать посещённую ссылку?",
    options: [":link", ":visited", ":focus", ":hover"],
    correctAnswers: [1],
    descriptions: [
      ":link применяется к любой ссылке, которую ещё не посещали.",
      "Правильно: :visited применяется к ссылкам, которые пользователь уже посещал.",
      ":focus активируется при получении фокуса, не про посещение ссылок.",
      ":hover — при наведении курсора, не про состояние посещения.",
    ],
    moduleId: "css",
    sectionTitle: "Псевдоклассы и псевдоэлемены",
    topic: "css_pseudo",
  },
  {
    id: "css_pseudo_4",
    title:
      "Какой псевдокласс выбирает первый дочерний элемент своего родителя?",
    options: [":last-child", ":nth-child(1)", ":first-child", ":only-child"],
    correctAnswers: [2],
    descriptions: [
      ":last-child выбирает последний дочерний элемент.",
      ":nth-child(1) тоже выбирает первый, но правильнее использовать :first-child для ясности.",
      "Правильно: :first-child применяет стиль к первому дочернему элементу.",
      ":only-child применяется, когда элемент является единственным ребёнком своего родителя.",
    ],
    moduleId: "css",
    sectionTitle: "Псевдоклассы и псевдоэлемены",
    topic: "css_pseudo",
  },
  {
    id: "css_pseudo_5",
    title: "Какой псевдокласс выбирает последний дочерний элемент?",
    options: [
      ":last-child",
      ":nth-last-child(1)",
      ":first-child",
      ":only-of-type",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: :last-child выбирает последний дочерний элемент.",
      ":nth-last-child(1) тоже выбирает последний, но :last-child более семантичен.",
      ":first-child выбирает первый, не последний.",
      ":only-of-type выбирает элемент, если он единственный своего типа среди братьев.",
    ],
    moduleId: "css",
    sectionTitle: "Псевдоклассы и псевдоэлемены",
    topic: "css_pseudo",
  },
  {
    id: "css_pseudo_6",
    title:
      "Какой псевдокласс выбирает элементы, у которых нет дочерних элементов?",
    options: [":empty", ":blank", ":only-child", ":only-of-type"],
    correctAnswers: [0],
    descriptions: [
      "Правильно: :empty выбирает элементы без дочерних узлов и текста.",
      ":blank не является стандартным псевдоклассом.",
      ":only-child выбирает единственного ребёнка, но не проверяет наличие потомков.",
      ":only-of-type выбирает, если элемент — единственный своего типа среди братьев.",
    ],
    moduleId: "css",
    sectionTitle: "Псевдоклассы и псевдоэлемены",
    topic: "css_pseudo",
  },
  {
    id: "css_pseudo_7",
    title:
      "Какой псевдокласс выбирает элементы с идентификатором target при использовании якоря?",
    options: [":link", ":target", ":hover", ":active"],
    correctAnswers: [1],
    descriptions: [
      ":link относится к ссылкам, не к целевому якорю.",
      "Правильно: :target выбирает элемент, соответствующий текущему фрагменту URL (#id).",
      ":hover — для наведения курсора, не для якоря.",
      ":active — при нажатии, не для URL-фрагмента.",
    ],
    moduleId: "css",
    sectionTitle: "Псевдоклассы и псевдоэлемены",
    topic: "css_pseudo",
  },
  {
    id: "css_pseudo_8",
    title:
      "Какой псевдокласс выбирает все элементы с нечетным порядковым индексом (1-based) среди братьев?",
    options: [
      ":nth-child(even)",
      ":nth-child(odd)",
      ":first-of-type",
      ":last-of-type",
    ],
    correctAnswers: [1],
    descriptions: [
      ":nth-child(even) выбирает чётные (2,4,6...).",
      "Правильно: :nth-child(odd) выбирает нечетные (1,3,5...).",
      ":first-of-type выбирает первый элемент данного типа, а не по индексу.",
      ":last-of-type выбирает последний элемент данного типа.",
    ],
    moduleId: "css",
    sectionTitle: "Псевдоклассы и псевдоэлемены",
    topic: "css_pseudo",
  },
  {
    id: "css_pseudo_9",
    title:
      "Какой псевдокласс выбирает элементы форм, неактивные для взаимодействия?",
    options: [":disabled", ":enabled", ":readonly", ":checked"],
    correctAnswers: [0],
    descriptions: [
      "Правильно: :disabled выбирает элементы, у которых disabled.",
      ":enabled — противоположность :disabled.",
      ":readonly — для полей только для чтения, но не все неактивные.",
      ":checked — для отмеченных чекбоксов или радиокнопок.",
    ],
    moduleId: "css",
    sectionTitle: "Псевдоклассы и псевдоэлемены",
    topic: "css_pseudo",
  },
  {
    id: "css_pseudo_10",
    title:
      "Какой псевдокласс выбирает элементы форм, доступные для взаимодействия?",
    options: [":disabled", ":enabled", ":readonly", ":invalid"],
    correctAnswers: [1],
    descriptions: [
      ":disabled — наоборот, неактивные.",
      "Правильно: :enabled выбирает элементы, которые не disabled.",
      ":readonly — поля только для чтения, не обязательно интерактивные.",
      ":invalid — для элементов с неверным значением, а не про доступность.",
    ],
    moduleId: "css",
    sectionTitle: "Псевдоклассы и псевдоэлемены",
    topic: "css_pseudo",
  },
  {
    id: "css_pseudo_11",
    title: "Какой псевдокласс выбирает отмеченные чекбоксы или радиокнопки?",
    options: [":checked", ":selected", ":active", ":visited"],
    correctAnswers: [0],
    descriptions: [
      "Правильно: :checked применяется к отмеченным элементам типа checkbox или radio.",
      ":selected — для опций в select, но не для чекбоксов.",
      ":active — при нажатии, не про состояние отметки.",
      ":visited — для ссылок, не для форм.",
    ],
    moduleId: "css",
    sectionTitle: "Псевдоклассы и псевдоэлемены",
    topic: "css_pseudo",
  },
  {
    id: "css_pseudo_12",
    title:
      "Какой псевдокласс выбирает первый элемент данного типа среди братьев?",
    options: [
      ":first-of-type",
      ":first-child",
      ":nth-of-type(1)",
      ":only-of-type",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: :first-of-type выбирает первый элемент своего типа среди братьев.",
      ":first-child выбирает первого ребёнка независимо от типа.",
      ":nth-of-type(1) тоже выбирает первый по типу, но :first-of-type более семантичен.",
      ":only-of-type выбирает, если элемент единственный своего типа.",
    ],
    moduleId: "css",
    sectionTitle: "Псевдоклассы и псевдоэлемены",
    topic: "css_pseudo",
  },
  {
    id: "css_pseudo_13",
    title:
      "Какой псевдокласс выбирает элементы, являющиеся единственными среди братьев того же типа?",
    options: [
      ":only-child",
      ":only-of-type",
      ":first-of-type",
      ":last-of-type",
    ],
    correctAnswers: [1],
    descriptions: [
      ":only-child проверяет единственность относительно всех братьев, но не учитывает тип.",
      "Правильно: :only-of-type выбирает элемент, если нет других такого же тега среди братьев.",
      ":first-of-type выбирает первого по типу, но не проверяет единственность.",
      ":last-of-type выбирает последнего по типу, но не проверяет единственность.",
    ],
    moduleId: "css",
    sectionTitle: "Псевдоклассы и псевдоэлемены",
    topic: "css_pseudo",
  },
  {
    id: "css_pseudo_14",
    title:
      "Какой псевдокласс выбирает элемент, если у него нет потомков и текста?",
    options: [":empty", ":root", ":only-child", ":first-child"],
    correctAnswers: [0],
    descriptions: [
      "Правильно: :empty выбирает элементы без дочерних узлов и текста.",
      ":root выбирает корневой элемент документа (обычно <html>), а не пустоту.",
      ":only-child проверяет единственность, но может быть не пустым.",
      ":first-child выбирает первого ребёнка, а не пустой.",
    ],
    moduleId: "css",
    sectionTitle: "Псевдоклассы и псевдоэлемены",
    topic: "css_pseudo",
  },
  {
    id: "css_pseudo_15",
    title: "Какой псевдокласс выбирает корневой элемент документа?",
    options: [":root", ":html", ":first-child", ":last-child"],
    correctAnswers: [0],
    descriptions: [
      "Правильно: :root соответствует корневому узлу (обычно <html>).",
      ":html — не псевдокласс, а селектор тега.",
      ":first-child выбирает первого ребёнка, а не корень.",
      ":last-child — последнего ребёнка, не корень.",
    ],
    moduleId: "css",
    sectionTitle: "Псевдоклассы и псевдоэлемены",
    topic: "css_pseudo",
  },
  {
    id: "css_pseudo_16",
    title: "Какой псевдокласс выбирает опцию внутри select, которая выбрана?",
    options: [":checked", ":selected", ":disabled", ":focused"],
    correctAnswers: [1],
    descriptions: [
      ":checked — для чекбоксов и радиокнопок, не для <option>.",
      "Правильно: :selected выбирает текущую выбранную <option>.",
      ":disabled — для неактивных элементов, не для выбранных.",
      ":focused — для элементов с фокусом, не для выбранных.",
    ],
    moduleId: "css",
    sectionTitle: "Псевдоклассы и псевдоэлемены",
    topic: "css_pseudo",
  },
  {
    id: "css_pseudo_17",
    title:
      "Какой псевдокласс выбирает элементы формы с неверным значением (не прошедшие валидацию)?",
    options: [":valid", ":invalid", ":required", ":optional"],
    correctAnswers: [1],
    descriptions: [
      ":valid выбирает проходящие проверку, а не непрошающие.",
      "Правильно: :invalid выбирает элементы с невалидными значениями.",
      ":required выбирает обязательные поля, вне зависимости от валидности.",
      ":optional выбирает необязательные поля, не про валидацию.",
    ],
    moduleId: "css",
    sectionTitle: "Псевдоклассы и псевдоэлемены",
    topic: "css_pseudo",
  },
  {
    id: "css_pseudo_18",
    title:
      "Как задать селектор, который исключает определённый класс, например .no-style?",
    options: [
      ":not(.no-style)",
      ":exclude(.no-style)",
      ":unless(.no-style)",
      ":skip(.no-style)",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: :not(.no-style) выбирает все элементы, у которых нет класса .no-style.",
      ":exclude не существует в CSS.",
      ":unless не является стандартным псевдоклассом.",
      ":skip также не поддерживается.",
    ],
    moduleId: "css",
    sectionTitle: "Псевдоклассы и псевдоэлемены",
    topic: "css_pseudo",
  },
  {
    id: "css_pseudo_19",
    title:
      "Какой псевдокласс выбирает элементы, получившие фокус, например при табе?",
    options: [":focus", ":hover", ":active", ":visited"],
    correctAnswers: [0],
    descriptions: [
      "Правильно: :focus выбирает элемент, получивший фокус (например, input при Tab).",
      ":hover — при наведении курсора.",
      ":active — при нажатии мыши.",
      ":visited — для посещённых ссылок.",
    ],
    moduleId: "css",
    sectionTitle: "Псевдоклассы и псевдоэлемены",
    topic: "css_pseudo",
  },
  {
    id: "css_pseudo_20",
    title:
      "Какой псевдокласс выбирает элементы только первого уровня вложенности среди братьев (например, <li>)?",
    options: [":first-of-type", ":first-child", ":nth-child(1)", ":only-child"],
    correctAnswers: [1],
    descriptions: [
      ":first-of-type выбирает первый по типу, но не обязательно первый среди всех.",
      "Правильно: :first-child выбирает первый элемент среди всех детей родителя.",
      ":nth-child(1) тоже выбирает первый, но :first-child более семантичен.",
      ":only-child выбирает только когда элемент единственный ребёнок.",
    ],
    moduleId: "css",
    sectionTitle: "Псевдоклассы и псевдоэлемены",
    topic: "css_pseudo",
  },
  {
    id: "css_pseudo_21",
    title:
      "Какой псевдоэлемент применяется для вставки контента перед содержимым элемента?",
    options: ["::after", "::before", "::first-line", "::first-letter"],
    correctAnswers: [1],
    descriptions: [
      "::after вставляет содержимое после содержимого элемента.",
      "Правильно: ::before вставляет содержимое перед содержимым элемента.",
      "::first-line влияет на первую строку текста внутри элемента.",
      "::first-letter влияет на первую букву, а не вставляет контент.",
    ],
    moduleId: "css",
    sectionTitle: "Псевдоклассы и псевдоэлемены",
    topic: "css_pseudo",
  },
  {
    id: "css_pseudo_22",
    title:
      "Какой псевдоэлемент используется для вставки контента после содержимого элемента?",
    options: ["::before", "::after", "::placeholder", "::selection"],
    correctAnswers: [1],
    descriptions: [
      "::before вставляет перед содержимым, а не после.",
      "Правильно: ::after вставляет контент после содержимого элемента.",
      "::placeholder стилизует текст-заполнитель в полях формы.",
      "::selection стилизует выделенный пользователем текст.",
    ],
    moduleId: "css",
    sectionTitle: "Псевдоклассы и псевдоэлемены",
    topic: "css_pseudo",
  },
  {
    id: "css_pseudo_23",
    title: "Какой псевдоэлемент выбирает первую строку текста элемента?",
    options: ["::first-letter", "::first-line", "::before", "::marker"],
    correctAnswers: [1],
    descriptions: [
      "::first-letter влияет на первую букву, а не строку.",
      "Правильно: ::first-line выбирает первую строку текста элемента.",
      "::before вставляет контент перед содержимым, а не первую строку.",
      "::marker стилизует маркеры списков, а не строки текста.",
    ],
    moduleId: "css",
    sectionTitle: "Псевдоклассы и псевдоэлемены",
    topic: "css_pseudo",
  },
  {
    id: "css_pseudo_24",
    title: "Какой псевдоэлемент выбирает первую букву внутри элемента?",
    options: ["::first-line", "::first-letter", "::before", "::selection"],
    correctAnswers: [1],
    descriptions: [
      "::first-line выбирает первую строку, а не букву.",
      "Правильно: ::first-letter применяется к первой букве текстового содержимого.",
      "::before вставляет контент, а не выделяет букву.",
      "::selection стилизует выделенный фрагмент, а не первую букву.",
    ],
    moduleId: "css",
    sectionTitle: "Псевдоклассы и псевдоэлемены",
    topic: "css_pseudo",
  },
  {
    id: "css_pseudo_25",
    title: "Какой псевдоэлемент стилизует маркер (буллет) списка?",
    options: ["::marker", "::bullet", "::list-item", "::before"],
    correctAnswers: [0],
    descriptions: [
      "::bullet не является стандартным псевдоэлементом.",
      "Правильно: ::marker применяется к маркеру списка (буллет или номер).",
      "::list-item не существует в CSS.",
      "::before вставляет контент, не влияет на маркер.",
    ],
    moduleId: "css",
    sectionTitle: "Псевдоклассы и псевдоэлемены",
    topic: "css_pseudo",
  },
  {
    id: "css_pseudo_26",
    title: "Какой псевдоэлемент стилизует текст-заполнитель в <input>?",
    options: ["::placeholder", "::input-text", "::text-placeholder", "::value"],
    correctAnswers: [0],
    descriptions: [
      "::input-text не является корректным псевдоэлементом.",
      "Правильно: ::placeholder позволяет стилизовать текст-заполнитель в полях ввода.",
      "::text-placeholder не существует в стандарте CSS.",
      "::value не является псевдоэлементом для placeholder.",
    ],
    moduleId: "css",
    sectionTitle: "Псевдоклассы и псевдоэлемены",
    topic: "css_pseudo",
  },
  {
    id: "css_pseudo_27",
    title:
      "Какой псевдоэлемент позволяет стилизовать выбранный пользователем текст?",
    options: ["::selection", "::highlight", "::text-select", "::focus"],
    correctAnswers: [0],
    descriptions: [
      "::highlight не является валидным псевдоэлементом.",
      "Правильно: ::selection задаёт стили для выделенного фрагмента текста.",
      "::text-select не существует в CSS.",
      "::focus — псевдокласс для фокуса, а не стилизация выделенного текста.",
    ],
    moduleId: "css",
    sectionTitle: "Псевдоклассы и псевдоэлемены",
    topic: "css_pseudo",
  },
  {
    id: "css_pseudo_28",
    title:
      "Какой псевдоэлемент используется для стилизации фоновой области <video>?",
    options: ["::video", "::backdrop", "::media", "::content"],
    correctAnswers: [1],
    descriptions: [
      "::video не является корректным псевдоэлементом.",
      "Правильно: ::backdrop стилизует фон за модальными элементами, в том числе <video> в полноэкранном режиме.",
      "::media не существует как псевдоэлемент.",
      "::content не относится к видео.",
    ],
    moduleId: "css",
    sectionTitle: "Псевдоклассы и псевдоэлемены",
    topic: "css_pseudo",
  },
  {
    id: "css_pseudo_29",
    title:
      "Какой псевдоэлемент позволяет стилизовать ::backdrop, появляющийся при <dialog>?",
    options: [
      "::dialog-backdrop",
      "::overlay",
      "::backdrop",
      "::modal-backdrop",
    ],
    correctAnswers: [2],
    descriptions: [
      "::dialog-backdrop не является валидным.",
      "::overlay — не стандартный псевдоэлемент.",
      "Правильно: ::backdrop стилизует фон за элементом <dialog> или полноэкранным медиа.",
      "::modal-backdrop — не существует в спецификации.",
    ],
    moduleId: "css",
    sectionTitle: "Псевдоклассы и псевдоэлемены",
    topic: "css_pseudo",
  },
  {
    id: "css_pseudo_30",
    title: "Какой псевдоэлемент стилизует фрейм <iframe>?",
    options: ["::iframe", "::frame", "::before", "::after"],
    correctAnswers: [2],
    descriptions: [
      "::iframe и ::frame не существуют в CSS.",
      "::before и ::after можно применять к контейнеру, оборачивающему <iframe>, но не к самому фрейму.",
      "Правильно: у <iframe> нет собственного псевдоэлемента; используют ::before/::after на контейнере.",
      "Неправильно: ::after аналогично ::before, но не специфично для <iframe>.",
    ],
    moduleId: "css",
    sectionTitle: "Псевдоклассы и псевдоэлемены",
    topic: "css_pseudo",
  },
  {
    id: "css_pseudo_31",
    title:
      'Какой псевдоэлемент селектирует строку в элементе <input type="text">?',
    options: ["::line", "::input-line", "::first-line", "::selection"],
    correctAnswers: [3],
    descriptions: [
      "::line и ::input-line не являются стандартными.",
      "::first-line применим к блочным элементам и не действует внутри <input>.",
      "Правильно: ::selection позволяет стилизовать выделенный текст внутри <input>.",
      "Неверно: ::selection, а не ::first-line, влияет на выделенный текст.",
    ],
    moduleId: "css",
    sectionTitle: "Псевдоклассы и псевдоэлемены",
    topic: "css_pseudo",
  },
  {
    id: "css_pseudo_32",
    title: "Какой псевдоэлемент выбирает содержимое <svg> внутри HTML?",
    options: ["::svg-content", "::svg", "::before", "::after"],
    correctAnswers: [2],
    descriptions: [
      "::svg-content и ::svg не существуют.",
      "::before можно добавить контент перед SVG, но не выбирать содержимое.",
      "Правильно: используют ::before/::after на родительском элементе <svg> для вставки контента, но нет псевдоэлемента ::svg.",
      "::after добавляет контент после содержимого, но не 'выбирает' SVG.",
    ],
    moduleId: "css",
    sectionTitle: "Псевдоклассы и псевдоэлемены",
    topic: "css_pseudo",
  },
  {
    id: "css_pseudo_33",
    title:
      "Какой псевдоэлемент позволяет стилизовать ::part в компонентах Shadow DOM?",
    options: ["::part", "::slotted", "::shadow", "::host"],
    correctAnswers: [0],
    descriptions: [
      "::slotted позволяет стилизовать слоты, а не части.",
      "Правильно: ::part используется для доступа к именованным частям (parts) в Shadow DOM.",
      "::shadow не является валидным псевдоэлементом.",
      "::host стилизует сам хост (элемент с тенью), а не part.",
    ],
    moduleId: "css",
    sectionTitle: "Псевдоклассы и псевдоэлемены",
    topic: "css_pseudo",
  },
  {
    id: "css_pseudo_34",
    title:
      "Какой псевдоэлемент позволяет стилизовать slotted-элемент внутри Shadow DOM?",
    options: ["::slotted", "::part", "::host", "::content"],
    correctAnswers: [0],
    descriptions: [
      "Правильно: ::slotted позволяет применить стили к элементам, переданным в слот Shadow DOM.",
      "::part стилизует именованные части внутри Shadow DOM.",
      "::host стилизует сам компонент, а не содержимое слота.",
      "::content устаревший псевдоэлемент, заменённый <slot>.",
    ],
    moduleId: "css",
    sectionTitle: "Псевдоклассы и псевдоэлемены",
    topic: "css_pseudo",
  },
  {
    id: "css_pseudo_35",
    title:
      "Какой псевдоэлемент позволяет стилизовать маркеры списка внутри <ol> или <ul>?",
    options: ["::list-marker", "::marker", "::bullet", "::list-item"],
    correctAnswers: [1],
    descriptions: [
      "::list-marker не является стандартным псевдоэлементом.",
      "Правильно: ::marker используется для стилизации маркеров списков.",
      "::bullet не существует.",
      "::list-item не является псевдоэлементом, а псевдоклассом.",
    ],
    moduleId: "css",
    sectionTitle: "Псевдоклассы и псевдоэлемены",
    topic: "css_pseudo",
  },
  {
    id: "css_pseudo_36",
    title:
      "Какой псевдоэлемент позволяет стилизовать внутренний контейнер <textarea> до ввода текста?",
    options: ["::placeholder", "::value", "::text", "::content"],
    correctAnswers: [0],
    descriptions: [
      "::placeholder правильно стилизует текст-заполнитель до ввода.",
      "::value не является валидным псевдоэлементом для <textarea>.",
      "::text не существует.",
      "::content используется для вставки контента, но не для <textarea>.",
    ],
    moduleId: "css",
    sectionTitle: "Псевдоклассы и псевдоэлемены",
    topic: "css_pseudo",
  },
  {
    id: "css_pseudo_37",
    title: "Какой псевдоэлемент выбирает первую строку элемента <pre>?",
    options: ["::first-line", "::pre-line", "::line", "::content"],
    correctAnswers: [0],
    descriptions: [
      "Правильно: ::first-line применим и к <pre>, выбирая первую строку.",
      "::pre-line не является валидным псевдоэлементом.",
      "::line не существует.",
      "::content не применяется к <pre>.",
    ],
    moduleId: "css",
    sectionTitle: "Псевдоклассы и псевдоэлемены",
    topic: "css_pseudo",
  },
  {
    id: "css_pseudo_38",
    title:
      "Какой псевдоэлемент позволяет стилизовать часть контента, скрытую свойством ::after?",
    options: ["::after", "::before", "::content", "::placeholder"],
    correctAnswers: [0],
    descriptions: [
      "Правильно: ::after вставляет контент после, который затем можно стилизовать.",
      "::before вставляет до, но не после.",
      "::content не существует как псевдоэлемент.",
      "::placeholder стилизует текст-заполнитель, а не вставленный контент.",
    ],
    moduleId: "css",
    sectionTitle: "Псевдоклассы и псевдоэлемены",
    topic: "css_pseudo",
  },
  {
    id: "css_pseudo_39",
    title:
      "Какой псевдоэлемент позволяет стилизовать первую букву заголовка <h1>?",
    options: ["::first-letter", "::first-line", "::before", "::after"],
    correctAnswers: [0],
    descriptions: [
      "Правильно: ::first-letter применяется к первой букве текста.",
      "::first-line стилизует всю первую строку, а не только букву.",
      "::before вставляет контент до начала, а не стилизует букву.",
      "::after вставляет контент после текста, а не первый символ.",
    ],
    moduleId: "css",
    sectionTitle: "Псевдоклассы и псевдоэлемены",
    topic: "css_pseudo",
  },
  {
    id: "css_pseudo_40",
    title:
      "Какой псевдоэлемент используется для стилизации ::backdrop у <video> в полноэкранном режиме?",
    options: [
      "::fullscreen-backdrop",
      "::backdrop",
      "::video-backdrop",
      "::fullscreen",
    ],
    correctAnswers: [1],
    descriptions: [
      "::fullscreen-backdrop не является стандартным.",
      "Правильно: ::backdrop стилизует фон при выходе в полноэкранный режим.",
      "::video-backdrop не существует.",
      "::fullscreen — псевдокласс, а не псевдоэлемент для фона.",
    ],
    moduleId: "css",
    sectionTitle: "Псевдоклассы и псевдоэлемены",
    topic: "css_pseudo",
  },
  {
    id: "css_pseudo_41",
    title:
      "Какой псевдокласс используется для стилизации элемента при наведении курсора?",
    options: [":active", ":focus", ":hover", ":visited"],
    correctAnswers: [2],
    descriptions: [
      ":active активируется при нажатии элемента, а не наведении.",
      ":focus активируется при фокусе элемента, например, при табе.",
      "Правильно: :hover применяется, когда курсор находится над элементом.",
      ":visited применяется к ссылкам, уже посещённым пользователем.",
    ],
    moduleId: "css",
    sectionTitle: "Псевдоклассы и псевдоэлемены",
    topic: "css_pseudo",
  },
  {
    id: "css_pseudo_42",
    title: "Какой псевдокласс выбирает элемент при получении фокуса?",
    options: [":focus", ":hover", ":active", ":checked"],
    correctAnswers: [0],
    descriptions: [
      "Правильно: :focus применяется, когда элемент получает фокус (нажатие табом или клик).",
      ":hover — при наведении курсора, а не при фокусе.",
      ":active — при нажатии мыши, но не при фокусе.",
      ":checked — для отмеченных чекбоксов и радиокнопок.",
    ],
    moduleId: "css",
    sectionTitle: "Псевдоклассы и псевдоэлемены",
    topic: "css_pseudo",
  },
  {
    id: "css_pseudo_43",
    title:
      "Какой псевдокласс активируется при нажатии на элемент, пока кнопка мыши удерживается?",
    options: [":hover", ":focus", ":active", ":visited"],
    correctAnswers: [2],
    descriptions: [
      ":hover активируется при наведении курсора.",
      ":focus — при фокусе, а не при удержании клика.",
      "Правильно: :active действует в момент удержания кнопки мыши.",
      ":visited — для посещённых ссылок, а не для нажатия.",
    ],
    moduleId: "css",
    sectionTitle: "Псевдоклассы и псевдоэлемены",
    topic: "css_pseudo",
  },
  {
    id: "css_pseudo_44",
    title: "Какой псевдокласс выбирает ссылку, которая ещё не была посещена?",
    options: [":visited", ":link", ":hover", ":active"],
    correctAnswers: [1],
    descriptions: [
      ":visited выбирает посещённые ссылки, а не новые.",
      "Правильно: :link применяется к ссылкам, которые пользователь ещё не посещал.",
      ":hover — при наведении курсора, а не при статусе посещения.",
      ":active — при нажатии, а не при статусе посещения.",
    ],
    moduleId: "css",
    sectionTitle: "Псевдоклассы и псевдоэлемены",
    topic: "css_pseudo",
  },
  {
    id: "css_pseudo_45",
    title:
      "Какой псевдокласс выбирает ссылку после того, как пользователь её посетил?",
    options: [":link", ":hover", ":visited", ":focus"],
    correctAnswers: [2],
    descriptions: [
      ":link — для непосещённых ссылок, а не для посещённых.",
      ":hover — при наведении курсора, а не при статусе посещения.",
      "Правильно: :visited применяется к ссылкам, уже посещённым пользователем.",
      ":focus — при фокусе, а не при статусе посещения.",
    ],
    moduleId: "css",
    sectionTitle: "Псевдоклассы и псевдоэлемены",
    topic: "css_pseudo",
  },
  {
    id: "css_pseudo_46",
    title:
      "Какой псевдокласс выбирает элементы формы, доступные для взаимодействия?",
    options: [":disabled", ":enabled", ":checked", ":invalid"],
    correctAnswers: [1],
    descriptions: [
      ":disabled — для неактивных элементов, а не доступных.",
      "Правильно: :enabled выбирает элементы, которые не disabled.",
      ":checked — для отмеченных чекбоксов и радиокнопок, а не про доступность.",
      ":invalid — для полей с неправильным содержимым, а не про доступность.",
    ],
    moduleId: "css",
    sectionTitle: "Псевдоклассы и псевдоэлемены",
    topic: "css_pseudo",
  },
  {
    id: "css_pseudo_47",
    title:
      "Какой псевдокласс выбирает элементы формы, которые недоступны для взаимодействия?",
    options: [":enabled", ":disabled", ":checked", ":required"],
    correctAnswers: [1],
    descriptions: [
      ":enabled — для активных элементов, а не недоступных.",
      "Правильно: :disabled выбирает элементы, у которых выставлен атрибут disabled.",
      ":checked — для отмеченных чекбоксов и радиокнопок, а не для недоступности.",
      ":required — для обязательных полей, а не для доступности.",
    ],
    moduleId: "css",
    sectionTitle: "Псевдоклассы и псевдоэлемены",
    topic: "css_pseudo",
  },
  {
    id: "css_pseudo_48",
    title: "Какой псевдокласс выбирает отмеченные чекбоксы и радиокнопки?",
    options: [":checked", ":selected", ":active", ":focus"],
    correctAnswers: [0],
    descriptions: [
      "Правильно: :checked применяется к отмеченным элементам типа checkbox и radio.",
      ":selected — для выбранных <option> внутри select.",
      ":active — при нажатии, а не для состояния отметки.",
      ":focus — при фокусе, но не обязательно для отметки.",
    ],
    moduleId: "css",
    sectionTitle: "Псевдоклассы и псевдоэлемены",
    topic: "css_pseudo",
  },
  {
    id: "css_pseudo_49",
    title:
      "Какой псевдокласс выбирает элемент, когда у него падает фокус ввода (например, после нажатия Tab)?",
    options: [":focus", ":focus-visible", ":focus-within", ":active"],
    correctAnswers: [0],
    descriptions: [
      "Правильно: :focus выбирает элемент после получения фокуса ввода.",
      ":focus-visible — похож на :focus, но применяется, когда браузер считает фокус видимым.",
      ":focus-within выбирает родителя, если внутри есть элемент с фокусом.",
      ":active выбирает в момент активации кликом, но не при потере фокуса.",
    ],
    moduleId: "css",
    sectionTitle: "Псевдоклассы и псевдоэлемены",
    topic: "css_pseudo",
  },
  {
    id: "css_pseudo_50",
    title:
      "Какой псевдокласс выбирает элементы, у которых значение формы прошло валидацию?",
    options: [":valid", ":invalid", ":required", ":optional"],
    correctAnswers: [0],
    descriptions: [
      "Правильно: :valid выбирает элементы формы с корректным значением.",
      ":invalid — для элементов с некорректным значением.",
      ":required — для обязательных полей, а не про валидацию.",
      ":optional — для необязательных полей, а не про валидацию.",
    ],
    moduleId: "css",
    sectionTitle: "Псевдоклассы и псевдоэлемены",
    topic: "css_pseudo",
  },
  {
    id: "css_pseudo_51",
    title:
      "Какой псевдокласс выбирает элементы form, которые не прошли валидацию?",
    options: [":valid", ":invalid", ":checked", ":disabled"],
    correctAnswers: [1],
    descriptions: [
      ":valid — для корректных значений, а не некорректных.",
      "Правильно: :invalid выбирает элементы формы с неверным значением.",
      ":checked — для отмеченных элементов, а не про валидацию.",
      ":disabled — для неактивных элементов, не про валидацию.",
    ],
    moduleId: "css",
    sectionTitle: "Псевдоклассы и псевдоэлемены",
    topic: "css_pseudo",
  },
  {
    id: "css_pseudo_52",
    title:
      "Какой псевдокласс выбирает элемент, если он является единственным элементом своего родителя?",
    options: [":only-child", ":first-child", ":last-child", ":empty"],
    correctAnswers: [0],
    descriptions: [
      "Правильно: :only-child выбирает элемент, если он единственный ребёнок.",
      ":first-child — выбирает первого ребёнка, даже если их несколько.",
      ":last-child — выбирает последнего ребёнка, даже если их несколько.",
      ":empty — для элементов без дочерних узлов и текста.",
    ],
    moduleId: "css",
    sectionTitle: "Псевдоклассы и псевдоэлемены",
    topic: "css_pseudo",
  },
  {
    id: "css_pseudo_53",
    title:
      "Какой псевдокласс выбирает элементы, являющиеся первым элементом указанного типа среди братьев?",
    options: [":first-of-type", ":first-child", ":only-child", ":only-of-type"],
    correctAnswers: [0],
    descriptions: [
      "Правильно: :first-of-type выбирает первый элемент данного тега среди братьев.",
      ":first-child выбирает первого ребёнка независимо от тега.",
      ":only-child — для единственного ребёнка, а не для типа.",
      ":only-of-type — для единственного среди своего типа, а не первого.",
    ],
    moduleId: "css",
    sectionTitle: "Псевдоклассы и псевдоэлемены",
    topic: "css_pseudo",
  },
  {
    id: "css_pseudo_54",
    title:
      "Какой псевдокласс выбирает элемент, если у него установлен атрибут tabindex и он может получить фокус?",
    options: [":focus", ":focus-visible", ":focus-within", ":focus-ring"],
    correctAnswers: [1],
    descriptions: [
      ":focus — при фокусе, но не учитывает видимость фокуса.",
      "Правильно: :focus-visible срабатывает, когда браузер определяет, что фокус должен быть видимым (например, при навигации клавиатурой).",
      ":focus-within выбирает родителя, если внутри есть фокус.",
      ":focus-ring не является стандартным псевдоклассом.",
    ],
    moduleId: "css",
    sectionTitle: "Псевдоклассы и псевдоэлемены",
    topic: "css_pseudo",
  },
  {
    id: "css_pseudo_55",
    title:
      "Какой псевдокласс выбирает родителя, если внутри него есть элемент с фокусом?",
    options: [":focus", ":focus-visible", ":focus-within", ":hover"],
    correctAnswers: [2],
    descriptions: [
      ":focus — для самого элемента, а не для родителя.",
      ":focus-visible — для видимого фокуса на самом элементе.",
      "Правильно: :focus-within выбирает родителя, когда внутри есть элемент с фокусом.",
      ":hover — при наведении курсора на элемент, не про фокус.",
    ],
    moduleId: "css",
    sectionTitle: "Псевдоклассы и псевдоэлемены",
    topic: "css_pseudo",
  },
  {
    id: "css_pseudo_56",
    title:
      "Какой псевдокласс выбирает первый элемент, удовлетворяющий условию среди нескольких?",
    options: [
      ":first-child",
      ":nth-child(1)",
      ":first-of-type",
      ":nth-of-type(1)",
    ],
    correctAnswers: [1],
    descriptions: [
      ":first-child выбирает первого ребёнка, но не обязательно удовлетворяющего условию.",
      "Правильно: :nth-child(1) выбирает именно первый элемент среди братьев.",
      ":first-of-type выбирает первого по типу, а не по порядковому номеру.",
      ":nth-of-type(1) выбирает первого данного типа, а не по общему порядку.",
    ],
    moduleId: "css",
    sectionTitle: "Псевдоклассы и псевдоэлемены",
    topic: "css_pseudo",
  },
  {
    id: "css_pseudo_57",
    title:
      "Какой псевдокласс выбирает элементы, находящиеся между :first-child и :last-child (внутренние)?",
    options: [
      ":between",
      ":not(:first-child):not(:last-child)",
      ":middle",
      ":nth-child(n+2):nth-last-child(n+2)",
    ],
    correctAnswers: [3],
    descriptions: [
      ":between не является стандартным псевдоклассом.",
      "Это выражение тоже выберет внутренние, но сложнее, чем существующее shorthand.",
      ":middle не существует в CSS.",
      "Правильно: :nth-child(n+2):nth-last-child(n+2) выбирает элементы, не являющиеся первым или последним.",
    ],
    moduleId: "css",
    sectionTitle: "Псевдоклассы и псевдоэлемены",
    topic: "css_pseudo",
  },
  {
    id: "css_pseudo_58",
    title:
      "Какой псевдокласс выбирает элементы, у которых значение атрибута checked?",
    options: [":checked", ":selected", ":disabled", ":valid"],
    correctAnswers: [0],
    descriptions: [
      'Правильно: :checked выбирает отмеченные <input type="checkbox"> и <input type="radio"> элементы.',
      ":selected — для выбранных <option>, а не для чекбоксов.",
      ":disabled — для неактивных элементов.",
      ":valid — для элементов с корректным содержимым.",
    ],
    moduleId: "css",
    sectionTitle: "Псевдоклассы и псевдоэлемены",
    topic: "css_pseudo",
  },
  {
    id: "css_pseudo_59",
    title:
      "Какой псевдокласс выбирает элементы формы, у которых поле не заполнено, но обязательно?",
    options: [":empty", ":required", ":invalid", ":optional"],
    correctAnswers: [1],
    descriptions: [
      ":empty — для элементов без дочерних узлов или текста.",
      "Правильно: :required выбирает обязательные поля формы (атрибут required), независимо от заполненности.",
      ":invalid — для некорректных значений, а не про обязательность.",
      ":optional — для необязательных полей.",
    ],
    moduleId: "css",
    sectionTitle: "Псевдоклассы и псевдоэлемены",
    topic: "css_pseudo",
  },
  {
    id: "css_pseudo_60",
    title:
      "Какой псевдокласс выбирает элементы, у которых изменилось состояние после загрузки страницы?",
    options: [":visited", ":focus", ":target", ":checked"],
    correctAnswers: [2],
    descriptions: [
      ":visited — для ссылок, которые уже посещены, а не про изменения после загрузки.",
      ":focus — для элементов с фокусом, а не про изменение состояния после загрузки.",
      "Правильно: :target выбирает элемент, соответствующий фрагменту URI, когда он меняется после загрузки.",
      ":checked — для отмеченных элементов, но не зависит от загрузки страницы.",
    ],
    moduleId: "css",
    sectionTitle: "Псевдоклассы и псевдоэлемены",
    topic: "css_pseudo",
  },
];
