export const cssSelectorsQuestions = [
  {
    id: "css_selectors_1",
    title: "Какое свойство CSS отвечает за цвет текста?",
    options: ["background-color", "text-color", "color", "font-color"],
    correctAnswers: [2],
    descriptions: [
      "background-color задаёт цвет фона, а не текста.",
      "Свойства text-color не существует в CSS.",
      "Правильный ответ: color — стандартное свойство для цвета текста.",
      "font-color не является валидным CSS-свойством.",
    ],
    moduleId: "css",
    sectionTitle: "Стилизация текста",
    topic: "css_selectors",
  },
  {
    id: "css_selectors_2",
    title: "Как задать красный цвет текста в HEX-формате?",
    options: [
      "color: #0000FF;",
      "color: #FF0000;",
      "color: #00FF00;",
      "color: red;",
    ],
    correctAnswers: [1],
    descriptions: [
      "#0000FF — это синий цвет.",
      "Правильно: #FF0000 — красный в HEX.",
      "#00FF00 — зелёный цвет.",
      "Хотя 'red' тоже допустим, вопрос был про HEX-формат.",
    ],
    moduleId: "css",
    sectionTitle: "Стилизация текста",
    topic: "css_selectors",
  },
  {
    id: "css_selectors_3",
    title: "Какой код сделает текст полупрозрачным (50%)?",
    options: [
      "color: rgba(255, 0, 0, 0.5);",
      "color: #FF000050;",
      "color: transparent;",
      "color: opacity(0.5);",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: rgba(255, 0, 0, 0.5) — последнее значение alpha = 0.5.",
      "HEX-формат с альфа-каналом (#RRGGBBAA) поддерживается не везде.",
      "transparent — полная прозрачность, не 50%.",
      "Свойства opacity(0.5) для color не существует.",
    ],
    moduleId: "css",
    sectionTitle: "Стилизация текста",
    topic: "css_selectors",
  },
  {
    id: "css_selectors_4",
    title:
      "Какой из этих цветов соответствует HSL-значению hsl(120, 100%, 50%)?",
    options: ["Красный", "Зелёный", "Синий", "Жёлтый"],
    correctAnswers: [1],
    descriptions: [
      "Красный — это hsl(0, 100%, 50%).",
      "Правильно: зелёный — hue=120° в HSL.",
      "Синий — hsl(240, 100%, 50%).",
      "Жёлтый — hsl(60, 100%, 50%).",
    ],
    moduleId: "css",
    sectionTitle: "Стилизация текста",
    topic: "css_selectors",
  },
  {
    id: "css_selectors_5",
    title: "Как задать цвет текста с помощью имени цвета (например, синий)?",
    options: [
      "color: #0000FF;",
      "color: blue;",
      "color: rgb(0, 0, 255);",
      "color: hsl(240, 100%, 50%);",
    ],
    correctAnswers: [1],
    descriptions: [
      "Это HEX-формат, а не имя цвета.",
      "Правильно: 'blue' — стандартное имя цвета в CSS.",
      "Это RGB-формат, а не имя.",
      "Это HSL-формат, а не имя.",
    ],
    moduleId: "css",
    sectionTitle: "Стилизация текста",
    topic: "css_selectors",
  },
  {
    id: "css_selectors_6",
    title: "Какое значение color сделает текст чёрным?",
    options: [
      "color: #FFFFFF;",
      "color: #000000;",
      "color: #FF0000;",
      "color: #00FF00;",
    ],
    correctAnswers: [1],
    descriptions: [
      "#FFFFFF — белый цвет.",
      "Правильно: #000000 — чёрный в HEX.",
      "#FF0000 — красный.",
      "#00FF00 — зелёный.",
    ],
    moduleId: "css",
    sectionTitle: "Стилизация текста",
    topic: "css_selectors",
  },
  {
    id: "css_selectors_7",
    title: "Какой CSS-код задаст белый текст с прозрачностью 75%?",
    options: [
      "color: rgba(255, 255, 255, 0.25);",
      "color: rgba(255, 255, 255, 0.75);",
      "color: #FFFFFF75;",
      "color: white opacity(0.75);",
    ],
    correctAnswers: [1],
    descriptions: [
      "0.25 — это 25% прозрачности.",
      "Правильно: rgba(255, 255, 255, 0.75) — белый с 75% непрозрачности.",
      "HEX с альфа-каналом менее читаем и поддерживается не везде.",
      "Синтаксис 'white opacity(0.75)' неверен.",
    ],
    moduleId: "css",
    sectionTitle: "Стилизация текста",
    topic: "css_selectors",
  },
  {
    id: "css_selectors_8",
    title: "Какой цвет получится при значении color: currentColor;?",
    options: [
      "Чёрный",
      "Наследуется от родителя",
      "Прозрачный",
      "Синий по умолчанию",
    ],
    correctAnswers: [1],
    descriptions: [
      "Только если родительский элемент чёрный.",
      "Правильно: currentColor наследует значение color родителя.",
      "transparent — для полной прозрачности.",
      "Нет «синего по умолчанию» — зависит от контекста.",
    ],
    moduleId: "css",
    sectionTitle: "Стилизация текста",
    topic: "css_selectors",
  },
  {
    id: "css_selectors_9",
    title: "Какой код сделает текст пурпурным (#800080)?",
    options: [
      "color: purple;",
      "color: #800080;",
      "color: rgb(128, 0, 128);",
      "Все варианты верны",
    ],
    correctAnswers: [3],
    descriptions: [
      "'purple' — это имя для #800080.",
      "HEX-код #800080 — пурпурный.",
      "RGB(128, 0, 128) — тоже пурпурный.",
      "Все варианты эквивалентны в CSS.",
    ],
    moduleId: "css",
    sectionTitle: "Стилизация текста",
    topic: "css_selectors",
  },
  {
    id: "css_selectors_10",
    title: "Какой из форматов цветов НЕ существует в CSS?",
    options: ["HEX", "RGB", "CMYK", "HSL"],
    correctAnswers: [2],
    descriptions: [
      "HEX (#RRGGBB) поддерживается.",
      "RGB (rgb(255, 0, 0)) — стандарт.",
      "Правильно: CMYK (для печати) не поддерживается в CSS.",
      "HSL (hsl(120, 100%, 50%)) — есть в CSS.",
    ],
    moduleId: "css",
    sectionTitle: "Стилизация текста",
    topic: "css_selectors",
  },
  {
    id: "css_selectors_11",
    title: "Какой цвет соответствует HSL-значению hsl(0, 100%, 50%)?",
    options: ["Зелёный", "Красный", "Синий", "Жёлтый"],
    correctAnswers: [1],
    descriptions: [
      "Зелёный — hsl(120, 100%, 50%).",
      "Правильно: красный — hue=0° в HSL.",
      "Синий — hsl(240, 100%, 50%).",
      "Жёлтый — hsl(60, 100%, 50%).",
    ],
    moduleId: "css",
    sectionTitle: "Стилизация текста",
    topic: "css_selectors",
  },
  {
    id: "css_selectors_12",
    title: "Какой код задаст тёмно-серый цвет (#333333)?",
    options: [
      "color: darkgray;",
      "color: #333;",
      "color: rgb(51, 51, 51);",
      "Все варианты верны",
    ],
    correctAnswers: [3],
    descriptions: [
      "darkgray — это #A9A9A9, но вопрос про #333.",
      "Сокращённый HEX #333 = #333333.",
      "RGB(51, 51, 51) = #333333.",
      "Все варианты (кроме darkgray) эквивалентны #333333.",
    ],
    moduleId: "css",
    sectionTitle: "Стилизация текста",
    topic: "css_selectors",
  },
  {
    id: "css_selectors_13",
    title: "Какой цвет получится при значении color: inherit;?",
    options: ["Чёрный", "Как у родительского элемента", "Прозрачный", "Синий"],
    correctAnswers: [1],
    descriptions: [
      "Только если у родителя чёрный.",
      "Правильно: inherit наследует цвет родителя.",
      "transparent — для полной прозрачности.",
      "Нет «синего по умолчанию» — зависит от контекста.",
    ],
    moduleId: "css",
    sectionTitle: "Стилизация текста",
    topic: "css_selectors",
  },
  {
    id: "css_selectors_14",
    title: "Какой код сделает текст жёлтым с помощью RGB?",
    options: [
      "color: rgb(255, 255, 0);",
      "color: #FFFF00;",
      "color: yellow;",
      "Все варианты верны",
    ],
    correctAnswers: [3],
    descriptions: [
      "RGB(255, 255, 0) — жёлтый.",
      "#FFFF00 — жёлтый в HEX.",
      "'yellow' — имя цвета для жёлтого.",
      "Все варианты задают жёлтый цвет.",
    ],
    moduleId: "css",
    sectionTitle: "Стилизация текста",
    topic: "css_selectors",
  },
  {
    id: "css_selectors_15",
    title: "Какой из этих цветов НЕ является стандартным именем в CSS?",
    options: [
      "rebeccapurple",
      "lightgoldenrodyellow",
      "facebookblue",
      "papayawhip",
    ],
    correctAnswers: [2],
    descriptions: [
      "rebeccapurple — валидный CSS-цвет.",
      "lightgoldenrodyellow — есть в спецификации.",
      "Правильно: 'facebookblue' — нестандартное имя.",
      "papayawhip — валидный цвет.",
    ],
    moduleId: "css",
    sectionTitle: "Стилизация текста",
    topic: "css_selectors",
  },
  {
    id: "css_selectors_16",
    title: "Какой код задаст цвет текста как #FFA500 (оранжевый)?",
    options: [
      "color: orange;",
      "color: #FFA500;",
      "color: rgb(255, 165, 0);",
      "Все варианты верны",
    ],
    correctAnswers: [3],
    descriptions: [
      "'orange' — имя для #FFA500.",
      "#FFA500 — оранжевый в HEX.",
      "RGB(255, 165, 0) — оранжевый.",
      "Все варианты эквивалентны.",
    ],
    moduleId: "css",
    sectionTitle: "Стилизация текста",
    topic: "css_selectors",
  },
  {
    id: "css_selectors_17",
    title: "Какой цвет получится при значении color: transparent;?",
    options: ["Чёрный", "Белый", "Полностью прозрачный", "Серый"],
    correctAnswers: [2],
    descriptions: [
      "Чёрный — color: black;.",
      "Белый — color: white;.",
      "Правильно: transparent = полная прозрачность.",
      "Серый — например, #808080.",
    ],
    moduleId: "css",
    sectionTitle: "Стилизация текста",
    topic: "css_selectors",
  },
  {
    id: "css_selectors_18",
    title: "Какой код сделает текст зелёным с помощью HSL?",
    options: [
      "color: hsl(120, 100%, 25%);",
      "color: #00FF00;",
      "color: green;",
      "Все варианты верны",
    ],
    correctAnswers: [3],
    descriptions: [
      "hsl(120, 100%, 25%) — тёмно-зелёный.",
      "#00FF00 — зелёный в HEX.",
      "'green' — имя для зелёного.",
      "Все варианты задают зелёный (разные оттенки).",
    ],
    moduleId: "css",
    sectionTitle: "Стилизация текста",
    topic: "css_selectors",
  },
  {
    id: "css_selectors_19",
    title: "Какой код задаст цвет текста как #FFFFFF (белый)?",
    options: [
      "color: white;",
      "color: #FFF;",
      "color: rgb(255, 255, 255);",
      "Все варианты верны",
    ],
    correctAnswers: [3],
    descriptions: [
      "'white' — имя для #FFFFFF.",
      "#FFF — сокращённый HEX для #FFFFFF.",
      "RGB(255, 255, 255) — белый.",
      "Все варианты эквивалентны.",
    ],
    moduleId: "css",
    sectionTitle: "Стилизация текста",
    topic: "css_selectors",
  },
  {
    id: "css_selectors_20",
    title: "Какой из этих цветов соответствует HEX-коду #FFD700?",
    options: [
      "Золотой (gold)",
      "Серебряный (silver)",
      "Бронзовый (bronze)",
      "Платиновый (platinum)",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: #FFD700 — это 'gold' в CSS.",
      "Серебряный — #C0C0C0.",
      "Бронзовый не имеет стандартного имени в CSS.",
      "Платиновый — #E5E4E2 (но не в стандарте).",
    ],
    moduleId: "css",
    sectionTitle: "Стилизация текста",
    topic: "css_selectors",
  },
  {
    id: "css_selectors_21",
    title: "Какое свойство CSS изменяет размер шрифта?",
    options: ["font-weight", "font-size", "text-size", "font-scale"],
    correctAnswers: [1],
    descriptions: [
      "font-weight отвечает за насыщенность (жирность).",
      "Правильно: font-size задаёт размер шрифта (например, 16px).",
      "Свойства text-size не существует.",
      "font-scale — не валидное свойство.",
    ],
    moduleId: "css",
    sectionTitle: "Стилизация текста",
    topic: "css_selectors",
  },
  {
    id: "css_selectors_22",
    title: "Как сделать текст жирным?",
    options: [
      "font-style: bold;",
      "font-weight: bold;",
      "text-weight: bold;",
      "font-bold: true;",
    ],
    correctAnswers: [1],
    descriptions: [
      "font-style используется для наклона (italic).",
      "Правильно: font-weight: bold; или 700.",
      "text-weight — несуществующее свойство.",
      "font-bold — не валидный CSS.",
    ],
    moduleId: "css",
    sectionTitle: "Стилизация текста",
    topic: "css_selectors",
  },
  {
    id: "css_selectors_23",
    title: "Какой код задаст курсивное начертание текста?",
    options: [
      "font-style: italic;",
      "font-weight: italic;",
      "text-style: italic;",
      "italic: true;",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: font-style: italic;.",
      "font-weight управляет жирностью, а не наклоном.",
      "text-style — не существует.",
      "italic — не свойство CSS.",
    ],
    moduleId: "css",
    sectionTitle: "Стилизация текста",
    topic: "css_selectors",
  },
  {
    id: "css_selectors_24",
    title: "Как изменить гарнитуру шрифта?",
    options: [
      "font-family: Arial;",
      "font-type: Arial;",
      "text-font: Arial;",
      "font: Arial;",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: font-family: Arial, sans-serif;.",
      "font-type — не валидное свойство.",
      "text-font — не существует.",
      "font — сокращённое свойство, но требует больше параметров.",
    ],
    moduleId: "css",
    sectionTitle: "Стилизация текста",
    topic: "css_selectors",
  },
  {
    id: "css_selectors_25",
    title: "Какой код выровняет текст по центру?",
    options: [
      "text-position: center;",
      "align-text: center;",
      "text-align: center;",
      "text-center: true;",
    ],
    correctAnswers: [2],
    descriptions: [
      "text-position — не свойство CSS.",
      "align-text — не существует.",
      "Правильно: text-align: center;.",
      "text-center — не валидный CSS.",
    ],
    moduleId: "css",
    sectionTitle: "Стилизация текста",
    topic: "css_selectors",
  },
  {
    id: "css_selectors_26",
    title: "Как добачить подчёркивание текста?",
    options: [
      "text-decoration: underline;",
      "text-line: underline;",
      "underline: true;",
      "font-underline: yes;",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: text-decoration: underline;.",
      "text-line — не свойство.",
      "underline — не валидное свойство.",
      "font-underline — не существует.",
    ],
    moduleId: "css",
    sectionTitle: "Стилизация текста",
    topic: "css_selectors",
  },
  {
    id: "css_selectors_27",
    title: "Какой код задаст межстрочный интервал (line-height) в 1.5?",
    options: [
      "line-height: 1.5;",
      "text-height: 1.5;",
      "font-spacing: 1.5;",
      "line-spacing: 1.5;",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: line-height: 1.5; (без единиц — множитель).",
      "text-height — не свойство.",
      "font-spacing — не существует.",
      "line-spacing — не валидный CSS.",
    ],
    moduleId: "css",
    sectionTitle: "Стилизация текста",
    topic: "css_selectors",
  },
  {
    id: "css_selectors_28",
    title: "Как изменить расстояние между буквами?",
    options: [
      "letter-spacing: 2px;",
      "text-spacing: 2px;",
      "font-spacing: 2px;",
      "char-spacing: 2px;",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: letter-spacing: 2px;.",
      "text-spacing — не свойство.",
      "font-spacing — не существует.",
      "char-spacing — не валидный CSS.",
    ],
    moduleId: "css",
    sectionTitle: "Стилизация текста",
    topic: "css_selectors",
  },
  {
    id: "css_selectors_29",
    title: "Какой код сделает текст заглавными буквами?",
    options: [
      "text-transform: uppercase;",
      "font-case: uppercase;",
      "text-uppercase: true;",
      "uppercase: yes;",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: text-transform: uppercase;.",
      "font-case — не свойство.",
      "text-uppercase — не существует.",
      "uppercase — не валидный CSS.",
    ],
    moduleId: "css",
    sectionTitle: "Стилизация текста",
    topic: "css_selectors",
  },
  {
    id: "css_selectors_30",
    title: "Какой код уберёт подчёркивание у ссылки?",
    options: [
      "text-decoration: none;",
      "text-underline: none;",
      "underline: remove;",
      "link-decoration: none;",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: text-decoration: none;.",
      "text-underline — не свойство.",
      "underline — не валидный CSS.",
      "link-decoration — не существует.",
    ],
    moduleId: "css",
    sectionTitle: "Стилизация текста",
    topic: "css_selectors",
  },
  {
    id: "css_selectors_31",
    title: "Какой код задаст тень для текста?",
    options: [
      "text-shadow: 2px 2px 4px #000;",
      "font-shadow: 2px 2px 4px #000;",
      "shadow: text 2px 2px 4px #000;",
      "text-effect: shadow(2px 2px 4px #000);",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: text-shadow: 2px 2px 4px #000;.",
      "font-shadow — не свойство.",
      "shadow — не применяется к тексту.",
      "text-effect — не существует.",
    ],
    moduleId: "css",
    sectionTitle: "Стилизация текста",
    topic: "css_selectors",
  },
  {
    id: "css_selectors_32",
    title: "Какой код изменит расстояние между словами?",
    options: [
      "word-spacing: 5px;",
      "text-spacing: 5px;",
      "space-words: 5px;",
      "font-word-spacing: 5px;",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: word-spacing: 5px;.",
      "text-spacing — не свойство.",
      "space-words — не валидный CSS.",
      "font-word-spacing — не существует.",
    ],
    moduleId: "css",
    sectionTitle: "Стилизация текста",
    topic: "css_selectors",
  },
  {
    id: "css_selectors_33",
    title:
      "Какой код сделает текст первым абзацем с отступом (красная строка)?",
    options: [
      "text-indent: 20px;",
      "paragraph-indent: 20px;",
      "first-line: indent 20px;",
      "indent-text: 20px;",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: text-indent: 20px;.",
      "paragraph-indent — не свойство.",
      "first-line — псевдоэлемент, но не свойство.",
      "indent-text — не валидный CSS.",
    ],
    moduleId: "css",
    sectionTitle: "Стилизация текста",
    topic: "css_selectors",
  },
  {
    id: "css_selectors_34",
    title: "Какой код задаст шрифт с засечками (serif) по умолчанию?",
    options: [
      "font-family: serif;",
      "font-type: serif;",
      "font: serif;",
      "text-font: serif;",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: font-family: serif; (например, Times New Roman).",
      "font-type — не свойство.",
      "font требует полного синтаксиса (например, font: 16px serif;).",
      "text-font — не существует.",
    ],
    moduleId: "css",
    sectionTitle: "Стилизация текста",
    topic: "css_selectors",
  },
  {
    id: "css_selectors_35",
    title: "Какой код запретит перенос слов на новую строку?",
    options: [
      "white-space: nowrap;",
      "text-wrap: none;",
      "word-break: no-wrap;",
      "no-wrap: true;",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: white-space: nowrap;.",
      "text-wrap управляет переносом, но не так.",
      "word-break: break-all — для переноса букв.",
      "no-wrap — не свойство.",
    ],
    moduleId: "css",
    sectionTitle: "Стилизация текста",
    topic: "css_selectors",
  },
  {
    id: "css_selectors_36",
    title: "Какой код сделает текст подчёркнутым пунктиром?",
    options: [
      "text-decoration: underline dashed;",
      "underline-style: dashed;",
      "text-underline: dashed;",
      "dashed-underline: true;",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: text-decoration: underline dashed;.",
      "underline-style — не свойство.",
      "text-underline — не существует.",
      "dashed-underline — не валидный CSS.",
    ],
    moduleId: "css",
    sectionTitle: "Стилизация текста",
    topic: "css_selectors",
  },
  {
    id: "css_selectors_37",
    title: "Какой код выровняет текст по ширине?",
    options: [
      "text-align: justify;",
      "text-align: stretch;",
      "align-text: justify;",
      "text-justify: true;",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: text-align: justify;.",
      "stretch — не значение для text-align.",
      "align-text — не свойство.",
      "text-justify — отдельное свойство для тонкой настройки.",
    ],
    moduleId: "css",
    sectionTitle: "Стилизация текста",
    topic: "css_selectors",
  },
  {
    id: "css_selectors_38",
    title: "Какой код задаст шрифт 'Arial' с запасным вариантом 'sans-serif'?",
    options: [
      "font-family: Arial, sans-serif;",
      "font: Arial, sans-serif;",
      "text-font: Arial, sans-serif;",
      "font-family: 'Arial'; fallback: sans-serif;",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: font-family: Arial, sans-serif;.",
      "font требует размера: font: 16px Arial, sans-serif;.",
      "text-font — не свойство.",
      "fallback — не ключевое слово в CSS.",
    ],
    moduleId: "css",
    sectionTitle: "Стилизация текста",
    topic: "css_selectors",
  },
  {
    id: "css_selectors_39",
    title: "Какой код сделает текст перечёркнутым?",
    options: [
      "text-decoration: line-through;",
      "text-line: through;",
      "strikethrough: true;",
      "line-through: yes;",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: text-decoration: line-through;.",
      "text-line — не свойство.",
      "strikethrough — не валидный CSS.",
      "line-through — не свойство.",
    ],
    moduleId: "css",
    sectionTitle: "Стилизация текста",
    topic: "css_selectors",
  },
  {
    id: "css_selectors_40",
    title: "Какой код задаст полужирное начертание (не bold)?",
    options: [
      "font-weight: 600;",
      "font-weight: semi-bold;",
      "font-bold: medium;",
      "text-weight: strong;",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: font-weight: 600; (между normal и bold).",
      "semi-bold — не валидное значение.",
      "font-bold — не свойство.",
      "text-weight — не существует.",
    ],
    moduleId: "css",
    sectionTitle: "Стилизация текста",
    topic: "css_selectors",
  },
  {
    id: "css_selectors_41",
    title: "Какое свойство задаёт ширину элемента?",
    options: ["height", "width", "size", "dimension"],
    correctAnswers: [1],
    descriptions: [
      "height задаёт высоту, а не ширину.",
      "Правильно: width определяет ширину элемента.",
      "size — не существует в CSS.",
      "dimension — не валидное свойство.",
    ],
    moduleId: "css",
    sectionTitle: "Стилизация текста",
    topic: "css_selectors",
  },
  {
    id: "css_selectors_42",
    title: "Какая единица измерения является относительной?",
    options: ["px", "em", "cm", "pt"],
    correctAnswers: [1],
    descriptions: [
      "px — пиксели (фиксированная единица).",
      "Правильно: em — относительная единица (зависит от размера шрифта родителя).",
      "cm — абсолютная единица (сантиметры).",
      "pt — пункты (фиксированная единица).",
    ],
    moduleId: "css",
    sectionTitle: "Стилизация текста",
    topic: "css_selectors",
  },
  {
    id: "css_selectors_43",
    title: "Какой код сделает ширину элемента 50% от родителя?",
    options: ["width: 50;", "width: 50em;", "width: 50%;", "width: 50px;"],
    correctAnswers: [2],
    descriptions: [
      "50 — невалидное значение (нет единицы измерения).",
      "50em — это 50 × текущий размер шрифта.",
      "Правильно: 50% — половина ширины родителя.",
      "50px — фиксированное значение в пикселях.",
    ],
    moduleId: "css",
    sectionTitle: "Стилизация текста",
    topic: "css_selectors",
  },
  {
    id: "css_selectors_44",
    title: "Какое свойство включает модель box-sizing: border-box?",
    options: [
      "padding и margin включаются в width",
      "padding включается в width, margin — нет",
      "margin включается в width, padding — нет",
      "ни padding, ни margin не включаются в width",
    ],
    correctAnswers: [1],
    descriptions: [
      "margin никогда не включается в width.",
      "Правильно: при border-box padding и border входят в width/height.",
      "margin всегда считается отдельно.",
      "При border-box padding и border учитываются в размерах.",
    ],
    moduleId: "css",
    sectionTitle: "Стилизация текста",
    topic: "css_selectors",
  },
  {
    id: "css_selectors_45",
    title: "Какой код задаст минимальную высоту элемента 100px?",
    options: [
      "min-height: 100px;",
      "height: min-100px;",
      "minimal-height: 100px;",
      "height-min: 100px;",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: min-height: 100px;.",
      "height: min-100px — невалидный синтаксис.",
      "minimal-height — не существует.",
      "height-min — не валидное свойство.",
    ],
    moduleId: "css",
    sectionTitle: "Стилизация текста",
    topic: "css_selectors",
  },
  {
    id: "css_selectors_46",
    title: "Что делает единица vh?",
    options: [
      "1% от ширины viewport",
      "1% от высоты viewport",
      "1% от ширины родителя",
      "1% от высоты родителя",
    ],
    correctAnswers: [1],
    descriptions: [
      "vw — это 1% от ширины viewport.",
      "Правильно: vh — 1% от высоты окна браузера.",
      "% зависит от родителя, а не viewport.",
      "Родительские размеры не влияют на vh.",
    ],
    moduleId: "css",
    sectionTitle: "Стилизация текста",
    topic: "css_selectors",
  },
  {
    id: "css_selectors_47",
    title: "Какой код ограничит ширину элемента максимум 800px?",
    options: [
      "max-width: 800px;",
      "width: max-800px;",
      "width-limit: 800px;",
      "maximum-width: 800px;",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: max-width: 800px;.",
      "width: max-800px — невалидный синтаксис.",
      "width-limit — не свойство.",
      "maximum-width — не существует.",
    ],
    moduleId: "css",
    sectionTitle: "Стилизация текста",
    topic: "css_selectors",
  },
  {
    id: "css_selectors_48",
    title: "Какой код сделает элемент «резиновым» (min: 300px, max: 100%)?",
    options: [
      "width: 100%; min-width: 300px;",
      "width: 300px; max-width: 100%;",
      "flex-width: 300px 100%;",
      "width: clamp(300px, 100%, 100%);",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: width: 100% с ограничением min-width: 300px.",
      "Не гарантирует резиновость (может быть фиксированным 300px).",
      "flex-width — не существует.",
      "clamp() требует трёх параметров (min, pref, max).",
    ],
    moduleId: "css",
    sectionTitle: "Стилизация текста",
    topic: "css_selectors",
  },
  {
    id: "css_selectors_49",
    title: "Что делает свойство aspect-ratio?",
    options: [
      "Задаёт соотношение сторон элемента",
      "Определяет пропорции шрифта",
      "Управляет скруглением углов",
      "Изменяет прозрачность",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: aspect-ratio (например, 16/9 для видео).",
      "Не имеет отношения к шрифтам.",
      "Для углов используется border-radius.",
      "Прозрачность — opacity или rgba().",
    ],
    moduleId: "css",
    sectionTitle: "Стилизация текста",
    topic: "css_selectors",
  },
  {
    id: "css_selectors_50",
    title: "Какой код задаст высоту элемента равной высоте viewport?",
    options: [
      "height: 100vh;",
      "height: 100%;",
      "height: 100vw;",
      "height: viewport;",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: height: 100vh (100% от высоты окна).",
      "100% зависит от родителя, а не окна.",
      "100vw — это ширина viewport.",
      "viewport — не валидное значение.",
    ],
    moduleId: "css",
    sectionTitle: "Стилизация текста",
    topic: "css_selectors",
  },
  {
    id: "css_selectors_51",
    title: "Что делает единица rem?",
    options: [
      "Зависит от размера шрифта родителя",
      "Зависит от размера шрифта корневого элемента (html)",
      "Равна 16px по умолчанию",
      "Относится к ширине viewport",
    ],
    correctAnswers: [1],
    descriptions: [
      "em зависит от родителя, а не rem.",
      "Правильно: rem — от размера шрифта <html> (обычно 16px).",
      "16px — дефолтный размер, но rem может измениться.",
      "От viewport зависят vw/vh.",
    ],
    moduleId: "css",
    sectionTitle: "Стилизация текста",
    topic: "css_selectors",
  },
  {
    id: "css_selectors_52",
    title: "Какой код включит border-box для всех элементов?",
    options: [
      "* { box-sizing: border-box; }",
      "html { box-model: border-box; }",
      "body { box-type: border-box; }",
      "all { box-sizing: border-box; }",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: универсальный селектор * + box-sizing.",
      "box-model — не свойство.",
      "box-type — не существует.",
      "all — не селектор.",
    ],
    moduleId: "css",
    sectionTitle: "Стилизация текста",
    topic: "css_selectors",
  },
  {
    id: "css_selectors_53",
    title: "Какой код задаст ширину элемента 50vw?",
    options: [
      "width: 50 viewport;",
      "width: 50vh;",
      "width: 50vw;",
      "width: 50% viewport;",
    ],
    correctAnswers: [2],
    descriptions: [
      "50 viewport — невалидный синтаксис.",
      "50vh — 50% от высоты viewport.",
      "Правильно: 50vw — 50% от ширины окна.",
      "50% viewport — неверный формат.",
    ],
    moduleId: "css",
    sectionTitle: "Стилизация текста",
    topic: "css_selectors",
  },
  {
    id: "css_selectors_54",
    title:
      "Какой код использует функцию clamp() для резинового размера (min: 200px, pref: 50%, max: 600px)?",
    options: [
      "width: clamp(200px, 50%, 600px);",
      "width: clamp(50%, 200px, 600px);",
      "width: clamp(200px, 600px, 50%);",
      "width: clamp(600px, 50%, 200px);",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: clamp(min, pref, max).",
      "Порядок параметров нарушен.",
      "Неверный порядок: min, pref, max.",
      "max должен быть последним.",
    ],
    moduleId: "css",
    sectionTitle: "Стилизация текста",
    topic: "css_selectors",
  },
  {
    id: "css_selectors_55",
    title:
      "Какой код задаст фиксированную ширину 200px и высоту, зависящую от содержимого?",
    options: [
      "width: 200px; height: auto;",
      "width: 200px; height: content;",
      "width: 200px; height: 100%;",
      "width: 200px; height: fit-content;",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: height: auto подстраивается под контент.",
      "height: content — невалидное значение.",
      "100% зависит от родителя, а не контента.",
      "fit-content — для ширины/высоты, но не всегда нужен.",
    ],
    moduleId: "css",
    sectionTitle: "Стилизация текста",
    topic: "css_selectors",
  },
  {
    id: "css_selectors_56",
    title: "Что делает свойство min-content?",
    options: [
      "Минимальная ширина/высота, чтобы вместить контент без переносов",
      "Минимальные отступы внутри элемента",
      "Минимальный размер шрифта",
      "Минимальная прозрачность",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: min-content — минимальный размер без переполнения.",
      "Не относится к padding/margin.",
      "Для шрифта — font-size: min-size — не существует.",
      "Прозрачность — opacity.",
    ],
    moduleId: "css",
    sectionTitle: "Стилизация текста",
    topic: "css_selectors",
  },
  {
    id: "css_selectors_57",
    title: "Какой код задаст высоту элемента равной его ширине?",
    options: [
      "height: width;",
      "height: 100%; aspect-ratio: 1/1;",
      "height: same-as-width;",
      "height: calc(width);",
    ],
    correctAnswers: [1],
    descriptions: [
      "height: width — невалидный CSS.",
      "Правильно: aspect-ratio: 1/1 + height: 100% (если width задана).",
      "same-as-width — не существует.",
      "calc(width) — не работает (width — не число).",
    ],
    moduleId: "css",
    sectionTitle: "Стилизация текста",
    topic: "css_selectors",
  },
  {
    id: "css_selectors_58",
    title: "Какой код задаст максимальную высоту 90vh, но не менее 400px?",
    options: [
      "max-height: 90vh; min-height: 400px;",
      "height: clamp(400px, 90vh, 90vh);",
      "max-height: min(90vh, 400px);",
      "height: max(90vh, 400px);",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: комбинация max-height и min-height.",
      "clamp() требует трёх параметров (min, pref, max).",
      "min(90vh, 400px) — выберет меньший размер (не то).",
      "max(90vh, 400px) — выберет больший размер (не то).",
    ],
    moduleId: "css",
    sectionTitle: "Стилизация текста",
    topic: "css_selectors",
  },
  {
    id: "css_selectors_59",
    title: "Какой код сделает ширину элемента равной 100% минус 40px?",
    options: [
      "width: 100% - 40px;",
      "width: calc(100% - 40px);",
      "width: subtract(100%, 40px);",
      "width: 100% subtract 40px;",
    ],
    correctAnswers: [1],
    descriptions: [
      "100% - 40px — невалидный синтаксис.",
      "Правильно: calc(100% - 40px).",
      "subtract() — не функция в CSS.",
      "Пробелы не заменяют calc().",
    ],
    moduleId: "css",
    sectionTitle: "Стилизация текста",
    topic: "css_selectors",
  },
  {
    id: "css_selectors_60",
    title: "Какой код задаст размер элемента в зависимости от содержимого?",
    options: [
      "width: auto; height: auto;",
      "width: content; height: content;",
      "width: fit; height: fit;",
      "width: content-size; height: content-size;",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: auto подстраивается под контент.",
      "content — невалидное значение.",
      "fit — не существует (есть fit-content).",
      "content-size — не свойство.",
    ],
    moduleId: "css",
    sectionTitle: "Стилизация текста",
    topic: "css_selectors",
  },
  {
    id: "css_selectors_61",
    title: "Какое свойство задаёт линию подчеркивания текста?",
    options: [
      "text-decoration-line: underline;",
      "text-underline: true;",
      "underline: text;",
      "line-underline: text;",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: text-decoration-line: underline; задаёт саму линию подчеркивания.",
      "text-underline — невалидное свойство.",
      "underline: text — неверный синтаксис.",
      "line-underline — несуществующее свойство.",
    ],
    moduleId: "css",
    sectionTitle: "Стилизация текста",
    topic: "css_selectors",
  },
  {
    id: "css_selectors_62",
    title:
      "Какое значение text-decoration-style добавляет пунктирную подчеркивающую линию?",
    options: [
      "text-decoration-style: solid;",
      "text-decoration-style: dashed;",
      "text-decoration-style: double;",
      "text-decoration-style: dotted;",
    ],
    correctAnswers: [1],
    descriptions: [
      "solid — это сплошная линия.",
      "Правильно: dashed — пунктирная линия.",
      "double — двойная линия.",
      "dotted — точечная линия.",
    ],
    moduleId: "css",
    sectionTitle: "Стилизация текста",
    topic: "css_selectors",
  },
  {
    id: "css_selectors_63",
    title:
      "Как задаётся цвет подчеркивающей линии через text-decoration-color?",
    options: [
      "text-decoration-color: #FF0000;",
      "underline-color: #FF0000;",
      "text-underline-color: #FF0000;",
      "decor-color: #FF0000;",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: text-decoration-color: #FF0000; задаёт цвет подчеркивания.",
      "underline-color — невалидное свойство.",
      "text-underline-color — несуществующее.",
      "decor-color — несуществующее свойство.",
    ],
    moduleId: "css",
    sectionTitle: "Стилизация текста",
    topic: "css_selectors",
  },
  {
    id: "css_selectors_64",
    title:
      "Как указать, чтобы подчеркивающая линия не пересекала пробелы (skip spaces)?",
    options: [
      "text-decoration-skip: spaces;",
      "text-decoration-skip-ink: none;",
      "text-decoration-skip: ink;",
      "text-decoration-skip: objects;",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: text-decoration-skip: spaces; пропускает пробелы.",
      "text-decoration-skip-ink — управляет прерыванием линии при обводке символов, а не пробелах.",
      "text-decoration-skip: ink — управляет пропуском по форме букв.",
      "text-decoration-skip: objects — пропускает графические элементы.",
    ],
    moduleId: "css",
    sectionTitle: "Стилизация текста",
    topic: "css_selectors",
  },
  {
    id: "css_selectors_65",
    title: "Как установить толщину подчеркивающей линии в 2px?",
    options: [
      "text-decoration-thickness: 2px;",
      "text-underline-thickness: 2px;",
      "underline-width: 2px;",
      "line-thickness: 2px;",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: text-decoration-thickness: 2px; задаёт толщину линии.",
      "text-underline-thickness — невалидное свойство.",
      "underline-width — несуществующее свойство.",
      "line-thickness — не валидное свойство.",
    ],
    moduleId: "css",
    sectionTitle: "Стилизация текста",
    topic: "css_selectors",
  },
  {
    id: "css_selectors_66",
    title:
      "Как сместить подчеркивающую линию ниже текста через text-underline-offset?",
    options: [
      "text-underline-offset: 4px;",
      "text-decoration-offset: 4px;",
      "underline-offset: 4px;",
      "line-offset: 4px;",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: text-underline-offset: 4px; смещает линию под текст.",
      "text-decoration-offset — невалидное свойство.",
      "underline-offset — несуществующее.",
      "line-offset — неверное свойство.",
    ],
    moduleId: "css",
    sectionTitle: "Стилизация текста",
    topic: "css_selectors",
  },
  {
    id: "css_selectors_67",
    title: "Как задать, чтобы подчеркивающая линия была двойной?",
    options: [
      "text-decoration-style: double;",
      "text-decoration-style: dotted;",
      "text-decoration: underline double;",
      "both 1px underline;",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: text-decoration-style: double; создаёт двойную линию.",
      "dotted — точечная линия.",
      "text-decoration: underline double; некорректный порядок, должно быть text-decoration-style.",
      "both 1px underline — неверный синтаксис.",
    ],
    moduleId: "css",
    sectionTitle: "Стилизация текста",
    topic: "css_selectors",
  },
  {
    id: "css_selectors_68",
    title: "Как отключить подчеркивающую линию полностью?",
    options: [
      "text-decoration: none;",
      "text-decoration-line: none;",
      "text-decoration: off;",
      "underline: none;",
    ],
    correctAnswers: [1],
    descriptions: [
      "text-decoration: none; отключит все виды декораций, но вопрос про линию, правильнее указать line.",
      "Правильно: text-decoration-line: none; убирает подчеркивание.",
      "text-decoration: off — невалидное.",
      "underline: none — несуществующее.",
    ],
    moduleId: "css",
    sectionTitle: "Стилизация текста",
    topic: "css_selectors",
  },
  {
    id: "css_selectors_69",
    title:
      "Как применить одновременно цвет и стиль подчеркивания через одно свойство?",
    options: [
      "text-decoration: underline solid #FF0000;",
      "text-decoration: underline #FF0000 solid;",
      "text-decoration-line: underline; text-decoration-color: #FF0000; text-decoration-style: solid;",
      "color: #FF0000; underline: solid;",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: text-decoration: underline solid #FF0000; задаёт всё в одной строке.",
      "Неверный порядок параметров.",
      "Хотя этот вариант задаёт отдельные свойства, вопрос просил «одно свойство».",
      "color и underline — не объединяются.",
    ],
    moduleId: "css",
    sectionTitle: "Стилизация текста",
    topic: "css_selectors",
  },
  {
    id: "css_selectors_70",
    title:
      "Как указать, чтобы линия подчеркивания шла через каждое слово, а не сплошь?",
    options: [
      "text-decoration-skip: ink;",
      "text-decoration-skip: objects;",
      "text-decoration-skip: spaces;",
      "text-decoration-skip: none;",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: text-decoration-skip: ink; обеспечивает обрыв при обводке символов, а не слов.",
      "objects — пропускает встроенные объекты, а не буквы.",
      "spaces — пропускает пробелы, но линия будет сплошной через слова.",
      "none — отменяет пропуски, линия остаётся сплошной.",
    ],
    moduleId: "css",
    sectionTitle: "Стилизация текста",
    topic: "css_selectors",
  },
  {
    id: "css_selectors_71",
    title: "Как убрать подчеркивающую линию только у ссылок (<a>)?",
    options: [
      "a { text-decoration-line: none; }",
      "a { underline: none; }",
      "a { no-underline: true; }",
      "a { text-underline: none; }",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: a { text-decoration-line: none; } убирает подчеркивание у всех ссылок.",
      "underline — невалидное свойство.",
      "no-underline — несуществующее.",
      "text-underline — невалидное свойство.",
    ],
    moduleId: "css",
    sectionTitle: "Стилизация текста",
    topic: "css_selectors",
  },
  {
    id: "css_selectors_72",
    title: "Как задать тень под текстом (text shadow)?",
    options: [
      "text-decoration: shadow 2px 2px 4px #000;",
      "text-shadow: 2px 2px 4px #000;",
      "shadow-text: 2px 2px 4px #000;",
      "text-effect: shadow(2px,2px,4px,#000);",
    ],
    correctAnswers: [1],
    descriptions: [
      "text-decoration: shadow — неверный синтаксис.",
      "Правильно: text-shadow: 2px 2px 4px #000; задаёт тень.",
      "shadow-text — несуществующее свойство.",
      "text-effect — невалидное.",
    ],
    moduleId: "css",
    sectionTitle: "Стилизация текста",
    topic: "css_selectors",
  },
  {
    id: "css_selectors_73",
    title: "Как добавить линию над текстом (overline)?",
    options: [
      "text-decoration-line: overline;",
      "text-decoration-line: line-over;",
      "text-overline: true;",
      "overline: text;",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: text-decoration-line: overline; создаёт надчеркивание.",
      "line-over — неверный.",
      "text-overline — невалидное.",
      "overline — не существует отдельно.",
    ],
    moduleId: "css",
    sectionTitle: "Стилизация текста",
    topic: "css_selectors",
  },
  {
    id: "css_selectors_74",
    title:
      "Как одновременно задать надчеркивание и подчеркивание (underline and overline)?",
    options: [
      "text-decoration-line: underline overline;",
      "text-decoration: both underline overline;",
      "text-decoration-line: consume both;",
      "underline: true; overline: true;",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: text-decoration-line: underline overline; задаёт обе линии.",
      "«both» — невалидное ключевое слово.",
      "consume both — неверный синтаксис.",
      "underline/overline — несуществующие свойства.",
    ],
    moduleId: "css",
    sectionTitle: "Стилизация текста",
    topic: "css_selectors",
  },
  {
    id: "css_selectors_75",
    title: "Как сделать надчеркивающую линию пунктирной?",
    options: [
      "text-decoration-line: overline; text-decoration-style: dashed;",
      "text-decoration: overline dashed;",
      "overline-style: dashed;",
      "text-overline-style: dashed;",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: указываем line и style отдельно для достижения эффекта.",
      "text-decoration: overline dashed; неверный синтаксис, должно быть text-decoration-style.",
      "overline-style — несуществующее свойство.",
      "text-overline-style — невалидное.",
    ],
    moduleId: "css",
    sectionTitle: "Стилизация текста",
    topic: "css_selectors",
  },
  {
    id: "css_selectors_76",
    title: "Как задать линию перечеркивания (line-through)?",
    options: [
      "text-decoration-line: line-through;",
      "text-decoration-line: strike;",
      "text-decoration: line-through;",
      "text-strikethrough: true;",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: text-decoration-line: line-through; создаёт перечеркивание.",
      "strike — невалидное значение.",
      "text-decoration: line-through; — работает, но вопрос про line property.",
      "text-strikethrough — несуществующее.",
    ],
    moduleId: "css",
    sectionTitle: "Стилизация текста",
    topic: "css_selectors",
  },
  {
    id: "css_selectors_77",
    title:
      "Как задать подчеркивающую линию с цветом и стилем через shorthand text-decoration?",
    options: [
      "text-decoration: underline #00FF00 dotted;",
      "text-decoration: dotted underline #00FF00;",
      "text-decoration: underline dotted #00FF00;",
      "text-decoration: #00FF00 underline dotted;",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: text-decoration: underline #00FF00 dotted; (order: line, color, style).",
      "Неправильный порядок: цвет идёт вторым.",
      "Неправильный порядок параметров.",
      "Цвет должен быть после слова underline.",
    ],
    moduleId: "css",
    sectionTitle: "Стилизация текста",
    topic: "css_selectors",
  },
  {
    id: "css_selectors_78",
    title:
      "Как запретить автоматическое обрезание подчеркивающей линии на концах слов (skip-ink)?",
    options: [
      "text-decoration-skip-ink: none;",
      "text-decoration-skip-ink: auto;",
      "text-decoration-skip: none;",
      "text-decoration-skip: ink;",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: text-decoration-skip-ink: none; запрещает обрезание линии на символах.",
      "auto — может обрезать, по умолчанию.",
      "text-decoration-skip — не управляет skip-ink.",
      "text-decoration-skip: ink — пропускает элементы формы букв.",
    ],
    moduleId: "css",
    sectionTitle: "Стилизация текста",
    topic: "css_selectors",
  },
  {
    id: "css_selectors_79",
    title: "Как воспроизвести эффект подчеркивания волнистой линией?",
    options: [
      "text-decoration-style: wavy;",
      "text-decoration-line: wavy underline;",
      "underline-style: wavy;",
      "text-underline-style: wavy;",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: text-decoration-style: wavy; создаёт волнистую линию.",
      "wavy underline — неверное сочетание свойств.",
      "underline-style — несуществующее.",
      "text-underline-style — невалидное.",
    ],
    moduleId: "css",
    sectionTitle: "Стилизация текста",
    topic: "css_selectors",
  },
  {
    id: "css_selectors_80",
    title:
      "Как удалить только цвет подчеркивающей линии, оставив стиль и линию?",
    options: [
      "text-decoration-color: transparent;",
      "text-decoration-color: none;",
      "text-decoration-line: line-through; text-decoration-style: solid;",
      "text-decoration: line-through solid transparent;",
    ],
    correctAnswers: [0],
    descriptions: [
      "Правильно: text-decoration-color: transparent; делает линию невидимой, сохраняя стиль.",
      "none — невалидное значение для color.",
      "этот вариант не задаёт цвет прозрачным.",
      "text-decoration: line-through solid transparent; тоже работает, но вопрос про отдельное свойство.",
    ],
    moduleId: "css",
    sectionTitle: "Стилизация текста",
    topic: "css_selectors",
  },
];
