export const cssIntroQuestions = [
  {
    id: "css_intro_1",
    title: "Что такое CSS?",
    options: [
      "Язык разметки",
      "Язык программирования",
      "Каскадные таблицы стилей",
      "Система управления базами данных",
    ],
    correctAnswers: [2],
    descriptions: [
      "HTML — язык разметки.",
      "CSS не является языком программирования.",
      "CSS — Cascading Style Sheets (каскадные таблицы стилей).",
      "СУБД — это, например, MySQL или PostgreSQL.",
    ],
    moduleId: "css",
    sectionTitle: "Введение в CSS",
  },
  {
    id: "css_intro_2",
    title: "Для чего используется CSS?",
    options: [
      "Добавления стилей к HTML-элементам",
      "Работы с базой данных",
      "Обработки пользовательского ввода",
      "Создания серверной логики",
    ],
    correctAnswers: [0],
    descriptions: [
      "CSS описывает внешний вид HTML-элементов.",
      "БД не имеет отношения к CSS.",
      "Обработка ввода — это задача JS.",
      "CSS не используется на сервере.",
    ],
    moduleId: "css",
    sectionTitle: "Введение в CSS",
  },
  {
    id: "css_intro_3",
    title: "Какие бывают способы подключения CSS?",
    options: [
      "Внутренний, внешний, встроенный",
      "GET, POST, PUT",
      "SQL, NoSQL",
      "React, Vue, Angular",
    ],
    correctAnswers: [0],
    descriptions: [
      "CSS можно подключать тремя способами: inline, internal, external.",
      "GET и POST — это HTTP-методы.",
      "SQL и NoSQL — это типы баз данных.",
      "React, Vue, Angular — это JS-фреймворки.",
    ],
    moduleId: "css",
    sectionTitle: "Введение в CSS",
  },
  {
    id: "css_intro_4",
    title: "Какой синтаксис правильный для CSS-селектора?",
    options: [
      "selector: property value;",
      "selector = value;",
      "property: selector;",
      "value: property selector;",
    ],
    correctAnswers: [0],
    descriptions: [
      "Верный синтаксис: `selector { property: value; }`.",
      "Это невалидная запись.",
      "Селектор не ставится после свойства.",
      "Такой порядок некорректен в CSS.",
    ],
    moduleId: "css",
    sectionTitle: "Введение в CSS",
  },
  {
    id: "css_intro_5",
    title: "Как задать цвет текста в CSS?",
    options: [
      "text-color: red;",
      "font-color: red;",
      "color: red;",
      "text: red;",
    ],
    correctAnswers: [2],
    descriptions: [
      "`text-color` — несуществующее свойство.",
      "`font-color` — устаревшее или ошибочное.",
      "`color` — верное CSS-свойство для цвета текста.",
      "`text` — это не CSS-свойство.",
    ],
    moduleId: "css",
    sectionTitle: "Введение в CSS",
  },
  {
    id: "css_intro_6",
    title: "Что делает свойство `margin`?",
    options: [
      "Устанавливает внутренние отступы",
      "Устанавливает внешние отступы",
      "Задаёт цвет фона",
      "Выравнивает текст",
    ],
    correctAnswers: [1],
    descriptions: [
      "`padding` отвечает за внутренние отступы.",
      "`margin` отвечает за внешние отступы.",
      "`background-color` задаёт фон.",
      "`text-align` управляет выравниванием текста.",
    ],
    moduleId: "css",
    sectionTitle: "Введение в CSS",
  },
  {
    id: "css_intro_7",
    title: "Как подключить внешний файл стилей CSS в HTML?",
    options: [
      "<style src='style.css'>",
      "<css href='style.css'>",
      "<link rel='stylesheet' href='style.css'>",
      "<script src='style.css'>",
    ],
    correctAnswers: [2],
    descriptions: [
      "`<style>` используется для внутренних стилей, не подключает файл.",
      "`<css>` — несуществующий тег.",
      "`<link rel='stylesheet' href='...'>` — правильный способ.",
      "`<script>` подключает JS, не CSS.",
    ],
    moduleId: "css",
    sectionTitle: "Введение в CSS",
  },
  {
    id: "css_intro_8",
    title: "Что такое каскадность в CSS?",
    options: [
      "Последовательность подключения JavaScript",
      "Приоритет стилей в зависимости от специфичности",
      "Подключение нескольких HTML-файлов",
      "Сортировка таблиц в HTML",
    ],
    correctAnswers: [1],
    descriptions: [
      "JS не имеет отношения к каскадности в CSS.",
      "Каскадность определяет, какой стиль применится при конфликте.",
      "HTML-файлы не подключаются каскадом.",
      "Таблицы не имеют отношения к понятию каскада.",
    ],
    moduleId: "css",
    sectionTitle: "Введение в CSS",
  },
  {
    id: "css_intro_9",
    title: "Что означает аббревиатура CSS?",
    options: [
      "Coded Style Sheets",
      "Creative Style Scripts",
      "Cascading Style Sheets",
      "Computer Style Syntax",
    ],
    correctAnswers: [2],
    descriptions: [
      "Неверная расшифровка.",
      "Нет такого понятия.",
      "Cascading Style Sheets — правильный ответ.",
      "Это несуществующая аббревиатура.",
    ],
    moduleId: "css",
    sectionTitle: "Введение в CSS",
  },
  {
    id: "css_intro_10",
    title: "Какой селектор выберет все элементы `<p>` в CSS?",
    options: ["#p", ".p", "p", "*p"],
    correctAnswers: [2],
    descriptions: [
      "`#p` — выбирает элемент с id 'p'.",
      "`.p` — выбирает элементы с классом 'p'.",
      "`p` — правильный селектор для всех `<p>`.",
      "`*p` — некорректный селектор.",
    ],
    moduleId: "css",
    sectionTitle: "Введение в CSS",
  },
];
