import { htmlSections } from "./htmlSectionsData";

export const htmlChapters = [
  {
    id: "html_intro",
    title: "Введение в HTML",
    sections: htmlSections.html_intro,
    testKeys: ["html_intro_test"],
    practiceIds: [
      "html_intro_task_1",
      "html_intro_task_2",
      "html_intro_task_3",
    ],
  },
  {
    id: "html_structure",
    title: "Структура HTML-документа",
    sections: htmlSections.html_structure,
    testKeys: ["html_structure_test"],
    practiceIds: [
      "html_structure_task_1",
      "html_structure_task_2",
      "html_structure_task_3",
    ],
  },
  {
    id: "html_elements",
    title: "Элементы и теги",
    sections: htmlSections.html_elements,
    testKeys: ["html_elements_test"],
    practiceIds: [
      "html_block_inline_1",
      "html_block_inline_2",
      "html_block_inline_3",
      "html_block_inline_4",
      "html_block_inline_5",
      "html_block_inline_6",
      "html_block_inline_7",
      "html_block_inline_8",
      "html_block_inline_9",
      "html_block_inline_10",
      "html_block_inline_11",
      "html_block_inline_12",
      "html_block_inline_13",
    ],
  },
  {
    id: "html_attributes",
    title: "Атрибуты элементов",
    sections: htmlSections.html_attributes,
    testKeys: ["html_attributes_test"],
    practiceIds: ["html_attributes_usage_1", "html_attributes_usage_2"],
  },
  {
    id: "html_semantics",
    title: "Семантическая разметка",
    sections: htmlSections.html_semantics,
    testKeys: ["html_semantics_test"],
    practiceIds: [
      "html_semantic_landing_1",
      "html_semantic_landing_2",
      "html_semantic_landing_3",
      "html_semantic_landing_4",
    ],
  },
  {
    id: "html_links_images",
    title: "Ссылки и изображения",
    sections: htmlSections.html_links_images,
    testKeys: ["html_links_images_test"],
    practiceIds: [
      "html_links_creation_1",
      "html_links_creation_2",
      "html_links_creation_3",
      "html_links_creation_4",
    ],
  },
  {
    id: "html_forms",
    title: "HTML-формы и элементы управления",
    sections: htmlSections.html_forms,
    testKeys: ["html_forms_test"],
    practiceIds: [
      "html_form_login_1",
      "html_form_login_2",
      "html_form_login_3",
      "html_form_login_4",
      "html_form_login_5",
    ],
  },
  {
    id: "html_tables",
    title: "HTML-таблицы",
    sections: htmlSections.html_tables,
    testKeys: ["html_tables_test"],
    practiceIds: [
      "html_table_simple_1",
      "html_table_simple_2",
      "html_table_simple_3",
    ],
  },
  {
    id: "html_multimedia",
    title: "Мультимедиа: видео и аудио",
    sections: htmlSections.html_multimedia,
    testKeys: ["html_multimedia_test"],
    practiceIds: ["html_video_embed_1", "html_video_embed_2"],
  },
  {
    id: "html_meta_head",
    title: "Мета-теги и <head>",
    sections: htmlSections.html_meta_head,
    testKeys: ["html_meta_head_test"],
    practiceIds: ["html_meta_basic_1", "html_meta_basic_2"],
  },
  {
    id: "html_best_practices",
    title: "Современные практики и доступность",
    sections: htmlSections.html_best_practices,
    testKeys: ["html_best_practices_test"],
  },
  {
    id: "html_final",
    title: "Заключение и практическая работа",
    sections: htmlSections.html_final,
    testKeys: ["html_final_test"],
    final: true,
  },
];
