export const html_final_test = {
  id: 14,
  name: "Итоговый HTML",
  category: "HTML",
  ques: [
    {
      id: 1,
      name: "Что означает аббревиатура HTML?",
      variants: [
        "Hyperlinks and Text Markup Language",
        "Hyper Text Markup Language",
        "Home Tool Markup Language",
      ],
      correct: [1],
    },
    {
      id: 2,
      name: "Какой тег определяет корень HTML-документа?",
      variants: ["<head>", "<body>", "<html>"],
      correct: [2],
    },
    {
      id: 3,
      name: "Какой элемент используется для создания заголовка первого уровня?",
      variants: ["<header>", "<h1>", "<head>"],
      correct: [1],
    },
    {
      id: 4,
      name: "Какой атрибут обязателен для тега <img>?",
      variants: ["src", "alt", "width"],
      correct: [0],
    },
    {
      id: 5,
      name: "Какой тег используется для создания ссылки?",
      variants: ["<link>", "<a>", "<href>"],
      correct: [1],
    },
    {
      id: 6,
      name: "Какой элемент HTML5 используется для навигации?",
      variants: ["<div>", "<nav>", "<menu>"],
      correct: [1],
    },
    {
      id: 7,
      name: "Какой тег создает ненумерованный список?",
      variants: ["<ol>", "<ul>", "<li>"],
      correct: [1],
    },
    {
      id: 8,
      name: "Какой атрибут указывает, что поле формы обязательно для заполнения?",
      variants: ["required", "mandatory", "validate"],
      correct: [0],
    },
    {
      id: 9,
      name: "Какой тег используется для вставки видео?",
      variants: ["<media>", "<video>", "<movie>"],
      correct: [1],
    },
    {
      id: 10,
      name: "Какой элемент используется для группировки строк в таблице?",
      variants: ["<group>", "<tbody>", "<collection>"],
      correct: [1],
    },
    {
      id: 11,
      name: "Какой тег определяет важный текст?",
      variants: ["<i>", "<b>", "<strong>"],
      correct: [2],
    },
    {
      id: 12,
      name: "Какой элемент используется для ввода многострочного текста?",
      variants: ["<input>", "<textarea>", "<textfield>"],
      correct: [1],
    },
    {
      id: 13,
      name: "Какой тег используется для мета-описания страницы?",
      variants: ["<meta>", "<description>", "<info>"],
      correct: [0],
    },
    {
      id: 14,
      name: "Какой атрибут указывает на тип вводимых данных в поле <input>?",
      variants: ["data-type", "format", "type"],
      correct: [2],
    },
    {
      id: 15,
      name: "Какой элемент HTML5 используется для независимого контента?",
      variants: ["<section>", "<article>", "<independent>"],
      correct: [1],
    },
    {
      id: 16,
      name: "Какой тег создает горизонтальную линию?",
      variants: ["<br>", "<hr>", "<line>"],
      correct: [1],
    },
    {
      id: 17,
      name: "Какой элемент используется для создания выпадающего списка?",
      variants: ["<input>", "<select>", "<dropdown>"],
      correct: [1],
    },
    {
      id: 18,
      name: "Какой атрибут используется для уникального идентификатора элемента?",
      variants: ["class", "id", "name"],
      correct: [1],
    },
    {
      id: 19,
      name: "Какой тег используется для вставки аудио?",
      variants: ["<sound>", "<audio>", "<mp3>"],
      correct: [1],
    },
    {
      id: 20,
      name: "Какой элемент используется для подвала документа?",
      variants: ["<bottom>", "<footer>", "<end>"],
      correct: [1],
    },
    {
      id: 21,
      name: "Какой тег используется для создания таблицы?",
      variants: ["<table>", "<tab>", "<grid>"],
      correct: [0],
    },
    {
      id: 22,
      name: "Какой атрибут указывает на текст, который будет отображаться при наведении?",
      variants: ["hover", "title", "tooltip"],
      correct: [1],
    },
    {
      id: 23,
      name: "Какой элемент используется для семантического выделения цитаты?",
      variants: ["<quote>", "<blockquote>", "<cite>"],
      correct: [1],
    },
    {
      id: 24,
      name: "Какой тег используется для переноса строки?",
      variants: ["<lb>", "<br>", "<newline>"],
      correct: [1],
    },
    {
      id: 25,
      name: "Какой элемент используется для создания формы?",
      variants: ["<form>", "<input-form>", "<webform>"],
      correct: [0],
    },
    {
      id: 26,
      name: "Какой тег используется для группировки связанных полей внутри формы?",
      variants: ["<group>", "<fieldset>", "<section>"],
      correct: [1],
    },
    {
      id: 27,
      name: "Какой элемент используется для создания строки таблицы?",
      variants: ["<tr>", "<td>", "<row>"],
      correct: [0],
    },
    {
      id: 28,
      name: "Какой тег используется для создания ячейки таблицы?",
      variants: ["<cell>", "<td>", "<item>"],
      correct: [1],
    },
    {
      id: 29,
      name: "Какой элемент используется для создания заголовка таблицы?",
      variants: ["<th>", "<table-header>", "<header>"],
      correct: [0],
    },
    {
      id: 30,
      name: "Какой атрибут объединяет ячейки таблицы по вертикали?",
      variants: ["colspan", "rowspan", "merge"],
      correct: [1],
    },
    {
      id: 31,
      name: "Какой тег внутри <video> добавляет субтитры?",
      variants: ["<subtitle>", "<track>", "<caption>"],
      correct: [1],
    },
    {
      id: 32,
      name: "Какой элемент используется для создания всплывающей подсказки?",
      variants: ["<abbr>", "<tooltip>", "<details>"],
      correct: [2],
    },
    {
      id: 33,
      name: "Какой атрибут указывает на альтернативный текст для изображения?",
      variants: ["title", "alt", "description"],
      correct: [1],
    },
    {
      id: 34,
      name: "Какой тег используется для создания выпадающего списка с автозаполнением?",
      variants: ["<select>", "<datalist>", "<autocomplete>"],
      correct: [1],
    },
    {
      id: 35,
      name: "Какой элемент используется для семантического выделения кода?",
      variants: ["<code>", "<pre>", "<samp>"],
      correct: [0],
    },
    {
      id: 36,
      name: "Какой тег используется для вставки внешнего ресурса, например PDF?",
      variants: ["<embed>", "<object>", "<iframe>"],
      correct: [0],
    },
    {
      id: 37,
      name: "Какой атрибут указывает на кодировку документа?",
      variants: ["encoding", "charset", "lang"],
      correct: [1],
    },
    {
      id: 38,
      name: "Какой элемент используется для создания ползунка?",
      variants: ["<slider>", "<range>", "<input type='range'>"],
      correct: [2],
    },
    {
      id: 39,
      name: "Какой тег определяет основное содержимое документа?",
      variants: ["<div>", "<main>", "<section>"],
      correct: [1],
    },
    {
      id: 40,
      name: "Какой тег сохраняет пробелы и переводы строк в тексте?",
      variants: ["<code>", "<pre>", "<samp>"],
      correct: [1],
    },
  ],
};
