export const verstka_final_test = {
  id: 380,
  name: "Итоговый тест по веб-верстке",
  category: "HTML/CSS/SCSS",
  ques: [
    {
      id: 1,
      name: "Какой тег используется для основного содержимого страницы?",
      variants: ["<content>", "<body>", "<main>", "<section>"],
      correct: [2],
    },
    {
      id: 2,
      name: "Какой атрибут обязателен для тега <img>?",
      variants: ["src", "alt", "title", "href"],
      correct: [0],
    },
    {
      id: 3,
      name: "Как создать выпадающий список с возможностью множественного выбора?",
      variants: [
        "<select multiple>",
        "<select multi>",
        "<dropdown multiple>",
        "<input type='multi-select'>",
      ],
      correct: [0],
    },
    {
      id: 4,
      name: "Какой тег используется для группировки элементов формы?",
      variants: ["<group>", "<fieldset>", "<form-group>", "<div>"],
      correct: [1],
    },
    {
      id: 5,
      name: "Какой атрибут делает поле формы обязательным для заполнения?",
      variants: ["required", "mandatory", "validate", "necessary"],
      correct: [0],
    },
    {
      id: 6,
      name: "Какой тег HTML5 используется для навигации?",
      variants: ["<menu>", "<nav>", "<navigation>", "<links>"],
      correct: [1],
    },
    {
      id: 7,
      name: "Какой тег используется для независимого контента, который можно извлечь из страницы?",
      variants: ["<section>", "<article>", "<div>", "<content>"],
      correct: [1],
    },
    {
      id: 8,
      name: "Как создать подсказку при наведении на элемент?",
      variants: [
        "title='Подсказка'",
        "tooltip='Подсказка'",
        "hint='Подсказка'",
        "hover='Подсказка'",
      ],
      correct: [0],
    },
    {
      id: 9,
      name: "Какой тег используется для заголовка таблицы?",
      variants: ["<th>", "<td>", "<thead>", "<header>"],
      correct: [0],
    },
    {
      id: 10,
      name: "Какой атрибут связывает label с элементом формы?",
      variants: ["for", "id", "name", "link"],
      correct: [0],
    },

    {
      id: 11,
      name: "Как выбрать все элементы с классом 'button'?",
      variants: [".button", "#button", "button", "*button"],
      correct: [0],
    },
    {
      id: 12,
      name: "Как установить красный цвет текста?",
      variants: [
        "color: red;",
        "text-color: red;",
        "font-color: red;",
        "rgb: red;",
      ],
      correct: [0],
    },
    {
      id: 13,
      name: "Как сделать элемент невидимым, но сохранить его место в потоке?",
      variants: [
        "display: none;",
        "visibility: hidden;",
        "opacity: 0;",
        "hidden: true;",
      ],
      correct: [1],
    },
    {
      id: 14,
      name: "Как центрировать элемент по горизонтали с помощью margin?",
      variants: [
        "margin: auto;",
        "margin: 0 center;",
        "margin-center: auto;",
        "margin: center;",
      ],
      correct: [0],
    },
    {
      id: 15,
      name: "Как создать плавный переход при наведении?",
      variants: [
        "transition: all 0.3s ease;",
        "animation: hover 0.3s;",
        "hover-effect: smooth;",
        "transform: smooth;",
      ],
      correct: [0],
    },
    {
      id: 16,
      name: "Как сделать элемент абсолютно позиционированным?",
      variants: [
        "position: absolute;",
        "display: absolute;",
        "float: absolute;",
        "layout: absolute;",
      ],
      correct: [0],
    },
    {
      id: 17,
      name: "Как создать тень для блока?",
      variants: [
        "shadow: 0 0 10px #000;",
        "box-shadow: 0 0 10px #000;",
        "element-shadow: 0 0 10px #000;",
        "block-shadow: 0 0 10px #000;",
      ],
      correct: [1],
    },
    {
      id: 18,
      name: "Как сделать flex-контейнер?",
      variants: [
        "display: flex;",
        "layout: flex;",
        "container-type: flex;",
        "flex: true;",
      ],
      correct: [0],
    },
    {
      id: 19,
      name: "Как выровнять flex-элементы по центру по вертикали?",
      variants: [
        "align-items: center;",
        "justify-content: center;",
        "flex-align: center;",
        "vertical-align: middle;",
      ],
      correct: [0],
    },
    {
      id: 20,
      name: "Как создать grid-сетку с 3 колонками равной ширины?",
      variants: [
        "grid-template-columns: 1fr 1fr 1fr;",
        "grid-columns: 3;",
        "grid: repeat(3, 1fr);",
        "grid-layout: 3-column;",
      ],
      correct: [0],
    },
    {
      id: 21,
      name: "Какой псевдокласс применяется к посещенной ссылке?",
      variants: [":visited", ":active", ":hover", ":link"],
      correct: [0],
    },
    {
      id: 22,
      name: "Как создать анимацию с именем 'fade'?",
      variants: [
        "@keyframes fade { ... }",
        "animation: fade { ... }",
        "@animate fade { ... }",
        "keyframes: fade { ... }",
      ],
      correct: [0],
    },
    {
      id: 23,
      name: "Как сделать элемент полупрозрачным?",
      variants: [
        "opacity: 0.5;",
        "transparency: 50%;",
        "alpha: 0.5;",
        "visible: 50%;",
      ],
      correct: [0],
    },
    {
      id: 24,
      name: "Как изменить курсор при наведении на указатель?",
      variants: [
        "cursor: pointer;",
        "pointer: cursor;",
        "mouse: pointer;",
        "hover-cursor: pointer;",
      ],
      correct: [0],
    },
    {
      id: 25,
      name: "Как сделать медиазапрос для экранов шириной менее 768px?",
      variants: [
        "@media (max-width: 768px) { ... }",
        "@media screen and (max-width: 768px) { ... }",
        "@media (width <= 768px) { ... }",
        "@media (device-width: 768px) { ... }",
      ],
      correct: [1],
    },
    {
      id: 26,
      name: "Какой единицы измерения лучше избегать для адаптивного дизайна?",
      variants: ["rem", "px", "em", "vw"],
      correct: [1],
    },
    {
      id: 27,
      name: "Как скрыть элемент на мобильных устройствах?",
      variants: [
        ".element { display: none; @media (min-width: 768px) { display: block; } }",
        ".element { visibility: hidden; @media (min-width: 768px) { visibility: visible; } }",
        ".element { mobile-hide: true; }",
        "@mobile { .element { display: none; } }",
      ],
      correct: [0],
    },
    {
      id: 28,
      name: "Как создать псевдоэлемент после содержимого блока?",
      variants: [
        "::after { content: ''; }",
        ":after { content: ''; }",
        "::post { content: ''; }",
        "::append { content: ''; }",
      ],
      correct: [0],
    },
    {
      id: 29,
      name: "Как сделать градиентный фон от синего к зеленому?",
      variants: [
        "background: linear-gradient(blue, green);",
        "background: gradient(blue to green);",
        "background-color: blue-green;",
        "gradient: linear(blue, green);",
      ],
      correct: [0],
    },
    {
      id: 30,
      name: "Какой CSS-методологии соответствует этот селектор: .block__element--modifier?",
      variants: ["BEM", "OOCSS", "SMACSS", "Atomic CSS"],
      correct: [0],
    },

    {
      id: 31,
      name: "Как правильно объявить переменную в SCSS?",
      variants: [
        "$primary-color: #3498db;",
        "primary-color: #3498db;",
        "$primary-color = #3498db;",
        "var primary-color = #3498db;",
      ],
      correct: [0],
    },
    {
      id: 32,
      name: "Какой символ используется для ссылки на родительский селектор?",
      variants: ["@parent", "&", "$", "*"],
      correct: [1],
    },
    {
      id: 33,
      name: "Как назвать файл-партиал в SCSS?",
      variants: [
        "variables.scss",
        "_variables.scss",
        "variables.css",
        "partial-variables.scss",
      ],
      correct: [1],
    },
    {
      id: 34,
      name: "Как объявить миксин с параметрами?",
      variants: [
        "@mixin box($width, $height) { ... }",
        "@mixin box width, height { ... }",
        "mixin box($width, $height) { ... }",
        "@function box($width, $height) { ... }",
      ],
      correct: [0],
    },
    {
      id: 35,
      name: "Как подключить миксин 'box' внутри селектора?",
      variants: [
        "@include box(100px, 100px);",
        "@mixin box(100px, 100px);",
        "@use box(100px, 100px);",
        "@extend box(100px, 100px);",
      ],
      correct: [0],
    },
    {
      id: 36,
      name: "Как наследовать стили одного селектора другому?",
      variants: ["@include", "@extend", "@inherit", "@use"],
      correct: [1],
    },
    {
      id: 37,
      name: "Как создать цикл для генерации классов от .col-1 до .col-5?",
      variants: [
        "@for $i from 1 through 5 { .col-#{$i} { ... } }",
        "@each $i in 1 to 5 { .col-#{$i} { ... } }",
        "@while $i <= 5 { .col-#{$i} { ... } }",
        "@loop $i from 1 to 5 { .col-#{$i} { ... } }",
      ],
      correct: [0],
    },
    {
      id: 38,
      name: "Как получить значение из карты (map)?",
      variants: [
        "map-get($map, key)",
        "$map[key]",
        "get($map, key)",
        "value($map, key)",
      ],
      correct: [0],
    },
    {
      id: 39,
      name: "Как использовать условие в SCSS?",
      variants: [
        "@if $condition { ... }",
        "if $condition then { ... }",
        "$condition ? { ... }",
        "when $condition { ... }",
      ],
      correct: [0],
    },
    {
      id: 40,
      name: "Как импортировать файл _variables.scss?",
      variants: [
        "@import 'variables';",
        "@use 'variables';",
        "@include 'variables';",
        "@require '_variables';",
      ],
      correct: [0],
    },
    {
      id: 41,
      name: "Как создать функцию для перевода px в rem?",
      variants: [
        "@function px-to-rem($px) { @return $px / 16 * 1rem; }",
        "function px-to-rem($px) { return $px / 16 * 1rem; }",
        "@mixin px-to-rem($px) { @return $px / 16 * 1rem; }",
        "@convert px-to-rem($px) { @return $px / 16 * 1rem; }",
      ],
      correct: [0],
    },
    {
      id: 42,
      name: "Как использовать директиву @content?",
      variants: [
        "Для вставки блока стилей в миксин",
        "Для возврата значения из функции",
        "Для импорта содержимого файла",
        "Для условного выполнения кода",
      ],
      correct: [0],
    },
    {
      id: 43,
      name: "Как создать вложенные селекторы?",
      variants: [
        ".parent { .child { ... } }",
        ".parent > .child { ... }",
        ".parent.child { ... }",
        "Все варианты верны",
      ],
      correct: [3],
    },
    {
      id: 44,
      name: "Как правильно использовать интерполяцию переменной в селекторе?",
      variants: [
        ".#{$class-name} { ... }",
        ".${class-name} { ... }",
        ".%{class-name} { ... }",
        "Все варианты неверны",
      ],
      correct: [0],
    },
    {
      id: 45,
      name: "Какой директивой можно заменить @import в современных версиях SCSS?",
      variants: ["@use", "@include", "@extend", "@require"],
      correct: [0],
    },

    {
      id: 46,
      name: "Какой инструмент используется для автоматического добавления вендорных префиксов?",
      variants: ["Autoprefixer", "PostCSS", "Babel", "Webpack"],
      correct: [0],
    },
    {
      id: 47,
      name: "Какой плагин VS Code помогает быстро разворачивать HTML-структуры?",
      variants: ["Emmet", "Prettier", "ESLint", "Live Server"],
      correct: [0],
    },
    {
      id: 48,
      name: "Какой инструмент используется для модульной сборки проекта?",
      variants: ["Webpack", "Gulp", "Grunt", "Все варианты верны"],
      correct: [3],
    },
    {
      id: 49,
      name: "Какой инструмент позволяет видеть изменения в реальном времени без перезагрузки страницы?",
      variants: [
        "Live Server",
        "BrowserSync",
        "Webpack Dev Server",
        "Все варианты верны",
      ],
      correct: [3],
    },
    {
      id: 50,
      name: "Какой инструмент используется для форматирования кода?",
      variants: ["Prettier", "ESLint", "Stylelint", "Все варианты верны"],
      correct: [3],
    },

    {
      id: 51,
      name: "Что означает принцип Mobile First?",
      variants: [
        "Сначала верстать для мобильных устройств",
        "Сначала верстать для десктопов",
        "Создавать отдельные версии для мобильных и десктопов",
        "Использовать только мобильные стили",
      ],
      correct: [0],
    },
    {
      id: 52,
      name: "Какой подход к организации CSS предполагает разделение на Блоки, Элементы и Модификаторы?",
      variants: ["BEM", "OOCSS", "SMACSS", "Atomic CSS"],
      correct: [0],
    },
    {
      id: 53,
      name: "Какой атрибут улучшает доступность для скринридеров?",
      variants: ["aria-label", "data-label", "alt-text", "accessibility-text"],
      correct: [0],
    },
    {
      id: 54,
      name: "Какой метод оптимизации предполагает отложенную загрузку изображений?",
      variants: ["Lazy loading", "Critical CSS", "Sprite sheets", "WebP"],
      correct: [0],
    },
    {
      id: 55,
      name: "Какой формат изображения лучше использовать для фоновых изображений с прозрачностью?",
      variants: ["PNG", "JPG", "WebP", "SVG"],
      correct: [2],
    },
    {
      id: 56,
      name: "Какой CSS-метод помогает уменьшить количество перерисовок страницы?",
      variants: [
        "Использование transform и opacity",
        "Использование margin и padding",
        "Использование !important",
        "Все варианты верны",
      ],
      correct: [0],
    },
    {
      id: 57,
      name: "Какой подход к верстке предполагает использование относительных единиц?",
      variants: [
        "Адаптивный дизайн",
        "Резиновый дизайн",
        "Фиксированный дизайн",
        "Все варианты верны",
      ],
      correct: [0],
    },
    {
      id: 58,
      name: "Какой атрибут улучшает SEO для изображений?",
      variants: ["alt", "title", "description", "Все варианты верны"],
      correct: [0],
    },
    {
      id: 59,
      name: "Какой метод позволяет ускорить загрузку критически важных стилей?",
      variants: [
        "Вставка критического CSS в <head>",
        "Использование @import",
        "Разделение стилей на несколько файлов",
        "Все варианты верны",
      ],
      correct: [0],
    },
    {
      id: 60,
      name: "Какой инструмент позволяет тестировать верстку в разных браузерах?",
      variants: [
        "BrowserStack",
        "CrossBrowserTesting",
        "LambdaTest",
        "Все варианты верны",
      ],
      correct: [3],
    },
  ],
};
