import {
  css_borders_task_1,
  css_borders_task_2,
  css_borders_task_3,
  css_borders_task_4,
  css_borders_task_5,
} from "./css_borders";
import {
  css_container_task_1,
  css_container_task_2,
  css_container_task_3,
  css_container_task_4,
  css_container_task_5,
  css_container_task_6,
} from "./css_container";
import {
  css_display_task_1,
  css_display_task_2,
  css_display_task_3,
  css_display_task_4,
  css_display_task_5,
} from "./css_display";
import {
  css_img_vs_bg_task_1,
  css_img_vs_bg_task_2,
  css_img_vs_bg_task_3,
  css_img_vs_bg_task_4,
} from "./css_img";
import {
  css_layers_task_1,
  css_layers_task_2,
  css_layers_task_3,
  css_layers_task_4,
  css_layers_task_5,
} from "./css_layers";
import {
  css_media_queries_task_1,
  css_media_queries_task_2,
  css_media_queries_task_3,
  css_media_queries_task_4,
  css_media_queries_task_5,
  css_media_queries_task_6,
} from "./css_media_queries";
import {
  css_offset_task_1,
  css_offset_task_2,
  css_offset_task_3,
  css_offset_task_4,
  css_offset_task_5,
} from "./css_offset";
import {
  css_position_task_1,
  css_position_task_2,
  css_position_task_3,
  css_position_task_4,
  css_position_task_5,
} from "./css_position";
import {
  css_pseudo_taskAll_1,
  css_pseudo_taskAll_2,
  css_pseudo_taskAll_3,
  css_pseudo_taskAll_4,
  css_pseudo_taskAll_5,
  css_pseudo_taskAll_6,
} from "./css_pseudo";
import {
  css_pseudoElement_task_1,
  css_pseudoElement_task_2,
  css_pseudoElement_task_3,
  css_pseudoElement_task_4,
  css_pseudoElement_task_5,
} from "./css_pseudoElement";
import {
  css_sizes_task_1,
  css_sizes_task_2,
  css_sizes_task_3,
  css_sizes_task_4,
  css_sizes_task_5,
} from "./css_sizes";
import {
  css_spacing_task_1,
  css_spacing_task_2,
  css_spacing_task_3,
  css_spacing_task_4,
  css_spacing_task_5,
} from "./css_spacing";
import {
  css_text_styling_task_1,
  css_text_styling_task_2,
  css_text_styling_task_3,
  css_text_styling_task_4,
  css_text_styling_task_5,
  css_text_styling_task_6,
  css_text_styling_task_7,
} from "./css_text_styling";
import {
  css_transition_task_1,
  css_transition_task_2,
  css_transition_task_3,
  css_transition_task_4,
  css_transition_task_5,
} from "./css_transition";
import {
  flex_task_1,
  flex_task_10,
  flex_task_11,
  flex_task_12,
  flex_task_13,
  flex_task_14,
  flex_task_15,
  flex_task_16,
  flex_task_17,
  flex_task_18,
  flex_task_19,
  flex_task_2,
  flex_task_3,
  flex_task_4,
  flex_task_5,
  flex_task_6,
  flex_task_7,
  flex_task_8,
  flex_task_9,
} from "./css_flex_task";
import {
  grid_task_1,
  grid_task_10,
  grid_task_11,
  grid_task_12,
  grid_task_13,
  grid_task_14,
  grid_task_15,
  grid_task_16,
  grid_task_17,
  grid_task_18,
  grid_task_19,
  grid_task_2,
  grid_task_20,
  grid_task_21,
  grid_task_22,
  grid_task_23,
  grid_task_24,
  grid_task_3,
  grid_task_4,
  grid_task_5,
  grid_task_6,
  grid_task_7,
  grid_task_8,
  grid_task_9,
} from "./css_grid_task";
import {
  css_text_decoration_task_1,
  css_text_decoration_task_2,
  css_text_decoration_task_3,
  css_text_decoration_task_4,
  css_text_decoration_task_5,
} from "./css_text_decoration";
import {
  css_animations_task_1,
  css_animations_task_2,
  css_animations_task_3,
  css_animations_task_4,
} from "./css_animations";
import {
  css_block_model_task_1,
  css_block_model_task_2,
  css_block_model_task_3,
  css_block_model_task_4,
  css_block_model_task_5,
} from "./css_block_task";
import {
  css_box_model_task_1,
  css_box_model_task_10,
  css_box_model_task_2,
  css_box_model_task_3,
  css_box_model_task_4,
  css_box_model_task_5,
  css_box_model_task_6,
  css_box_model_task_7,
  css_box_model_task_8,
  css_box_model_task_9,
} from "./css_box_model_task";
import {
  css_flexbox_task_1,
  css_flexbox_task_10,
  css_flexbox_task_11,
  css_flexbox_task_12,
  css_flexbox_task_2,
  css_flexbox_task_3,
  css_flexbox_task_4,
  css_flexbox_task_5,
  css_flexbox_task_6,
  css_flexbox_task_7,
  css_flexbox_task_8,
  css_flexbox_task_9,
} from "./css_flexbox_task";
import {
  css_grid_task_new,
  css_grid_task_10,
  css_grid_task_11,
  css_grid_task_2,
  css_grid_task_3,
  css_grid_task_4,
  css_grid_task_5,
  css_grid_task_6,
  css_grid_task_7,
  css_grid_task_8,
  css_grid_task_9,
} from "./css_grid_task_new";
import {
  css_images_task_1,
  css_images_task_2,
  css_images_task_3,
  css_images_task_4,
} from "./css_images";
import { css_intro_task_1 } from "./css_intro_task";
import {
  css_layout_task_1,
  css_layout_task_2,
  css_layout_task_3,
  css_layout_task_4,
} from "./css_layout";
import {
  css_methodologies_task_1,
  css_methodologies_task_2,
} from "./css_methodologies_task";
import {
  css_pseudo_task_1,
  css_pseudo_task_3,
  css_pseudo_task_4,
  css_pseudo_task_5,
  css_pseudo_task_6,
  css_pseudo_task_7,
} from "./css_pseudo_task";
import {
  css_responsive_task_1,
  css_responsive_task_2,
  css_responsive_task_3,
  css_responsive_task_4,
} from "./css_responsive";
import {
  css_selectors_task_1,
  css_selectors_task_2,
  css_selectors_task_3,
  css_selectors_task_4,
  css_selectors_task_5,
  css_selectors_task_6,
  css_selectors_task_7,
  css_selectors_task_8,
} from "./css_selectors_task";
import {
  css_background_task_1,
  css_background_task_2,
  css_background_task_3,
  css_background_task_4,
} from "./css_background";

export const dataTaskCss = [
  css_intro_task_1,

  css_selectors_task_1,
  css_selectors_task_2,
  css_selectors_task_3,
  css_selectors_task_4,
  css_selectors_task_5,
  css_selectors_task_6,
  css_selectors_task_7,
  css_selectors_task_8,

  css_box_model_task_1,
  css_box_model_task_2,
  css_box_model_task_3,
  css_box_model_task_4,
  css_box_model_task_5,
  css_box_model_task_6,
  css_box_model_task_7,
  css_box_model_task_8,
  css_box_model_task_9,
  css_box_model_task_10,

  css_block_model_task_1,
  css_block_model_task_2,
  css_block_model_task_3,
  css_block_model_task_4,
  css_block_model_task_5,

  css_pseudo_task_1,
  css_pseudo_task_3,
  css_pseudo_task_4,
  css_pseudo_task_5,
  css_pseudo_task_6,
  css_pseudo_task_7,

  css_methodologies_task_1,
  css_methodologies_task_2,

  css_flexbox_task_1,
  css_flexbox_task_2,
  css_flexbox_task_3,
  css_flexbox_task_4,
  css_flexbox_task_5,
  css_flexbox_task_6,
  css_flexbox_task_7,
  css_flexbox_task_8,
  css_flexbox_task_9,
  css_flexbox_task_10,
  css_flexbox_task_11,
  css_flexbox_task_12,

  css_grid_task_new,
  css_grid_task_2,
  css_grid_task_3,
  css_grid_task_4,
  css_grid_task_5,
  css_grid_task_6,
  css_grid_task_7,
  css_grid_task_8,
  css_grid_task_9,
  css_grid_task_10,
  css_grid_task_11,

  css_layout_task_1,
  css_layout_task_2,
  css_layout_task_3,
  css_layout_task_4,

  css_images_task_1,
  css_images_task_2,
  css_images_task_3,
  css_images_task_4,

  css_responsive_task_1,
  css_responsive_task_2,
  css_responsive_task_3,
  css_responsive_task_4,

  css_animations_task_1,
  css_animations_task_2,
  css_animations_task_3,
  css_animations_task_4,

  // CSS задачник дополнение
  css_text_styling_task_1,
  css_text_styling_task_2,
  css_text_styling_task_3,
  css_text_styling_task_4,
  css_text_styling_task_5,
  css_text_styling_task_6,
  css_text_styling_task_7,

  css_sizes_task_1,
  css_sizes_task_2,
  css_sizes_task_3,
  css_sizes_task_4,
  css_sizes_task_5,

  css_text_decoration_task_1,
  css_text_decoration_task_2,
  css_text_decoration_task_3,
  css_text_decoration_task_4,
  css_text_decoration_task_5,

  css_display_task_1,
  css_display_task_2,
  css_display_task_3,
  css_display_task_4,
  css_display_task_5,

  css_offset_task_1,
  css_offset_task_2,
  css_offset_task_3,
  css_offset_task_4,
  css_offset_task_5,

  css_position_task_1,
  css_position_task_2,
  css_position_task_3,
  css_position_task_4,
  css_position_task_5,

  css_layers_task_1,
  css_layers_task_2,
  css_layers_task_3,
  css_layers_task_4,
  css_layers_task_5,

  css_spacing_task_1,
  css_spacing_task_2,
  css_spacing_task_3,
  css_spacing_task_4,
  css_spacing_task_5,

  css_borders_task_1,
  css_borders_task_2,
  css_borders_task_3,
  css_borders_task_4,
  css_borders_task_5,

  css_pseudo_taskAll_1,
  css_pseudo_taskAll_2,
  css_pseudo_taskAll_3,
  css_pseudo_taskAll_4,
  css_pseudo_taskAll_5,
  css_pseudo_taskAll_6,

  css_pseudoElement_task_1,
  css_pseudoElement_task_2,
  css_pseudoElement_task_3,
  css_pseudoElement_task_4,
  css_pseudoElement_task_5,

  flex_task_1,
  flex_task_2,
  flex_task_3,
  flex_task_4,
  flex_task_5,
  flex_task_6,
  flex_task_7,
  flex_task_8,
  flex_task_9,
  flex_task_10,
  flex_task_11,
  flex_task_12,
  flex_task_13,
  flex_task_14,
  flex_task_15,
  flex_task_16,
  flex_task_17,
  flex_task_18,
  flex_task_19,

  grid_task_1,
  grid_task_2,
  grid_task_3,
  grid_task_4,
  grid_task_5,
  grid_task_6,
  grid_task_7,
  grid_task_8,
  grid_task_9,
  grid_task_10,
  grid_task_11,
  grid_task_12,
  grid_task_13,
  grid_task_14,
  grid_task_15,
  grid_task_16,
  grid_task_17,
  grid_task_18,
  grid_task_19,
  grid_task_20,
  grid_task_21,
  grid_task_22,
  grid_task_23,
  grid_task_24,

  css_container_task_1,
  css_container_task_2,
  css_container_task_3,
  css_container_task_4,
  css_container_task_5,
  css_container_task_6,

  css_background_task_1,
  css_background_task_2,
  css_background_task_3,
  css_background_task_4,

  css_img_vs_bg_task_1,
  css_img_vs_bg_task_2,
  css_img_vs_bg_task_3,
  css_img_vs_bg_task_4,

  css_media_queries_task_1,
  css_media_queries_task_2,
  css_media_queries_task_3,
  css_media_queries_task_4,
  css_media_queries_task_5,
  css_media_queries_task_6,

  css_transition_task_1,
  css_transition_task_2,
  css_transition_task_3,
  css_transition_task_4,
  css_transition_task_5,
];
