import { htmlSections } from "./htmlSectionsData";

export const htmlChapters = [
  {
    id: "html_intro",
    title: "Введение в HTML",
    sections: htmlSections.html_intro,
    testKeys: ["html_intro_test"],
    practiceIds: ["html_intro_task_1", "html_intro_task_2"],
  },
  {
    id: "html_structure",
    title: "Структура HTML-документа",
    sections: htmlSections.html_structure,
    testKeys: ["html_structure_test"],
    practiceIds: ["html_structure_task_1", "html_structure_task_2"],
  },
  {
    id: "html_elements",
    title: "Элементы и теги",
    sections: htmlSections.html_elements,
    testKeys: ["html_elements_test"],
    practiceIds: [
      "html_block_inline_1",
      "html_block_inline_2",
      "html_block_inline_3",
    ],
  },
  {
    id: "html_attributes",
    title: "Атрибуты элементов",
    sections: htmlSections.html_attributes,
    testKeys: ["html_attributes_test"],
    practiceIds: [
      "html_attributes_usage_1",
      "html_attributes_usage_2",
      "html_attributes_usage_3",
    ],
  },
  {
    id: "html_semantics",
    title: "Семантическая разметка",
    sections: htmlSections.html_semantics,
    testKeys: ["html_semantics_test"],
    practiceIds: ["html_semantic_landing_1"],
  },
  {
    id: "html_text_formatting",
    title: "Форматирование текста",
    sections: htmlSections.html_text_formatting,
    testKeys: ["html_text_formatting_test"],
    practiceIds: ["html_format_text_1", "html_format_text_2"],
  },
  {
    id: "html_links_images",
    title: "Ссылки и изображения",
    sections: htmlSections.html_links_images,
    testKeys: ["html_links_images_test"],
    practiceIds: ["html_links_creation_1", "html_links_creation_2"],
  },
  {
    id: "html_forms",
    title: "HTML-формы и элементы управления",
    sections: htmlSections.html_forms,
    testKeys: ["html_forms_test"],
    practiceIds: [
      "task_html_form_login",
      "task_html_form_survey",
      "task_html_form_validation",
    ],
  },
  {
    id: "html_tables",
    title: "HTML-таблицы",
    sections: htmlSections.html_tables,
    testKeys: ["html_tables_test"],
    practiceIds: ["task_html_table_simple", "task_html_table_merged"],
  },
  {
    id: "html_multimedia",
    title: "Мультимедиа: видео и аудио",
    sections: htmlSections.html_multimedia,
    testKeys: ["html_multimedia_test"],
    practiceIds: ["task_html_video_embed", "task_html_audio_player"],
  },
  {
    id: "html_meta_head",
    title: "Мета-теги и <head>",
    sections: htmlSections.html_meta_head,
    testKeys: ["html_meta_head_test"],
    practiceIds: ["task_html_meta_basic", "task_html_head_setup"],
  },
  {
    id: "html_best_practices",
    title: "Современные практики и доступность",
    sections: htmlSections.html_best_practices,
    testKeys: ["html_best_practices_test"],
    practiceIds: ["task_html_accessibility", "task_html_seo_structure"],
  },
  {
    id: "html_legacy",
    title: "Устаревшие теги и практики",
    sections: htmlSections.html_legacy,
    testKeys: ["html_legacy_test"],
    practiceIds: ["task_html_refactor_legacy"],
  },
  {
    id: "html_final",
    title: "Заключение и практическая работа",
    sections: htmlSections.html_final,
    testKeys: ["html_final_test"],
    practiceIds: ["task_html_final_project"],
    final: true,
  },
];
